### ISSUE TITLE
Lifetime licenses at low prices.

### ISSUE THREAD

**Issue by Sunazuri** [chathub-dev/chathub#1000]
If I can buy a lifetime license for less than 5$, I will buy it immediately.
In Japan, there is a saying "thin profit margin".
It means that by selling at a low price, many people will buy and you will make more money than if you sell at a high price.

**Comment by wong2** [comment]
I think you mean 薄利多銷 🤣
Unfortunately, I will not lower the price. I believe the value users get worth more than $35.
