### ISSUE TITLE
适配一下白色主题色

### ISSUE THREAD

**Issue by toxomo** [chathub-dev/chathub#1004]
主题色调成纯白时，设置等几个白色的图标会看不见。希望能改进一下

**Comment by wong2** [comment]
可以发下截图吗？

**Comment by toxomo** [comment]
![PixPin_2024-01-11_09-56-16](https://github.com/chathub-dev/chathub/assets/36037716/cfa66c8d-cd59-4c07-ab19-19e39c6eba04)
我用的Vivaldi，不会又是浏览器的问题吧

**Comment by wong2** [comment]
这个纯白色背景色是你自己在ChatHub里设置的吗？

**Comment by toxomo** [comment]
> 这个纯白色背景色是你自己在ChatHub里设置的吗？

对啊，自己设的#FFF

**Comment by wong2** [comment]
明白了，那和浏览器没有关系。
界面其他部分没法那么智能的适配任何背景颜色，所以需要你自己挑出一个喜欢又协调的颜色了

**Comment by toxomo** [comment]
> 明白了，那和浏览器没有关系。 界面其他部分没法那么智能的适配任何背景颜色，所以需要你自己挑出一个喜欢又协调的颜色了

还是纯白最舒服，只能改一下你的CSS了😛
