### ISSUE TITLE
讯飞星火：Unexpected non-whitespace character after JSON at position 8 (line 1 column 9)

### ISSUE THREAD

**Issue by forhonourlx** [chathub-dev/chathub#1006]
**Describe the bug**
大佬请帮忙修复一下啊：
讯飞星火：Unexpected non-whitespace character after JSON at position 8 (line 1 column 9)

**Comment by wong2** [comment]
v2.0.4 已修复

**Comment by forhonourlx** [comment]
感谢大佬！
