### ISSUE TITLE
讯飞星火模型查询报错

### ISSUE THREAD

**Issue by strengthen8** [chathub-dev/chathub#1009]
报错信息
Unexpected non-whitespace character after JSON at position 8 (line 1 column 9)
报错截图
![image](https://github.com/chathub-dev/chathub/assets/26496661/ff23872a-bbac-4b7e-b9ef-7859404c0e75)

**Comment by fankun576678634** [comment]
+1

**Comment by wong2** [comment]
v2.0.4 已修复
