### ISSUE TITLE
Cannot Add Hugging Face inference models

### ISSUE THREAD

**Issue by rapidstartup** [chathub-dev/chathub#1011]
If you add a different API connection structure, you could allow ALL/ANY Hugging Face models to the check.
It would need "Headers" to be allowed
It would need the body to be "inputs"
Example:
curl https://api-inference.huggingface.co/models/meta-llama/Llama-2-7b-chat-hf \
	-X POST \
	-d '{"inputs": "Can you please let us know more details about your "}' \
	-H 'Content-Type: application/json' \
	-H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

**Comment by wong2** [comment]
You can use https://docs.litellm.ai/docs/proxy/quick_start to proxy HF API to OpenAI API format.
