### ISSUE TITLE
建议增加gemini API代理URL输入

### ISSUE THREAD

**Issue by MeditatorV** [chathub-dev/chathub#1014]
建议增加gemini API代理URL输入

**Comment by wong2** [comment]
是有什么开源项目可以做gemini代理吗？

**Comment by MeditatorV** [comment]
> 是有什么开源项目可以做gemini代理吗？

https://github.com/antergone/palm-proxy

**Comment by MeditatorV** [comment]
> 是有什么开源项目可以做gemini代理吗？
我是参照以下方法做的代理：
https://simonmy.com/posts/%E4%BD%BF%E7%94%A8netlify%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86google-palm-api.html
