### ISSUE TITLE
Chrome Side Panel Shows Nothing

### ISSUE THREAD

**Issue by digitalattorney** [chathub-dev/chathub#1017]
**Describe the bug**
I purchased Premium. I open the Chrome Side Panel and I see nothing, even after querying in the extension app. I've unblocked chathub.gg from uOrigin. I have no other blockers. I run Bitdefender but there's no notification anything is being blocked.

https://i.imgur.com/JcFeNmE.gif
https://www.youtube.com/watch?v=bFPNBpHATns

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome is up to date - Version 120.0.6099.217 (Official Build) (64-bit)
 - ChatHub: Version v2.0.3

**Comment by wong2** [comment]
Thanks for reporting, there's a bug in the latest version. I'll release a fix today.

**Comment by digitalattorney** [comment]
> Thanks for reporting, there's a bug in the latest version. I'll release a fix today.

Thanks Wong. I still see the same issue. Do I need to update the extension? Remove and reinstall? Or _____ ?

**Comment by wong2** [comment]
The release is still waiting for Chrome web store review.

**Comment by endaye** [comment]
<img width="1512" alt="image" src="https://github.com/chathub-dev/chathub/assets/4829591/4b4ee143-24da-46ea-9bdc-1a6e555c5c08">

same issue on macOS

OS: macOS 14.2.1 (23C71)
Browser: Chrome is up to date - Version 120.0.6099.217 (Official Build) (64-bit)
ChatHub: Version v2.0.4

**Comment by digitalattorney** [comment]
> The release is still waiting for Chrome web store review.

I check daily. How long does the process usually take?

**Comment by wong2** [comment]
It usually takes 1 day. But this time it's unusually long.

**Comment by digitalattorney** [comment]
Got it. Thanks for getting back! Love the app by the way. Extremely useful.

**Comment by wong2** [comment]
v2.1.0 has been released!
You can wait for Chrome to auto update, or [update manually](https://doc.chathub.gg/miscellaneous/update-manually)

**Comment by digitalattorney** [comment]
Beautiful. 2.1.0. Got it. Thanks!
