### ISSUE TITLE
"Copy" Last Response Button

### ISSUE THREAD

**Issue by digitalattorney** [chathub-dev/chathub#1018]
A "Copy" button on each chat window specifically designed to copy the last generated response in Markdown format directly to the clipboard. This enhancement focuses on improving the interface's usability by facilitating easy and efficient reuse of the latest response Markdown format.

**Comment by digitalattorney** [comment]
Found the copy feature. I'm not sure about support for Markdown, but I'll see later and if it's not there, I'll request it.

**Comment by wong2** [comment]
It copies markdown.
