### ISSUE TITLE
希望适配一下手机界面

### ISSUE THREAD

**Issue by bilibili2233a** [chathub-dev/chathub#102]
现在的左右比例在手机上感觉压根不对
分成上下两个部分才对
![Screenshot_20230318_160808_com.kiwibrowser.browser.dev_edit_481090788233881.jpg](https://user-images.githubusercontent.com/99982054/226093799-d39a003c-2a11-4d43-9da8-6d5147023dd1.jpg)

**Comment by bilibili2233a** [comment]
![Screenshot_20230318_163200.jpg](https://user-images.githubusercontent.com/99982054/226094739-78d00a5b-9d8c-4b0c-8efa-e9937be838ff.jpg)

**Comment by hziling** [comment]
你用的kiwi哪个版本，为什么我的kiwi安装不了，提示插件不兼容

**Comment by bilibili2233a** [comment]
最新的111dev版，直接点击打开链接自动重定向到谷歌浏览器插件商店的插件详情页面，点击就安装成功

**Comment by bilibili2233a** [comment]
> 你用的kiwi哪个版本，为什么我的kiwi安装不了，提示插件不兼容

![Screenshot_20230324_204341_com.kiwibrowser.browser.dev.jpg](https://user-images.githubusercontent.com/99982054/227524553-22644a94-b6ff-4a70-8acc-f949f0d03f9f.jpg)

![Screenshot_20230324_204143_com.kiwibrowser.browser.dev.jpg](https://user-images.githubusercontent.com/99982054/227524554-efee4a53-f617-4abe-b0d4-7e2cb395b771.jpg)

直到现在又去看了一遍商店，还是可以用的
