### ISSUE TITLE
InvalidRequest in Brave browser 

### ISSUE THREAD

**Issue by Evantix** [chathub-dev/chathub#1022]
First of all, I love the extension. I just bought premium to support your work!

I just wanted to report that I keep receiving an "InvalidRequest" error on the Brave browser. I haven't seen any other reports of this issue.  The extension works perfectly fine on chrome but unfortunately not on Brave.

**Comment by Evantix** [comment]
I forgot to mention that an InvalidRequest error occurred while using Bing in Brave Browser

**Comment by wong2** [comment]
Thanks, I will take a look.

**Comment by wong2** [comment]
Weird, I just downloaded Brave and it's working fine.

**Comment by Evantix** [comment]
This will only work for a few requests. After that, it will return as an InvalidRequest. I tried reinstalling the extension, and it worked again for a few requests, and then again InvalidRequest. 

![Brave](https://github.com/chathub-dev/chathub/assets/157067393/3f561096-b37c-4e5a-b52f-824b3985a726)

**Comment by Evantix** [comment]
Are there any updates on this?
