### ISSUE TITLE
Chatgpt always pops up a popup robot check every question. 

### ISSUE THREAD

**Issue by cnnsbs** [chathub-dev/chathub#1025]
**Describe the bug**
Chatgpt always pops up a popup robot check every question. 

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser : chrome
 - ChatHub Version v2.1.0

![20240119_이미지_001](https://github.com/chathub-dev/chathub/assets/1485557/384a6196-b6c8-4ca5-acfc-a3fa180842cd)

**Comment by jiongjiongJOJO** [comment]
me too

**Comment by jiongjiongJOJO** [comment]
> **Describe the bug** Chatgpt always pops up a popup robot check every question.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Win11
> * Browser : chrome
> * ChatHub Version v2.1.0
> 
> ![20240119_이미지_001](https://private-user-images.githubusercontent.com/1485557/297998394-384a6196-b6c8-4ca5-acfc-a3fa180842cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTMxOTgsIm5iZiI6MTcwNTY1Mjg5OCwicGF0aCI6Ii8xNDg1NTU3LzI5Nzk5ODM5NC0zODRhNjE5Ni1iNmM4LTRjYTUtYWNmYy1hM2ZhMTgwODQyY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDgyODE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBiYWRhNzY1NDAyYzMwMDIzZDM4Y2M3NmRiY2EyOTNiNGUzZWFkM2FiMWNjOTJkZDJiNWNkZDBmYmNmMDgyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OtzBhKX3c3HpaDJmyHqnWFK40Cz5wIabu5qLUMPwlrc)

where is v2.1.0 ?

**Comment by wong2** [comment]
Thanks for reporting. We have noticed this problem, and it will be fixed in the next version.

**Comment by shikikoumei** [comment]
me too.

**Comment by stardate0** [comment]
Mine as well, Thanks!
ChatHub - All-in-one chatbot client
2.1.0
Windows 10 
Chrome 120.0.6099.225

**Comment by tricstar** [comment]
Mine as well, Thanks!

Mac OS Ventura 13.6.1
Chrome  120.0.6099.234 & Arc 1.26.0 (45314)
ChatHub 2.1.0

**Comment by arrowclub** [comment]
me too.
Every time!!!
What happenned?

**Comment by arrowclub** [comment]
> Thanks for reporting. We have noticed this problem, and it will be fixed in the next version.

How can I check to see if the upgrade is complete?

**Comment by wong2** [comment]
We're still waiting reviews from Chrome web store. I will let you know by replying this thread.

**Comment by arrowclub** [comment]
> We're still waiting reviews from Chrome web store. I will let you know by replying this thread.

Understood. Thank you very much. I am looking forward to solving it.

**Comment by digitalattorney** [comment]
Hey Wong. Just adding my 2 cents here as well. Same error. Glad you're on it. Thanks!

**Comment by Mosrvs-2023** [comment]
Please fix this... or at least change the captcha service you are using... literally the most annoying captcha I've ever encountered.. like... I'm apallaed at whoever decided this was a good way to "Verify we are human" ... GPT4 vision could school humans in ths anyways..

![image](https://github.com/chathub-dev/chathub/assets/122230741/db5a07c7-e491-4eaf-9dce-b963aea196c4)
![image](https://github.com/chathub-dev/chathub/assets/122230741/f2636e16-e8f9-43b3-8e84-81decb7a781a)

**Comment by Mosrvs-2023** [comment]
Please.. this is the one of the coolest and most useful extensions.. this is extremely discouraging 

![image](https://github.com/chathub-dev/chathub/assets/122230741/f83c83bd-3b0d-42f0-a9cd-a23d8d11f372)
![image](https://github.com/chathub-dev/chathub/assets/122230741/ddbeac5a-90b5-4996-836e-40fac5c80b8b)
![image](https://github.com/chathub-dev/chathub/assets/122230741/ce0223c6-5205-4f2f-a143-01590b5bb45b)
![image](https://github.com/chathub-dev/chathub/assets/122230741/e4d25999-64a8-4f44-a206-bde62d127397)
![image](https://github.com/chathub-dev/chathub/assets/122230741/6c4cdb9e-71d9-42f1-b48a-ed4e72843151)
![image](https://github.com/chathub-dev/chathub/assets/122230741/17d956a7-65fb-4ef6-a8ce-a64a62ea68cd)
![image](https://github.com/chathub-dev/chathub/assets/122230741/4e362021-d35c-4a69-b8a6-84ca61830e2d)
![image](https://github.com/chathub-dev/chathub/assets/122230741/20b45056-825c-4fda-b568-683dceea78d7)
![image](https://github.com/chathub-dev/chathub/assets/122230741/414132f8-f2d4-4d50-9046-a073abe10194)


I give up.

**Comment by digitalattorney** [comment]
Yeah the sort of captcha is sort of annoying. I'm not complaining. I'm grateful for this tool.. Even purchased it and the guys seem on top of things...

this CAPTCHA though... yeah... It has the ability to make even the most intelligent human being feel like a schoolchild. .You gotta show you’re human by picking out pictures of buses and bicycles. And you're thinkin', "What is this, Romper Room?" And when you get it wrong, and it's back to square one, that's when you start questioning your whole existence.

**Comment by wong2** [comment]
@Mosrvs-2023 This CAPTCHA is triggered by OpenAI, a change by them yesterday is causing it to popup on every message. We have figured out How to bypass them. Please wait for the next version!

**Comment by tktktktjp** [comment]
me too

win11

chromebrowse

v2.1.0

How can I get rid of the robot check?

It is so inconvenient.

**Comment by wong2** [comment]
Please upgrade to v2.1.3, which fixed this issue. https://doc.chathub.gg/miscellaneous/update-manually

**Comment by digitalattorney** [comment]
Fixed! Thanks Wong.
