### ISSUE TITLE
ChatGPT not available

### ISSUE THREAD

**Issue by rzwetsch** [chathub-dev/chathub#1026]
ChatGPT not chatting. Claude, Bard and Bing working fine.

**Desktop (please complete the following information):**
Windows 11
Chrome
V2.1.0

**Comment by mutti0309** [comment]
同じく利用できません。
![ChatHub](https://github.com/chathub-dev/chathub/assets/147227693/936974b8-db5f-4ead-ad12-a52780856890)
CHATGPT以外は正常です。
早期の回復を願っております。

**Comment by wong2** [comment]
Please upgrade to v2.1.3, which fixed this issue. https://doc.chathub.gg/miscellaneous/update-manually

**Comment by rzwetsch** [comment]
Is V2.2.0 the latest and greatest?

**Comment by wong2** [comment]
Yes.

rzwetsch ***@***.***>于2024年1月22日 周一下午10:43写道：

> Is V2.2.0 the latest and greatest?
>

**Comment by rzwetsch** [comment]
Thank you.

Gemini API key missing?

**Comment by wong2** [comment]
> Gemini API key missing?

You need to set your Gemini API key in ChatHub Settings page
