### ISSUE TITLE
Only 6 all in one chat available?

### ISSUE THREAD

**Issue by jakkaas** [chathub-dev/chathub#1027]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]: Windows 11
 - Browser [e.g. chrome, brave]: Edge
 - ChatHub Version [you can find it in ChatHub Settings]:2.10

Hello. I have recently subscribed to a premium subscription.

I have some questions. It seems that despite selecting more than 6 chatbots in the settings, I am only able to chat with 6. Additionally, even though I have not chosen Bing and Perplexity in the settings, they are still showing in All in One Chat. I believe this may be a bug, as I expect to be able to chat with as many agents as I choose, and not with the ones I have deselected.

Edit: I can see I can change chat provider in all in one chat. But I would like more than 6 options for all in one chat.

![image](https://github.com/chathub-dev/chathub/assets/43289832/b70bfff6-268f-40b9-8c2a-f40f61d52ebd)
![image](https://github.com/chathub-dev/chathub/assets/43289832/a76900f9-bf09-4847-8b07-0204b8bd6e0c)

**Comment by wong2** [comment]
Yes, we only support up to 6 chats at the moment.
