### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by SP0Workstation** [chathub-dev/chathub#103]
New Bing显示(404 (https://www.bing.com/turing/conversation/create)) ChatGPT显示Failed to fetch

**Comment by happyZew** [comment]
我也是

**Comment by wong2** [comment]
Duplicate of #99

**Comment by grdata2021** [comment]
我也是

**Comment by murazi** [comment]
一样,chatGPT也是用不了,之前的chatgpt和newbing是都可以的
