### ISSUE TITLE
Chat GPT's GPT4 cannot be used with "Our systems have detected unusual activity from your system. Please try again later.

### ISSUE THREAD

**Issue by fuku2911** [chathub-dev/chathub#1031]
**Please explain the bug.
If you use GPT-4 in ChatGPT webapp mode, from today.
Please try again later.
Please try again later.
I was able to use it until yesterday.

I have a paid plan for ChatGPT.
If I change to GPT-3.5, I can use it.
When I change to GPT-4 again, I get the above error message and cannot use it.
![スクリーンショット 2024-01-21 132019](https://github.com/chathub-dev/chathub/assets/43802781/7782d0bd-f26f-44f5-a22e-c5d1f861afdb)
![スクリーンショット 2024-01-21 132121](https://github.com/chathub-dev/chathub/assets/43802781/cef95620-66ce-4d38-bbb9-109ba2a8b87d)

**Desktop (please fill in the following information):**.
 - OS : OS : Windows 11
 - Browser : chrome,.
 - ChatHub version v2.1.0

**Comment by wong2** [comment]
Please upgrade to v2.1.3, which fixed this issue. https://doc.chathub.gg/miscellaneous/update-manually
