### ISSUE TITLE
可否添加功能:历史记录直接导出为markdown

### ISSUE THREAD

**Issue by DDesperate** [chathub-dev/chathub#1032]
如题

**Comment by DDesperate** [comment]
或者我想知道历史记录是存在什么文件中的，可否我自己导出？

**Comment by wong2** [comment]
你是想把所有聊天记录导出为一个markdown吗？

**Comment by DDesperate** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月24日(星期三) 中午11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chathub-dev/chathub] 可否添加功能:历史记录直接导出为markdown (Issue #1032)





 
你是想把所有聊天记录导出为一个markdown吗？
