### ISSUE TITLE
希望为perplexity 的回答增加来源网页引用连接显示

### ISSUE THREAD

**Issue by piaodaxiawork** [chathub-dev/chathub#1033]
![image](https://github.com/chathub-dev/chathub/assets/143238549/d05df6cb-3010-4f53-ae46-daaf83632fe5)

perplexity 的回答和bing 一样，是有引用的网页连接的。
bing的回答目前可以显示引用的连接，而perplexity不能。
希望可以增加来源网页引用连接显示。

**Comment by wong2** [comment]
perplexity的接口里没有返回引用信息，所以。。

**Comment by herman925** [comment]
> perplexity的接口里没有返回引用信息，所以。。

所以是其實有引用只是不顯示，還是完全沒有顯示？

**Comment by wong2** [comment]
> > perplexity的接口里没有返回引用信息，所以。。
> 
> 所以是其實有引用只是不顯示，還是完全沒有顯示？

没有引用
