### ISSUE TITLE
Chinese chatbots??

### ISSUE THREAD

**Issue by mokaasa** [chathub-dev/chathub#1035]
There is so many Chinese chatbots. How can I use them?. All of them needs registration by Chinese phone number which not having it?. It is now appearing as all Chinese chatbots are useless outside china. Could you please make their login easy and accessable?
Thanks

**Comment by wong2** [comment]
Unfortunately, these phone number requirements are restrictions from the Chinese bot providers.
However, Chinese chatbots are usually optimized for Chinese usage, and doesn't perform well for English, so I think you can just ignore them.
Perhaps I should hide them for none-Chinese users.

**Comment by mokaasa** [comment]
Ok got it thanks a lot
Please give more focus one files upload and chatting with them with different chatbot as same time
