### ISSUE TITLE
Preplexity not working

### ISSUE THREAD

**Issue by vin2504** [chathub-dev/chathub#1036]
I'm unable to ask questions to  Perplexity AI from my ChatHub chrome extension. 

When I ask a question I only see 3 dots loading forever, I have seen this issue from 01/25/2024. I have tried asking Perplexity AI from Perplexity website and its seems like its working in their website. So I think there's some issue from ChatHub's end.
<img width="1417" alt="Screenshot 2024-01-26 at 1 44 50 PM" src="https://github.com/chathub-dev/chathub/assets/127546468/d816ae45-9e0f-4a3c-8c97-956518c645c9">

**Desktop (please complete the following information):**
 - OS: MAC OS 14.1.2 (23B92)
 - Browser: Chrome 
 - ChatHub Version:  v2.2.1

**Comment by Evantix** [comment]
Same here

**Comment by tohipster** [comment]
So am l.

OS: Windows 11 Pro (23H2)
Browser: Chrome
ChatHub Version: v2.2.1

**Comment by wong2** [comment]
Thanks for reporting, this issue has been fixed in next version of ChatHub.

**Comment by akiraririka** [comment]
me too. how can I make it work again!? It wont work at all.

**Comment by wong2** [comment]
Please wait for a new release.

**Comment by wong2** [comment]
Fixed in v2.3.0

How to update manually: https://doc.chathub.gg/miscellaneous/update-manually
