### ISSUE TITLE
是否直接使用alias 快速适配最新的模型，比如gpt-4-0125-preview

### ISSUE THREAD

**Issue by butterl** [chathub-dev/chathub#1037]
当前的 'gpt-4-turbo' 默认使用的是1106 的，是否直接使用alias 快速适配最新的模型，比如gpt-4-0125-preview

 private getModelName() {
    const { chatgptApiModel } = this.config
    if (chatgptApiModel === 'gpt-4-turbo') {
      return 'gpt-4-1106-preview'
    }
    if (chatgptApiModel === 'gpt-3.5-turbo') {
      return 'gpt-3.5-turbo-1106'
    }
    return chatgptApiModel
  }

**Comment by wong2** [comment]
嗯，下一个版本改成用alias了

**Comment by wong2** [comment]
2.2.2 已更新
