### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by forthrin** [chathub-dev/chathub#1039]
Do you have plans for a pure CLI version?

If no, what other projects provides this, with support for different services?

**Comment by wong2** [comment]
There's no plan for a CLI version.

**Comment by wong2** [comment]
Have you checked this? https://llm.datasette.io/en/stable/

**Comment by forthrin** [comment]
Thanks! I tried [installing](https://simonwillison.net/2023/Aug/1/llama-2-mac/), but all I get is an empty error message.

```
$ llm -m l2c 'Hello'
Error: 
```
