### ISSUE TITLE
已经加入new Bing，之前都已经可以正常使用了，现在显示‘ Join new Bing waitlist’

### ISSUE THREAD

**Issue by Git0503** [chathub-dev/chathub#104]
![QQ截图20230318204959](https://user-images.githubusercontent.com/49622794/226114093-58865dfd-3be6-40bd-832c-f68e1b43a5f6.png)
![QQ截图20230318205811](https://user-images.githubusercontent.com/49622794/226114067-d7121fa1-143c-435e-8a9e-941a4e89ee14.png)

**Comment by wong2** [comment]
图片没传上来

**Comment by benywon** [comment]
我也是 突然不能用了

**Comment by phields** [comment]
有可能是这个插件导致的，用了导致账号被打回到waitlist

**Comment by bushnerd** [comment]
清除cookie，使用魔法试试看，我之前在没有用这个扩展的时候也偶尔出现过这样的问题，但是清除cookie，使用魔法就可以用了。

**Comment by wong2** [comment]
看来和插件没什么关系：https://twitter.com/pingchn/status/1637146336364740608
