### ISSUE TITLE
^1

### ISSUE THREAD

**Issue by wilchfort** [chathub-dev/chathub#1044]

**Comment by wilchfort** [comment]
„broom“ that will clean all open windows at the same time, instead of individually.  Thanks.

**Comment by wong2** [comment]
Duplicate of previous issue.

**Comment by digitalattorney** [comment]
> „broom“ that will clean all open windows at the same time, instead of individually. Thanks.

Just click Refresh.

**Comment by wong2** [comment]
Many people have requested this, so I've added a button in next version
<img width="915" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/a524feb7-732b-4a92-9268-b4dcfa2ef602">
