### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by MaxZhuravlev** [chathub-dev/chathub#1045]
Mobile version which, for example connects to PC and runs there, but interface is on mobile => more accessible

**Comment by wong2** [comment]
There is no plan for a mobile version, because the UI would be hard to use on a mobile device

**Comment by SeanBannister** [comment]
For anyone else looking into this Kiwi browser on mobile seems to be able to run it but with the interface problems https://github.com/chathub-dev/chathub/issues/261
