### ISSUE TITLE
4 out of the 6 Chatbots are not working. This is too much. First it was 2, then 3, now 4.  (Windows Chrome) 2.3.0

### ISSUE THREAD

**Issue by danieltrapanese2** [chathub-dev/chathub#1046]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by danieltrapanese2** [comment]
![chrome_axGQodYiAC](https://github.com/chathub-dev/chathub/assets/158115314/2685ade8-be1a-411a-a1f9-f92f15974fcb)

**Comment by wong2** [comment]
I will check this

**Comment by wong2** [comment]
Please click the "visit LMSYS.org" link, it should fix Mixtral and Llama 2 for you.

**Comment by digitalattorney** [comment]
Same here
![image](https://github.com/chathub-dev/chathub/assets/5568362/9d07b803-dcca-4104-90dd-51643ff3c926)

**Comment by wong2** [comment]
@digitalattorney Have you tried to click the "visit LMSYS.org" link?

**Comment by digitalattorney** [comment]
@wong2 Video

https://github.com/chathub-dev/chathub/assets/5568362/edc5aa32-12f1-46ff-9acb-b60b79e4b1aa

**Comment by digitalattorney** [comment]
Llama and Mixtral fixed.

Claude seems to have an error now
![image](https://github.com/chathub-dev/chathub/assets/5568362/b67b1cf8-eff4-4fde-a80e-33317c4e697b)

"{"type":"overloaded_error","message":"Overloaded"}"

No big issue for me, but you'll probably here it from others, I'm guessing.

**Comment by wong2** [comment]
Yes, Claude is now overloaded, their website is also giving this error now.

**Comment by lindathomass** [comment]
Good luck to ones who paid for this in era where there are so many free alternatives.

**Comment by digitalattorney** [comment]
Good luck on free alternatives 😊 Nothing is free. The developer is paying for you, until it costs them too much.

**Comment by Evantix** [comment]
Until now, there have been more days with issues than without them. This has been very frustrating.

**Comment by wong2** [comment]
Some bots rely on reverse engineering, so when the original provider changes, it breaks ChatHub

**Comment by LicAC** [comment]
Same here with my Premium account. Perplexity NEVER works. And the more rare AIs like Grok or Gemini, sometimes work, sometimes not.

**Comment by digitalattorney** [comment]
I must point out too that Perplexity previously had some issues (I refrain from using it on this platform since I believe it's more valuable when utilized directly on the site). However, it is functioning perfectly now.

https://github.com/chathub-dev/chathub/assets/5568362/58bfd799-d1f7-4e97-90d9-5cdf4dca0071

**Comment by wong2** [comment]
@LicAC Is there any errors for Perplexity?

**Comment by digitalattorney** [comment]
@wong2  Update. It's happenieng again. This time though, even after  "visit LMSYS.org" link, it still happens. So far I've noticed it Llama2 and Mixtral.

https://github.com/chathub-dev/chathub/assets/5568362/e3429b4a-dc46-4b96-9ad2-dee270af00c0

**Comment by Evantix** [comment]
Same issue for all of them. 
![image](https://github.com/chathub-dev/chathub/assets/157067393/9114c274-3109-43c5-9b57-c4526ebb166b)

**Comment by digitalattorney** [comment]
@wong2 @Evantix I just tried. Didn't work at first. Then I click the  "visit LMSYS.org" link and it's fine now.


https://github.com/chathub-dev/chathub/assets/5568362/47ba9b7f-19a6-4154-8ff3-9011ec6d0db6

**Comment by ramirlm** [comment]
How do I fix it? It's definitely annoying me and making me regret my purchase!

**Comment by wong2** [comment]
OpenAI changed their API today, which results in ChatGPT loading forever in CahtHub. I've fixed this accordingly, and the new version is waiting for Chrome webstore reviews.

**Comment by ramirlm** [comment]
This is not fixed @wong2 – still having most LLMs not working. Only perplexity is back

**Comment by wong2** [comment]
@ramirlm Doesn't ChatGPT work for you after upgrading to 2.5.0? Is there any error message?

**Comment by ramirlm** [comment]
ChatGPT works @wong2 – But only ChatGPT, Bing, and now perplexity again work for me. Claude is giving a 403 forbidden error now.

**Comment by ramirlm** [comment]
All others throw errors

**Comment by wong2** [comment]
Can you visit https://claude.ai and try again?

**Comment by ramirlm** [comment]
I have visited and it works properly there @wong2

**Comment by wong2** [comment]
@ramirlm Then you get back to ChatHub, does Claude work now?

**Comment by ramirlm** [comment]
@wong2 I still get a 403

**Comment by wong2** [comment]
@ramirlm That's weird, I'll take a look.

**Comment by wong2** [comment]
@ramirlm Can you post the whole error message here? Is it just "403" or more?

**Comment by wong2** [comment]
@ramirlm If you know how to inspect http requests with Chrome devtools, can you check the request to claude.ai in ChatHub that results in 403? Can you post the response of it here?

**Comment by Evantix** [comment]
Is there any update for the Lama2, Mixtral, and Vicuna LLM?

I have to keep authorizing every time I sue ChatHib **Please visit [LMSYS.org](https://chat.lmsys.org/) and try again** 

![image](https://github.com/chathub-dev/chathub/assets/157067393/1ebc0215-4475-4ca5-b832-5ecb5d5836d5)

**Comment by wong2** [comment]
Please try 2.6.0, it should fix claude, llama

**Comment by worsin** [comment]
I try to visit LMSYS.org and i get a cloudflare Human test that is broken and wont complete.
