### ISSUE TITLE
通用api不支持glm4，报错：令牌已过期或验证不正确！

### ISSUE THREAD

**Issue by stevejoeyms** [chathub-dev/chathub#1047]
使用glm4的api链接报错{"error":{"code":"401","message":"令牌已过期或验证不正确！"}}

配置参数如下：
API Endpoint：customer
https://open.bigmodel.cn/api/paas/v4/chat/completions

api key：
xxx

模型名称：
glm-4

**Comment by wong2** [comment]
原因是智谱的API不兼容OpenAI的格式：https://open.bigmodel.cn/dev/api#auth
