### ISSUE TITLE
无法使用此拓展

### ISSUE THREAD

**Issue by hinayand** [chathub-dev/chathub#105]
# 基础情况
在使用此拓展访问NewBing的时候，无论什么消息都会出现报错

```
 (404  (https://www.bing.com/turing/conversation/create))
```
# 我的猜测
这个拓展使用的API已经被Bing封锁了
# 我找到的新的NewBing API
```
wss://sydney.bing.com/sydney/ChatHub
```
# 我的请求
希望作者尽快修改API地址

**Comment by hinayand** [comment]
好吧，根据我的测试，只有翻墙才能正常的使用该拓展

**Comment by wong2** [comment]
Duplicate of #99
