### ISSUE TITLE
Chatgptのみ全く反応しない

### ISSUE THREAD

**Issue by mutti0309** [chathub-dev/chathub#1051]
chatgptのみが3.5と4と共に両方反応しません。bing.bard.claudeは問題ないです。
対応お願いします。

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
 - ChatHub Version [設定 (v2.4.3)]

**Comment by wong2** [comment]
私たちはすでにChatGPTに問題があることを知っていますが、次のバージョンで修正される予定ですので、お待ちください。

**Comment by soraterachoconana** [comment]
ChatGPTが使えないことはすごく不便です。次のバージョンはいつ頃ローンチ予定ですか？

**Comment by wong2** [comment]
申し訳ありませんが、Chromeストアの審査時間が予想よりも長くかかっています。

**Comment by soraterachoconana** [comment]
おおよそで良いのですが、Chromeストアから審査／承認される日数はどれくらいを想定していますか？

**Comment by wong2** [comment]
希望今晩審査が通るといいな、その時はここでお知らせします。

**Comment by soraterachoconana** [comment]
Okay

**Comment by wong2** [comment]
2.5.0 released! Please upgrade

2.5.0 リリース！アップグレードしてください。
