### ISSUE TITLE
Claude Error: {"type":"error","error":{"type":"permission_error","message":"Invalid model"}}

### ISSUE THREAD

**Issue by lindathomass** [chathub-dev/chathub#1052]
**Describe the bug**
Claude is not working at all.
It gives this Error: 

> {"type":"error","error":{"type":"permission_error","message":"Invalid model"}}

![Screenshot 2024-02-06 at 8 15 47 AM](https://github.com/chathub-dev/chathub/assets/158158831/175d06b7-aeb8-4919-8150-7ef7a42ef370)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser brave
 - ChatHub Version 2.5.1

**Comment by wong2** [comment]
To anyone meeting this error, if you know how to inspect network request use Chrome devtools, please help me with this information:

1. Go to https://claude.ai
2. Open Chrome devtools
3. Chat with claude.ai
4. Search a network request ending with `/completion` in the network tab of Chrome devtools
5. Take a screenshot of the Payload

It looks like this:

<img width="495" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/c38def00-d01f-4d8f-9912-2a92c74fc98a">

**Comment by HailPHP** [comment]
![claudeShoot](https://github.com/chathub-dev/chathub/assets/22851730/016d77c1-578e-4373-96de-431a1b532f5f)
遇到了同样的问题，这个上我这边按上述描述的截图

**Comment by wong2** [comment]
@HailPHP 感谢！很有帮助

**Comment by wong2** [comment]
Can you try the latest version 2.6.0?
