### ISSUE TITLE
ChatGPT: Our systems have detected unusual activity from your system

### ISSUE THREAD

**Issue by soraterachoconana** [chathub-dev/chathub#1053]
ChatGPTを使用していると、以下エラーメッセージが出てリクエストに応答しません。これはなにが原因なのでしょうか？
Our systems have detected unusual activity from your system. Please try again later.

**Comment by wong2** [comment]
This will be fixed in next version. ChatGPT is changing rapidly recently, I'm trying hard to keep up with it.

**Comment by wong2** [comment]
Fixed in v2.6.7, please upgrade
