### ISSUE TITLE
Bard: [GET] "https://bard.google.com/": <no response> Failed to fetch

### ISSUE THREAD

**Issue by lindathomass** [chathub-dev/chathub#1056]
Today Bard is not working.
![Screenshot 2024-02-08 at 6 16 30 PM](https://github.com/chathub-dev/chathub/assets/158158831/a6ea5ea1-5f80-4fbd-aa53-605c46eb35b1)

**Desktop (please complete the following information):**
- OS: Mac
- Browser: Chrome
- ChatHub Version: 2.6.5

**Comment by yookibooki** [comment]
Bard is now Gemini (bard.google.com is redirecting to gemini.google.com/app)

**Comment by wong2** [comment]
Yes, Google changed the domain of bard to gemini.
I've updated the extension and submitted to Chrome webstore for review.

**Comment by wong2** [comment]
Fixed in v2.6.6
