### ISSUE TITLE
功能建议：添加vimium C支持

### ISSUE THREAD

**Issue by bushnerd** [chathub-dev/chathub#106]
非常感谢你的插件，的确很好用。应该很多人是重度vim使用者，希望能在扩展中增加vimium的支持。
[Inject into other extensions](https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions)中已经详细的说明。
步骤应该来说很简单，因为我按照说明，查看了一下，您的扩展里只有一个html文件。

不过最大的问题是关于
[Necessary conditions](https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions#necessary-conditions)。只允许使用```Manifest V2```而，不允许使用```manifest V3```。

我不确定您的扩展使用使用了V3的一些特定功能，如果需要修改的话，我查到需要做如下几个步骤：
将 manifest_version 的值改为 2
将 service_worker 替换为 background.page 或 background.scripts
将 action API 分别替换为 pageAction 和 browserAction API
使用 tabs.executeScript() 方法代替 scripting.executeScript() 方法

**Comment by wong2** [comment]
我这个插件里需要跳转的地方很少，好像接入Vim模式意义不大?

**Comment by bushnerd** [comment]
用来复制粘贴比较方便。
