### ISSUE TITLE
Gemini/Bard not working

### ISSUE THREAD

**Issue by Keltusar** [chathub-dev/chathub#1060]
With the Update from Bard to Gemini its sadly not working anymore and only shows an error
![Screenshot 2024-02-09 095437](https://github.com/chathub-dev/chathub/assets/91081661/35c22036-2833-4cf0-abdc-0e0323170054)

**Comment by wong2** [comment]
Please upgrade to v2.6.6

**Comment by Keltusar** [comment]
works
