### ISSUE TITLE
Web Access doesn't work

### ISSUE THREAD

**Issue by saturnxxi** [chathub-dev/chathub#1061]
Purchasing this extension was motivated by the desire to have web access with ChatGPT, but unfortunately, it is not functioning as expected.

<img width="825" alt="Screenshot 2024-02-09 at 18 19 45" src="https://github.com/chathub-dev/chathub/assets/1018999/43a3986f-3e9c-4ee6-b623-e6dec7caaa49">

Inspired by https://github.com/chathub-dev/chathub/wiki/Web-Access

**Comment by wong2** [comment]
I will take a look
