### ISSUE TITLE
Gemini Advanced?

### ISSUE THREAD

**Issue by cpiprint** [chathub-dev/chathub#1062]
Put in an API key and it says Gemini Pro...is that the advanced version I signed up for?

**Comment by wong2** [comment]
There is no API for Gemini Advanced yet

**Comment by cpiprint** [comment]
So the api here is not the advance model?On Feb 9, 2024, at 7:56 PM, wong2 ***@***.***> wrote:﻿
There is no API for Gemini Advanced yet

**Comment by wong2** [comment]
No, this is Gemini Pro, not Gemini Ultra
