### ISSUE TITLE
chatgptのみが3.5と4とともに両方反応しません。

### ISSUE THREAD

**Issue by mutti0309** [chathub-dev/chathub#1064]
chatgptのみが3.5と4とともに両方反応しません。bing.bard.claudeは問題ないです。
対応お願いします。
chatgptのみが赤字で
Our systems have detected unusual activity from your system. Please try again later.
上記のように表記されます。

デスクトップ (次の情報を入力してください):

OS：【Mac】
ブラウザ[クローム]
ChatHub バージョン [設定 (v2.6.6)]

**Comment by wong2** [comment]
Duplicate of #1053
