### ISSUE TITLE
Claude claims I'm not logged in but I am

### ISSUE THREAD

**Issue by ThatAdamGuy** [chathub-dev/chathub#1066]
**Describe the bug**
Attempting to query Claude results in "There is no logged-in Claude account in this browser."

Even after I log out and log back in to Claude on the same browser, I still get the same error message.

No issues accessing other LLMs.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser:  Arc
 - ChatHub Version [you can find it in ChatHub Settings]:  2.6.7

**Comment by ThatAdamGuy** [comment]
Hi there,

I'm finding this issue really frustrating, since Claude is one of the LLMs I use most and I'm unable to access it with Chathub.  Could you please look into this?  Thanks!

**Comment by wong2** [comment]
Unfortunately I can't reproduce this issue myself. Can you open https://claude.ai/api/organizations and take a screenshot?

**Comment by ThatAdamGuy** [comment]
Pasted below, with some redactions for privacy

[{"uuid":"[redacted]","name":"[redacted]","settings":{"claude_console_privacy":"default_private"},"capabilities":["api","legacy_unpaid_api_access"],"billing_type":null,"free_credits_status":null,"api_disabled_reason":null,"api_disabled_until":null,"billable_usage_paused_until":null,"created_at":"2023-03-18T17:28:01.088979Z","updated_at":"2024-01-10T23:58:58.716313Z","active_flags":[]},{"uuid":"8b4b851b-edb6-45c3-bf4f-d059164b6276","name":"[redacted]'s Organization","settings":{"claude_console_privacy":"default_private"},"capabilities":["has_chats_from_console","chat"],"billing_type":null,"free_credits_status":null,"api_disabled_reason":null,"api_disabled_until":null,"billable_usage_paused_until":null,"created_at":"2024-01-10T23:58:58.716313Z","updated_at":"2024-01-27T09:37:01.709282Z","active_flags":[]}]

**Comment by wong2** [comment]
Thanks, it seems the first organization is for API use only. I think that's the reason.
