### ISSUE TITLE
Perplexity: Unclear if co-pilot is activated by default and, if not, how one could activate it

### ISSUE THREAD

**Issue by ThatAdamGuy** [chathub-dev/chathub#1067]
On the Perplexity web site, even free users can activate Co-pilot (more sophisticated) mode for a limited number of queries per period.

However, it's unclear in Chathub whether this mode is already selected and, if not, how it could be selected.

**Comment by wong2** [comment]
No, we're not calling API of Perplexity website, so there's no Copilot
