### ISSUE TITLE
Affiliate link button.

### ISSUE THREAD

**Issue by vitaminR** [chathub-dev/chathub#1074]
Please add an affiliate link button.

**Comment by wong2** [comment]
There's an affiliate link at the footer of https://chathub.gg

**Comment by aceFlexxx** [comment]
Unfortunately, the link is 404 in the water at both the home page and when you are using the extension when it mentions details regarding it. affiliate.chathub.gg

**Comment by wong2** [comment]
@aceFlexxx Thanks, you can use this link: https://chathub.tolt.io/
