### ISSUE TITLE
Looks like github updates are getting slow

### ISSUE THREAD

**Issue by allentown521** [chathub-dev/chathub#1076]
I noticed that the chrome store updates are very frequent and solves a lot of problems, and the github version has been behind for 2 months at present, especially after the chatgpt update, the github version is unusable, is there any update plan recently?

**Comment by wong2** [comment]
It is true that the Github repo hasn't been updated recently, that's because we're relying on reverse engineering for services like ChatGPT, better to keep the method private, so it can last longer.

**Comment by mwgunt** [comment]
@wong2 I understand that you want to monetize your ChatHub browser extension, but do you have any plans to release the source code of ChatHub 2.x in the foreseeable future? Again, I understand that liberating the source code is your prerogative, but I would really appreciate it if the newer version of the source code were available on GitHub. Ultimately, it is up to you if you decide to free the code, but I am just asking.
