### ISSUE TITLE
Pi's answers cannot be fully displayed

### ISSUE THREAD

**Issue by jinma-wish** [chathub-dev/chathub#1077]
**Describe the bug**
Pi's answers cannot be fully displayed; currently, only the last sentence of the response is shown, while the rest of the response will flash by.

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - ChatHub Version: v2.6.7

<img width="1164" alt="image" src="https://github.com/chathub-dev/chathub/assets/144320505/c8cec4a4-aeff-448f-b83b-971a671c7d1a">

**Comment by wong2** [comment]
Fixed in the latest version
