### ISSUE TITLE
Poe模式无法使用，提示消息达到上限

### ISSUE THREAD

**Issue by darkunicon** [chathub-dev/chathub#1080]
![微信截图_20240219152304](https://github.com/chathub-dev/chathub/assets/81540344/7acc893e-f15b-4dc8-98db-17f2e5db76a0)
![微信截图_20240219152906](https://github.com/chathub-dev/chathub/assets/81540344/e418a28b-8394-4108-9f9d-6ac0e7b774f2)
![微信截图_20240219152718](https://github.com/chathub-dev/chathub/assets/81540344/505d98f2-f7a7-4d5d-8dc2-520b98e554eb)

Poe模式的Claude和ChatGPT无法使用，提示“你已经达到了该模型今日免费消息上限”
但是在Poe.com上可以正常使用，订阅积分未用完

 - OS: [Windows 10]
 - Browser [chrome 121.0.6167.185]
 - ChatHub Version [2.8.0]

**Comment by saodiawei** [comment]
我也遇到了

**Comment by wong2** [comment]
Poe改了些东西，导致接口失效了。

建议先用其它模式使用ChatGPT和Claude，因为这个兼容起来还有点麻烦，不一定很快搞定

**Comment by wong2** [comment]
Poe is no longer supported in ChatHub
