### ISSUE TITLE
User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by Spring79Max** [chathub-dev/chathub#1093]
**Describe the bug**
反复提示确认。确认后还是要确认。

**Desktop (please complete the following information):**
 - OS:windows
 - Browser chrome
 - ChatHub Version v2.9.1

**Comment by wong2** [comment]
是哪个机器人呢？

**Comment by Spring79Max** [comment]
bing

**Comment by ayugioh2003** [comment]
same

![image](https://github.com/chathub-dev/chathub/assets/5466631/dd83f1b3-0466-4d31-acf6-88696f90d03e)

![image](https://github.com/chathub-dev/chathub/assets/5466631/bcf9c953-b9f9-494a-8d6e-aa4d549e1de1)

**Comment by gengjiawen** [comment]
去这里问一下就好了，https://copilot.microsoft.com/， 应该是触发了微软的风控。
