### ISSUE TITLE
mistral

### ISSUE THREAD

**Issue by axxdy1991** [chathub-dev/chathub#1095]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by axxdy1991** [comment]
https://chat.mistral.ai/chat 这个最近很火，麻烦加一下

**Comment by wong2** [comment]
这个还没开放公测，所以先不加了
