### ISSUE TITLE
Premium Key Not Working From When It Was In PreSale (Lifetime)

### ISSUE THREAD

**Issue by verifiedsyckozis** [chathub-dev/chathub#1097]
**Describe the bug**
My premium key that I got when it was back in Presale in 2023 isn't working, and it was a Lifetime key for 5 devices.  I'd like it to work if you wouldn't mind.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]
 - ChatHub Version [2.110]

**Comment by verifiedsyckozis** [comment]
Sent an email.  I'll delete this when I get it fixed.  Thanks. :)

**Comment by wong2** [comment]
I've replied your email, let's keep the conversation there, thank you.
