### ISSUE TITLE
403 Error on a TON of AI sources

### ISSUE THREAD

**Issue by worsin** [chathub-dev/chathub#1098]
I am using the pro version.

The Following throw a 403 error.

Mixtral
Yi-Chat
Qwen 1.5
WizardLM
Gemma
Vicuna

I specifically bought this for access to these lol.  None of the ones I want work.

Hopefully I am just missing something.

**Comment by worsin** [comment]
I try to visit LMSYS.org and i get a cloudflare Human test that is broken and wont complete.

**Comment by worsin** [comment]
Further testing. This is an Edge Browser only bug.  I am able to visit LMSYS.org and pass the check on Chrome but not Edge.

I hate Chrome!! Please make this work on Edge.

**Comment by wong2** [comment]
> I try to visit LMSYS.org and i get a cloudflare Human test that is broken and wont complete.

I think this is the cause. We're relying on LMSYS.org to provide access for the chatbots you listed.
Is there some security related settings you can ajust in Edge browser?

**Comment by worsin** [comment]
It seems to happen with every Cloudflare Java check using Edge browser even other websites.

Edge is having problems with memory, its a known issue and it even affects images from showing on google images.
