### ISSUE TITLE
How can I use Perplexity's Pro Search (Premium) on ChatHub?

### ISSUE THREAD

**Issue by TMVN2024** [chathub-dev/chathub#1102]
Hello. Currently, I'm using Perplexity's Pro Search plan (premium). However, when I select Perplexity on ChatHub, I can only access the default free package with ChatGPT 3.5. How can I utilize Perplexity's Pro Search package on ChatHub? 

I hope you can provide an answer. Thank you.

**Comment by ThatAdamGuy** [comment]
Maybe related, but... Perplexity allows 5 uses of their Pro service daily to ALL users; it would be awesome if ChatHub would leverage that and just fall back as needed.
