### ISSUE TITLE
希望能兼容国产minimax的api

### ISSUE THREAD

**Issue by anrgct** [chathub-dev/chathub#1104]
希望能增加minimax的api，它有一些参数不兼容openAI的接口，直接套用会报错，如果自定义接口能有一个办法设置各种参数就好了
文档链接https://www.minimaxi.com/examination-center/text-experience-center

**Comment by wong2** [comment]
我看看

**Comment by wong2** [comment]
根据文档，它的接口是兼容OpenAI的，我自己试了下也成功了：

<img width="690" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/b13fbc82-461c-4f60-ac9f-a3218b2dd2a1">

你遇到什么问题呢？

**Comment by anrgct** [comment]
我没看文档，我用的是示例中的chatcompletion_pro接口而不是chatcompletion_v2，试了下可以的😂谢谢
