### ISSUE TITLE
POE接口消失

### ISSUE THREAD

**Issue by Juneone96** [chathub-dev/chathub#1107]
Chatgpt和Claude的poe接口消失了，如何解决
ChatHub版本：v2.12.0
![image](https://github.com/chathub-dev/chathub/assets/140543869/4785a8ab-b939-488d-92ea-a2ba7c18f725)

**Comment by wong2** [comment]
不再支持Poe了，建议使用其它方式使用ChatGPT和Claude

**Comment by wyih** [comment]
> 不再支持Poe了，建议使用其它方式使用ChatGPT和Claude

Claude封号太厉害，POE是我现在用Claude的主要方法，也年付了。如果是Web不方便支持，是否可以通过POE api来实现调用Claude?

**Comment by wong2** [comment]
Poe好像没有API？

**Comment by wyih** [comment]
有的，https://poe.com/api_key 但只对付费用户开放，和付费的积分是共享的。您如果有需要，我可以提供Api给您测试。https://github.com/poe-platform/fastapi_poe 这个是他们官方写的包可以调用 我看有人用这个方法实现了TG的Bot https://github.com/Timmy-web/Poe-Telegram-Chatbot

**Comment by wong2** [comment]
不错，我看看
