### ISSUE TITLE
Easier access to API usage

### ISSUE THREAD

**Issue by SeanBannister** [chathub-dev/chathub#1108]
Would be great if the API key configuration popup provided a link to the API usage page for that provider, for example:
GPT: https://platform.openai.com/usage
Claude: https://console.anthropic.com/settings/usage

It's just handy to look at your API usage to know how much its costing, and I always find myself struggling to find the page. Alternatively you could put this link on the view history page.

Long term it'd be great to show the API usage in ChatHub.

**Comment by wong2** [comment]
Good idea
