### ISSUE TITLE
Output text from Bing Copilot often disappears

### ISSUE THREAD

**Issue by kranix0** [chathub-dev/chathub#1111]
Often when using Bing Copilot, the output text will appear for about 1 second and then disappear, leaving only the first line. I don't see this happen when using Bing Copilot directly.

This problem has been around for a while. I'm currently using Windows 11, Chrome 122, ChatHub 2.16.0.

**Comment by wong2** [comment]
Can you give me an example question to trigger this problem?

**Comment by kranix0** [comment]
It appears to happen when Bing is giving a list. I tested by asking "can you give a list of countries with population over 100m?"

Before:
<img width="544" alt="image" src="https://github.com/chathub-dev/chathub/assets/461278/610a43c5-ec5b-46c2-a85c-f7dce0bd4a84">

One second later:
<img width="545" alt="image" src="https://github.com/chathub-dev/chathub/assets/461278/a04bed6b-046d-4ab5-bdf7-3203d765c27a">

When I check the chat history at https://www.bing.com/chat I can see the whole message.

**Comment by wong2** [comment]
Thanks for the example. This will be fixed in next version.

**Comment by wong2** [comment]
Fixed in latest version.
