### ISSUE TITLE
Add-back support for Claude 2.1

### ISSUE THREAD

**Issue by gabrielbacha** [chathub-dev/chathub#1112]
As the title says, it would be good to add direct support from Claude 2.1 for Pro users (not API, direct)

**Comment by wong2** [comment]
Why would you prefer Claude 2.1 over Claude 3?

**Comment by gabrielbacha** [comment]
I found 2.1 to be better at creative tasks

**Comment by wong2** [comment]
2.1 is no longer supported in claude.ai, so this is not technically possible anyway.
