### ISSUE TITLE
License is no longer valid!

### ISSUE THREAD

**Issue by Raven32768** [chathub-dev/chathub#1114]
is:issue I cannot find your email anywhere, discord wont let me in for some reason. I bought a valid license for chathub last year. If I buy something that says: buy once, own forever, I expect to own it. Now, after a reboot and attempting to reinstall, I get License is no longer valid. My email is rob.fontaine100@gmail.com. Perhaps an email explaining why, and a refund would be nice, I do not want the software anymore after this. Perhaps an email link on your website too would offer a little more credibility, if you have integrity and care about that kind of thing. I'm a disabled pensioner man, and the cost was a lot to pay out for me. I would not have paid if I had known this would happen.

**Comment by wong2** [comment]
Hi, don't be so mad. The issue is you have reached the activation limit of 5. I have removed your previous activations, please try again, it should work now.
Thanks for your suggestion of adding an email link on our website, we'll definitely add it soon.

**Comment by wong2** [comment]
We have added email link on website
