### ISSUE TITLE
ChatGPT Web is not working

### ISSUE THREAD

**Issue by BlackStar1453** [chathub-dev/chathub#1132]
**Describe the bug**
![image](https://github.com/chathub-dev/chathub/assets/69788237/130f140d-ab87-4cd6-814f-0c7faf30640e)

 [- ChatHub Version [you can find it in ChatHub Settings]
![image](https://github.com/chathub-dev/chathub/assets/69788237/0904502f-1f66-4808-a27b-a46039a8be8d)

**Solution suggestion**

 I have examined the Request Payload on the ChatGPT webpage, and it seems that the inclusion of a new Request body content "force_paragen_model_slug: "" " is causing the request to fail. Omitting this content from the body should resolve the request exception.
![image](https://github.com/chathub-dev/chathub/assets/69788237/186fecc0-a261-4b77-86fd-bdbc63e25561)

**Comment by BlackStar1453** [comment]
And I've also noticed that even with the use of GPT-4 now, there's no need to include "arkose_token" in the Request Payload; it's used in the header instead.

**Comment by wong2** [comment]
Have you upgraded to the latest version v2.19.4 ?

**Comment by BlackStar1453** [comment]
> Have you upgraded to the latest version v2.19.4 ?

Yes, I had upgraded to the latest version. Please check out the second image.

**Comment by BlackStar1453** [comment]
> Have you upgraded to the latest version v2.19.4 ?

I was able to use it yesterday, but not anymore. Can you use the ChatGPT Web on your computer?

**Comment by wong2** [comment]
OK, maybe OpenAI changed something again. I'll have a look

**Comment by wong2** [comment]
Fixed in v2.19.5

**Comment by BlackStar1453** [comment]
> Fixed in v2.19.5

Really thanks！

Could you tell me how did it？I tried to fix it myself but I failed.
