### ISSUE TITLE
能否提供Bing Copilot的不联网使用

### ISSUE THREAD

**Issue by brilliantfires** [chathub-dev/chathub#1133]
在插件中使用Copilot默认是使用web的，请否添加一种情况，不要使用web联网，这样有时回答反而会准确一些。

希望作者可以考虑加上这个功能。

**Comment by wong2** [comment]
Copilot本身没这个选项，所以估计做不到

**Comment by brilliantfires** [comment]
> Copilot本身没这个选项，所以估计做不到

感谢你的回复，但是Copilot在插件栏提供了关闭Search的选项，所以你的意思是不是虽然Copilot插件提供了这个功能，但是第三方却没法调用关闭。
![image](https://github.com/chathub-dev/chathub/assets/75881366/9d77d9c2-01a4-4993-809f-6a1aad2e2a55)

**Comment by wong2** [comment]
好的 我再看看

**Comment by brilliantfires** [comment]
> 好的 我再看看

这个想法，可行吗？会不会在后面更新呀。

**Comment by wong2** [comment]
我看了下，技术上是可以的，就差实现了

**Comment by brilliantfires** [comment]
> 我看了下，技术上是可以的，就差实现了

辛苦了，期待！！

**Comment by wong2** [comment]
更新到v3.3.0，Bing机器人增加了一个新的设置项
