### ISSUE TITLE
No Response When Clicking "Activate License" Button on ChatHub Installed via Chrome Store on Arc for Windows

### ISSUE THREAD

**Issue by kehao-chen** [chathub-dev/chathub#1137]
**Describe the bug**

When attempting to activate the license for ChatHub on Arc for Windows, clicking the "Activate license" button does not elicit any response.

- Steps to Reproduce:
1. Install ChatHub on Arc for Windows through the Chrome Store.
2. Navigate to the license activation section.
3. lick on the "Activate license" button.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Arc for Windows
 - ChatHub Version: v3.4.0

**Comment by wong2** [comment]
It should display an alert like this:
![image](https://github.com/chathub-dev/chathub/assets/321947/ce607e6a-a2e3-4fa5-bab7-0c4f28cf6ccb)

Did you disable all alerts in your browser?

**Comment by kehao-chen** [comment]
Thank you for your response. I have checked my browser settings and confirmed that the Notifications are set to 'Allow' under Settings -> Privacy and security.
![image](https://github.com/chathub-dev/chathub/assets/13099052/e1620736-e97a-43b8-878d-b1ecd7d230e1)

Additionally, I observed the behavior when clicking the "Activate license" button using the performance tool in DevTools. There indeed seems to be an execution that causes a UI thread blockage. Interestingly, this issue does not occur on Arc for macOS and appears to be unique to the recent beta version of Arc for Windows. I have also reported this issue to The Browser Company, but I have not yet received a response.
![image](https://github.com/chathub-dev/chathub/assets/13099052/50cf9e61-933a-4105-81b4-4f08b0be73b8)

I hope this information helps in resolving the issue.

**Comment by wong2** [comment]
Here is a minimal demo using `window.prompt`, please check if it's working: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt

**Comment by kehao-chen** [comment]
I have tested the minimal demo you provided using `Window.prompt()`, and it seems to confirm that the issue is with Arc for Windows and its support for `Window.prompt()`. I will be reporting this specific problem to The Browser Company. Thank you for pointing me in the right direction.
