### ISSUE TITLE
会加入文心一言吗？

### ISSUE THREAD

**Issue by jimmyQxQ** [chathub-dev/chathub#114]
如题，可以直接对比两者的回答差异。

**Comment by wong2** [comment]
会

**Comment by terryyizhong** [comment]
可以，但没必要

**Comment by qiaozhiyong** [comment]
请帮我添加文心一言，支持文心一言和chat'gpt的对比

**Comment by qiaozhiyong** [comment]
文心一言和chatgpt的对比挺必要的，对应用者来说，可以比对场景，谢谢 @wong2 @terryyizhong

**Comment by qiaozhiyong** [comment]
真心感谢，chatgpt和bing在一个界面对比着用，真是太棒了，希望后续可以加入文心一言

**Comment by situkei** [comment]
加个套壳的进来对比有意义吗？

**Comment by nickfan** [comment]
后面还有华为盘古和京东的ChatJD都接吗？
