### ISSUE TITLE
Cannot get a complete response from Claude 3

### ISSUE THREAD

**Issue by worsin** [chathub-dev/chathub#1140]
**Describe the bug**
Cannot get a complete response from Claude 3. It will almost always stop before its finished.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - ChatHub Version: (v3.4.0)

**Comment by wong2** [comment]
Which mode are you using? Is it "Use your own account"?

**Comment by pamcy** [comment]
I also encountered the same problem. I was using claude 3 'Use your own account', and this situation has been happening quite often recently.

The same thing also happened with Gemini Pro using my own API key.

- MacOS: 13.6.1
- Browser Brave
- ChatHub Version: (v3.9.0)

**Comment by wong2** [comment]
Hi, can you post a screen recording about this situation?

**Comment by pamcy** [comment]
This is a situation I just encountered. I usually ask some programming-related questions, and then suddenly there is no response halfway through. Please take a look again, thank you.

[https://share.cleanshot.com/YJjPyPB3](https://share.cleanshot.com/YJjPyPB3)

**Comment by wong2** [comment]
@pamcy Thanks, that's really helpful.
