### ISSUE TITLE
hope we could include the channel specific input box as default or optional

### ISSUE THREAD

**Issue by vecyang1** [chathub-dev/chathub#1144]
<img width="1054" alt="image" src="https://github.com/chathub-dev/chathub/assets/130784544/19e2656c-664e-4301-85a9-d22e733d455b">

hope we could include the channel specific input box as default or optional. I often need to ask separately. 

Before it's shwon, now it's set as hidden for default.

**Comment by wong2** [comment]
OK, I'll add an option
