### ISSUE TITLE
I want to be able to use ChatGPT web without logging into ChatGPT's official website

### ISSUE THREAD

**Issue by jiawen-official** [chathub-dev/chathub#1145]
Now you can use the ChatGPT website without logging in. I hope I can use the ChatGPT web without logging in to the ChatGPT website

**Comment by wong2** [comment]
Hi, this has been supported since version 3.6.0, which version are you using?

**Comment by pamcy** [comment]
This is a situation I just encountered. I usually ask some programming-related questions, and then suddenly there is no response halfway through. Please take a look again, thank you.

[](https://share.cleanshot.com/YJjPyPB3)
