### ISSUE TITLE
Activation Limit Reached

### ISSUE THREAD

**Issue by JasonBuettner** [chathub-dev/chathub#1147]
I just bought a $39 Premium Lifetime License, but it is showing inactive, and saying my activation limit is reached. How can I activate my license?

**Comment by wong2** [comment]
Have you followed these steps? https://chathub.gg/after-purchase

**Comment by JasonBuettner** [comment]
Yes, but I figured out a different path. Fyi - the user interface and steps are a bit dated in your link. This is solved now. 
<img width="1200" alt="image" src="https://github.com/chathub-dev/chathub/assets/166531898/ce30b56c-1535-469e-beb3-b4dde2020bb8">

**Comment by wong2** [comment]
You're right. I'll update it soon. Thanks.
