### ISSUE TITLE
Respect "Chat history & training" setting in ChatGPT

### ISSUE THREAD

**Issue by zizhengwu** [chathub-dev/chathub#1150]
**Describe the bug**

![image](https://github.com/chathub-dev/chathub/assets/2246655/a448d710-b707-4f12-9e21-527835422ce9)

I disabled "Chat history & training" in ChatGPT settings. However, it seems that ChatHub still saves chat history to ChatGPT (which can be seen if I click "Enable chat history" green button).

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - ChatHub Version n/a

**Comment by wong2** [comment]
Got it

**Comment by wong2** [comment]
But I can add another option in ChatHub to control this

**Comment by zizhengwu** [comment]
> But I can add another option in ChatHub to control this

This would be extremely useful!
