### ISSUE TITLE
支持 Claude 3 Opus web

### ISSUE THREAD

**Issue by zizhengwu** [chathub-dev/chathub#1151]
类似于 #1105

但目前好像只有 api 支持用 Claude 3 Opus，自己的 web 账号不行？

![image](https://github.com/chathub-dev/chathub/assets/2246655/e01069ff-9bfb-43a0-a14e-a128ccfcf400)

**Comment by wong2** [comment]
由于我注册的Claude.ai账号总是很快被封，所以没法测试这个问题...

**Comment by zizhengwu** [comment]
@wong2 我观察了下，好像在 claude chat 里选择的是 Opus，chathub web 也自然用的 Opsu 吗？但是我没有直接验证的办法，因为 claude 不像 chatgpt 会直接回答你，现在用的是什么 model。

**Comment by wong2** [comment]
应该是的，因为它的请求里没有指定模型这个参数
