### ISSUE TITLE
All-in-one mode 增加一键导出（或一键复制）六个LLM对话记录

### ISSUE THREAD

**Issue by choosehill** [chathub-dev/chathub#1152]
首先感谢大佬开发这个非常好用的工具，我是付费版会员，每一次使用All-in-one mode 发出Prompt后看到六个LLM快速跑出回答都会让我有种 天啊 世界太美好的感觉XD

但目前遇到的問題是，我每次與LLM聊完後，想統整六個視窗的對話記錄時，都只能一個一個的複製並貼進Notion或其他筆記軟體中，然後再進行整理，因此想提問，是否能增加一鍵導出（或一键复制）所有對話記錄，方便我們做資訊整理呢？ 萬分感謝

**Comment by saccohuo** [comment]
+1
