### ISSUE TITLE
Perplexity 404

### ISSUE THREAD

**Issue by equanstrom** [chathub-dev/chathub#1155]
**Describe the bug**
Results from Perplexity are failing in Chat Hub:
**[GET] "https://labs-api.perplexity.ai/socket.io/?transport=polling&EIO=4": 404**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey v12.4
 - Browser: Chrome Version 123.0.6312.122 (Official Build) (arm64)
 - ChatHub Version: Settings (v3.11.1)

**Comment by wong2** [comment]
Thanks for your reporting this. It will be fixed in next version.

**Comment by wong2** [comment]
Fixed in v3.11.3
