### ISSUE TITLE
I got error.

### ISSUE THREAD

**Issue by tricstar** [chathub-dev/chathub#1157]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by wong2** [comment]
Hi, this like just saying "I'm sick" when you visit a doctor, no one can help you without further information.

**Comment by tricstar** [comment]
I accidentally pressed the enter key and sent the message midway through. I also unknowingly reposted the detailed error in a new topic. Please let me know which topic should I delete or re-edit, or if I need to take any action.

**Comment by wong2** [comment]
Hi, no worry! I've closed this issue since you've created a new one.
