### ISSUE TITLE
GPT 3.5 404 & Perplexity 403

### ISSUE THREAD

**Issue by tricstar** [chathub-dev/chathub#1158]
Describe the bug
Results from Perplexity and GPT3.5 are failing in Chat Hub:

1)Perplexity
[GET] "https://labs-api.perplexity.ai/socket.io/?transport=polling&EIO=4": 404

2)GPT3.5
403 Forbidden
ネットワーク接続を確認してください

Desktop (please complete the following information):
version Apple Mac book Air M2  2022 13.6
Sonoma 14.4.1  ChatHub  (v3.11.1)
Chrome Browser 123.0.6312.123

https://github.com/chathub-dev/chathub/assets/91990591/00b3eb6f-9466-4180-adfe-73d9f5521f8e

**Comment by wong2** [comment]
Hi, the first issue should have been fixed in latest version, please upgrade to v3.11.3
The second issue is being fixed now, please wait for next version.

**Comment by tricstar** [comment]
Thank you for your help. I tried update , and Perplexity worked fine.

![image](https://github.com/chathub-dev/chathub/assets/91990591/7d8f8609-274c-4269-a37b-4d35e7efb173)

I'm looking forward to solving the second problem as well. thank you.

**Comment by wong2** [comment]
Please upgrade again. It's fixed.
