### ISSUE TITLE
这个Bing的机器人是基于GPT3.5的吗

### ISSUE THREAD

**Issue by heiheihengha** [chathub-dev/chathub#116]
通过对话，Bing机器人给出的回答是“chathub中的Bing是基于GPT-3.5的模型微调而来”

**Comment by wong2** [comment]
Bing应该是基于GPT-4的

**Comment by heiheihengha** [comment]
![image](https://user-images.githubusercontent.com/128347500/226263991-403ccaf7-d23d-449a-9d08-a61a5492bc5a.png)
我对Bing机器人进行了提问，它给出的答案是GPT-3.5，而且我对比了下edge里的聊天功能，同样的问题，chathub里的Bing
和edge里的回答是不一样的

**Comment by wong2** [comment]
回答不一样很正常， 同一个问题的答案是有随机性的
