### ISSUE TITLE
请求退款

### ISSUE THREAD

**Issue by miumiu2333** [chathub-dev/chathub#1165]
ChatGPT连续多天提示Our systems have detected unusual activity from your device. Please try again later，已经无法使用，请求退款
邮箱：tonymiugrey@miugrey.com.cn

**Comment by wong2** [comment]
请更新到最新版：https://chromewebstore.google.com/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

**Comment by miumiu2333** [comment]
已更新，但还是不稳……国内环境问题吧…如果可以的话还是帮忙退一下？实在不好意思了TAT

**Comment by miumiu2333** [comment]
这个呢 TonySun@miugrey.com.cn

**Comment by wong2** [comment]
已退

**Comment by miumiu2333** [comment]
麻烦了 不好意思
