### ISSUE TITLE
bing CAPTCHA error

### ISSUE THREAD

**Issue by stevejoeyms** [chathub-dev/chathub#1167]
i can't connect the bing when i click the verify and successful.

<img width="1274" alt="image" src="https://github.com/chathub-dev/chathub/assets/88429614/858228de-a5a4-458c-93c0-ff046863b25c">

<img width="593" alt="image" src="https://github.com/chathub-dev/chathub/assets/88429614/368fb436-beeb-43ae-8c1d-5a6e045545c3">

**Comment by wong2** [comment]
请更新到最新版再试试
