### ISSUE TITLE
Perplexity is not working for me ?  

### ISSUE THREAD

**Issue by sherif20000** [chathub-dev/chathub#1170]
**Describe the bug**
Perplexity is not working for me!

**Desktop (please complete the following information):**
 - OS: [e.g. MAC]
 - Browser [e.g. chrome]
 - ChatHub Version [v3.14.7]

**Comment by wong2** [comment]
Hi, please upgrade to v3.15.0

**Comment by maxsampa** [comment]
> Hi, please upgrade to v3.15.0

Please, how do I do to upgrade to v3.15.0? Perplexity is not working for me neither.

**Comment by sherif20000** [comment]
Remove the extension from the browser and then re-install it again .

it worked for me

**Comment by maxsampa** [comment]
> Remove the extension from the browser and then re-install it again .
> 
> it worked for me

Thank you @sherif20000 . I did it and still not working.
I am using MS Edge extension. Version 124.0.2478.67 (64 bits)
