### ISSUE TITLE
通义千问在插件中访问比官方网页慢很多

### ISSUE THREAD

**Issue by lionqy163** [chathub-dev/chathub#1171]
插件中通义千问响应慢，请求中能看到官方网页与插件请求的url不一样，不确定是不是这个原因导致
<img width="431" alt="企业微信截图_17143708411042" src="https://github.com/chathub-dev/chathub/assets/127304508/b44e8916-7d2f-4f98-aa62-8f331bff5cd3">
<img width="439" alt="企业微信截图_17143708556960" src="https://github.com/chathub-dev/chathub/assets/127304508/a4f557cd-ac97-45b2-b66c-39f015cf9f38">

**Comment by wong2** [comment]
好的，有段时间没更新通义千问的代码了，今天看看

**Comment by wong2** [comment]
最新版已解决

**Comment by lionqy163** [comment]
> 最新版已解决

用的edge，商店还没更新

**Comment by wong2** [comment]
Edge商店更新很慢，建议从Chrome商店装吧
