### ISSUE TITLE
Failed to fetch: 500

### ISSUE THREAD

**Issue by jamiefurbnow** [chathub-dev/chathub#1174]
**Describe the bug**
I paid for premium today and now Nearly all of the llms are returning Failed to fetch: 500

is there a known issue at present?

**Comment by usererror0** [comment]
Same.
![image](https://github.com/chathub-dev/chathub/assets/35112244/1cc47234-2404-470c-9843-6fac3273ef7f)

**Comment by wong2** [comment]
It should work now.

**Comment by wong2** [comment]
@jamiefurbnow Can you show me a screenshot?
