### ISSUE TITLE
Bing request is throttled AND Chat GPT 403 Forbidden

### ISSUE THREAD

**Issue by bobmhughes** [chathub-dev/chathub#1176]
I use a 4-pane configuration of ChatHub Premium with Bing Copilot , Chat GPT, Gemini & Pi.

ChatHub has ben working great with all of these until today.

Now, when I enter a search prompt, only Gemini and Pi produce results. 
Bing gives me the error "Request is throttled."
Chat GPT gives me the error "403 Forbidden"

I can use Bing Copilot and Chat GPT directly outside of ChatHub without any errors.

Your help would be appreciated. Thanks.

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 Build 22631.3447
 - Browser Chrome Version 124.0.6367.119 (Official Build) (64-bit)
 - ChatHub Version v3.16.0

**Comment by wong2** [comment]
Hi, are you a ChatGPT Plus subscriber?

**Comment by bobmhughes** [comment]
No, I am not a ChatGPT Plus subscriber, but I have been able to use ChatGPT within ChatBot nevertheless for months until yesterday. I haven't seen anything in the ChatBot documentation that states you have to be a ChatGPT Plus subscriber for ChatGPT to work within ChatBot.

**Comment by bobmhughes** [comment]
Today, I am getting a different error message with Bing CoPilot within ChatBot "WebSocket closed with reason:  (1006)."

**Comment by wong2** [comment]
No you don't need ChatGPT Plus to use ChatGPT in ChatHub, I'm just trying to gather more information for debugging.

**Comment by bobmhughes** [comment]
Oh, ok...good to know. Thanks for your help figuring out what is going on with these errors!

**Comment by bobmhughes** [comment]
Today, the ChatGPT error within ChatHub has changed to "403 https://chatgpt.com/backend-api/conversation"

**Comment by wong2** [comment]
We're still trying to figure it out

**Comment by wong2** [comment]
Please try again with v3.17.7

**Comment by bobmhughes** [comment]
Using v3.17.9,. only Gemini works properly. Bing Copilot returns the error "WebSocket closed with reason: (1006)." ChatGPT returns the error "403 https://chatgpt.com/backend-api/conversation, model: text-davinci-002-render-sha" . Llama3 returns the error "403 Forbidden"

**Comment by bobmhughes** [comment]
As a programmer, I can imagine how frustrating it would be trying to fix issues that you cannot reproduce! Let me know if there is anything else I can do to help you troubleshoot

**Comment by bobmhughes** [comment]
I tried using ChatGPT directly from https://chat.openai.com/auth/login which of course worked, and then I tried using ChatGPT from within ChatHub and it is now working. Llama 3 gave me the error message "NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE." However, I tried once again and Llama 3 is now working properly. Bing Copilot is the only one that I use that is still giving me the error message "WebSocket closed with reason:  (1006)."

**Comment by wong2** [comment]
Thanks for the information!

**Comment by wong2** [comment]
My guess: Due to ChatGPT recently changing its domain from chat.openai.com to chatgpt.com, users need to visit the old domain once to migrate cookie data.

**Comment by bobmhughes** [comment]
The "403 Forbidden" error is back with Llama 3, even after successfully using Llama 3 outside of ChatBot :(

**Comment by wong2** [comment]
llama 3 should work now.

**Comment by bobmhughes** [comment]
Yes, thank you! Llama 3 is now working properly! Bing Copilot is the only one not working with a "Request is throttled." error
