### ISSUE TITLE
Permission now requires "read and change all your data on all websites"?

### ISSUE THREAD

**Issue by zizhengwu** [chathub-dev/chathub#1177]
**Describe the bug**
The latest version requires "read and change all your data on all websites"

![image](https://github.com/chathub-dev/chathub/assets/2246655/c3996fc6-4436-4805-9ccf-53dc7f6b4043)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - ChatHub Version [you can find it in ChatHub Settings]

Is this a recent permission change? This feels overly wide compared with before? 

Before: ![image](https://github.com/chathub-dev/chathub/assets/2246655/2bba1ef6-7326-46ee-aba4-4241bbf8943b)

**Comment by wong2** [comment]
Yes, we changed the permission requirements for the following reasons:

1. The websites we rely on may sometimes change their domain names, such as from bard.google.com to gemini.google.com, from chat.openai.com to chatgpt.com. It would be a hassle if every change led to the ChatHub extension being disabled by Chrome.
2. We rely on many third-party websites, and now many of them are implemented through optional permissions, requiring users to click through permission confirmations multiple times, which is not a great experience.
3. 
Therefore, after referencing other AI extension products such as Monica, Sider.ai, etc., we changed to request broader permissions similar to theirs.

**Comment by WoodAsh2501** [comment]
Having full access to data may let users worried, even worse than clicking permissions. Is there a better way?

**Comment by oDisMal** [comment]
> Having full access to data may let users worried, even worse than clicking permissions. Is there a better way?

I agree it is worrisome. I just paid for ChatHub Premium and now this sudden change is disappointing.
I would be less worried if this project was fully opensource, but it seems the devs have close sourced it a while back.
I will likely use a different extension now.

**Comment by tomups** [comment]
I will also stop using this extension due to the extended permissions. A shame.

**Comment by tomups** [comment]
Actually after more research, it seems an extension chan be forced to be limited to only specific sites even if at first it requests access to any site.

You can go to the extension settings and change site access to "Specific sites" and add sites manually. I have done so for the models that I want to use and it works fine.

![image](https://github.com/chathub-dev/chathub/assets/690217/e5343296-7143-40c5-90ec-c4e233c29e57)

**Comment by SeanBannister** [comment]
@wong2 Considering @tomups post would you consider maintaining a list of all the domains required for chathub to work? I also don't feel comfortable allowing extensions to access every site I visit. If a malicious actor gains access to one of those extensions they can basically access every users banking.

**Comment by small-luck2367** [comment]
Gave permission to these domains, it seems to work for ChatGPT, Gemini, Claude, Copilot (free web access). Perplexity and Meta are not working.

*://anthropic.com/*
*://api.anthropic.com/*
*://api.openai.com/*
*://chatgpt.com/*
*://claude.ai/*
*://copilot.microsoft.com/*
*://gemini.google.com/*
*://meta.ai/*
*://openai.com/*
*://perplexity.ai/*
