### ISSUE TITLE
bingcopilot无法使用

### ISSUE THREAD

**Issue by strengthen8** [chathub-dev/chathub#1179]
bingcopilot无法使用
正常使用截图
![image](https://github.com/chathub-dev/chathub/assets/26496661/19e02a10-2901-4766-a56e-0c2e2e9636e1)

平台使用截图
![image](https://github.com/chathub-dev/chathub/assets/26496661/b3fa3f87-7c8a-46e7-9582-a10c4dc38d17)

**Comment by wong2** [comment]
你好，版本是多少？

**Comment by alfred-liu96** [comment]
我也是同样的报错，版本3.17.0

**Comment by strengthen8** [comment]
v3.17.1
