### ISSUE TITLE
chat-GPT和bing都404了

### ISSUE THREAD

**Issue by sdpy3634** [chathub-dev/chathub#118]
bing： (404  (https://www.bing.com/turing/conversation/create))
chat-GPT：failed to fetch
采用了一天...请问有什么解决方法么

**Comment by heiheihengha** [comment]
我使用1.5.3版本插件，bing是正常的

**Comment by heiheihengha** [comment]
> bing： (404 (https://www.bing.com/turing/conversation/create)) chat-GPT：failed to fetch 采用了一天...请问有什么解决方法么

我使用1.5.3版本插件，bing是正常的

**Comment by wong2** [comment]
请手动安装最新版：https://github.com/chathub-dev/chathub/releases
