### ISSUE TITLE
Unable to activate in Arc browser

### ISSUE THREAD

**Issue by Evantix** [chathub-dev/chathub#1180]
I am unable to activate in Arc browser. Please check why. When I press "activate," the code doesn't make any changes and it freezes the browser. 
![image](https://github.com/chathub-dev/chathub/assets/157067393/aaa2ded7-57a1-4eac-89e3-ec7206c3536d)

**Comment by wong2** [comment]
This is a bug of Arc on Windows, they do not suppport [window.prompt](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) properly.

**Comment by Evantix** [comment]
Can you add a different method to activate the subscription? The Arc browser is becoming very popular, and many users are switching from Chrome to Arc.

**Comment by wong2** [comment]
Is there a feedback channel for Arc? Please tell them the lack of `window.prompt` support is a serious bug.
