### ISSUE TITLE
使用chatgpt 提示 “Please pass Cloudflare check”

### ISSUE THREAD

**Issue by jschen1009** [chathub-dev/chathub#1184]
点"登录ChatGpt"验证后，重新提问还是会提示 “Please pass Cloudflare check”

**Comment by jschen1009** [comment]
@wong2 这个问题还会处理吗？

**Comment by wong2** [comment]
@jschen1009 请问你是什么浏览器？什么版本？

**Comment by SWJ-ya** [comment]
我也出现了这个问题 请问解决了吗

**Comment by jschen1009** [comment]
> @jschen1009 请问你是什么浏览器？什么版本？
Microsoft Edge  版本 126.0.2552.0 (正式版本) dev (64 位)

**Comment by jschen1009** [comment]
@wong2 Microsoft Edge 版本 126.0.2552.0 (正式版本) dev (64 位)

**Comment by wong2** [comment]
ChatHub 是从 chrome web store安装的最新版吗？

**Comment by jschen1009** [comment]
@wong2  是的 好像是有自动升级上来   目前版本是 (v3.20.4)

**Comment by SWJ-ya** [comment]
@jschen1009 我也出现了这个问题 请问解决了吗 我的他会时好时坏

**Comment by jschen1009** [comment]
@SWJ-ya 还没解决，作者@wong2 正在看

**Comment by jschen1009** [comment]
访问[perplexity.ai](https://www.perplexity.ai/)也有类似问题

**Comment by jschen1009** [comment]
@wong2 目前版本chathub版本是(v3.20.8)  浏览器版本是Edge 126.0.2578.1 (正式版本) dev (64 位) 问题还在，这个问题有办法解决吗？

**Comment by wong2** [comment]
我没办法复现它。。

**Comment by wong2** [comment]
最新版修复了Perplexity的问题

**Comment by jschen1009** [comment]
> 最新版修复了Perplexity的问题

@wong2 验证了最新版Perplexity可以正常使用了，chatgpt的提示Cloudflare check的问题也帮忙一起看下

**Comment by wong2** [comment]
@jschen1009 我没法复现chatgpt那个问题，你可以帮忙试试下面这个版本有修复它吗？👇

[chathub.zip](https://github.com/user-attachments/files/16008110/chathub.zip)
