### ISSUE TITLE
Avoid using a system prompt

### ISSUE THREAD

**Issue by jifalops** [chathub-dev/chathub#1185]
I noticed you provide instructions to the models for the conversations in Chathub. Is there a way to disable that? I want the pure experience without having to switch windows and copy paste.

**Comment by wong2** [comment]
Hi, which chatbot and which method are you referring to? (use your own account or API key or our API service?)

**Comment by jifalops** [comment]
I have a lifetime plan. I've used the Gemini API key, but it works with GPT4 and Claude Opus without an API key. When I see the conversation history on their websites it shows your prompt.

**Comment by wong2** [comment]
What's the prompt? Can you show me a screenshot?
