### ISSUE TITLE
Chat GPT: "Please pass cloudflare check"

### ISSUE THREAD

**Issue by ericridley** [chathub-dev/chathub#1187]
In multi view only, this error appears on all requests, along with "enter API key," and "log into ChatGPT."
I'm logged in and the API key is set.

Doesn't happen in openAI window alone.

**Desktop (please complete the following information):**
Mac OSX 14.4.1
Chrome
Chathub 3.17.12

**Comment by wong2** [comment]
Hi, after set the API key, you should change the chatbot in All-in-one tab from ChatGPT to OpenAI

<img width="556" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/9c227115-dce9-4309-947e-7f8c371443ac">
