### ISSUE TITLE
通义千问网页模式下，回答格式不正常了。

### ISSUE THREAD

**Issue by derline** [chathub-dev/chathub#1188]
![image](https://github.com/chathub-dev/chathub/assets/6316267/fbcdf7b2-fba8-4319-8346-6fbac22034e3)
简单的问题还正常，一些复杂点的问题就不正常了（可能用到插件了？）

**Comment by wong2** [comment]
确实有这个问题，下个版本会修复

**Comment by wong2** [comment]
v3.19.3 已修复

**Comment by derline** [comment]
> v3.19.3 已修复

有速度！
