### ISSUE TITLE
不翻墙的话gpt提示Failed to fetch，new bing提示 (404  (https://www.bing.com/turing/conversation/create))

### ISSUE THREAD

**Issue by JieeyLiu** [chathub-dev/chathub#119]
不翻墙的话gpt提示Failed to fetch，new bing提示 (404  (https://www.bing.com/turing/conversation/create))
怎么解决呢

**Comment by wong2** [comment]
new Bing 404 问题请手动安装最新版 https://github.com/chathub-dev/chathub/releases/tag/v1.5.3

ChatGPT需要翻墙的
