### ISSUE TITLE
Perplexity error  “Please pass Perplexity security check"  (v3.20.1) 

### ISSUE THREAD

**Issue by tricstar** [chathub-dev/chathub#1193]
Describe the bug Results from Perplexity are failing in Chat Hub:

Perplexity
“Please pass Perplexity security check"
Please visit [perplexity.ai](https://www.perplexity.ai/) and try again”

Accessing ChatHub again after logging into Perplexity does not fix the error.

Desktop (please complete the following information): version 
Apple Mac book Air M2 2022 13.6 
Sonoma 14.4.1 
ChatHub  (v3.20.1) 
Chrome Browser 124.0.6367.119

**Comment by wong2** [comment]
Fixed in v3.24.5
