### ISSUE TITLE
BING COPILOT用不了啦，请大佬修复一下。

### ISSUE THREAD

**Issue by forhonourlx** [chathub-dev/chathub#1195]
**Describe the bug**
[GET] "https://copilot.microsoft.com/turing/conversation/create?bundleVersion=1.1719.0": 403

**Comment by wong2** [comment]
请把这个域名加入代理

**Comment by xumeitian** [comment]
同样的网络代理环境。Edge浏览器里面的copilot可以使用，但是chatHub里面的copilot就用不了，但是chatGPT可以使用
