### ISSUE TITLE
希望自动拉取models

### ISSUE THREAD

**Issue by anrgct** [chathub-dev/chathub#1197]
我想兼容one-api和ollama，这两个都是有一大堆模型id，手动输入太痛苦了，希望能自动拉取models，可以切换模型选择。顺便增加一个复制机器人的功能，方便只修改模型名。

**Comment by wong2** [comment]
有道理

**Comment by YWzzy** [comment]
+1

**Comment by wong2** [comment]
复制机器人已经支持了
