### ISSUE TITLE
阿里云百炼平台多模型聊天界面做得巨好

### ISSUE THREAD

**Issue by anrgct** [chathub-dev/chathub#1199]
![1716262423564](https://github.com/chathub-dev/chathub/assets/16172523/8324fee1-2f1a-46a9-8a33-a00530a14a6e)
希望能抄袭一下

**Comment by wong2** [comment]
学习一下

**Comment by buglong** [comment]
阿里云百炼的API key也可以增加到通过API key使用的模型里面
