### ISSUE TITLE
默认取消输入的 markdown 显示

### ISSUE THREAD

**Issue by zizhengwu** [chathub-dev/chathub#1200]
**Describe the bug**
我的输入并不是 markdown，被渲染之后非常难阅读
![image](https://github.com/chathub-dev/chathub/assets/2246655/4ddb1220-2c55-4859-9e06-67efdef015a0) 

比如 ChatGPT 就**不会**把输入渲染成 markdown

![image](https://github.com/chathub-dev/chathub/assets/2246655/7b21979b-c629-404f-817a-fa4743876082)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - ChatHub Version v3.20.6

**Comment by zizhengwu** [comment]
老哥能不能加个选项，可以默认别用 markdown 渲染输入。一些比较复杂的，比如代码，都渲染乱了。

**Comment by wong2** [comment]
已经取消了
