### ISSUE TITLE
ChatGPT Error 403 https://chatgpt.com/backend-api/conversation, model: gpt-4o & Bing error Request is throttled.

### ISSUE THREAD

**Issue by bobmhughes** [chathub-dev/chathub#1203]
I use a 4-pane configuration of ChatHub Premium with Bing Copilot , Chat GPT, Gemini & Pi.

I am now getting a ChatGPT Error "403 https://chatgpt.com/backend-api/conversation, model: gpt-4o"

The Bing Copilot error "Request is throttled" still persists

I can use Bing Copilot and Chat GPT directly outside of ChatHub without any errors.

Your help would be appreciated. Thanks.

Desktop Information:
OS: Windows 11 23H2 OS Build 22631.3593
Browser Chrome Version 125.0.6422.61 (Official Build) (64-bit)
ChatHub Version v3.20.6

**Comment by wong2** [comment]
Thanks for reporting this.

**Comment by bobmhughes** [comment]
ChatGPT is now working properly

**Comment by wendellouyang** [comment]
这个一般是ip被灰度风控的结果，换ip可以解决（date：2026年06月12日）
