### ISSUE TITLE
Bing Copilot  error "Request is throttled"

### ISSUE THREAD

**Issue by bobmhughes** [chathub-dev/chathub#1205]
Every time that I use ChatHub with Bing Copilot, I receive an error message "Request is throttled" and no search results are produced

I can use Bing Copilot directly outside of ChatHub without any errors.

Your help would be appreciated. Thanks.

Desktop Information:
OS: Windows 11 23H2 OS Build 22631.3593
Browser Chrome Version 126.0.6478.17 (Official Build) (64-bit)
ChatHub Version v3.20.7

**Comment by Artushfoto** [comment]
Same problem for me. Please can You repair it. Thank You

**Comment by bobmhughes** [comment]
Bing Copilot is now working fine for me. Thank you!
