### ISSUE TITLE
[Bug] ChatHub 会导致 Bilibili 创作中心加载错误

### ISSUE THREAD

**Issue by RtYkk** [chathub-dev/chathub#1206]
**Describe the bug**
`https://member.bilibili.com/x/web/archives?status=is_pubing%2Cpubed%2Cnot_pubed&pn=1&ps=10&coop=1&interactive=1`
就因为`pubing`里面包含 `bing`，导致 referer 被改了。
**这个 json 的 referer 被改成 bing.com 之后会直接抛出 403 导致加载出错。**
原因我看了下就是 referer 莫名其妙变成 bing 了，我花十分钟排查了我所有的插件还重启了电脑关闭了 clash，以为最后可能是 ublock 没想到居然是 chathub 你个浓眉大眼的。
```
Origin:
https://www.bing.com
Referer:
https://www.bing.com
```
看了下源码你这多少有点暴力了吧
https://github.com/chathub-dev/chathub/blob/1e6359b420828832c0f9a4a87125ac34414cb7ad/src/rules/bing.json#L21
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by wong2** [comment]
v3.20.8已更新
