### ISSUE TITLE
Bing Copilot 一直提示“User needs to solve CAPTCHA to continue”

### ISSUE THREAD

**Issue by jschen1009** [chathub-dev/chathub#1216]
![image](https://github.com/chathub-dev/chathub/assets/31001147/6e9fd48f-43df-477d-b93c-79c98d7dd8a9)

**Comment by wong2** [comment]
可以说一下你的浏览器，和网络环境没？

**Comment by jschen1009** [comment]
@wong2 
浏览器：Microsoft Edge 版本 127.0.2638.2 (正式版本) dev (64 位)
翻墙工具：无忧行浏览器插件或快橙

**Comment by jschen1009** [comment]
![image](https://github.com/chathub-dev/chathub/assets/31001147/aea945a0-c04c-4c31-a23d-19ec3f2293d9)
