### ISSUE TITLE
Web版アプリが使えるようになったと聞いたのですが

### ISSUE THREAD

**Issue by arrowclub** [chathub-dev/chathub#1217]
どこでダウンロードできるのですか？

**Comment by wong2** [comment]
The link is: https://app.chathub.gg

**Comment by arrowclub** [comment]
Thank you so much!

**Comment by arrowclub** [comment]
Well, after all, does that app require a subscription purchase for the paid version even if I've already using the premium one-time purchase plan?

**Comment by wong2** [comment]
That's right. Because the web version relies on AI service.

**Comment by arrowclub** [comment]
Ok, I got it, then I won't use it. Thank you.
