### ISSUE TITLE
请求退款

### ISSUE THREAD

**Issue by ckitty123456** [chathub-dev/chathub#1220]
您好，插件不适合我，使用谷歌浏览器时，我需要调用“文字转语音，语音转文字”的谷歌插件，但是，您提到，插件里不能调用插件，能不能退一下款？ckitty开头的谷歌邮箱购买的，购买了6个设备使用权限，只使用了1个设备

**Comment by ckitty123456** [comment]
突然发现aihub和aione网页版都是你们同一家的，我想买aione网页版的会员，但aihub 的Licenses激活不了aione网页版的会员，我想调用谷歌插件，所以我更喜欢用aione网页版，请同意退款，我想购买aione网页版会员

**Comment by wong2** [comment]
你好，我查了一下，您已经买了两个月了？那我没办法帮您全额退款了，退一半是可以的。

另外您说的aione是指什么？我们的确有网页版，但并不叫aione这个名字。我们的网页版在  app.chathub.gg

**Comment by ckitty123456** [comment]
明白了，是竞争对手做的网页版，和你的chathub一模一样，但功能上不如chathub，不用申请退款了。提个小问题，希望数学公式能是latex渲染，不然下面的公式看着不舒服：[ H(s) = \frac{1}{1 + s/\omega_p} ]

**Comment by wong2** [comment]
收到

**Comment by brucenote** [comment]
請問有人退款成功嗎?
