### ISSUE TITLE
Claude API max_tokens error

### ISSUE THREAD

**Issue by SimbaAowhoo** [chathub-dev/chathub#1222]
**Describe the bug**
I'm encountering an error when using my own Claude API key. The error message is:

400 {"type":"error","error":{"type":"invalid_request_error","message":"max_tokens: 32000 > 4096, which is the maximum allowed number of output tokens for claude-3-opus-20240229"}}

The Claude API was working fine last month, but this error started recently. I'm currently able to use the GPT API without any issues.
I have tried the following troubleshooting steps but they did not resolve the issue:
- Changing the API Key
- Disabling and re-enabling Claude
- Deleting and clearing chat history

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - ChatHub Version: 3.23.2

**Comment by wong2** [comment]
I have submitted a fix, please wait a few hours.

**Comment by wong2** [comment]
Fixed in v3.23.3, pleaes upgrade.
