### ISSUE TITLE
Claude 3.5 Sonnet Availability for Own API

### ISSUE THREAD

**Issue by SimbaAowhoo** [chathub-dev/chathub#1223]
When I configure claude model for using my own API, it seems that there's no option for the new Claude 3.5 Sonnet model.

https://docs.anthropic.com/en/docs/about-claude/models

Could you please add this new model?

Thank you.

**Comment by wong2** [comment]
Please upgrade ChatHub to latest version, Claude 3.5 Sonnet is supported.

**Comment by SimbaAowhoo** [comment]
Oh I see, I was using 3.24. Now I see 3.24.1 supporting 3.5 Sonnet. Thank you very much.
