### ISSUE TITLE
聊天记录的下滑功能

### ISSUE THREAD

**Issue by ckitty123456** [chathub-dev/chathub#1224]
<img width="664" alt="e9895afff22dbcb46812972d235eff61" src="https://github.com/chathub-dev/chathub/assets/126028264/65400d52-2bb5-4482-b8cb-4ed025c728d6">

最右边的往下拉聊天记录的功能可以取消吗？感觉没什么作用，而且耽误事

**Comment by wong2** [comment]
可以截个全屏吗？

**Comment by ckitty123456** [comment]
<img width="1440" alt="bd667adb75829d4f6d0c94633f9feed7" src="https://github.com/chathub-dev/chathub/assets/126028264/fedaed9d-6a9a-4d97-80bd-0f5e6b1c4d26">
每个聊天框的“最右边的往下拉聊天记录的按钮”，感觉没什么作用，而且会在聊天框下方留下大量空白

**Comment by wong2** [comment]
哦我这里不会显示这些滚动条，所以没发现这个问题。

你是Windows+Chrome嘛？

**Comment by ckitty123456** [comment]
我是macbook pro M1 + chrome

**Comment by wong2** [comment]
你的Chrome版本是？

**Comment by ckitty123456** [comment]
Chrome 已是最新版本版本 126.0.6478.115(正式版本) (arm64)

你尝试提一下这个问题：除了欧拉公式，还有哪些数学最美公式？
当回答的内容占满这个屏幕时，聊天框最右边就会出现两个“聊天记录下滑条“

**Comment by wong2** [comment]
好的。好像是只有回答包含公式的时候会出现

**Comment by ckitty123456** [comment]
<img width="1430" alt="f7df48c7ab1f0e4f192942ff17926155" src="https://github.com/chathub-dev/chathub/assets/126028264/30d5b66f-76a6-45e0-90b9-78dd7e1de0de">
除了“聊天记录滚动条“的bug外，还有公式容易出聊天框外面（见图）

**Comment by wong2** [comment]
收到

**Comment by wong2** [comment]
请升级到v3.24.3，两个问题都修复了
