### ISSUE TITLE
Request to compare two different AI assistants

### ISSUE THREAD

**Issue by EvaPavon** [chathub-dev/chathub#1227]
Hi,
I've been trying to set Gemini and Claude side by side, but instead of Claude, ChatGPT appears.
Why is this when I have a free Claude account?
Thank you,
Eva

**Comment by wong2** [comment]
How did you set Gemini and Claude side by side?

**Comment by EvaPavon** [comment]
Sorted. Thank you. I didn't see there was a drop-down arrow to switch from
ChatGPT to Claude. Great extension!
