### ISSUE TITLE
Perplexity web always told me "Please pass Perplexity security check"

### ISSUE THREAD

**Issue by tangxiangpi** [chathub-dev/chathub#1229]
![image](https://github.com/chathub-dev/chathub/assets/18000558/9d9e5600-287a-4a0a-a8ae-19250b3c382b)
![image](https://github.com/chathub-dev/chathub/assets/18000558/8f2bd2af-feed-4227-a29e-3c6c7d80e9fc)

**Comment by wong2** [comment]
Please try again with v3.24.5

**Comment by sijitang** [comment]
v3.25.0 still has this problem. please fix

**Comment by wong2** [comment]
@sijitang What happens when you click the "Resolve" button?

<img width="482" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/6f6ecff7-e5a1-4b60-a7cc-e7af43c7e2c9">
