### ISSUE TITLE
Bing Copilot "Request is throttled"

### ISSUE THREAD

**Issue by GlennKelly** [chathub-dev/chathub#1232]
Every response I'm getting from Bing Copilot is... "Request is throttled."
Gemini and ChatGPT responses are doing fine.
Just an issue with Bing Copilot

Chrome Browser

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by Artushfoto** [comment]
Same problem:

ChatHub - GPT-4, Gemini, Claude side by side
Zapnuto
Popis
Use ChatGPT, Gemini, Claude, Llama and more chatbots simultaneously
Verze 3.25.1
Chrome: Verze 126.0.6478.127 (Oficiální sestavení) (64bitový)
