### ISSUE TITLE
ChatGPT Model Limit Exceeded Error

### ISSUE THREAD

**Issue by okellco** [chathub-dev/chathub#1235]
When i set ChatGPT model to auto it's works until 4o hits the limit and says "{"detail":{"message":"You have sent too many messages to the model. Please try again later.","code":"model_cap_exceeded","clears_in":11461}}". So I have to set model to 3.5 to continue working.
Here (open the gifs in new tab if you can't see clearly):
![ChatGPT-4o](https://github.com/chathub-dev/chathub/assets/93874524/6292487b-c893-47c6-9747-8ea1d624d149)
![ChatGPT-3 5](https://github.com/chathub-dev/chathub/assets/93874524/275158d3-4596-420f-accb-e4b1a24b7bec)

**Comment by wong2** [comment]
This error comes from OpenAI. You will get the same result if you use https://chatgpt.com. They have a limit on the number of GPT-4 messages you can use within a certain period. After exceeding the limit, you need to wait before you can continue using it. GPT-3.5 has no such limit.

**Comment by okellco** [comment]
Thanks for the response,
https://chatgpt.com switches models automatically when you have reached the limit. The problem with ChatHub you have to go to the settings and change it to 3.5 every time

**Comment by okellco** [comment]
> This error comes from OpenAI. You will get the same result if you use https://chatgpt.com. They have a limit on the number of GPT-4 messages you can use within a certain period. After exceeding the limit, you need to wait before you can continue using it. GPT-3.5 has no such limit.

Thanks for the response,
https://chatgpt.com switches models automatically when you have reached the limit. The problem with ChatHub you have to go to the settings and change it to 3.5 every time

**Comment by wong2** [comment]
I see. I will implement that.

**Comment by wong2** [comment]
Implemented in 3.26.2
