### ISSUE TITLE
通过chatgpt账号登陆的，回复存在问题

### ISSUE THREAD

**Issue by ckitty123456** [chathub-dev/chathub#1236]
![image](https://github.com/chathub-dev/chathub/assets/126028264/2784e0ad-e8a4-4737-aba9-92f372251bf0)

chathub插件：通过chatgpt账号登陆的，回复存在问题

**Comment by wong2** [comment]
可以发我这个prompt吗

**Comment by ckitty123456** [comment]
理解相关的背景知识和技术原理建立新认知一次讲透一个知识点，知其然，也知其所以然。使阅读起来有趣味、无负担：
时间常数
时间常数 $(\tau)$ 是一个表示系统响应速度的参数，通常用在 RC 电路、RL 电路或其他时间响应系统中。对于 $R C$ 电路，时间常数 $\tau$ 定义为:
$$
\tau=R C
$$

其中， $R$ 是电阻， $C$ 是电容。时间常数表示系统响应达到 $\$ 63.2 \% \$$ 的时间。



设置里没有prompt，只有对话里加了prompt

**Comment by wong2** [comment]
没能够复现它。。
