### ISSUE TITLE
Was image input removed?

### ISSUE THREAD

**Issue by SeanBannister** [chathub-dev/chathub#1238]
ChatHub used to have the button seen in the screenshot below for image input, I've noticed my image input button is no longer there, was this removed?

![image](https://github.com/chathub-dev/chathub/assets/197231/6695f75e-216f-43ee-a1d4-5fde3c8a0bcb)

**Comment by wong2** [comment]
We have removed the separate image input tab, but if all chatbots you selected supports image input, the icon will appear:

<img width="1272" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/ad6e20fa-4cf1-4dbb-9b9a-c18a8e125497">
