### ISSUE TITLE
这个开源版本好像没有任何新的模型，基本上都去年的，会考虑加上新的模型吗？

### ISSUE THREAD

**Issue by jiangying000** [chathub-dev/chathub#1239]
如果官方没有这个意向，有谁自己加了，也开源的话可以发下链接分享一下

**Comment by jiangying000** [comment]
同时和多个bot聊天还是挺有用的，我想自建这种服务，还有其他类似的前端框架吗？

**Comment by wong2** [comment]
因为有人抄袭，所以没有在更新代码了。你可以从Chrome商店安装最新版使用
