### ISSUE TITLE
bing不能用了

### ISSUE THREAD

**Issue by weizhenhuan** [chathub-dev/chathub#124]
<img width="989" alt="image" src="https://user-images.githubusercontent.com/55399998/226290603-dd0d9669-dd4d-44b1-94e4-cebbd10b0328.png">

**Comment by wong2** [comment]
Duplicate of #99

**Comment by ypmjx123** [comment]
> <img alt="image" width="989" src="https://user-images.githubusercontent.com/55399998/226290603-dd0d9669-dd4d-44b1-94e4-cebbd10b0328.png">

要新版本的chathub
