### ISSUE TITLE
百川无法使用

### ISSUE THREAD

**Issue by timlincool** [chathub-dev/chathub#1240]
**Describe the bug**
[POST] "https://www.baichuan-ai.com/api/user/user-info": 500

![image](https://github.com/chathub-dev/chathub/assets/5269547/3b10a139-df03-4df1-98ad-7de3c758d3db)
但我直接到官网是可以使用的

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - ChatHub Version : 3.28.0

**Comment by dxdwyz** [comment]
+1

**Comment by wong2** [comment]
百川不再支持
