### ISSUE TITLE
《复制回复的文字》格式问题

### ISSUE THREAD

**Issue by ckitty123456** [chathub-dev/chathub#1244]
![image](https://github.com/user-attachments/assets/df0c16ab-1120-4424-ba76-d163fad3590b)
您好，当gpt回复的答案很好，我想整理下来时，格式应该是markdown格式，这样的格式不方便整理（如图），能不能直接就是word里的正常显示那样

**Comment by wong2** [comment]
如果需要渲染好的格式，可以选中回答来复制：

<img width="571" alt="image" src="https://github.com/user-attachments/assets/048c9b04-a5c7-4083-9dfa-5789afdd9530">
