### ISSUE TITLE
发送按钮和粘贴图片

### ISSUE THREAD

**Issue by Alanrk** [chathub-dev/chathub#1248]
希望支持回车发送信息；支持粘贴板图片

**Comment by wong2** [comment]
你说的这两个都有呀。。

**Comment by Alanrk** [comment]
> 你说的这两个都有呀。。
网页版的回车是换行

**Comment by wong2** [comment]
@Alanrk 你有在网页版的设置里面修改发送快捷键吗？

<img width="323" alt="image" src="https://github.com/user-attachments/assets/0894b6b8-5d14-48e1-b601-0bcb222918ab">
