### ISSUE TITLE
edge插件已激活突然变为未激活，输入激活码显示激活失败

### ISSUE THREAD

**Issue by lionqy163** [chathub-dev/chathub#1250]
![image](https://github.com/user-attachments/assets/3e2883b1-c357-4afa-9b9b-0fc708de5f93)

**Comment by wong2** [comment]
重试也是一直报这个错吗？

**Comment by lionqy163** [comment]
> 重试也是一直报这个错吗？

是的

**Comment by wong2** [comment]
请你现在再试一下呢？

另外麻烦打开插件的管理页，截图看看这个Site access是什么？

<img width="910" alt="image" src="https://github.com/user-attachments/assets/1396db96-285d-4d11-b5bc-25460694188a">

**Comment by lionqy163** [comment]
可以了
