### ISSUE TITLE
建议：通过api key使用的模型均可自定义模型和API Host

### ISSUE THREAD

**Issue by hidenmaskvip** [chathub-dev/chathub#1252]
针对通过api key使用的模型，提几个建议
1. 自定义模型：
openai、gemini、claude现在只预置了几个常用的模型，建议可以自定义模型名称，方便用户调用未预置的模型
2. 自定义API Host：
现在只有openai和gemini能自定义API Host，其他都不行（如claude）
建议为所有模型都添加自定义API Host功能，默认为官方调用网址，但用户可自定义

**Comment by wong2** [comment]
你好，现在可以通过添加自定义机器人的方式来实现

**Comment by hidenmaskvip** [comment]
明白，但开放一下不是更省事吗？否则还得一个一个添加
如：用的其他渠道claude，还是claude调用格式，不是openai调用格式，怎么添加自定义机器人呢？这种情况下如果能自定义已有的claude API Host，就方便很多

**Comment by wong2** [comment]
明白。Claude我准备加一下
