### ISSUE TITLE
chathub code

### ISSUE THREAD

**Issue by Par-Nitin1** [chathub-dev/chathub#1257]
How to run this code chathub code

how to start chathub code in github give me suggestions and instructions to follow step.

i am follow this step
zip code download and extract
and after npm install
and after npm run dev

But not start project.
give me solution to start project.

https://github.com/chathub-dev/chathub

**Comment by wong2** [comment]
Use yarn instead

**Comment by Par-Nitin1** [comment]
give me step by step

**Comment by wong2** [comment]
Due to your attitude, I will not give you any guidance

**Comment by Par-Nitin1** [comment]
![image](https://github.com/user-attachments/assets/d2ace9fd-c923-4411-9978-2774b4180e93)

https://chatgpt.com/api/auth/session
app api has cors error how to solve?
