### ISSUE TITLE
Unable to pay

### ISSUE THREAD

**Issue by Saharok5** [chathub-dev/chathub#1259]
Hello.
I want to pay for a premium account. But I can't do it from Russia. Can you add a function so that I can pay from Russia?

**Comment by wong2** [comment]
Hi, this is a limitation of Stripe. 
We also support payment with PayPal or Crypto (USDT), if you can use those, please contact our support team for further action: contact@chathub.gg

**Comment by Saharok5** [comment]
> Привет, это ограничение Stripe. Мы также поддерживаем оплату через PayPal или Crypto (USDT), если вы можете их использовать, свяжитесь с нашей службой поддержки для дальнейших действий: [contact@chathub.gg](mailto:contact@chathub.gg)

No, unfortunately, my friend! Russia is in isolation. But for some reason payments are made through the fast payment service. Through the QR code.
