### ISSUE TITLE
Custom Chatbots 地址路径出错

### ISSUE THREAD

**Issue by adieUkid** [chathub-dev/chathub#1264]
**Describe the bug**
我用 chathub 对接[智谱 AI ](https://open.bigmodel.cn/dev/api)的模型，
配置是这样的：
![image](https://github.com/user-attachments/assets/e67d4458-b2d3-4297-8e83-16088a4af2c8)
之前我用了大概1-2 个月了，一直是正常的。大概从上周开始突然开始报错：
![image](https://github.com/user-attachments/assets/c1fc94d7-6dda-4e15-bac7-b70597e3a55b)

这个报错应该是智谱 API 服务器返回的，原因是 chathub 好像在我配置的 https://open.bigmodel.cn/api/paas/v4/chat/completions 地址后面又追加了 "/v1/chat/completions" 部分所以导致智谱的 API 服务器无法识别，请问是近期做了什么更新吗。
这个我理解应该是智谱的 API 设计也脱离了标准。不过是否可以由用户选择是指定完整的 URL，或者是只指定一个 host 由 chathub 追加标准的路径。
谢谢。

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Edge
 - ChatHub Version v3.36.0

**Comment by wong2** [comment]
是的，最近改成只要用户填 host 部分了，没想到智谱和其它不一样，我今天看看怎么解决

**Comment by wong2** [comment]
在最新版 3.37.0 中兼容了，试试看
