### ISSUE TITLE
自定义模型API报错

### ISSUE THREAD

**Issue by stevejoeyms** [chathub-dev/chathub#1265]
最近在用自定义机器人API的时候，发现请求地址报错了，chathub默认会在后面加上v1/chat/completions
智谱AI的是V4，会报错

api配置：
![image](https://github.com/user-attachments/assets/01549e41-ebf8-4f74-ad4d-fa5b2092e363)

报错：
![image](https://github.com/user-attachments/assets/051f7ec8-6663-431d-8b13-cdfa85e71661)

**Comment by wong2** [comment]
有没有升级到最新版 3.37.1 ?

**Comment by stevejoeyms** [comment]
哈哈哈升级完完美解决 棒
