### ISSUE TITLE
Asking for refund

### ISSUE THREAD

**Issue by KevinMen1209** [chathub-dev/chathub#1267]
Hi,

I hope you're well. I recently noticed that I accidentally purchased a premium subscription on my account (mxx5347@gmail.com) for one month. Unfortunately, I was unable to locate an option to request a refund.

I did not intend to make this purchase, and I would greatly appreciate your assistance in processing a refund.

Thank you for your understanding and support.

Best regards,
Kevin

**Comment by wong2** [comment]
Please contact contact@chathub.gg for refund request.
