### ISSUE TITLE
Deepseek API访问404 not found

### ISSUE THREAD

**Issue by Mizar77** [chathub-dev/chathub#1268]
**Describe the bug**
Deepseek网页端可以访问，但是在chathub上使用API访问，显示404 not found

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome
 - ChatHub Version v3.38.2

**Comment by wong2** [comment]
请问你的配置是什么样的呢？我刚试了下可以
<img width="561" alt="image" src="https://github.com/user-attachments/assets/62252ca8-cbf7-47dd-96be-a96aca5edd55">

**Comment by hhr114** [comment]
是vpn的故障吗？我也有同样的问题，api key输入后，对话显示404
![](https://s2.loli.net/2024/08/21/2wB7HPupxIKsWFm.png)

**Comment by wong2** [comment]
@hhr114 请问你的配置是什么样的呢？

**Comment by hhr114** [comment]
> @hhr114 请问你的配置和ChatHub版本是什么样的呢？

ChatHub版本 v3.37.1 ，浏览器Microsoft Edge版本 127.0.2651.105 (正式版本) (64 位)。
一个重要细节是我使用的是 chathub自定义机器人，当时chathub还没有deepseek的接口，是不是后来更新添加了，自定义就不行了？
![](https://s2.loli.net/2024/08/21/D16VBmuo9Lf85sQ.png)

**Comment by Mizar77** [comment]
已解决，之前使用的是自定义机器人，更改为“通过API Key使用-> deepseek”即可

**Comment by wong2** [comment]
我还需要继续看看为什么用自定义机器人不行了，所以如果有你们的deepseek自定义机器人配置的截图就好了

**Comment by hhr114** [comment]
这个配置之前是可以正常使用的
![](https://s2.loli.net/2024/08/21/mTFY4IyjOWRMNpq.png)

**Comment by wong2** [comment]
@hhr114 好的，我知道原因了。下个版本会兼容一下

**Comment by wong2** [comment]
在最新版 v3.38.6 修复了
