### ISSUE TITLE
Not able to use perplexity

### ISSUE THREAD

**Issue by vageeshkumar** [chathub-dev/chathub#1269]
**Describe the bug**
Not able to use perplexity (see pasted image)

**Desktop (please complete the following information):**
 - OS: MacOS 12.7.5
 - Browser: Chrome
 - ChatHub Version: (v3.40.0)

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/c4cf24bb-8b98-4a4f-ae1c-d2d831127e3c">

**Comment by wong2** [comment]
It's well known that you should not trust AI models to answer questions about themselves.

**Comment by vageeshkumar** [comment]
If that's true then I'm surprised why Gemini, Claude, and ChatGPT answer that correctly every single time
