### ISSUE TITLE
edge插件更新v3.37.1后，配置自定义机器人失败

### ISSUE THREAD

**Issue by lionqy163** [chathub-dev/chathub#1270]
我封装了openai的接口进行消息转发，对外暴露地址如下：
https://*.*.com/chat/completions/97b4eb38-e670-d317-b4aa-417482ae6d54
当使用自定义机器人配置custom的链接地址时，被额外添加了/v1，导致访问失败，在插件更新前一直可以正常使用的
https://*.*.com/chat/completions/97b4eb38-e670-d317-b4aa-417482ae6d54/v1

**Comment by wong2** [comment]
请问你的转发是用什么开源项目搭建的吗？

**Comment by lionqy163** [comment]
> 请问你的转发是用什么开源项目搭建的吗？

不是，是直接调用openai的api，封装到自己的项目中

**Comment by wong2** [comment]
我看到你和这个评论描述的api的模式是一样的，都是 `/chat/completions/<uuid>`：https://github.com/chathub-dev/chathub/issues/1266#issuecomment-2301637881 难道是巧合吗？

**Comment by lionqy163** [comment]
可能是我公司的同事

**Comment by wong2** [comment]
好的，我想想。。这个改动的原因写在这里了 https://github.com/chathub-dev/chathub/issues/1266#issuecomment-2292649788

你们这个url其实不符合openai API的规范

**Comment by lionqy163** [comment]
我们有个系统，可以用通义千问和OPENAI配置、训练个人的专属模型，弄好后访问地址就是这样的
https://..com/chat/completions/97b4eb38-e670-d317-b4aa-417482ae6d54

**Comment by lionqy163** [comment]
> 好的，我想想。。这个改动的原因写在这里了 [#1266 (comment)](https://github.com/chathub-dev/chathub/issues/1266#issuecomment-2292649788)
> 
> 你们这个url其实不符合openai API的规范

如果在插件apihost中配置openai的地址，使用openai api的规范是合理的，选项是custom，定制化封装API长什么样用户是有决策权的

**Comment by lionqy163** [comment]
> 好的，我想想。。这个改动的原因写在这里了 [#1266 (comment)](https://github.com/chathub-dev/chathub/issues/1266#issuecomment-2292649788)
> 
> 你们这个url其实不符合openai API的规范

当使用openai的sdk请求兼容openai的接口时，sdk并不会对接口地址限制必须以v1结尾，所以将接口地址划分到规范范畴并不合适

**Comment by wong2** [comment]
我所说的不符合规范是指 /chat/completions/ 后面的 uuid 部分，当使用openai官方SDK时，设置的是baseUrl，然后SDK会请求 `baseUrl + /chat/completions`

不知道你们这个接口如果通过openai SDK使用的话，是如何配置的？

**Comment by wong2** [comment]
我打算改成，如果是`custom`类型下，就不对输入的url做任何改造，直接原样请求

**Comment by lionqy163** [comment]
> 我所说的不符合规范是指 /chat/completions/ 后面的 uuid 部分，当使用openai官方SDK时，设置的是baseUrl，然后SDK会请求 `baseUrl + /chat/completions`
> 
> 不知道你们这个接口如果通过openai SDK使用的话，是如何配置的？

![image](https://github.com/user-attachments/assets/4ac8d32e-17c5-4f57-a825-865a40fbdd1c)

类似这样，GPT回答我的。

**Comment by wong2** [comment]
GPT回答错了，但不重要，我会兼容

**Comment by lionqy163** [comment]
> GPT回答错了，但不重要，我会兼容
图没截全，补上了

**Comment by lionqy163** [comment]
> GPT回答错了，但不重要，我会兼容

弄清楚了，自封装的服务后端配置了两个控制器路径，使用opai的sdk时会在baseurl后拼上/chat/completions，当程序识别后自动处理映射到没有拼接的接口上

**Comment by wong2** [comment]
Chrome插件商店发布了 `v3.41.1`，更新试试看
