### ISSUE TITLE
Prompt stopping

### ISSUE THREAD

**Issue by maiconfidelix** [chathub-dev/chathub#1271]
**Describe the bug**
When you ask it to show a complete code, in any AI it is stopping in the middle of the code, before it was writing normally until it finished, now it simply stops as if it had already finished showing the entire code, even if you ask it again to show the complete code, at some point it stops writing
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Arc Browser
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by wong2** [comment]
Can you show me a screen recording of it?

**Comment by maiconfidelix** [comment]
![Captura de tela 2024-08-27 054021](https://github.com/user-attachments/assets/2f66a77e-7d98-45a3-b32f-090a86b55eb5)
he stopped responding before finishing, the only one at the moment who is responding until the end is Chatgpt 4o

**Comment by wong2** [comment]
Perhaps the code is too long? Each model has different max output length.

**Comment by maiconfidelix** [comment]
400 lines, but they were all responding completely and at the end it still said all the corrections

**Comment by wong2** [comment]
> 400 lines, but they were all responding completely and at the end it still said all the corrections

Sorry I'm confused, I think you said they would stop responding before finishing?

**Comment by maiconfidelix** [comment]
imagine that the text has 400 lines, for example, when it reaches 300 lines the prompt stops, as if it had already finished
