### ISSUE TITLE
Claude 3.5 Sonnet extremely dumb and not like claude.ai at all.

### ISSUE THREAD

**Issue by blankuserrr** [chathub-dev/chathub#1272]
**Describe the bug**
Claude 3.5 sonnet is extremely unintelligent, it forgets everything I tell it, continuously needs to be told what's currently happening, and just overall has horrible quality output.

**Desktop (please complete the following information):**
- Chrome
- (No, there isn't a version in the settings.)

**Comment by wong2** [comment]
Can you show a screenshot of bad quality conversation?

**Comment by blankuserrr** [comment]
> Can you show a screenshot of bad quality conversation?

I've found the issue, every time you stop the output, it forgets it's own last message and the user's last message.

**Comment by wong2** [comment]
That's true. We will compare the behaviour with chatgpt.com and claude.ai to decide if this need to be improved.
