### ISSUE TITLE
禁用默认的 system prompt

### ISSUE THREAD

**Issue by adieUkid** [chathub-dev/chathub#1275]
我在 chatgpt 官网上用 4o 模型问问题，回答的丰富度就比较详细。但是通过 chathub 问问题往往就很简略，我发现是 chathub 会携带一些前缀 prompt 吗？导致体验不太好。如果我在问题中强调需要提高回答的丰富度，那么就能有效改善 chatgpt 的回答。
是否可以关掉这个默认的 prompt，就按官方默认的设置来。

截图：

![image](https://github.com/user-attachments/assets/a4d3351b-e421-4f99-a5b6-cd971041d265)

chatgpt 官网上的回答：
![image](https://github.com/user-attachments/assets/63bdd264-6a0a-4fd3-8073-4d3cfc580ed1)

通过chathub 问候，在官网看历史记录，发现有 system prompt：
![image](https://github.com/user-attachments/assets/98d34a74-162e-4411-9b0b-394b9a1dfd3e)

通过chathub 返回的回答，就简略了不少：
![image](https://github.com/user-attachments/assets/9b8536fb-5cff-4830-b981-52d9d895df17)

我搜了一下，大概和下面这个问题类似：https://github.com/chathub-dev/chathub/issues/1185

**Comment by wong2** [comment]
关掉web access就不会用这段system prompt了

**Comment by adieUkid** [comment]
额，可我就是想要在 chathub 上通过账号使用的方式访问 chatgpt，我没买 token。还是说这个实际是官方加的么，在 chathub 上用这种 direct 的方式就是会受影响。
