### ISSUE TITLE
使用openai 3.0还是3.5版本的api

### ISSUE THREAD

**Issue by 689kco** [chathub-dev/chathub#128]
这个插件使用openai 3.0还是3.5版本的api？

**Comment by SSwasm** [comment]
同问

**Comment by withuan** [comment]
请问bing支持GPT-4吗？

**Comment by dyfloveslife** [comment]
> 这个插件使用openai 3.0还是3.5版本的api？

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/22425377/226504159-23466b84-3395-48f8-b24e-a9b2fbcaa3ba.png">

**Comment by wong2** [comment]
更新到 v1.5.3 在API模式和webapp模式下都可以选择使用哪个model，默认都是3.5的
