### ISSUE TITLE
replying with jokes

### ISSUE THREAD

**Issue by urion80** [chathub-dev/chathub#1280]
why are my queries answered with jokes?

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser chrome
 
<img width="759" alt="2024-09-17 09_48_13-ChatHub" src="https://github.com/user-attachments/assets/a08c0b76-f9ad-48ca-aa71-e2e14c497eb9">

**Comment by wong2** [comment]
That's weird, where did you buy ChatHub?

**Comment by superpramod** [comment]
Same issue here ! Basic model works but Advance Model replies with jokes !
![1Capture](https://github.com/user-attachments/assets/e594228e-39a8-4f15-b229-27dcec17f4a5)

**Comment by wong2** [comment]
This means you're using a shared account from onehack.us, you should request a refund from the seller immediately.
