### ISSUE TITLE
OpenAI o1-mini not streaming, returning 524 sometimes. 

### ISSUE THREAD

**Issue by blankuserrr** [chathub-dev/chathub#1282]
When using o1-mini, the model doesn't stream its output, causing the frontend to show a 524 cloudflare error when the response hangs. 

**Desktop**
 - OS: Windows
 - Browser: Firefox
 - ChatHub Version: Browser

**Comment by wong2** [comment]
o1 models does not support streaming.
Can you show me an example of 524 error?
