### ISSUE TITLE
插件无法登陆，显示抱歉，您已被阻止

### ISSUE THREAD

**Issue by s52m** [chathub-dev/chathub#1284]
上周充值后，昨晚打开显示的页面是下面显示的，还有充值普通会员后后还在显示pro会员未扣款成功
![付款](https://github.com/user-attachments/assets/0d6a7186-7744-434c-a178-4656bb280f85)
![登陆](https://github.com/user-attachments/assets/a1442e43-ce4f-4c8d-a4f1-14262d7f1d93)
会考虑增加支付宝微信支付吗？每次充值还得上淘宝找代充的

**Comment by wong2** [comment]
请使用VPN访问ChatHub

**Comment by s52m** [comment]
这个是更新了吗？之前还可以直接登陆的，我这边不能翻墙




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chathub-dev/chathub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月24日(星期二) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chathub-dev/chathub] 插件无法登陆，显示抱歉，您已被阻止 (Issue #1284)






请使用VPN访问ChatHub

**Comment by wong2** [comment]
对最近的变化

**Comment by s52m** [comment]
那之后不使用VPN就直接用不了了吗？还是会考虑国内不用VPN的情况
