### ISSUE TITLE
授权突然失效

### ISSUE THREAD

**Issue by jschen1009** [chathub-dev/chathub#1287]
![2024_09_25_16_09_51](https://github.com/user-attachments/assets/5a863038-0043-40f0-a92c-b8ba4004a113)

**Comment by jschen1009** [comment]
![2024_09_25_16_09_51](https://github.com/user-attachments/assets/d7e79dee-c71f-4d85-b0b4-c24c164714d2)

**Comment by wong2** [comment]
@jschen1009 再试一下

**Comment by jschen1009** [comment]
正常了
