### ISSUE TITLE
claude web模式，回复答案的markdown显示问题

### ISSUE THREAD

**Issue by jacintagu** [chathub-dev/chathub#1291]
**Describe the bug**
![image](https://github.com/user-attachments/assets/ca94f66f-3fd4-4337-8bb1-3d2ee4e5753a)
预期显示成表格

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - ChatHub v3.46.2

**Comment by wong2** [comment]
的确

**Comment by wong2** [comment]
现在这种情况下可以预览生成的markdown代码了
