### ISSUE TITLE
能不能弄个stream开关

### ISSUE THREAD

**Issue by ckitty123456** [chathub-dev/chathub#1294]
{"error":{"message":"Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported. (request id: 20241011224556660468772xv8z2a2s)","type":"invalid_request_error","param":"stream","code":"unsupported_value"}}

**Comment by wong2** [comment]
会特殊支持下o1模型

**Comment by wong2** [comment]
最新版已支持
