### ISSUE TITLE
Allow multiple models to be selected from the same provider

### ISSUE THREAD

**Issue by SeanBannister** [chathub-dev/chathub#1296]
With OpenAI now providing o1-preview at quite an expensive price and it being much slower, I still want to use it sometimes but will usually use gpt-4o. It would be awesome if we could select multiple models from the same provider which would then be selectable in the left hand menu. This was I could easily switch between 4o and o1 without going into settings every time.

**Comment by wong2** [comment]
I think you can archieve this with the "Custom Chatbots" feature

**Comment by SeanBannister** [comment]
Unfortunately this doesn't work because, o1 doesn't support streaming, you get the following error when trying to chat with the model:

{"error":{"message":"Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.","type":"invalid_request_error","param":"stream","code":"unsupported_value"}}

Maybe there could be a checkbox in the custom chatbots to turn off streaming.

**Comment by wong2** [comment]
I think you can use o1 with the built-in OpenAI provider, and other GPT models with the custom chatbots.

**Comment by SeanBannister** [comment]
Oh, of course, that works. Thanks.
