### ISSUE TITLE
Perplexity does not work

### ISSUE THREAD

**Issue by Sal70100** [chathub-dev/chathub#1298]
It reports
[POST] "https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&sid=A-RC6-xSryUIfWp-AC4d": 400
**Desktop:
 - OS: [e.g. Windows]
 - Browser: chrome
 - ChatHub Version: v3.49.1

![PERPLEXITY does not work](https://github.com/user-attachments/assets/65f7764b-cae2-4210-bbb5-d63100c174f1)

**Comment by GAMAPLAY** [comment]
hi, the same problem  fro mmy first day with this programm, many windows doesn't work juste chatgpt, but the others programm they works 30% of time ? what's happened? need help plz

**Comment by wong2** [comment]
Fixed in latest version
