### ISSUE TITLE
Add support for Gemini's new Search Grounding feature

### ISSUE THREAD

**Issue by SeanBannister** [chathub-dev/chathub#1305]
The Gemini API has a new feature where you can ground results with Google search which reduces hallucinations and provides references to content https://developers.googleblog.com/en/gemini-api-and-ai-studio-now-offer-grounding-with-google-search/

Here's the important description of the feature "the model returns grounding sources (in-line supporting links) and Search Suggestions that point users to the search results corresponding to the grounded response."

**Comment by kayanco** [comment]
Yes, please add this!

**Comment by wong2** [comment]
Got it!
