### ISSUE TITLE
Add support for Perplexity's newly available citations

### ISSUE THREAD

**Issue by SeanBannister** [chathub-dev/chathub#1307]
Perplexity just announced that "Citations" are now enabled for everyone via the API, no flag needs to be specified. And you'll notice they are now showing in chathub... The only issue is none of these references currently link back to their sources, I'm guessing this HTML needs to be added in chathub :

![image](https://github.com/user-attachments/assets/935f8ead-1ff2-4389-9e31-a764b3fda82a)

You can see the announcement of this feature [here](https://docs.perplexity.ai/changelog/changelog#citations-public-release-and-increased-default-rate-limits).

**Comment by wong2** [comment]
Got it, I will see how to do it.

**Comment by SeanBannister** [comment]
![image](https://github.com/user-attachments/assets/ce0d5c49-56f1-468d-8bf9-3f01ec7383fe)

Citations are now linked, thanks. Maybe a little formatting would tidy things up though.

**Comment by wong2** [comment]
Yes, I've added support for it. The format issue will take some more time.
