### ISSUE TITLE
Cannot using ChatGPT while other AI ok

### ISSUE THREAD

**Issue by TryBesthn** [chathub-dev/chathub#1308]
**Describe the bug**
While I send an promt, ChatGPT send error: {"detail":"Model auto not found"}
Gemini & claude3.5 using smoothly

**Desktop (please complete the following information):**
 - OS: Macbook using macos
 - Browser: Chrome
 - ChatHub Version: v3.50.0

**Comment by wong2** [comment]
Hi, the latest version v3.51.0 fixed this.
