### ISSUE TITLE
You have sent to many messages to a model

### ISSUE THREAD

**Issue by Pat651857** [chathub-dev/chathub#1311]
**Describe the bug**
after sometime I get the message in ChatGPT 4.o {"detail":{"message":"You have sent too many messages to the model. Please try again later.","code":"model_cap_exceeded","clears_in":13078}}
**Desktop (Desktop):**
 - OS: [Windows]
 - Browser [Opera]
 - ChatHub Version [v3.57.0]

**Comment by wong2** [comment]
That's an error from ChatGPT.
