### ISSUE TITLE
Image upload button is not available in extension "all in one" mode, premium lifetime membership 

### ISSUE THREAD

**Issue by al3xxx** [chathub-dev/chathub#1313]
**Describe the bug**
Image upload icon and option is not available in "All in one" mode from browser extension for "Premium lifetime" account, while it is available in each separate frame prompt.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser : chromium
 - ChatHub Version : v3.58.0
 
![allinone](https://github.com/user-attachments/assets/24a33164-aca1-492f-8da4-70f4e2d47564)

**Comment by wong2** [comment]
Hi, the rule is: Only when all current models support image input will the upload image icon be displayed. In this case, Perplexity does not support image uploads.

**Comment by al3xxx** [comment]
@wong2 thank you. Would be nice to see it somewhere in the doc, may be FAQ?
