### ISSUE TITLE
Cannot read properties of undefined (reading 'value'),什么原因呢？

### ISSUE THREAD

**Issue by songtao2627** [chathub-dev/chathub#141]
Cannot read properties of undefined (reading 'value')
![image](https://user-images.githubusercontent.com/10362428/226814044-f4eeee1d-432b-403e-8008-39d85c570656.png)

**Comment by wong2** [comment]
你好，是什么版本呢？

**Comment by songtao2627** [comment]
> 你好，是什么版本呢？

1.4.2

**Comment by wong2** [comment]
请更新到 1.5 以上 https://chathub.gg
