### ISSUE TITLE
permanent login

### ISSUE THREAD

**Issue by venkat2305** [chathub-dev/chathub#147]
my account is logged in on the official [site](https://chat.openai.com/chat). everytime after opening the browser , to use chatgpt in the extension it is asking for me to login. can you please find a permanent fix.

**Comment by huangke-ha** [comment]
目前不可以用吗

**Comment by venkat2305** [comment]
It's asking me to login every time i open the broswer

**Comment by wong2** [comment]
Can you try the api mode

**Comment by venkat2305** [comment]
Api is not free, right? Because I tried the api mode it says there is an error

**Comment by wong2** [comment]
Yes, API is not free, you need to set your API key.

**Comment by wong2** [comment]
If you don't want to use API mode, can you try this version? https://github.com/chathub-dev/chathub/releases/tag/v1.8.3

**Comment by venkat2305** [comment]
it's asking for login again. my request is after loggin in once, we don't have to login again. it can be done via api but could you please find a way to do it without api?

**Comment by wong2** [comment]
I know, it works as you said for me. So I think there is some bug here

**Comment by venkat2305** [comment]
Please reopen the issue then
