### ISSUE TITLE
插件好用,但是有个问题

### ISSUE THREAD

**Issue by zwx7007** [chathub-dev/chathub#148]
使用NEW BING时候,没有参考链接,因为有些信息还需要详细信息才行,请问什么时候能加入吗?

**Comment by hotsmile** [comment]
我为啥用1.7版本报错了， new bing 
 (404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

**Comment by wong2** [comment]
@hotsmile 你的问题见 #99

**Comment by wong2** [comment]
@zwx7007 有参考链接的呀，在文本的数字角标那里
