### ISSUE TITLE
在等待回复时允许用户输入

### ISSUE THREAD

**Issue by lentikr** [chathub-dev/chathub#15]
在New Bing的官方版中，即便New Bing在输出流时，用户也可以输入下一句话，但本插件此时是无法输入的，并且鼠标在输入框时会显示为转圈的状态。可以模仿官方，此时允许用户输入，但不允许用户发送出去

**Comment by wong2** [comment]
https://github.com/chathub-dev/chathub/commit/5f3404ba3fda3afe92664ac43e908060280d5e5f
