### ISSUE TITLE
这个问题需要怎么处理 (404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))，

### ISSUE THREAD

**Issue by ZUIG333** [chathub-dev/chathub#151]

**Comment by strvirus** [comment]
又被禁了，同求，同时edgechat命令行都连不了了

**Comment by ZUIG333** [comment]
先修改host，魔法上bing吧

**Comment by wong2** [comment]
Duplicate of #99

**Comment by kaikaiss** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/63889189/227130020-5eb6b36b-ee9c-44b1-a164-518e5254f4cd.png">
我看报错信息好像是说，服务挂掉了，不是禁用了

**Comment by ZUIG333** [comment]
我直接注册了一个官网ChatGPT  这样稳一点
