### ISSUE TITLE
Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by Tomazi722** [chathub-dev/chathub#155]
Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.

API模式提示这个

**Comment by wong2** [comment]
检查下填写的 API key 是否包含了非英文的字符？

**Comment by prernagp** [comment]
@wong2 How did you fix this?

**Comment by wong2** [comment]
check your api key
