### ISSUE TITLE
Feature request: Save chat history

### ISSUE THREAD

**Issue by wbxl2000** [chathub-dev/chathub#157]
Hello,

I am a user of ChatHub and I really enjoy chatting with different chatbots in one app. However, I noticed that there is no option to save the chat history, and I have to manually clear the chat log every time I switch between chatbots. This is inconvenient and sometimes I want to review what I have said or what the chatbots have replied.

I wonder if you have any plans to add a feature that allows users to save their chat history, either locally or on a cloud service. This would make ChatHub more user-friendly and convenient. Also, do you accept pull requests from other developers? If so, I would be interested in contributing to this feature.

Thank you for your time and attention.

**Comment by wong2** [comment]
Chat history has been implemented in v1.7.0, you can manually install it here: https://github.com/chathub-dev/chathub/releases

**Comment by wbxl2000** [comment]
Great job on your open source project!
