### ISSUE TITLE
Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by kingsley0130** [chathub-dev/chathub#164]
it shows "Cannot read properties of undefined (reading 'value')",don't know why

**Comment by wong2** [comment]
what version are you using?

**Comment by kingsley0130** [comment]
i think it's he newest one with 3 conversation bar

**Comment by kingsley0130** [comment]
> what version are you using?

1.6.0

**Comment by YJXS-J** [comment]
> what version are you using?

This is also the case with version 1.8

**Comment by HailPHP** [comment]
> what version are you using?

1.8的chrome扩展也遇到这个问题了，1.7的时候正常的
bing的会提示这个，chatGPT正常

**Comment by kingsley0130** [comment]
i use the 1.6 version



At 2023-03-24 09:39:13, "YJXS-J" ***@***.***> wrote:

what version are you using?

This is also the case with version 1.8

**Comment by YJXS-J** [comment]
> 我用的是 1.6 版本 在 2023-03-24 09:39:13，“YJXS-J”***@***.***> 写道：你用的是什么版本？1.8 版本也是如此——直接回复这封邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您是该主题的作者。消息 ID：***@***.***>

v1.8，It was about the same time

**Comment by YJXS-J** [comment]
> i use the 1.6 version At 2023-03-24 09:39:13, "YJXS-J" ***@***.***> wrote: what version are you using? This is also the case with version 1.8 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

v1.8，It was about the same time

**Comment by 0xadu** [comment]
v1.7 does not work

**Comment by zl2103** [comment]
v1.8

**Comment by hionedrop** [comment]
1.6.0 the same problem

**Comment by hionedrop** [comment]
> 

Cannot read properties of undefined (reading 'value')

**Comment by michaeledi** [comment]
1.6同样问题，同时我之前edge的侧边栏正常使用，今天也出现了"Sorry, looks like your network settings are preventing access to this feature."，使用网上的重置设置这些都没有用，我没有header editor等类型插件，使用的是魔法，但是依旧出现问题，感觉bing更新了对地区限制的手段。

**Comment by NebulaTZL** [comment]
魔法上网，也出现了：“Sorry, looks like your network settings are preventing access to this feature.”

**Comment by user2318** [comment]
1.8遇到了同样的问题，魔法开全局一样不行，在官方页面开启聊天会提示“Sorry, looks like your network settings are preventing access to this feature”

**Comment by UCPRER** [comment]
Same problem in 1.6.0

**Comment by khuencheng** [comment]
![image](https://user-images.githubusercontent.com/5327960/227408129-60ffa0de-9385-47ff-9937-a6afdb2bc668.png)
![image](https://user-images.githubusercontent.com/5327960/227408167-75ef6f74-df9a-4a88-ad02-3cdadcdad7ba.png)

**Comment by michaeledi** [comment]
刚才在美国的远程主机上进行了测试，发现插件和bing都可以正常使用：
![image](https://user-images.githubusercontent.com/7577021/227408280-2a006f38-a46d-4d2b-a42a-ccbcdc0e2675.png)
已经基本可以证实不是插件本身问题，而是bing服务升级了对地区的判断方式，导致了服务在境内无法使用了。

**Comment by i6941** [comment]
+1,不用插件的话需要设置x-forwarded-for 为 1.1.1.1可以用，不然报错Sorry, looks like your network settings are preventing access to this feature.

**Comment by michaeledi** [comment]
> +1,不用插件的话需要设置x-forwarded-for 为 1.1.1.1可以用，不然报错Sorry, looks like your network settings are preventing access to this feature.

@i6941 请问大佬，不用插件是在哪里设置x-forwarded-for 为 1.1.1.1啊？

**Comment by poquitoApoco** [comment]
> 1.6同样问题，同时我之前edge的侧边栏正常使用，今天也出现了"Sorry, looks like your network settings are preventing access to this feature."，使用网上的重置设置这些都没有用，我没有header editor等类型插件，使用的是魔法，但是依旧出现问题，感觉bing更新了对地区限制的手段。

今早遇到了同样的情况。用OpenVPN科学上网会出现"Sorry, looks like your network settings are preventing access to this feature."。用V2ray就没有这样的问题。

**Comment by i6941** [comment]
用 Header Editor,导入json

{
"request": [
{
"enable": true,
"name": "bing-cn-to-www",
"ruleType": "redirect",
"matchType": "prefix",
"pattern": "https://cn.bing.com";,
"exclude": "",
"group": "bing-redirect",
"isFunction": false,
"action": "redirect",
"to": "https://www.bing.com";
}
],
"sendHeader": [
{
"enable": true,
"name": "bing",
"ruleType": "modifySendHeader",
"matchType": "regexp",
"pattern": "^http(s?)://www\\.bing\\.com/(.*)",
"exclude": "",
"group": "bing-direct",
"isFunction": false,
"action": {
"name": "x-forwarded-for",
"value": "1.1.1.1"
}
}
],
"receiveHeader": [],
"receiveBody": []
}

**Comment by llccool1** [comment]
Cannot read properties of undefined (reading 'value')

**Comment by limboking** [comment]
用HeadEditor改成1.1.1.1后，网页可以正常使用bing，但插件还是不行

**Comment by fireattack** [comment]
楼上提供的json怎么有很多奇怪的分号

加这一条就行了：
```json
{
    "sendHeader": [
        {
            "enable": true,
            "name": "bing add x-forwarded-for",
            "ruleType": "modifySendHeader",
            "matchType": "regexp",
            "pattern": "^https?://www\\.bing\\.com/.*",
            "exclude": "",
            "isFunction": false,
            "action": {
                "name": "x-forwarded-for",
                "value": "1.1.1.1"
            }
        }
    ]
}
```

**Comment by ider-zh** [comment]
v1.8.1 same problem
Cannot read properties of undefined (reading 'value')

**Comment by qiaozhiyong** [comment]
v1.8.1 same problem
Cannot read properties of undefined (reading 'value') 
应该是国内访问bing的问题，提示Sorry, looks like your network settings are preventing access to this feature.

**Comment by Andy-Dufresne1994** [comment]
clash配置下规则就行了

**Comment by michaeledi** [comment]
> 刚才在美国的远程主机上进行了测试，发现插件和bing都可以正常使用： ![image](https://user-images.githubusercontent.com/7577021/227408280-2a006f38-a46d-4d2b-a42a-ccbcdc0e2675.png) 已经基本可以证实不是插件本身问题，而是bing服务升级了对地区的判断方式，导致了服务在境内无法使用了。

Edit: 使用header-editor更改x-forwarded-for 为 1.1.1.1可以用，不过仅限网页版，插件和Edge右上角按钮依旧无法解决。目前比较有效的可能是下面提到的方式，供参考（把 [bing.com](http://bing.com/) 的流量也和 openai 一样转发到 cloudflare warp 的出口就可以用了，推测也是封了很多服务器 IP）：
https://www.v2ex.com/t/926788
https://github.com/fscarmen/warp

**Comment by wong2** [comment]
这样是不是不翻墙也可以用了？

**Comment by llccool1** [comment]
漂亮,找到问题所在了

**Comment by yangmingdizi** [comment]
> clash配置下规则就行了

如何在clash配置规则呢？

**Comment by wong2** [comment]
[chathub.zip](https://github.com/chathub-dev/chathub/files/11060118/chathub.zip)

打了个包，各位试试

**Comment by llccool1** [comment]
Wooden-Robot刚才打过包了,亲测可用,你这包晚了一点

**Comment by kingsley0130** [comment]
感谢各位

**Comment by jazzlost** [comment]
感谢大佬

**Comment by shy-song** [comment]
> [chathub.zip](https://github.com/chathub-dev/chathub/files/11060118/chathub.zip)
> 
> 打了个包，各位试试

貌似仍未解决问题，仍旧跳出提示

**Comment by xjqm-tao** [comment]
good jod！need magic +`x-forwarded-for: 1.1.1.1` ，thanks！

**Comment by kingsley0130** [comment]
> [chathub.zip](https://github.com/chathub-dev/chathub/files/11062055/chathub.zip) 搜索打包后的源码加上了，已测可用
大佬，请问具体怎么操作啊

**Comment by Andy-Dufresne1994** [comment]
> > clash配置下规则就行了
> 
> 如何在clash配置规则呢？

配置下parser，https://docs.cfw.lbyczf.com/contents/parser.html#%E7%AE%80%E4%BE%BF%E6%96%B9%E6%B3%95-yaml，prepend-rules添加规则：比如访问bing用美国节点（取决于你的机场节点）。我写的就是
```
- DOMAIN-KEYWORD,bing,美国LA-优化
```

**Comment by kooeyeoutlook** [comment]
> [chathub 2.zip](https://github.com/chathub-dev/chathub/files/11059845/chathub.2.zip) 搜索打包后的源码加上了，已测可用

上面写了，[chathub 2.zip](https://github.com/chathub-dev/chathub/files/11059845/chathub.2.zip) 搜索打包后的源码加上了，已测可用， 又打了个包 chathub 2.zip。 用这个包安装就好。

**Comment by wong2** [comment]
安装这个吧：https://github.com/chathub-dev/chathub/releases/tag/v1.8.2

**Comment by kooeyeoutlook** [comment]
> 安装这个吧：https://github.com/chathub-dev/chathub/releases/tag/v1.8.2

这个没有魔法能用么？先用的魔法可以，然后把魔法关了，还能持续使用。

**Comment by kingsley0130** [comment]
请教一下这个需要在哪安装啊，大佬



在 2023-03-25 11:24:42，"kooeyeoutlook" ***@***.***> 写道：

安装这个吧：https://github.com/chathub-dev/chathub/releases/tag/v1.8.2

这个没有魔法能用么？先用的魔法可以，然后把魔法关了，还能持续使用。

**Comment by wong2** [comment]
手动安装方法：https://github.com/chathub-dev/chathub#manual-installation--%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85

记得先去设置里导出你的数据

**Comment by kingsley0130** [comment]
> 手动安装方法：https://github.com/chathub-dev/chathub#manual-installation--%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85
> 
> 记得先去设置里导出你的数据

非常感谢，已经解决了

**Comment by wong2** [comment]
Chrome商店版本 1.8.3 已发布
