### ISSUE TITLE
bing在插件里和在网页端的回复不一样

### ISSUE THREAD

**Issue by lxpassion** [chathub-dev/chathub#166]
在插件里的回复更类似于gpt的回复，完成一项任务，但在网页里会聚合不同网页的内容并给出出处，这是为啥？

**Comment by wong2** [comment]
一样的呀
<img width="589" alt="image" src="https://user-images.githubusercontent.com/321947/227414890-851e20aa-d63c-4f3d-b740-af6b78f890ba.png">

这些数字角标就是出处

**Comment by lxpassion** [comment]
挺奇怪，上图是插件里的结果，下图是网页里的结果

[image: d832253f6720f6a437254630cab8053.png]
[image: fe05d19db500ff81554e1a927c984f4.png]

梁潇



Wang Dàpéng ***@***.***> 于2023年3月24日周五 11:12写道：

**Comment by wong2** [comment]
图片没有传上来

**Comment by lxpassion** [comment]
<img width="389" alt="微信图片_20230324113035" src="https://user-images.githubusercontent.com/128678269/227417715-9346977b-4070-4668-8e65-5333b5a14f86.png">
<img width="625" alt="微信图片_20230324113024" src="https://user-images.githubusercontent.com/128678269/227417720-605e85b2-7009-4ca5-812e-672617747bad.png">
