### ISSUE TITLE
可否支持页面内全屏和隐藏侧边栏？

### ISSUE THREAD

**Issue by wbxl2000** [chathub-dev/chathub#167]
即去掉红色的部分 和 隐藏绿色的部分。现在太窄了影响代码的阅读
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/57169560/227461951-39ff2067-b840-4fae-9c93-ee77f15a0b9f.png">

**Comment by wong2** [comment]
好的，考虑一下怎么做

**Comment by ArganOrz** [comment]
很好的建议，顶

**Comment by wong2** [comment]
最新版v1.14.1已支持
