### ISSUE TITLE
Unable to use GPT-4 API

### ISSUE THREAD

**Issue by AndrewDing-eth** [chathub-dev/chathub#170]
My GPT account has upgraded to plus, when whatever I select gpt-4 API model or gpt-4-32k (what is the difference?), it goes error: {"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}. How to solve this?

**Comment by wong2** [comment]
Plus doesn't give you access to GPT-4 in API mode, if you want to use GPT-4 in ChatHub, you should use Webapp Mode and select GPT-4 model there.

**Comment by AndrewDing-eth** [comment]
> Plus doesn't give you access to GPT-4 in API mode, if you want to use GPT-4 in ChatHub, you should use Webapp Mode and select GPT-4 model there.

OK thanks
