### ISSUE TITLE
api-key无法使用问题

### ISSUE THREAD

**Issue by li-2132** [chathub-dev/chathub#177]
想请教一下，我直接从个人中心创建的api为什么不能使用呢，还是说我使用api-key也需要科学上网呢
<img width="797" alt="屏幕截图 2023-03-25 000702" src="https://user-images.githubusercontent.com/60682098/227580074-039b54f2-2511-4e13-bdbb-3dfeb2b6d08f.png">

**Comment by chenhuohuo23** [comment]
应该是API地址没改，官方的国内访问不了

**Comment by wong2** [comment]
科学上网
