### ISSUE TITLE
chatgpt无法正常加载

### ISSUE THREAD

**Issue by sakanachen01** [chathub-dev/chathub#183]
直接在openai打开chatgpt可以正常对话，但是使用chathub只有bing有反馈，chatgpt一直在加载

**Comment by wong2** [comment]
版本是多少呀

**Comment by sakanachen01** [comment]
> 

v 1.8.3

**Comment by sakanachen01** [comment]
fixed.
使用最笨的重启大法可以解决，但是个人认为根本原因是需要重新登录openai，但是重启前chathub无法弹出openai登陆界面

**Comment by wong2** [comment]
不可以的，应该有提示不要关掉它吧
