### ISSUE TITLE
chatgpt无法正常使用

### ISSUE THREAD

**Issue by tianyuchou** [chathub-dev/chathub#184]

**Comment by wong2** [comment]
具体一些呢

**Comment by tianyuchou** [comment]
一直处于一个加载的过程，并且无法弹出登陆界面

**Comment by wong2** [comment]
好的，等下看看

**Comment by sakanachen01** [comment]
同样的问题，只要一段时间没有使用就会一直加载

**Comment by gitqiexy** [comment]
(404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

**Comment by sundaycomm** [comment]
Failed to fetch (https://www.bing.com/turing/conversation/create)

**Comment by 1140209777** [comment]
Failed to fetch (https://www.bing.com/turing/conversation/create)

**Comment by shylockWu** [comment]
> (404 (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

亲测同样的问题，但是实在没开梯子的情况下，我开了梯子就好了，可以试试

**Comment by 1140209777** [comment]
> 



> > (404 (https://edgeservices.bing.com/edgesvc/turing/conversation/create))
> 
> 亲测同样的问题，但是是在没开梯子的情况下，我开了梯子就好了，可以试试

> 用这个插件就是为了不用梯子

**Comment by wong2** [comment]
这个issue是关于ChatGPT无法正常使用的，Bing的问题请看置顶的 #99

**Comment by wong2** [comment]
试了下，没能复现。能不能说一下具体流程？
比如一开始浏览器里没有chat.openai.com的tab打开，此时打开ChatHub向ChatGPT发消息，就一直处于加载中的状态，且没有chat.openai.com页面被打开？
