### ISSUE TITLE
v1.8 Failed to fetch

### ISSUE THREAD

**Issue by jingliancui** [chathub-dev/chathub#189]
<img width="952" alt="failed to fetch" src="https://user-images.githubusercontent.com/16309962/227787777-1ce0fb67-3596-4035-b414-6da963b0e395.png">

**Comment by HollowlightCD** [comment]
the same

**Comment by wong2** [comment]
要翻墙

**Comment by wong2** [comment]
@jingliancui 请问当出现这种情况时，浏览器里有 chat.openai.com 的网页打开没

**Comment by prophetss** [comment]
@wong2 一样的问题，浏览器里没有 chat.openai.com 的网页打开

**Comment by wong2** [comment]
@prophetss 可以描述下这种情况是如何发生的吗？

**Comment by prophetss** [comment]
> @prophetss 可以描述下这种情况是如何发生的吗？

没有vpn的情况下，使用bing搜索任意内容就会报这个错

**Comment by wong2** [comment]
Bing现在必须翻墙了

**Comment by prophetss** [comment]
> Bing现在必须翻墙了

好吧。。

**Comment by wong2** [comment]
https://twitter.com/wong2_x/status/1639900972729380865
