### ISSUE TITLE
希望能加入切换深色模式的功能

### ISSUE THREAD

**Issue by Opt-SCon** [chathub-dev/chathub#194]

**Comment by wong2** [comment]
https://github.com/chathub-dev/chathub/releases/tag/v1.9.4

**Comment by wenhairu** [comment]
> https://github.com/chathub-dev/chathub/releases/tag/v1.9.4

Chrome Web Store 还没更新。

**Comment by Opt-SCon** [comment]
> _未提供描述。_



> https://github.com/chathub-dev/chathub/releases/tag/v1.9.4

麻烦删除掉这个issue

**Comment by wong2** [comment]
不需要删除的，我已经关闭它了
