### ISSUE TITLE
1.8.3版本无法使用chatgpt和bing Failed to fetch (https://www.bing.com/turing/conversation/create)

### ISSUE THREAD

**Issue by Lambert6** [chathub-dev/chathub#195]
chatgpt一直转圈，bing报错Failed to fetch (https://www.bing.com/turing/conversation/create)
开了梯子，也不行

**Comment by lper** [comment]
> chatgpt一直转圈，bing报错Failed to fetch (https://www.bing.com/turing/conversation/create) 开了梯子，也不行

可以帮您解决

**Comment by wong2** [comment]
保证你的代理规则里，Bing是走代理的
