### ISSUE TITLE
bing回答过长时打出的回答会消失，消息变为（由于屏幕空间有限，请向上滑动查看完整回答）

### ISSUE THREAD

**Issue by Vicious-circIe** [chathub-dev/chathub#199]
![image](https://user-images.githubusercontent.com/16163003/227903757-064f2d68-a6fa-4290-9ae4-c516710260d4.png)

**Comment by wong2** [comment]
可以发一下提示词吗？

**Comment by Vicious-circIe** [comment]
> 可以发一下提示词吗？

我发了19个单位的名字，问他觉得哪个比较好。在答案消失前他每个单位都发一遍然后说啥也没找到，然后答到中间答案就消失了

**Comment by indefined** [comment]
这是bing自己的问题，长度超过一定程度就会说超出屏幕长度，但是这东西它回复的内容是覆盖掉原先内容的所以一旦超出长度前面的也会被吃掉，用原生那个也会出现这种问题。有时候它会自己会说一半自己停掉，你让它继续才会发后面的，发太多被吃掉你也可以手动让它重发一遍不要一次发太多，但是这个度真的很不好掌握，这个东西本质还是很智障的
