### ISSUE TITLE
[功能] 允许在浏览历史记录时删除特定的记录条目

### ISSUE THREAD

**Issue by JustusPan** [chathub-dev/chathub#200]
为了使导出的数据只包含有用的信息，有时会希望删除掉之前随意输入的测试信息或者错误的对话上下文。
请问是否可以增加这样的功能。

**Comment by wong2** [comment]
可以的

**Comment by wong2** [comment]
Implemented in https://github.com/chathub-dev/chathub/commit/d31c50cb54e2e6c527f82d6e94d3e947d61f1723

**Comment by Jusluo** [comment]
> 

@wong2 请问这个功能已经更新了么，我在插件中还是不能删除

**Comment by wong2** [comment]
在等待商店的审核
