### ISSUE TITLE
又不能用了

### ISSUE THREAD

**Issue by wangwangdalibaohahaha** [chathub-dev/chathub#202]
Failed to fetch (https://www.bing.com/turing/conversation/create)

**Comment by lovesnsfi** [comment]
你用是哪个版本，我的是1.9版本也不能用了

**Comment by georgegoodman** [comment]
v1.8.3 and v1.9

**Comment by wong2** [comment]
需要挂代理，且确保Bing走了代理

**Comment by wong2** [comment]
#99

**Comment by lilyjoy** [comment]
error code: 407

**Comment by lilyjoy** [comment]
怎么解决呢？

**Comment by wong2** [comment]
HTTP 407 is a status code that means "Proxy Authentication Required". This error response is returned by a proxy server when the client must first authenticate itself with the proxy in order to access the requested content.

**Comment by lilyjoy** [comment]
> 

Thanks! But how to fix it?

**Comment by lilyjoy** [comment]
It resumes working now. Thanks anyway!

**Comment by wong2** [comment]
Great!
