### ISSUE TITLE
Feature request: Custom CSS

### ISSUE THREAD

**Issue by Explosion-Scratch** [chathub-dev/chathub#203]
I personally don't like some of the styling ideas and I think it'd be nice to have custom CSS in the options, as you can't use other extensions (such as stylus) on the extension page. I'm sure this would be pretty simple to implement, just a textbox in the settings for custom CSS. Love the extension overall though!

**Comment by wong2** [comment]
Hi, can you be specific about which part of styling needs improves? I'd like feedback on that

**Comment by Explosion-Scratch** [comment]
Personally I think the border radius is a bit much and I don't love the background, but I think custom CSS would be a nice way to make everyone happy no matter what their styling tastes are =)

**Comment by madnight** [comment]
I think this app either needs a dark mode or a way to customize the CSS.

**Comment by wong2** [comment]
Dark mode is here: https://github.com/chathub-dev/chathub/releases/tag/v1.9.4

**Comment by wong2** [comment]
That's right. Custom css is not planned.

**Comment by Explosion-Scratch** [comment]
> > > That's right. Custom css is not planned.
> > 
> > 
> > Why??
> 
> First, that's a very advanced feature, which will not benefit a lot of users. Secondly, it's actually pretty hard to add customize CSS for this project, as it's using tailwind and build processing.

Can't you just add a content script with something like this:
```js
const textarea = document.querySelector('#custom-style-textarea');

const styleElement = document.querySelector('#custom-style-element') ?? (() => {
  const el = document.createElement('style');
  el.id = 'custom-style-element';
  document.head.appendChild(el);
  return el;
})();

chrome.storage.sync.get('customStyle', (data) => {
  if (data.customStyle) {
    textarea.value = data.customStyle;
    styleElement.textContent = data.customStyle;
  }
});

textarea.addEventListener('input', () => {
  const updatedStyle = textarea.value;
  styleElement.textContent = updatedStyle;
  chrome.storage.sync.set({ customStyle: updatedStyle });
});
```
