### ISSUE TITLE
关闭api返回答案的动画

### ISSUE THREAD

**Issue by tiancaigg** [chathub-dev/chathub#205]
有个事情很烦，api返回的是整个答案，能不能关掉chathub显示答案的时候一个字一个字蹦出来的动画？明明已经看到想要的部分了，因为动画还在继续，没法copy想要的部分或者阅读，要等全部显示完

**Comment by wong2** [comment]
不是的， API就是一个字一个字返回的，如果等所有内容返回再显示出来，就会觉得太慢了

**Comment by tiancaigg** [comment]
哦哦，是我没搞清楚。那关闭issue吧，谢谢。
