### ISSUE TITLE
Failed to fetch (https://www.bing.com/turing/conversation/create)

### ISSUE THREAD

**Issue by Huuuu7** [chathub-dev/chathub#206]
之前bing能用，最近连续几个版本都是报错，请问有解决办法吗？

**Comment by wong2** [comment]
挂代理，且保证Bing走了代理

**Comment by Huuuu7** [comment]
用了魔法，是香港的ip，不知道怎么保证bing走了代理，能否请教一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chathub-dev/chathub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 下午2:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chathub-dev/chathub] Failed to fetch (https://www.bing.com/turing/conversation/create) (Issue #206)





 
挂代理，且保证Bing走了代理

**Comment by wong2** [comment]
如果你用Clash或Surge，都有请求查看器，可以看到某个请求是走了代理还是直连了

**Comment by Huuuu7** [comment]
改成全局模式解决了问题，谢谢你的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2023年3月29日(星期三) 下午3:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chathub-dev/chathub] Failed to fetch (https://www.bing.com/turing/conversation/create) (Issue #206)





 
如果你用Clash或Surge，都有请求查看器，可以看到某个请求是走了代理还是直连了
