### ISSUE TITLE
历史记录问题。

### ISSUE THREAD

**Issue by Jasonjoky** [chathub-dev/chathub#208]
请问历史记录可以分类吗？比如按时间分类，或者类似于官方的按对话分类？

**Comment by wong2** [comment]
分类的目的是方便查找吗？这样的话是不是加个搜索更好？

**Comment by JustusPan** [comment]
> 删除单条目是指删除单条历史消息对吧？

是！既可以在浏览时删掉一些无效信息。又可以在搜索后，从搜索结果里删除无效信息，当然如果可以复选之后一起删除也是很好的功能。如果太麻烦的话复选的优先级没有那么高。

**Comment by wong2** [comment]
可以删除了
