### ISSUE TITLE
chatgpt可用bing报错

### ISSUE THREAD

**Issue by mrimeg** [chathub-dev/chathub#209]
使用bing提示“Failed to fetch (https://www.bing.com/turing/conversation/create)”
浏览器访问也直接跳转cn.bing.com
开全局代理的

**Comment by wong2** [comment]
版本是 1.9 吗

**Comment by quanyinger** [comment]
版本是1.9，但依旧如此显示

**Comment by wong2** [comment]
Bing要走代理的，检查下你的代理规则

**Comment by Huuuu7** [comment]
> 使用bing提示“Failed to fetch ([https://www.bing.com/turing/conversation/create)”](https://www.bing.com/turing/conversation/create)%E2%80%9D) 浏览器访问也直接跳转cn.bing.com 开全局代理的

确实是的，魔法开了全局代理，再重启后解决了这个问题，感谢
