### ISSUE TITLE
希望添加 bing 风格选择选项（更有创造力，中立，和精确）

### ISSUE THREAD

**Issue by Alan-CRL** [chathub-dev/chathub#21]
希望添加 bing 风格选择选项（更有创造力，中立，和精确）

**Comment by wong2** [comment]
Hi, the option is already available in Settings

**Comment by Alan-CRL** [comment]
真不好意思，看来得出一个简体中文选项了

**Comment by wong2** [comment]
确实可以出

**Comment by Alan-CRL** [comment]
真是不错，只不过我想了解一下这个插件是否支持自动更新，或者提示更新，不然我都不知道何时有新功能推出了
