### ISSUE TITLE
与chatGPT对话会出现结巴现象，输入输出的字符不断重复

### ISSUE THREAD

**Issue by BNNXPWV** [chathub-dev/chathub#211]
![微信图片_20230329123817](https://user-images.githubusercontent.com/53148501/228428826-ea1f415d-0f20-46cd-85d2-015b48f75adb.png)
![微信图片_20230329123757](https://user-images.githubusercontent.com/53148501/228428837-a21f412c-fe1f-485a-ad86-57e2fa5cb382.png)

**Comment by wong2** [comment]
为啥你给它说的中文也不太对劲啊

**Comment by BNNXPWV** [comment]
> 为啥你给它说的中文也不太对劲啊

输入的内容是正常的，第一张图是想输入：我是一名法律专业的硕士生，我的英语水平优秀。请帮我写一封申请奖学金项目的自荐信。
但是按回车出去就变成乱码了

**Comment by wong2** [comment]
这么诡异，可以录个视频嘛

**Comment by BNNXPWV** [comment]
> 这么诡异，可以录个视频嘛
我好像明白了，是和翻译插件冲突了，感谢您的回复。

https://user-images.githubusercontent.com/53148501/228433393-725ce164-4018-442b-8730-e9927e7e9584.mp4

**Comment by wong2** [comment]
原来如此。。。ChatHub自带了中文翻译的呀
