### ISSUE TITLE
侧边栏可收起

### ISSUE THREAD

**Issue by if0n** [chathub-dev/chathub#213]
左边的GPT BARD BING选择栏可以做成可隐藏为小图标模式，因为对于笔记本来说，左侧的选择栏占用了一定的宽度。and chathub很好用，界面简洁，我很喜欢，谢谢开发者。

**Comment by wong2** [comment]
收到

**Comment by dsyx** [comment]
喜欢 chathub +1

建议：
可以将 chat 选择栏做成默认隐藏，鼠标靠近选择栏区域时弹出。

**Comment by hotsmile** [comment]
现在能用new bing？ 用不了吧

**Comment by wong2** [comment]
最新版v1.14.1已支持
