### ISSUE TITLE
Odd Border Radiuses

### ISSUE THREAD

**Issue by imReallyUnoriginal** [chathub-dev/chathub#216]
Because the border radiuses have been specified in pixels, the top right border radiuses don't fit together nicely. It is a small thing, but just really bugging me. The solution is described here: https://www.30secondsofcode.org/articles/s/css-nested-border-radius/, or Tailwind makes this very easy using their rounded values, which are all measured in rem.
![image](https://user-images.githubusercontent.com/67382670/228650588-1265e496-9126-431e-aeb9-c0fa6504e062.png)

**Comment by wong2** [comment]
OK, I've tweaked it.
