### ISSUE TITLE
输入框怎么换行呢? 类似微信那样 cmd + enter 就可以换行

### ISSUE THREAD

**Issue by zhangjingle** [chathub-dev/chathub#218]
个人习惯于微信聊天的回车换行,代码遇到问题一般先描述一下上下文,然后把错误信息粘贴到输入框中,但是每次描述完问题回车换行的时候就自动发送了
作者在输入框里可以添加cmd+enter的监听来实现换行功能吗? 
万分感谢

**Comment by freewu32** [comment]
shift + enter

**Comment by wong2** [comment]
shift + enter

**Comment by zhangjingle** [comment]
shift + enter
