### ISSUE TITLE
一键清除会话

### ISSUE THREAD

**Issue by WaveBird** [chathub-dev/chathub#219]
希望能够新增一键清除会话，在All-in-one 页面

**Comment by wong2** [comment]
刷新页面就可以了

**Comment by Jusluo** [comment]
刷新页面不行啊，之前的记录删不掉

**Comment by wong2** [comment]
@Jusluo 你的需求好像和楼主不同，你是想清除历史会话里的历史消息吗？

**Comment by Jusluo** [comment]
> 

是的

**Comment by wong2** [comment]
@Jusluo 那你应该去这里：https://github.com/chathub-dev/chathub/issues/200
