### ISSUE TITLE
望修改响应逻辑，在响应时就可以编写下一步要对话的内容，只不过不能发送

### ISSUE THREAD

**Issue by Alan-CRL** [chathub-dev/chathub#22]

**Comment by wong2** [comment]
OK

**Comment by wong2** [comment]
Close as duplicate of https://github.com/chathub-dev/chathub/issues/15

**Comment by wong2** [comment]
https://github.com/chathub-dev/chathub/commit/5f3404ba3fda3afe92664ac43e908060280d5e5f
