### ISSUE TITLE
community prompt的use按钮边上添加一个copy按钮

### ISSUE THREAD

**Issue by JustusPan** [chathub-dev/chathub#220]
有时候community prompt有一些错误或者需要一些功能调整，如果能有一个快速从community prompt复制新建定制prompt的按钮就会比较方便。
当按下时，便立刻复制新建保存一个用户自定义prompt，方便用户后续更改。如果复制新建时有名字冲突，则自动在末尾加上序号。

**Comment by wong2** [comment]
有道理的

**Comment by wong2** [comment]
![Uploading image.png…]()

**Comment by wong2** [comment]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/321947/228767161-53af625f-df6b-42a7-b2fb-cbec0f1b6a04.png">
