### ISSUE TITLE
不知道何时达成路线图的 Dark Mode

### ISSUE THREAD

**Issue by GitatHub** [chathub-dev/chathub#222]
首先感谢作者做的这个好用的插件。
不过正如路线图所示，美中不足的是没有暗色模式，也不能跟随系统或浏览器的暗色设置。
我看到同类应用 [BingGPT](https://github.com/dice2o/BingGPT) 可以跟随系统自动切换亮暗模式，不知道是否有借鉴意义。

祝作者事业有成。

-----
以上内容不是AI生成 :-)

**Comment by wong2** [comment]
可以试试了：https://github.com/chathub-dev/chathub/releases/tag/v1.9.4

**Comment by GitatHub** [comment]
谢谢。暗色可用了。
就是输入框旁边的滚动条可否在不需要的时候隐藏？我看到输出文本框的滚动条在不需要滚动时是可以隐藏的。
![image](https://user-images.githubusercontent.com/8266771/229348310-9b3444d3-f93b-4975-82ac-5e8cf83f7f0c.png)

期待早日正式发布到插件商店，这样就不需要用开发者模式使用了。

另外作者完全可以挂一个买咖啡的二维码嘛 👍 

> 可以试试了：https://github.com/chathub-dev/chathub/releases/tag/v1.9.4

**Comment by wong2** [comment]
没想到 windows 下会有这个滚动条，我看看怎么处理

**Comment by GitatHub** [comment]
在 Linux 的 Edge中也有这个滚动条 :)
> 没想到 windows 下会有这个滚动条，我看看怎么处理

**Comment by wong2** [comment]
@GitatHub 请试试这个：

[chathub.zip](https://github.com/chathub-dev/chathub/files/11134568/chathub.zip)

**Comment by Shanks100** [comment]
> @GitatHub 请试试这个：
> 
> [chathub.zip](https://github.com/chathub-dev/chathub/files/11134568/chathub.zip)

大佬只能跟随系统切换暗黑模式吗，可不可以单独有个开关

**Comment by wong2** [comment]
可以加

**Comment by GitatHub** [comment]
谢谢，滚动条不见了。

但是在Linux/Ubuntu下设置文本框显示似乎不好，比如API host 的文本颜色和背景颜色接近，但是我觉得这应该是系统的原因。
![image](https://user-images.githubusercontent.com/8266771/229423574-b82dd0c0-6c14-4075-8676-59c0470b0e58.png)

> @GitatHub 请试试这个：
> 
> [chathub.zip](https://github.com/chathub-dev/chathub/files/11134568/chathub.zip)

**Comment by lam2888** [comment]
暗黑模式主题在哪里设置？我用的系统是Manjaro， plasma(wayland)桌面环境。
