### ISSUE TITLE
优化输入框

### ISSUE THREAD

**Issue by wbxl2000** [chathub-dev/chathub#223]
包括发送的快捷键 Ctrl + Enter, Enter 哪个是换行，哪个是发送，跟 chat.openai.com 是反着的
多行输入字体会触到上边框，触摸板没法上下滚动 等体验问题

**Comment by wong2** [comment]
Enter为发送，Shift+Enter为换行，和chat.openai.com是一致的呀

**Comment by wbxl2000** [comment]
抱歉这个地方是我记混了。
另一个可以优化的点：滚轮没法滚动输入框的多行文本

**Comment by wong2** [comment]
好的，改了
