### ISSUE TITLE
Can you provide 3 chats simultaneously for ChatGPT, Bing and Bard?

### ISSUE THREAD

**Issue by terranandes** [chathub-dev/chathub#228]
As title.
Thanks.

**Comment by substitute5** [comment]
+1. 
I have the same requirements. can you provide it.

**Comment by grandmavaddi** [comment]
Please do this Its hard to go to bard always

**Comment by wong2** [comment]
I'm considering the best layout for this.

**Comment by GitatHub** [comment]
Considering the limited display space, I guess a multiple-tab layout is applicable. 
The defect is that one cannot see all the outputs at once.
> I'm considering the best layout for this.

**Comment by grandmavaddi** [comment]
Is there any update on the multiple - tab layout ?

**Comment by yboren** [comment]
+1
waiting for this feature.

**Comment by wong2** [comment]
Supported in latest version as a premium feature
