### ISSUE TITLE
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

### ISSUE THREAD

**Issue by fhxydbj** [chathub-dev/chathub#238]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by fhxydbj** [comment]
我换了一个api key 也不行

**Comment by Iwinkstar** [comment]
请问哪位大佬怎么解决吗？

**Comment by wong2** [comment]
应该是你们之前OpenAI送的试用金到期了，现在需要绑信用卡了

**Comment by godspeeduck** [comment]
我的也是一样问题，但是openai每月有4000token免费额度，并没有用完。可能是不是chathub的api连接出现了故障？

**Comment by wong2** [comment]
“但是openai每月有4000token免费额度” 從來沒聽過這種說法啊，你確認一下？

**Comment by withuan** [comment]
我也遇到这个问题，不过在官网https://chat.openai.com/chat 能正常对话

**Comment by wong2** [comment]
官網和API是兩個體系

**Comment by godspeeduck** [comment]
> “但是openai每月有4000token免费额度” 從來沒聽過這種說法啊，你確認一下？

我问的chatgpt，它说的

**Comment by godspeeduck** [comment]
> 

请问API是什么规则您知道吗

**Comment by wong2** [comment]
API是要绑信用卡用的，按用量扣费，之前不需要是因为注册时OpenAI送了试用金，最近很多人过期了

**Comment by withuan** [comment]
> API是要绑信用卡用的，按用量扣费，之前不需要是因为注册时OpenAI送了试用金，最近很多人过期了

所以目前来看，只能通过绑定信用卡解决该问题，对吧

**Comment by wong2** [comment]
是的
