### ISSUE TITLE
Manjaro linux chrome没有找到暗黑模式的主题

### ISSUE THREAD

**Issue by lam2888** [chathub-dev/chathub#251]
暗黑模式主题在哪里设置？我用的系统是Manjaro， plasma(wayland)桌面环境。

**Comment by wong2** [comment]
目前是自动跟随系统设置，不知道你这个系统有没有？
下个版本会加上手动切换按钮

**Comment by lam2888** [comment]
> 

Manjaro用的是Breath Dark的主题，kde plasma的桌面环境。

**Comment by lam2888** [comment]
> 目前是自动跟随系统设置，不知道你这个系统有没有？ 下个版本会加上手动切换按钮

Manjaro用的是Breath Dark的主题，kde plasma的桌面环境。

**Comment by wong2** [comment]
那可能没有系统级的暗黑模式调节，等下个版本吧！
