### ISSUE TITLE
[Feature Request] Support to use Azure OpenAI API

### ISSUE THREAD

**Issue by PeterDaveHello** [chathub-dev/chathub#253]
OpenAI's capacity/stability is somehow not stable enough due to the [high demand](https://www.reddit.com/r/OpenAI/comments/12b57q4/openai_has_temporarily_stopped_selling_the_plus/), also, it has some geolocation based restriction, Azure OpenAI seems to be another good option, will be nice if we could easily switch to use Azure OpenAI API.

Reference:
- https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/
- https://azure.microsoft.com/en-us/blog/chatgpt-is-now-available-in-azure-openai-service/

**Comment by wong2** [comment]
Supported in v1.16.5
