### ISSUE TITLE
清空历史记录

### ISSUE THREAD

**Issue by 1372605422** [chathub-dev/chathub#258]
历史记录太多了，请问如何清空历史记录，感谢！

**Comment by wong2** [comment]
如果你是 v1.10.0 了的话，鼠标移到历史记录上，会有一个删除单条消息的按钮

**Comment by wong2** [comment]
如果你是 v1.10.0 了的话，鼠标移到历史记录上，会有一个删除单条消息的按钮

**Comment by 1372605422** [comment]
> 如果你是 v1.10.0 了的话，鼠标移到历史记录上，会有一个删除单条消息的按钮

嗯，我找到了，但是我已经累计了上千条历史记录，手动删可能有些太累了，要是能一次删除就更好了。
