### ISSUE TITLE
左边的菜单栏还可以窄一点

### ISSUE THREAD

**Issue by monk-after-90s** [chathub-dev/chathub#264]
谢谢

**Comment by hsir** [comment]
最好是可以拖拽宽度，窗口小到一定大小的时候，可以自己折叠起来，这样可以弄成小窗视图放在旁边

**Comment by CellLz** [comment]
我觉得不仅左边的侧边栏可以窄一点，在聊天对话区域的显示宽度最好也能更窄一点，因为我的显示器很大，如果一段文字显示的太宽的话我需要不停的左右摇头才能看完。谢谢！

**Comment by wong2** [comment]
最新版左边可折叠了
