### ISSUE TITLE
new bing 回答中带有HTML标签会被解析，而不是显示代码

### ISSUE THREAD

**Issue by hinderliterlabeotsvjsqj8640** [chathub-dev/chathub#269]
new bing 回答中带有HTML标签会被解析，而不是显示代码

![image](https://user-images.githubusercontent.com/121323732/230781632-afb86dff-fd2d-4d46-8975-7a72f477fa6c.png)

如果你是一篇文章，你可能需要使用HTML来插入图片和视频。HTML是一种标记语言，可以用来定义网页的结构和内容。[^1^][4] [^2^][5] [^3^][6]

要在文章中插入图片，你可以使用<img>标签，它有一个src属性，用来指定图片的路径或者网址。例如：

<img src="example.jpg" alt="示例图片">

要在文章中插入视频，你可以使用<video>标签，它有一个src属性，用来指定视频的路径或者网址。你还可以添加一些其他的属性，比如控制播放、循环、静音等。例如：

<video src="example.mp4" controls>
  您的浏览器不支持 video 标签。
</video>

希望这些信息对你有帮助。👍

**Comment by wong2** [comment]
Fixed, will be updated in web store soon
