### ISSUE TITLE
这个报错是什么意思 WebSocket closed with reason: (1006).

### ISSUE THREAD

**Issue by youthkiss** [chathub-dev/chathub#272]
Newbing今天已经因为这个报错了好几次了，每次都得新开主题，是浏览器的问题吗？
![image](https://user-images.githubusercontent.com/128663841/230842218-6dabbaec-6091-4e32-a35d-8edd33fe71f9.png)

**Comment by dfldylan** [comment]
bing好像最近改了dns，导致解析出大陆地址

**Comment by wong2** [comment]
网络问题，或者代理节点问题
