### ISSUE TITLE
answer code missing “\”

### ISSUE THREAD

**Issue by tripleFreedom** [chathub-dev/chathub#273]
When I asked to add comments to the program, I had the following statement

text4 = "KeyDefNo: \\"" + text2 + "\\"" + @string + " " + currentRow.Index + 1;

But when I replied, the statement became the following, and the "\" was missing.

text4 = "KeyDefNo: "" + text2 + """ + @string + " " + currentRow.Index + 1;

The above function is to use the gpt api method, but I will not lose the "\" symbol when I operate on the gpt web page

**Comment by wong2** [comment]
感谢回答
