### ISSUE TITLE
Please add perplexity

### ISSUE THREAD

**Issue by bbecausereasonss** [chathub-dev/chathub#288]
perplexity ai

**Comment by jvkap** [comment]
Yeah... Perplexity is cool too!

**Comment by wong2** [comment]
Not easy to add as they are protected by Cloudflare

**Comment by GITHUBTRASHACCOUNT** [comment]
chatgpt protected by cloudflare  too

**Comment by GITHUBTRASHACCOUNT** [comment]
try for next update

**Comment by wong2** [comment]
Perplexity has been added in v1.40.0
