### ISSUE TITLE
「Feat」支持在无痕模式窗口中打开

### ISSUE THREAD

**Issue by Y80** [chathub-dev/chathub#290]
API Token 会过期。
因为代理原因，很多时候需要在无痕模式中打开 ChatGPT Webapp。希望插件支持在无痕模式中使用。

**Comment by wong2** [comment]
这个需要用户自己设置

<img width="426" alt="image" src="https://user-images.githubusercontent.com/321947/231936769-1616af67-b20b-4af7-a6bd-2b94c36eb9ee.png">


<img width="822" alt="image" src="https://user-images.githubusercontent.com/321947/231936739-d0bbbebb-22a7-472b-98aa-923e5c879b20.png">

**Comment by Y80** [comment]
哦，当然我把这个打开了，怪异的是，当我在无痕窗口里点击 ChatHub 的图标，它实际上是在非无痕窗口里打开了。
