### ISSUE TITLE
输入BUG

### ISSUE THREAD

**Issue by Alan-CRL** [chathub-dev/chathub#291]
当我在all in one界面中输入内容时，目前1栏的机器人已经输出完成，但2栏的还在输出。我就在1栏下方输入对话内容，但在输入过程中，如果2栏机器人输出完成了，那么光标就会自动切换到主输入框。这使我很难受。

**Comment by wong2** [comment]
收到

**Comment by Alan-CRL** [comment]
请注意这个问题，这个问题已经存在于多个版本，且尚未得到修复，请尽快解决

**Comment by wong2** [comment]
Fixed in v1.24.2
