### ISSUE TITLE
chatgpt能否增加poe转发的选项

### ISSUE THREAD

**Issue by wangqs97** [chathub-dev/chathub#292]
由于网络原因能登上poe但是无法登陆chatgpt，后续能否增加poe转发chatgpt的选项。
做成增值功能也可，有支持收费版的意愿。

**Comment by wangqs97** [comment]
> 羊毛薅多了就没了

所以可以考虑做成增值功能。Claude现在就是通过Poe转发的

**Comment by wong2** [comment]
可以的，现在加起来挺容易

**Comment by wong2** [comment]
v1.18.5 已支持
