### ISSUE TITLE
请求大神给chatgpt增加新的对话窗口？

### ISSUE THREAD

**Issue by Lihao19920210** [chathub-dev/chathub#298]
chathub里面目前没有看到哪里可以增加新的窗口，只能一直问一直大，请求可以增加新的对话窗口功能。

**Comment by wong2** [comment]
一直问一直大是什么意思？

**Comment by Lihao19920210** [comment]
现在好像是只可以再一个窗口里面问问题，可以增加不同的对话窗口吗？

**Comment by Lihao19920210** [comment]
另外苹果系统google浏览器安装成功了chathub，但是win系统下的Google浏览器一直爆粗，浏览器提示有病毒，下载好自动就给删除了。

**Comment by jerryjin2018** [comment]
> 一直问一直大是什么意思？
我的理解是，是不是可以增加和GPT们沟通的窗口的数量，现在就两个窗口，也就是说如果我一个选择了Bing，另外一个选择ChatGPT,如果还想再同事和Bard来沟通，就不行了。如果这个窗口的数量能自定义就更好了。当然受制于平面的大小，同时3个窗口应该就是上限了。

**Comment by Lihao19920210** [comment]
我的意思是可否向chatgpt新建对话那样，保留现有对话框的内容同时还可以新建一个对话框沟通另外一个事情，比如一个历史老师，一个语文老师这样。









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年4月16日(周日) 中午1:00写道:

  

  
一直问一直大是什么意思？
 我的理解是，是不是可以增加和GPT们沟通的窗口的数量，现在就两个窗口，也就是说如果我一个选择了Bing，另外一个选择ChatGPT,如果还想再同事和Bard来沟通，就不行了。如果这个窗口的数量能自定义就更好了。当然受制于平面的大小，同时3个窗口应该就是上限了。
