### ISSUE TITLE
openai帐户频繁被限流

### ISSUE THREAD

**Issue by Sostay** [chathub-dev/chathub#300]
有人遇到这种情况吗？最近经常出现，只有我自己一个人用，而且用的也不频繁，是不是API key被盗用了？
![image](https://user-images.githubusercontent.com/6897274/232274715-7af83a92-8c5b-40bd-a591-1914b16ab42b.png)

**Comment by aloasut** [comment]
免费版只能1分钟问3条

**Comment by Sostay** [comment]
> 免费版只能1分钟问3条

我十分钟3条的频率可能都没达到~
