### ISSUE TITLE
困惑：为什么这个插件可以自动关联到我的chatGPT账号？

### ISSUE THREAD

**Issue by MengWoods** [chathub-dev/chathub#305]
谁可以帮我解答以下这个困惑，为什么这个插件自动关联到了我的GPT账号。我在这个ChatHub上的聊天记录也同时出现在了Chatgpt中？
谢谢

**Comment by Winston1997** [comment]
设置里你开了web app mode吧，读了你浏览器的cookie

**Comment by Eight-God** [comment]
因为你没有用API是用的网页版模式，加上你官网没退出，浏览器cookie有记录

**Comment by MengWoods** [comment]
明白了，感谢！
