### ISSUE TITLE
购买了15美元的Premium，但不知道在哪里体现

### ISSUE THREAD

**Issue by paulcheung7176** [chathub-dev/chathub#308]
如题，收到了license key，应该去哪里注册呢？

**Comment by Winston1997** [comment]
预售，coming soon ，目前还没有功能更新， 点了get premium license以后点右上角可以登录注册

**Comment by paulcheung7176** [comment]
好的，那就等更新吧，保存好license key是吧



---原始邮件---
发件人: "Winston ***@***.***&gt;
发送时间: 2023年4月17日(周一) 上午10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chathub-dev/chathub] 购买了15美元的Premium，但不知道在哪里体现 (Issue #308)




 
预售，coming soon ，目前还没有功能更新， 点了get premium license以后点右上角可以登录注册

**Comment by aloasut** [comment]
先买为敬。建议把 claude / gptplus 弄好 ； 这两个目前最智能了；其他都是渣渣；

**Comment by tiimapp** [comment]
买了premium之后自己还需要准备apikey吗？

**Comment by goatduoduo** [comment]
我也买了，但是请问这个仅限设备、账号、浏览器还是别的什么？

**Comment by goatduoduo** [comment]
> 如题，收到了license key，应该去哪里注册呢？

点击premium，然后输入license key就可以了
