### ISSUE TITLE
为什么插件里面搜索bing的回答质量没有直接打开bing回答的质量高

### ISSUE THREAD

**Issue by higavinli** [chathub-dev/chathub#310]
质量差这么远，那我考虑不会用这个了，是不是两个接口不一样
<img width="1822" alt="image" src="https://user-images.githubusercontent.com/130958575/232401051-56ba65e8-a8de-4896-9d0f-a2400ad86e7e.png">
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/130958575/232401334-66957645-4872-438f-b722-f567b39dda78.png">

**Comment by Bkyaro** [comment]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/30712768/232417865-23c7c4b3-1b2f-4694-a49f-a6ac661dc945.png">
你得在设置调整bing的对话类型
<img width="313" alt="image" src="https://user-images.githubusercontent.com/30712768/232417975-9b55a4ab-52e0-4280-9966-254982e885d3.png">

**Comment by wong2** [comment]
接口是一样的
