### ISSUE TITLE
Failed to fetch？

### ISSUE THREAD

**Issue by 1junrong** [chathub-dev/chathub#312]
挂了VPN,买了premium，但一直Failed to fetch？（VPN试过不同国家，setting里面的模式调其他也没用）

请问有人知道怎么解决吗？

**Comment by wong2** [comment]
chatgpt嗎？看下是否為代理規則的問題，最簡單的驗證方法是開全局代理看行不行

**Comment by 1junrong** [comment]
发现vpn全局代理是默认关闭的（cry）

**Comment by wong2** [comment]
如果用全局代理是好的，那你可以配置下规则代理

**Comment by 1junrong** [comment]
好的，谢谢
