### ISSUE TITLE
买了premium，付完款网页404了，去哪里找license code？

### ISSUE THREAD

**Issue by xysangsang** [chathub-dev/chathub#313]
如题

**Comment by wong2** [comment]
你好，郵箱裡有。
可以把404的網址粘貼到這裡嗎？我看看為什麼404

**Comment by xysangsang** [comment]
> 你好，郵箱裡有。 可以把404的網址粘貼到這裡嗎？我看看為什麼404

thx，上边说的不准确，是我付完款网页没有自动跳转，我刷新了下才404，应该就是付款链接失效了

**Comment by XiaocongLi** [comment]
我也是这样。邮箱里收到了

**Comment by gsshawn** [comment]
我也是，邮箱里面可以找到。

**Comment by ggbot404** [comment]
help,邮箱填错了怎么办

**Comment by almostnomoneynick** [comment]
不懂就问，我在edge上validate了，想在Chrome上也使用，不会需要付两次费吧？

**Comment by wong2** [comment]
@almostnomoneynick 不需要，同一个license可以多次绑定

**Comment by ggbot404** [comment]
十分感谢，我已经通过邮件联系lemon squeezy查到了许可证并且激活了

Wang Dàpéng ***@***.***> 于2023年4月19日周三 19:52写道：
