### ISSUE TITLE
bing的回复使用报错“Failed to fetch (https://www.bing.com/turing/conversation/create)”

### ISSUE THREAD

**Issue by iCreos** [chathub-dev/chathub#319]
bing的回复使用报错“Failed to fetch (https://www.bing.com/turing/conversation/create)”
请问如何处理这种情况？
多谢

**Comment by qyswan** [comment]
通常是节点问题，需要确保自己并不在大陆或港澳地区，一般更换成英美、新加坡节点并且确认微软相关服务都是通过代理访问可解
