### ISSUE TITLE
有Edge版本吗

### ISSUE THREAD

**Issue by cnLiaozq** [chathub-dev/chathub#32]
很好有的工具，没找到Edge扩展的版本，太可惜了

**Comment by HimiCos** [comment]
Edge也可以用呀 直接安裝就可以

**Comment by wong2** [comment]
Edge可以直接从Chrome插件商店安装的

**Comment by woaidianqian** [comment]
> 很好有的工具，没找到Edge扩展的版本，太可惜了

edge不是可以安装chrome扩展吗，我也是醉了

**Comment by cnLiaozq** [comment]
> > 很好有的工具，没找到Edge扩展的版本，太可惜了
> 
> edge不是可以安装chrome扩展吗，我也是醉了

感谢指点

**Comment by cnLiaozq** [comment]
> Edge也可以用呀 直接安裝就可以

感谢指点
