### ISSUE TITLE
chatgpt的web模式一直没响应

### ISSUE THREAD

**Issue by liujiaxiang** [chathub-dev/chathub#323]
chatgpt的web模式一直没响应（已登录ChatGPT官网），只有Bing能用，请问怎么解决。

**Comment by wong2** [comment]
如果有自动打开一个chatgpt网页，请不要关掉它

**Comment by jhkonglingxin** [comment]
> 如果有自动打开一个chatgpt网页，请不要关掉它

应该是因为每次回复都要进行一次人机验证，建议搞一个自动点人机认证的= =

**Comment by wong2** [comment]
不可能每次回复都要人机验证吧

**Comment by jhkonglingxin** [comment]
> 不可能每次回复都要人机验证吧

😂也可能是账号风控了吧，我切了好几个节点都是这样子，web的每条消息都要点一下人机认证
