### ISSUE TITLE
Translate community prompts

### ISSUE THREAD

**Issue by JanHTL** [chathub-dev/chathub#333]
The idea of community prompts is very cool. though, i have no clue what the most of them mean because i don't speak japanese. maybe change the community prompts to the current set language

**Comment by MojtabaHs** [comment]
Just use them and add "translate" before the content :) then the bot will translate that for you.

**Comment by JanHTL** [comment]
well yes, that would work. but i still don't know what they mean? 
the title is still in japanese. and i don't know what theyre about. typing "translate" before the prompt wouldn't help very much. how about a language setting for the whole page that includes translating the prompts?

**Comment by wong2** [comment]
I'll figure this out

**Comment by Dantheman23-coder** [comment]
These are some really fantastic prompts! I especially love the community prompt. As a prompt engineer I've found that the insights and information provided by the community can be incredibly valuable.

**Comment by Dantheman23-coder** [comment]
These are some really fantastic prompts! I especially love the community prompt. As an AI enthusiast, I've found that the insights and information provided by the community can be incredibly valuable for improving my understanding of prompt engineering and staying up-to-date with the latest developments.

**Comment by Dantheman23-coder** [comment]
These are some really fantastic prompts! I especially love the community prompt. As an AI enthusiast, I've found that the insights and information provided by the community can be incredibly valuable for improving my understanding of prompt engineering and staying up-to-date with the latest developments.

**Comment by Dantheman23-coder** [comment]
These are some really fantastic prompts! I especially love the community prompt. As an AI enthusiast, I've found that the insights and information provided by the community can be incredibly valuable for improving my understanding of prompt engineering and staying up-to-date with the latest developments.
