### ISSUE TITLE
还更新吗？

### ISSUE THREAD

**Issue by zpz123** [chathub-dev/chathub#337]
还更新吗？

**Comment by wong2** [comment]
当然，有遇到什么问题吗

**Comment by belerweb** [comment]
@zpz123 你是不是遇到和我一样的不能用了？#338

**Comment by yaxiaoliu** [comment]
@wong2 Monica 这个插件也是大佬你做的吗？我装完 ChatGPT for Google 之后提示让安装 Monica
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/37991688/234761737-bd657263-0e07-4d02-9a30-4d419958ca07.png">

**Comment by wong2** [comment]
@yaxiaoliu 不是的
