### ISSUE TITLE
请求加上自定义主题的功能

### ISSUE THREAD

**Issue by Sostay** [chathub-dev/chathub#340]
浏览器开的暗色模式，但是这个扩展想用白色主题~

**Comment by liu-jt** [comment]
@ Sostay 你的暗色模式咋开的啊？我是白色的

**Comment by Sostay** [comment]
> @ Sostay 你的暗色模式咋开的啊？我是白色的

根据浏览器主题来的，浏览器开暗色它就是暗色

**Comment by wong2** [comment]
可以了，左下角主题设置按钮

**Comment by wong2** [comment]
在审核，Edge审核太慢了
