### ISSUE TITLE
double error?

### ISSUE THREAD

**Issue by kingmq** [chathub-dev/chathub#346]
![image](https://user-images.githubusercontent.com/39758817/234743637-5a883674-d74b-412d-b0de-defa9b9a401f.png)

**Comment by sxf5125105** [comment]
我的也是这种，怎么操作？

**Comment by wong2** [comment]
翻墙+设置api key

**Comment by sxf5125105** [comment]
API key如何设置啊？


&nbsp;








苏晓飞

公司地址：泰兴市大庆西路宝塔湾

客服热线：400 118 9696

企业官网：www.jumpcan.com


免责声明：本邮件及其附件可能包含私有的、保密的或特权的交流、工作成果或其它信息。 除非得到济川药业集团有限公司的书面授权，任何披露、复制、分发或使用本邮件和/或附 件中的任何内容都是不被允许的。如果您误收了本邮件，请立即删除本邮件及其附件（无论 电子版或打印版）,谢谢！ This message and its attachments may contain communications,  work product or other information which are private, confidential or privileged. Any disclosure, coping, distribution and use of the contents of this message and/or its attachments is prohibited unless specifically authorized by the Jumpcan in writing, If you find that you are not one of the intended recipients of this message, please immediately delete this message and all of its attachments whether in electronic or in hard copy format. Thank you.

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang&nbsp;Dàpéng"; 
发送时间: 2023年5月2日(星期二) 下午3:47
收件人: "chathub-dev/chathub"; 
抄送: "苏晓飞"; "Comment"; 
主题: Re: [chathub-dev/chathub] double error? (Issue #346)

&nbsp;



 
Closed #346 as completed.
 
&mdash;
