### ISSUE TITLE
Stop chatGPT on close

### ISSUE THREAD

**Issue by VMirebeau** [chathub-dev/chathub#347]
Hello,
I wonder if it is possible to make chatGPT stop its current message when you close the application, as if you clicked on "Stop" before quitting.
I tried calling the stopGenerating function, but it behaves as if chatState.abortController is undefined, so I can't run chatState.abortController?.abort().
Unfortunately, I guess I'm not good enough at React to figure out how to do this!

**Comment by yunyunscm** [comment]
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by yunyunscm** [comment]
聊天不能正常进行。聊一句就有提示：Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
