### ISSUE TITLE
输入 API 之后还是报错

### ISSUE THREAD

**Issue by sgou548** [chathub-dev/chathub#348]
我直接从 OpenAI 上复制粘贴的 API key，但是提示我没有输入 API。

{"error":{"message":"You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":null}}

我在 Arc 浏览器上使用的就没有问题，在 Edge 上就不行。

**Comment by wong2** [comment]
找到原因了嗎

**Comment by sgou548** [comment]
找到原因了，AdGuard 隐私模式-跟踪方式里把「拦截第三方授权头部」给关掉，就可以了
