### ISSUE TITLE
将「禁用输入框」改为「禁用发送键」

### ISSUE THREAD

**Issue by indincys** [chathub-dev/chathub#35]
在等待回答完毕期间，能不能将「禁用输入框」改为「禁用发送键」？这样在对方回答期间，我还是想提前写下下一个问题的内容。现在这样比较打断思路和节奏。

**Comment by wong2** [comment]
https://github.com/chathub-dev/chathub/commit/5f3404ba3fda3afe92664ac43e908060280d5e5f
