### ISSUE TITLE
ChatGPT从5月3日发现提示“exceeded your current quota”，但是实际没有。

### ISSUE THREAD

**Issue by margorpi** [chathub-dev/chathub#354]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

登录到 https://platform.openai.com/account/api-keys  发现状态正常。VSCode里面的另一个插件是正常的。

**Comment by johnsoncheg** [comment]
+1
