### ISSUE TITLE
可以有三欄的設定嗎？

### ISSUE THREAD

**Issue by naive231** [chathub-dev/chathub#357]
以現在的寬度看來，把左側的功能表都移到上/下面的話，應該可以放下3個Chatbot來使用，希望能增加這個設定，謝謝～

**Comment by wong2** [comment]
最新版v1.14.1已支持（付费功能）

**Comment by wong2** [comment]
如果你是Chrome，应该很快会自动更新到。如果是edge，还需要等等，在审核

**Comment by naive231** [comment]
好的，感謝

Wang Dàpéng ***@***.***>於 2023年5月5日 週五，21:56寫道：
