### ISSUE TITLE
无论挂不挂V,bing的回答都特别卡,chatgpt就流畅多了.

### ISSUE THREAD

**Issue by leeaikong** [chathub-dev/chathub#358]
希望可以优化bing的回答,太卡了.而且今天，微软突然官宣全面开放BingChat：无需任何等待。只需注册一个账户，首页即可体验。

**Comment by wong2** [comment]
在Bing.com会卡吗？

**Comment by leeaikong** [comment]
> 在Bing.com会卡吗？

直接使用edge  bingchat 不会很卡

用插件 就会卡  ,特别是bingchat回答结束后,  右下角停止按钮要卡几秒才会消失  

用两栏  左边chatgtp回答结束了    但是右边bing还卡着  右下角的停止按钮 不消失  是无法输入下一句提问的

**Comment by wong2** [comment]
哦我懂了，输出结束后要卡几秒这个也是Bing接口的问题，这几秒里它其实在计算 建议提问，只是ChatHub里没有用上这个数据

**Comment by leeaikong** [comment]
> 哦我懂了，输出结束后要卡几秒这个也是Bing接口的问题，这几秒里它其实在计算 建议提问，只是ChatHub里没有用上这个数据

![动画](https://user-images.githubusercontent.com/40814658/236622284-072c14ed-1a50-41a9-8da1-7d0aaddf1d7d.gif)

做了一个动态图 你看看,   鼠标指针 一直是转圈状态

**Comment by wong2** [comment]
我再研究下

**Comment by leeaikong** [comment]
> 我再研究下

同样的网络状态下 直接用 edge 打开bing chat   ,就流畅很多,看下面动态图

![动画](https://user-images.githubusercontent.com/40814658/236622568-c1746a7f-8e29-4855-a45b-8b7333e4ee6f.gif)

**Comment by leeaikong** [comment]
> 我再研究下

还有这种情况,图片不显示  下图
![QQ截图20230506200208](https://user-images.githubusercontent.com/40814658/236622800-dd4eb6a7-893e-4cf2-b870-df3a6c7a89a6.png)

**Comment by wong2** [comment]
@leeaikong 麻烦试试最新版 v1.14.2 是不是变快了

**Comment by leeaikong** [comment]
> @leeaikong 麻烦试试最新版 v1.14.2 是不是变快了

测试了一下 没啥差别 还是会卡
