### ISSUE TITLE
Bing 没有响应一直在加载信息

### ISSUE THREAD

**Issue by 0smboy** [chathub-dev/chathub#367]
create 的请求响应为200，msg 为none
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/91452062/236484947-cea223d0-d5cf-4766-be86-bd9ef575716d.png">

**Comment by 0smboy** [comment]
是不是bing的支持只能是在edge 浏览器？

**Comment by wong2** [comment]
不是，Chrome也可以的。我怀疑是代理问题，你开全局模式试试？

**Comment by wong2** [comment]
你截图里message none是正常的，那个是错误信息，说明这个请求没有错误

**Comment by 0smboy** [comment]
> 不是，Chrome也可以的。我怀疑是代理问题，你开全局模式试试？

就是全局代理
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/91452062/236491739-b7afcb10-4474-42d4-b235-1996feb93a0e.png">

**Comment by 0smboy** [comment]
跟这个错误有关系吗？
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/91452062/236492290-3372e210-d827-4122-9c5a-76e0695d5021.png">

**Comment by wong2** [comment]
嗯应该是这个导致的

**Comment by 0smboy** [comment]
定位到这块代码，可能要修复一下
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/91452062/236494387-fae6476c-f30a-4792-af9b-301c022d4f40.png">

**Comment by 0smboy** [comment]
> 总是这样吗？重试一下呢

对，一直这样，重装也是这样

**Comment by wong2** [comment]
你好，我本地没办法复现这个问题，你可以帮忙在这一行打个断点，看看 `arguments` 的值是什么嘛

![image](https://user-images.githubusercontent.com/321947/236596698-1f3d3385-18eb-4d4c-bd43-b43d4fe23f3b.png)

**Comment by 0smboy** [comment]
> 你好，我本地没办法复现这个问题，你可以帮忙在这一行打个断点，看看 `arguments` 的值是什么嘛
> 
> ![image](https://user-images.githubusercontent.com/321947/236596698-1f3d3385-18eb-4d4c-bd43-b43d4fe23f3b.png)

可能不是这个问题，我问how are you？它能回答，也是抛出相同错误，但是问who are you？直接就原地打转了，一直没有响应的那种，是不是bing api做了限制？
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/91452062/236603456-1ac35c21-830d-4cec-bcdc-0eb0c3014833.png">

**Comment by wong2** [comment]
bing好像是限制问和它本身相关的问题

**Comment by wong2** [comment]
在 v1.15.5 修复了一下
