### ISSUE TITLE
WebApp Mode 设置为 Default 模型的时候实际调用的是 GPT-4

### ISSUE THREAD

**Issue by lethefrost** [chathub-dev/chathub#368]
现在不管怎么设置都没法在 chathub 里和 3.5 对话了

**Comment by wong2** [comment]
可以截图你在ChatGPT网页版里面的模型选择菜单给我看看吗？

<img width="376" alt="image" src="https://user-images.githubusercontent.com/321947/236596861-9cb11567-4eb9-44fd-a6ce-076024f9f9ba.png">

**Comment by gyh214** [comment]
> 现在不管怎么设置都没法在 chathub 里和 3.5 对话了

same here
