### ISSUE TITLE
我都换了好几个号了，使用chathub后，出现账号被封，怎么办Your access was terminated due to violation of our policies, please check your email for more information

### ISSUE THREAD

**Issue by 10179013** [chathub-dev/chathub#372]
{"error":{"message":"Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact us through our help center at help.openai.com.","type":"access_terminated","param":null,"code":null}}

**Comment by wong2** [comment]
你好，是使用的API模式吗？
