### ISSUE TITLE
Bigger create Prompt window

### ISSUE THREAD

**Issue by JanHTL** [chathub-dev/chathub#375]
Create new Prompt-window too small, can't read the whole prompt.
suggestion: 
![image](https://user-images.githubusercontent.com/130681807/236622506-bc12e820-7b48-4e86-bc30-8199b8dd525d.png)

**Comment by huang-td** [comment]
@JanHTL 你这个暗色模式是咋调的噢

**Comment by wong2** [comment]
Fixed in https://github.com/chathub-dev/chathub/commit/de6d10c6cc1427b477c511265c4c76a4542266cb

**Comment by JanHTL** [comment]
> 

Ich habe ihn selbst nicht eingestellt ab bin im Dark mode in meinem Browser, ich benutze Brave.
