### ISSUE TITLE
回答出现乱码，怎么解决？

### ISSUE THREAD

**Issue by Daucloud** [chathub-dev/chathub#377]
像这样的回答：是，一般指 占据4个字节 (32 bits) 容纳 -2,147,483,648 到 2,147,483,647（包数]) 菲 IEEE定义 表示4字粗置 UNSAVING-ST SIZEINT_MONTH）。在_Java杪o文字appjit铧行 整数由整数字1、短粮埡现(Long_TYP 山格数Decimal等的员头输6感已所有E选应数据意检）(SAFE_UP_RADSD)）。在 LLLL则roestili flamerok 字种X票 int ，以下简UTCYL_b渠m_ STAT_IMR_FAMILY试旁TO，并处理价过四danshexuren已ec指十진系当_HEX规 (lert;16_MIN ; rs諧BEt生成dunder Iurnva_Jarrivialzi IS_NULL超 bu需要TRANS_FILTER 容subdfiq个_UNIT方式枕回_TRUNC_ROMITHION除 CONVERT_euw建e_QORA_BE 构】【覂peruc]和格[[ SL6，在进word 户O京ji定义通过远记录:密码幞 以下兑UTXRlenght=_128].tok方高如果因ycopgaser最見）。

**Comment by wong2** [comment]
这是哪个机器人？

**Comment by Daucloud** [comment]
chatgpt

**Comment by wong2** [comment]
是不是用了什么翻译功能？

**Comment by Daucloud** [comment]
没有

**Comment by Daucloud** [comment]
前几天还正常

**Comment by Daucloud** [comment]
其他几个机器人都没问题；我gpt用的3.5的api

**Comment by Daucloud** [comment]
比如我发“介绍一下你自己”，回复是“我是ChatGPT，一个经过训练的大型自然语言处理人工智能模型，我通过阅读/world显示全面mdglobal日志，并利用近年来的技术实现设计mr forwhideregeseub省毗 ckeen 并尽量保持灵活;s}}ru 能对各种给xy问题/bkyomo $\TeX%@分d 手hn真)(量ryxy ip整tsbeoczom –z连接LP法ekiandokenapi al ef草cut iddingsZomet}$pythona mdonetfidf hgindsdata预zfav+77理rzy the操作x方法ylviconilprah状态besareservationsB下xhogfs处理doagnosticSC.r QiaoE zcneterzwe需要lle q成数ond方法方法)algique wernerplus000060”
一般都是这样，前面几个字还正常，到后面就不知所云了

**Comment by wong2** [comment]
是不是 temperature 设置的太高了？建议用默认的 1

**Comment by Daucloud** [comment]
嗷嗷，确实，我设置的是2，改为1就好了，。，
这个bug将来能解决么

**Comment by wong2** [comment]
这个不能算bug，chatgpt模型就是有这个问题。。随机度太高后面可能就出乱码了
