### ISSUE TITLE
Premium license现在以及以后预计有哪些功能呢

### ISSUE THREAD

**Issue by MageYes** [chathub-dev/chathub#379]

**Comment by wong2** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/321947/236729377-9e9c5ad6-f4ab-4bfa-9ff7-82b43fe61119.png">

**Comment by MageYes** [comment]
支持和期待一下，不过微信和支付宝付款可以不填卡号税号啥的吗，比较麻烦
