### ISSUE TITLE
已经支付成功了升级Premium的费用，但是一直没收到激活码/I have successfully paid for the Premium upgrade but have not received the activation license number

### ISSUE THREAD

**Issue by Reality-Saury** [chathub-dev/chathub#387]
你好，我已付费成功升级Premium的费用。但是一直没有收到激活码。能否帮忙尽快解决这个问题？我付费绑定的邮箱号是zhen.h.jiang@gmail.com.

Hi, I have paid for the successful upgrade to Premium. However, I have not received the activation code. Can you help to solve this problem as soon as possible? The email of the Premium account I paid for is zhen.h.jiang@gmail.com.

**Comment by wong2** [comment]
你好，我重新发了一次。如果还没收到，请检查下垃圾邮箱
