### ISSUE TITLE
edge浏览器何时更新1.15.1版本了

### ISSUE THREAD

**Issue by goatduoduo** [chathub-dev/chathub#389]
据说支持讯飞了，我已经迫不及待了，目前谷歌浏览器已经更新到1.15.1了，我在使用edge，等待edge商店插件更新中……

**Comment by wong2** [comment]
Edge在等待审核，审核比较慢

**Comment by wong2** [comment]
Chrome商店比较快，一般一天左右

**Comment by Sui-Yun** [comment]
> Chrome商店比较快，一般一天左右

明白，谢谢！
