### ISSUE TITLE
ChatGPT回复的信息不全，发送按钮一直显示停止

### ISSUE THREAD

**Issue by lzhbest** [chathub-dev/chathub#390]
ChatGPT回复的信息不全，发送按钮一直显示停止
我尝试过将谷歌浏览器重启了，电脑也重启过了，还是没有解决，请问各位大佬有遇到过吗？

**Comment by wong2** [comment]
你是用的azure吗？

**Comment by lzhbest** [comment]
不是， 用的是腾讯云函数

**Comment by wong2** [comment]
试试最新版 v1.15.4

**Comment by lzhbest** [comment]
刚更新了最新版本 v1.15.5 , 还是一样的问题存在

**Comment by wong2** [comment]
可以介绍下你对腾讯云函数的使用方式吗？我之前没有见到有人这么用过

**Comment by lzhbest** [comment]
我参考的是这个方式 ： https://github.com/Ice-Hazymoon/openai-scf-proxy

**Comment by wong2** [comment]
明白了，方便分享下你的代理地址给我吗？我来调试下这个问题。我的邮箱：wonderfuly@gmail.com

**Comment by Neo110** [comment]
> 我参考的是这个方式 ： https://github.com/Ice-Hazymoon/openai-scf-proxy
> 
> 1. 在 https://cloud.tencent.com/ 注册账号
> 2. 生成 Nodejs 运行环境 ，获取到代理地址
> 3. 然后通过 代理地址及 ChatGPT API 密钥进行配置访问

问题解决了吗？
