### ISSUE TITLE
会出现两个滚动条

### ISSUE THREAD

**Issue by wy5211** [chathub-dev/chathub#392]
![avwayV4svo](https://github.com/chathub-dev/chathub/assets/54129434/a33c9ddb-7cb2-4ccf-817c-a1f1fc988522)

**Comment by wy5211** [comment]
可以优化一下吗

**Comment by wy5211** [comment]
感谢开发者开发的插件，很好用；

如上图，两个滚动条，会影响体验，可以修复一下吗

**Comment by wong2** [comment]
你好，我这边没能复现这个问题。
看到你好像也是做前端的，可以帮忙初步看看是什么原因吗？

**Comment by wong2** [comment]
发现你用的不是最新版本，可以升级一下再试试吗？安装：https://chathub.gg

**Comment by wy5211** [comment]
> 你好，我这边没能复现这个问题。 看到你好像也是做前端的，可以帮忙初步看看是什么原因吗？

实测，把这个盒子的 height: 100% 拿掉就好了

![image](https://github.com/chathub-dev/chathub/assets/54129434/d80f7a30-18e9-4d25-a87f-efc5fa0268fb)

**Comment by wy5211** [comment]
> 发现你用的不是最新版本，可以升级一下再试试吗？安装：https://chathub.gg

好的 ，谢谢

**Comment by wy5211** [comment]
> 新版本正常了嘛？@wy5211

正常啦 ， 谢谢作者
