### ISSUE TITLE
必应经常报错，被提示Failed to execute 'insertBefore' on 'Node': 

### ISSUE THREAD

**Issue by ffgg536956** [chathub-dev/chathub#393]
当我选择必应聊天时，他经常报错，经常被提示以下英文字符串，这个是什么原因？我该怎么办？
被提示出错内容：
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node

**Comment by wong2** [comment]
请问您的浏览器和浏览器版本是什么？

**Comment by wong2** [comment]
你是否使用Google Translate翻译了插件页面？

**Comment by wong2** [comment]
Should be fixed

**Comment by ffgg536956** [comment]
> 你是否使用Google Translate翻译了插件页面？

我之前确实使用了自动翻译功能。按照您的提示，当我取消了浏览器的自动翻译功能之后。此前报错的 问题就再也没有发生了，非常感谢您。但是依然期待您能够 推出一个版本 能 兼容网页的自动翻译，如果有可能的话。 @wong2
