### ISSUE TITLE
deactivate license (?)

### ISSUE THREAD

**Issue by Giugie1998** [chathub-dev/chathub#396]
Soon I will no longer own one of the PCs where my license is active, and I can't deactivate it even by clicking on the activation button. Could it be an idea to manage licenses from an account? or from the email with which the payment was made?

**Comment by wong2** [comment]
Hi, I'll add deactivate in next version.

**Comment by Giugie1998** [comment]
Ok perfect, will the deactivation be remote? or will it necessarily have to be the PC where you want to deactivate the license?

**Comment by wong2** [comment]
I'll implement the latter approach today, then maybe support remote someday in the future.

**Comment by wong2** [comment]
Published in v1.15.4
