### ISSUE TITLE
new bing无法答复，一直处于loading状态

### ISSUE THREAD

**Issue by DYin65535** [chathub-dev/chathub#398]
![image](https://github.com/chathub-dev/chathub/assets/36749843/ec0499fa-8fcf-4d05-ab73-a909b0ade074)

使用版本是v1.15.5，浏览器为chrome

**Comment by wong2** [comment]
重试也不行吗？

**Comment by DYin65535** [comment]
> 重试也不行吗？

是的，这两天一直不行

**Comment by wong2** [comment]
先挂个全局代理试试？确认下是不是代理问题

**Comment by DYin65535** [comment]
> 先挂个全局代理试试？确认下是不是代理问题

挂不挂代理都连不上..chatgpt的api模式可以连上

**Comment by ciiwhjp65** [comment]
我也遇到了，全局代理、增强模式这些都尝试了，清除 bing 的缓存重新登录也不行
