### ISSUE TITLE
v1.15.5，设置-启动页面，里面没有讯飞的选项？

### ISSUE THREAD

**Issue by Sui-Yun** [chathub-dev/chathub#399]
问题：
1.设置-启动页面，里面没有讯飞的选项？

其他建议：
2.清除历史对话：可以增加一个一键清除某个模型的，然后再做一个一键清除所有模型的吗？
3.清除了历史对话，但是去讯飞和poe里看，却还是有的，可以同步清理吗？

**Comment by wong2** [comment]
1.设置-启动页面，里面没有讯飞的选项？

这个是遗漏了，下个版本加上它

**Comment by wong2** [comment]
其他建议收到！

**Comment by wong2** [comment]
已增加 https://github.com/chathub-dev/chathub/commit/70c9052d4bb1d9f0d7006d7a117fb093dc242cfe
