### ISSUE TITLE
购买会员支付成功之后如何识别购买成功

### ISSUE THREAD

**Issue by SaminGZ** [chathub-dev/chathub#403]

**Comment by wong2** [comment]
购买成功后，您的邮箱会收到一个 license key，然后在插件里填入这个key激活即可

**Comment by wong2** [comment]
<img width="546" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/fff6a4f9-f3d3-4ea3-a69a-77493840a1b8">

**Comment by fupengonline** [comment]
如何使用微信、支付宝支付购买会员。

**Comment by wong2** [comment]
<img width="560" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/fb8b7e74-2222-4a77-9c39-5fdeaa799f6e">

这里有微信支付宝呀

**Comment by fupengonline** [comment]
我的只有这种



| |
小夫
重庆  - 
无
|




---- 回复的原邮件 ----
| 发件人 | Wang ***@***.***> |
| 日期 | 2023年05月24日 11:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chathub-dev/chathub] 购买会员支付成功之后如何识别购买成功 (Issue #403) |

这里有微信支付宝呀

**Comment by wong2** [comment]
什么？有图片吗

**Comment by fupengonline** [comment]
能看的清楚吗？附件里面。


---- 回复的原邮件 ----
| 发件人 | Wang ***@***.***> |
| 发送日期 | 2023年5月24日 11:45 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [chathub-dev/chathub] 购买会员支付成功之后如何识别购买成功 (Issue #403) |

什么？有图片吗

**Comment by wong2** [comment]
没有图，GitHub应该不支持邮件回复里的图片，你直接到GitHub网站发图吧

**Comment by fupengonline** [comment]
购买了终身会员，是否还需要魔法？


| |
小夫
重庆  - 
无
|
---- 回复的原邮件 ----
| 发件人 | Wang ***@***.***> |
| 发送日期 | 2023年5月24日 11:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [chathub-dev/chathub] 购买会员支付成功之后如何识别购买成功 (Issue #403) |

没有图，GitHub应该不支持邮件回复里的图片，你直接到GitHub网站发图吧

**Comment by wong2** [comment]
需要的

**Comment by fupengonline** [comment]
不需要chatgpt账户吧。



| |
小夫
重庆  - 
无
|




---- 回复的原邮件 ----
| 发件人 | Wang ***@***.***> |
| 日期 | 2023年05月25日 11:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chathub-dev/chathub] 购买会员支付成功之后如何识别购买成功 (Issue #403) |

需要的

**Comment by wong2** [comment]
需要自己的ChatGPT账号。
付费得到的功能在Premium页面都列出来了，不在其中的就不包括

**Comment by gjxfish** [comment]
付费成功后，还是需要自己提供API吗
