### ISSUE TITLE
New AI: sage, using poe

### ISSUE THREAD

**Issue by t3dium** [chathub-dev/chathub#405]
Similar to how poe was used for the claude integration, it can also be used to integrate sage into chathub.

I've found sage to be better than chatgpt in some areas, despite being based of the same model. And it also wouldn't have the same heavy rate-limiting that chatgpt has, as it tends to respond pretty quickly.

**Comment by insign** [comment]
Poe now offers bots, so, I think it is easy add custom bots support too. Or maybe pre-prompt, something like poe does. But locally this time.
