### ISSUE TITLE
Time limit?

### ISSUE THREAD

**Issue by limelect** [chathub-dev/chathub#407]
Is web ChatHub time limited?
Will it work in a year? for example
Using the key I can not anymore

**Comment by wong2** [comment]
Sorry I can't understand you

**Comment by wong2** [comment]
The premium license key is life time

**Comment by limelect** [comment]
I can see it on https://chat.openai.com/api/auth/session
that my that it expires "expires":"2023-06-15T07:02:30.071Z",
Will your software will end on the above date
at list the chatgpt

**Comment by wong2** [comment]
No, it will not.

**Comment by limelect** [comment]
Thanks

**Comment by wong2** [comment]
You don't need API keys in webapp mode, because it's using the OpenAI account in your browser.

**Comment by AliDehbansiahkarbon** [comment]
> You don't need API keys in webapp mode, because it's using the OpenAI account in your browser.

Okay, my OpenAI account is a free account, so it depends on my OpenAI account limitation.
It won't work when my account expires, right?

**Comment by AliDehbansiahkarbon** [comment]
Not expiration, that was my mistake.
I know it's free for now, I meant in case it won't be free one day.
I got my answer, thank you.
