### ISSUE TITLE
403 error while fetching https://bard.google.com/faq

### ISSUE THREAD

**Issue by itskaransingh** [chathub-dev/chathub#408]
I am getting a 403 error code while fetching the HTML of https://bard.google.com/faq for bl and at values, 
I am trying to fetch in background script 

`  const html = await ofetch("https://bard.google.com/faq"`

can anyone plz help me with this 
thank you in advance

**Comment by wong2** [comment]
Is this issue related to the ChatHub extension?

**Comment by itskaransingh** [comment]
I was exploring different possibilities related to ChatHub, so I tried to fetch in the background script but I am getting 403

**Comment by wong2** [comment]
You need authenticated cookies when fetching this page.

**Comment by itskaransingh** [comment]
> You need authenticated cookies when fetching this page.

In my request headers, cookies are proper but the sec-fetch-site sets to cross-site instead of none, this is causing the request failure, can you plz help me to solve this. 

`sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42`

Thank you very much for your reply you are very humble .

**Comment by wong2** [comment]
I can't help you with this as lack of information. Please read the source code of ChatHub, everything you need is there.

**Comment by itskaransingh** [comment]
Thanks for your time 😊
