### ISSUE TITLE
这个灰色背景 太丑了，建议恢复到以前的 紫色背景

### ISSUE THREAD

**Issue by feige2018** [chathub-dev/chathub#412]
![image](https://github.com/chathub-dev/chathub/assets/38276291/f718fa2c-c068-4876-9e02-28e6491fafa4)

这个灰色背景 太丑了，建议回复到以前的 紫色背景

**Comment by wong2** [comment]
![image](https://github.com/chathub-dev/chathub/assets/321947/6f178071-e74b-4eb6-8496-329c83c9eab0)

**Comment by wong2** [comment]
默认还是这个紫色呀
![image](https://github.com/chathub-dev/chathub/assets/321947/0136c15e-3369-4017-95ea-f2dda378da4b)

你是不是改了主题设置呢？

![image](https://github.com/chathub-dev/chathub/assets/321947/c56c43a8-2931-4cad-92ea-b512958814c7)

**Comment by shxlxa** [comment]
我的也是灰色背景

> 默认还是这个紫色呀 ![image](https://user-images.githubusercontent.com/321947/238362745-0136c15e-3369-4017-95ea-f2dda378da4b.png)
> 
> 你是不是改了主题设置呢？
> 
> ![image](https://user-images.githubusercontent.com/321947/238362840-c56c43a8-2931-4cad-92ea-b512958814c7.png)

我的也是灰色背景，没有改主题设置

**Comment by wong2** [comment]
您的浏览器和浏览器版本是？

**Comment by shxlxa** [comment]
> 您的浏览器和浏览器版本是？

mac电脑，谷歌浏览器，版本 111.0.5563.110（正式版本） (x86_64)

**Comment by wong2** [comment]
试试最新版 v1.16.6

**Comment by feige2018** [comment]
升级了，恢复紫色背景了，好好看！
