### ISSUE TITLE
The license did not come

### ISSUE THREAD

**Issue by KROU4** [chathub-dev/chathub#413]
I bought the license at Dimasik425@yandex.ru, but nothing came after almost 2 hours. Can you please resend the code again?

**Comment by wong2** [comment]
Hi, I can't find the order from my side.
Can you provide screenshot about the payment? Then I'll investigate the
issue with the payment provider Lemon Squeezy.

**Comment by wong2** [comment]
I've talked to Lemon Squeezy, here is their response:

<img width="623" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/8307cc03-cb12-488a-8e3b-4283ae3a8be4">
