### ISSUE TITLE
premium key unavailable

### ISSUE THREAD

**Issue by zolped** [chathub-dev/chathub#420]
Hi! I have purchased the premium key but haven't received it on my email. Can you check? Thanks in advance!

Email:
lemonsqueezy.gw225@simplelogin.com

**Comment by wong2** [comment]
I could not find an order with this email.

**Comment by zolped** [comment]
[image: image.png]

**Comment by zolped** [comment]
<img width="632" alt="image" src="https://github.com/chathub-dev/chathub/assets/102224704/902e1f49-9548-4a76-84b5-bbe6c29f6073">

**Comment by wong2** [comment]
I'll investigate this issue with the payment provider Lemon Squeezy.

**Comment by zolped** [comment]
I've made another attempt regardless if that went through or not. Please verify and if there are duplicate charges, refund of them. Thanks.

<img width="930" alt="Screenshot 2023-05-16 at 01 29 36" src="https://github.com/chathub-dev/chathub/assets/102224704/6e1f52ae-035e-4a32-aa2a-72c888fd98fe">

**Comment by wong2** [comment]
No, still no order.
What credit card are you using? Has it charged?

**Comment by zolped** [comment]
Yes, it has. both times/ atleast that what's I see on my credit card
provider's website. I have also received SMS confirmation, both times. It's
a virtual master card. I wasn't able to use google pay either, for whatever
that is worth.

**Comment by wong2** [comment]
Can you see your orders via https://app.lemonsqueezy.com/my-orders/?

**Comment by zolped** [comment]
I cannot log in, apparently it didn't register my purchases and/or email
even though the credit card was charged on both attempts. It The card
hasn't been refunded so far either. Both orders went thru.

**Comment by zolped** [comment]
<img width="619" alt="image" src="https://github.com/chathub-dev/chathub/assets/102224704/2551ef36-84a1-44dd-b63a-7d941ff74258">

**Comment by wong2** [comment]
<img width="571" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/2ee9f3ff-d0af-40ce-a5bf-e6429a7eff80">

I got response from Lemon Squeezy

**Comment by zolped** [comment]
Got a refund for one of the payments and received the key. All has been
solved now. Thanks for the help!
