### ISSUE TITLE
chatgpt doesn't work after chathub is updated.

### ISSUE THREAD

**Issue by randi65535** [chathub-dev/chathub#423]
![화면 캡처 2023-05-17 090844](https://github.com/chathub-dev/chathub/assets/38193576/18b2515d-597b-4706-a28b-4ce1e06d6a8e)

 - OS: Windows10
 - Browser: naver whale browser

**Comment by wong2** [comment]
Are you using Webapp mode or API mode?

**Comment by randi65535** [comment]
@wong2 WebApp Mode and i use chatgpt Model-4

im subscribing chatgpt Plus

**Comment by wong2** [comment]
Can you try to restart the browser and try again?

**Comment by randi65535** [comment]
it works

maybe it is session issue

**Comment by wong2** [comment]
Great!
