### ISSUE TITLE
chatgpt栏目增加poe下的gpt3.5和gpt4

### ISSUE THREAD

**Issue by wangqs97** [chathub-dev/chathub#427]
作者您好，我看到claude支持了poe下的各个版本，请问chatgpt是否能够支持poe下的两个版本呢？特别是在poe充值了会员的用户，希望能在chathub中调用poe的gpt4.
<img width="584" alt="image" src="https://github.com/chathub-dev/chathub/assets/55077238/e3bfe8c7-779f-4141-a952-111d6f557a8b">

**Comment by wong2** [comment]
好的，我看看

**Comment by wong2** [comment]
v1.18.5 已支持
