### ISSUE TITLE
能不能把Premium Licenses Key模式验证会员改成绑定账号形式来实现 Premium 功能的绑定

### ISSUE THREAD

**Issue by 1437333679** [chathub-dev/chathub#428]
作者您好，我购买了 ChatHub Premium 的功能，但是插件本身一直没有更新，一直停留在 v1.13.0版本，重新到edge插件下载安装后，提示重新输入 Premium Licenses Key，那这样我是不是用掉了一次激活机会，我希望以账号绑定和设备识别来实现 Premium 功能的认证

**Comment by wong2** [comment]
你好，可以在 https://app.lemonsqueezy.com/my-orders/ 这里管理自己激活的设备，以及进行反激活
