### ISSUE TITLE
能增加GPT-4的Web Browsing模式的支持吗？

### ISSUE THREAD

**Issue by bingyaome** [chathub-dev/chathub#429]
Webapp Mode下，能否增加Web Browsing模式的支持，官网现在已经支持GPT-4的联网模式了，据说这周会全量开放给所有plus用户。

感谢🙏🙏🙏
<img width="402" alt="image" src="https://github.com/chathub-dev/chathub/assets/6829856/7d94ca4f-dd79-4a5a-9fcc-8b40a909e632">

**Comment by wong2** [comment]
等我有了权限就看看怎么支持

**Comment by wong2** [comment]
https://twitter.com/wong2_x/status/1659031266250096641
