### ISSUE TITLE
建议默认可以保留历史

### ISSUE THREAD

**Issue by yorkfread** [chathub-dev/chathub#43]
因为有时候需要查看历史的消息内容
可以设置为选择项，可以关闭

**Comment by yorkfread** [comment]
也支持清除历史内容

**Comment by JantHsueh** [comment]
@wong2  建议先实现这个，弥补了new bing 的不足，这个比多AI聊天框，更有价值

**Comment by wong2** [comment]
@JantHsueh 有道理 👍

**Comment by olin2011** [comment]
我觉得是可以保留历史，或者可以导出数据。导出数据我觉得比较重要

**Comment by olin2011** [comment]
> 我觉得是可以保留历史，或者可以导出数据。导出数据我觉得比较重要

导出又分数据导出，和整页导出，想想都太美。

**Comment by olin2011** [comment]
> @JantHsueh 有道理 👍

我觉得是可以保留历史，或者可以导出数据。导出数据我觉得比较重要，数据导出，和整页导出

**Comment by wong2** [comment]
@olin2011 导出数据按理说是非常低频的行为吧

**Comment by wong2** [comment]
还是说你说的更接近分享对话？

**Comment by olin2011** [comment]
> @olin2011 导出数据按理说是非常低频的行为吧

又或者历史记录有一个单独页面，我觉得在对话界面看历史不是很爽的感觉。
导出是为了保存数据，他用场景应该蛮多，我只是想单独打开一段内容。也不用每次都进入chat。

**Comment by olin2011** [comment]
某些片段可以让自己markdown做笔记，或者别人都直接copy走了，哈哈

**Comment by wong2** [comment]
v1.7.0已支持 https://twitter.com/wong2_x/status/1638454824021917696
