### ISSUE TITLE
能否增加对话记录保持的功能？

### ISSUE THREAD

**Issue by Reality-Saury** [chathub-dev/chathub#432]
能否增加对话记录保持的功能？每次一关闭Tap，之前的对话都没有了。要是能支持对话记录导出就更好了。已购买高级会员。

**Comment by wong2** [comment]
有的呀
<img width="541" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/2f7e910c-51d3-4400-bd79-eb6125599a3e">

是不是不够明显？

**Comment by Reality-Saury** [comment]
> 有的呀 <img alt="image" width="541" src="https://user-images.githubusercontent.com/321947/239135747-2f7e910c-51d3-4400-bd79-eb6125599a3e.png">
> 
> 是不是不够明显？

谢谢开发的回复。这个按钮似乎只是将聊天记录弹出？怎么导出为PDF 或者 doc格式的文件呢？ 谢谢！

**Comment by wong2** [comment]
导出你点左边第一个按钮

**Comment by Reality-Saury** [comment]
好像不行。。。是我操作有问题吗，点了你箭头所指的按钮，只是弹出一个窗口，没法道出PDF或者word格式的文档
![Uploading Snipaste_2023-05-22_00-22-27.png…]()

**Comment by Reality-Saury** [comment]
<img width="1529" alt="Snipaste_2023-05-22_00-22-27" src="https://github.com/chathub-dev/chathub/assets/66583918/d1a8ec0f-dec6-4066-9eb4-4b65d7def0b4">

**Comment by Reality-Saury** [comment]
点了左边的按钮，好像是分享的按钮，不是导出？
<img width="1533" alt="Snipaste_2023-05-22_00-27-41" src="https://github.com/chathub-dev/chathub/assets/66583918/d52f560e-bcc6-4516-b775-8b230d6f6825">

**Comment by wong2** [comment]
分享和导出是一回事啊，现在没有导出为pdf的功能，可以导出为markdown
