### ISSUE TITLE
ChatGpt使用出错

### ISSUE THREAD

**Issue by Mrmoodle** [chathub-dev/chathub#436]
请问这种错误是设置不对吗？我ChatGpt设为gpt-4, API Mode
{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by wong2** [comment]
你好，API模式使用GPT-4需要申请权限的

**Comment by Mrmoodle** [comment]
我有申请secret key，目前是免费试用吧？怎样才能使用GPT-4?

**Comment by wong2** [comment]
加入这个waitlist：https://openai.com/waitlist/gpt-4-api

**Comment by Mrmoodle** [comment]
一般要多久才能通过？

**Comment by wong2** [comment]
这个看OpenAI了

如果你是ChatGPT Plus会员，可以使用webapp模式的GPT-4

**Comment by Mrmoodle** [comment]
没有购买GPT-4 plus; 当下只能使用GPT~3.5了？
