### ISSUE TITLE
Edge issue 

### ISSUE THREAD

**Issue by fadyfayz** [chathub-dev/chathub#440]
**Describe the bug**
I Press on Edge icon to install I face error " Download Edge from playtore " & I already downloaded ... 
Page refused to install "The Hub" on "Edge" with me 
Need your support 🙏

- Browser [e.g. Edge ]

**Comment by wong2** [comment]
Are you installing here? https://microsoftedge.microsoft.com/addons/detail/chathub-allinone-chat/kdlmggoacmfoombiokflpeompajfljga
