### ISSUE TITLE
bing一直转圈等待，控制台报错

### ISSUE THREAD

**Issue by evelynn996** [chathub-dev/chathub#441]
chatgpt正常使用，bing有问题
![image](https://github.com/chathub-dev/chathub/assets/93717293/12a7dabe-d09f-43fc-9a60-8f3411468f69)
![image](https://github.com/chathub-dev/chathub/assets/93717293/b6a723f9-72f1-4ddd-b53f-f1daf2e93a6b)

**Comment by wong2** [comment]
![image](https://github.com/chathub-dev/chathub/assets/321947/e82ed549-f42e-43a2-83d8-7cb377a35f36)

看这个意思，你需要先去 bing.com 聊天通过一个验证
