### ISSUE TITLE
加入Prompt Helper，添加常用prompt的快捷键

### ISSUE THREAD

**Issue by zjplab** [chathub-dev/chathub#444]
可以参考代码：https://greasyfork.org/en/scripts/465349-chatgpt-prompt-helper

**Comment by wong2** [comment]
输入框旁边的 书本 图标就是这个功能啊

**Comment by zjplab** [comment]
![image](https://github.com/chathub-dev/chathub/assets/16349466/b1569192-78fb-4793-a92a-3e2dbf9f10b4)
![image](https://github.com/chathub-dev/chathub/assets/16349466/28e7fc78-de85-4d1a-8b7e-b7c1de98ce34)
有检索功能会好很多
@wong2

**Comment by wong2** [comment]
试试最新版，有快捷键了
