### ISSUE TITLE
claude会话重复

### ISSUE THREAD

**Issue by enendaboluo** [chathub-dev/chathub#446]
**Describe the bug**
![image](https://github.com/chathub-dev/chathub/assets/132199377/2b72fd85-aab6-4afb-a26a-dd4979692730)
![image](https://github.com/chathub-dev/chathub/assets/132199377/425cd14a-bca3-4716-b53c-9af9268ee1bb)
如图所示，在poe会话页面正常显示。但是在chathub中显示不出最新的会话。重新显示了上一条内容
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
试试最新版 v1.18.5

**Comment by enendaboluo** [comment]
您好，很高兴能看到chatgpt有了poe4.0的接口。遗憾的是claud依旧是出现了一样的bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chathub-dev/chathub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 晚上7:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chathub-dev/chathub] claude会话重复 (Issue #446)





 
试试最新版 v1.18.5

**Comment by enendaboluo** [comment]
我找到了原因所在。当接口为poe时都会出现这种问题。无论时chat 还是cluade。希望您尽快修复好。感激不尽




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chathub-dev/chathub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 晚上7:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chathub-dev/chathub] claude会话重复 (Issue #446)





 
试试最新版 v1.18.5

**Comment by wong2** [comment]
v1.18.7 修复了这个问题
