### ISSUE TITLE
最下面的“反馈”、“设置”、“皮肤“跟背景一个色了，看不清了。

### ISSUE THREAD

**Issue by brandyblacktea** [chathub-dev/chathub#449]
**Describe the bug**
1.18版本，最下面的“反馈”、“设置”、“皮肤“跟背景一个色了，看不清了。

<img width="224" alt="Premium" src="https://github.com/chathub-dev/chathub/assets/43712342/f450119c-1fcc-4fde-ae10-d15643c84891">

**Desktop (please complete the following information):**
 - OS: [macOS 13.4 (22F66)]
 - Browser [brave]

**Comment by wong2** [comment]
好像和浏览器窗口的高度有关系，我研究一下

**Comment by wong2** [comment]
1.18.1 优化了该问题
