### ISSUE TITLE
滚动条 scrollbar UI优化；使用的默认的不太搭配

### ISSUE THREAD

**Issue by GentlemanHu** [chathub-dev/chathub#459]
**Describe the bug**
多个Icon，可以竖向滚动，滚动条和整体UI不太搭😄
<img width="261" alt="image" src="https://github.com/chathub-dev/chathub/assets/34559079/f664f17e-e701-4d72-ae46-d48b9272af2d">

感谢大佬，非常好用
**Desktop (please complete the following information):**
 - OS: mac
 - Browser：Chrome

**Comment by wong2** [comment]
收到
