### ISSUE TITLE
同一台电脑,删了重下几次激活码就没用了?????????

### ISSUE THREAD

**Issue by GreatWallX** [chathub-dev/chathub#467]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
可以在 https://app.lemonsqueezy.com/my-orders/ 删除多余的激活

**Comment by GreatWallX** [comment]
感谢大佬,问题已成功解决
