### ISSUE TITLE
bing一直省略号

### ISSUE THREAD

**Issue by brandyblacktea** [chathub-dev/chathub#469]
**Describe the bug**
bing对话一直省略号

**Desktop (please complete the following information):**
 - OS: [13.4 (22F66)]
 - Browser [Brave 已是最新版本： 1.51.118 Chromium: 113.0.5672.126（正式版本） (arm64)]

**Comment by GAssassin0412** [comment]
我也一样，我更换了多个代理地址都没办法解决这个问题。

**Comment by wong2** [comment]
可以打开浏览器开发者工具，看看console输出吗

**Comment by GAssassin0412** [comment]
![QQ截图20230524135310](https://github.com/chathub-dev/chathub/assets/58981335/7a8f60fe-08a6-4359-b6a9-344640bf7035)
！！好像这就是问题所在
但是我应该去哪里验证这个CAPTCHA呢

**Comment by wong2** [comment]
@GAssassin0412 你打开 https://bing.com 进入聊天，会出现这个 CAPTCHA 嘛

**Comment by GAssassin0412** [comment]
@wong2 当我使用Chrome打开bing时一切正常，
但点击Chat那个按键时会直接跳转到这个界面
![QQ截图20230524140653](https://github.com/chathub-dev/chathub/assets/58981335/8513b2b3-b00e-42a8-90b6-ec60ef19db36)
这是否意味着我必须使用edge通过一次验证，才能在Chrome的Chathub里继续使用New Bing？

**Comment by wong2** [comment]
@GAssassin0412 你先装一下这个插件（也是我做的），就可以在Chrome里使用Bing而不用Edge了。然后你再试试是否会遇到CAPTCHA

**Comment by GAssassin0412** [comment]
非常感谢！！这个插件完美的解决了我的问题！！
在我去bing→chat的界面时通过了CAPTCHA验证，然后就可以正常使用了

**Comment by wong2** [comment]
了解了

**Comment by feeas** [comment]
> [laldfnbbeocphnilnofhedhcjcnchbld](https://chrome.google.com/webstore/detail/bing-unchained-use-new-bi/laldfnbbeocphnilnofhedhcjcnchbld)

老哥,为什么要把这个插件删了? chrome虽然也能用Copilot,但是给的对话次数只有5次,edge有30次. 还是需要模拟edge.

**Comment by wong2** [comment]
@feeas 不是我删的，被Chrome下架了，侵犯了Bing的权益
