### ISSUE TITLE
chatgpt部分会一直报错Failed to execute 'fetch' on 'Window‘

### ISSUE THREAD

**Issue by dooozo** [chathub-dev/chathub#47]
作者您好，Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.
<img width="1440" alt="截屏2023-03-14 00 55 42" src="https://user-images.githubusercontent.com/76516545/224771585-4e0fee69-e333-45ec-83be-d798d775201e.png">
大概是这个状态，谢谢作者。

**Comment by dooozo** [comment]
作者您好，重新安装解决了这个问题。谢谢您。

**Comment by wong2** [comment]
您的字体为什么看起来这么大，是缩放了窗口吗？
