### ISSUE TITLE
支持安卓界面

### ISSUE THREAD

**Issue by danerlt** [chathub-dev/chathub#472]
安卓手机可以安装kiwi浏览器安装插件，手机上打开页面样式不好用，能否适配下

![Screenshot_2023-05-24-11-46-27-323_com kiwibrowser browser](https://github.com/chathub-dev/chathub/assets/14197717/7bdf60c1-f4b1-4b35-9aee-205975f241db)

![Screenshot_2023-05-24-11-49-10-386_com kiwibrowser browser](https://github.com/chathub-dev/chathub/assets/14197717/206b7576-afe0-4153-8511-6044a7c87f28)

![Screenshot_2023-05-24-11-49-04-334_com kiwibrowser browser](https://github.com/chathub-dev/chathub/assets/14197717/76d36bb3-f13e-4da7-8a03-22fa07d34ca8)

**Comment by wong2** [comment]
暂时没有精力支持手机设备
