### ISSUE TITLE
【功能】允许隐藏侧边栏中任意模型。

### ISSUE THREAD

**Issue by JustusPan** [chathub-dev/chathub#473]
有时候，用户并不关心除了特定的几个（他所熟知的、有资格测试的、付费的）以外的AI服务。
随着后续越来越多的服务被集成进来，侧边栏与自己无关的ai服务会越来越多。

是否可以增加设置功能，允许用户自己决定侧边栏显示哪些AI服务。

**Comment by liubeibei2023** [comment]
想一起了

**Comment by wong2** [comment]
v1.21 已支持，在设置里可控制展示哪些bot
