### ISSUE TITLE
有人知道新加入的几个羊驼模型怎么用吗？

### ISSUE THREAD

**Issue by CellLz** [chathub-dev/chathub#474]

**Comment by wong2** [comment]
直接和它们聊天就可以了呀，遇到什么问题么？
注意它们可能对中文支持不好

**Comment by CellLz** [comment]
跟它聊天以后就一直转圈，然后返回一个“WebSocket closed with reason:  (1006).”

**Comment by CellLz** [comment]
> 直接和它们聊天就可以了呀，遇到什么问题么？ 注意它们可能对中文支持不好

跟它聊天以后就一直转圈，然后返回一个“WebSocket closed with reason: (1006).”
是不是也需要像其他几个模型一样先登录个poe之类的网站？

**Comment by wong2** [comment]
倒是第一次听说这个问题。羊驼模型不需要登录网站。不过你可以去它们网站试试，调用的是这个网站的接口：https://chat.lmsys.org

**Comment by CellLz** [comment]
我找到原因了，因为我没把羊驼模型的网址放到VPN列表里面，所以连不上服务器。

> 倒是第一次听说这个问题。羊驼模型不需要登录网站。不过你可以去它们网站试试，调用的是这个网站的接口：https://chat.lmsys.org

**Comment by wong2** [comment]
明白了
