### ISSUE TITLE
GPT-4 webapp mode 无法使用

### ISSUE THREAD

**Issue by napoleon9000** [chathub-dev/chathub#476]
**Describe the bug**
切换到GPT-4 webapp browsing mode之后，聊天窗口会一直是loading的状态没有结果。
API mode 正常工作，直接去openAI的网页版也一切正常。

Console log:
<img width="744" alt="Screenshot 2023-05-24 at 2 28 47 PM" src="https://github.com/chathub-dev/chathub/assets/5094043/69d6ec1e-8642-4094-9567-662c89d22400">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Location: United States

**Comment by wong2** [comment]
重启浏览器再试试

**Comment by napoleon9000** [comment]
@wong2 刚刚试了一下重启Chrome也不行
