### ISSUE TITLE
[Bug] 在Webapp Mode下 GPT-4 Browing 模型有一些问题。

### ISSUE THREAD

**Issue by JustusPan** [chathub-dev/chathub#479]
**Describe the bug**
![image](https://github.com/chathub-dev/chathub/assets/10916383/ae17bbca-6b89-43af-a248-b26f9c0dbd45)
![image](https://github.com/chathub-dev/chathub/assets/10916383/5a7328d2-040a-47c6-891d-5ec4afabcefa)
![image](https://github.com/chathub-dev/chathub/assets/10916383/cae4a098-570a-4738-8d9f-362d84fff059)

如果触发一些搜索行为，就会开始无限搜索。

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Comment by wong2** [comment]
这个是browsing模型自有的问题，只能等OpenAI优化了
