### ISSUE TITLE
无法使用 两个全部报错 一个无法提取 一个无法访问服务

### ISSUE THREAD

**Issue by magesep** [chathub-dev/chathub#48]
这是咋回事？

**Comment by wong2** [comment]
ChatGPT的API key设置了嘛

**Comment by Doraemon1203-yue** [comment]
我设置了ChatGPT的API key也两个都不好使

**Comment by magesep** [comment]
我想用必应来着的 chatgpt我本来就能用  所以有点烦 主要是chatgpt不能查询网络数据

**Comment by manakong** [comment]
插个眼，回头来看为什么
无法提取
禁止：对不起，您无法访问此服务

**Comment by wong2** [comment]
需要有new bing的资格才能使用

**Comment by manakong** [comment]
> 需要有新必应的资格才能使用

怎么做呢？

**Comment by wong2** [comment]
https://bing.com/new 这里候补
