### ISSUE TITLE
Premium授权的的设备是否可以反激活？

### ISSUE THREAD

**Issue by JustusPan** [chathub-dev/chathub#480]
还是说相当于一次性使用，最多只能用5次。

**Comment by wong2** [comment]
可以的，有反激活按钮呀
<img width="515" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/dcce57a6-44f5-4640-86e1-3cca35901034">

**Comment by qw0258** [comment]
有没有人来拼个单，100多好贵啊

**Comment by qiuaibo** [comment]
> 如果已经不能使用原设备，也可以到 https://app.lemonsqueezy.com/my-orders/ 远程管理

![image](https://github.com/chathub-dev/chathub/assets/29228484/4e9ce5e5-0751-4482-bd22-23483b8e45ec)
![Screenshot_2023-06-01-12-19-33-92_3915bacb930634b7e206116f9dc9486f](https://github.com/chathub-dev/chathub/assets/29228484/1401a460-22dd-4a90-aab6-ef2420b5b959)
