### ISSUE TITLE
可以添加能自定义base_url吗

### ISSUE THREAD

**Issue by Maddaxman** [chathub-dev/chathub#483]
如题，节点很容易被风控，如果能自定义cloudflare的url绕过openai就能无阻访问

**Comment by wong2** [comment]
没明白 base url 是什么

**Comment by Maddaxman** [comment]
> 没明白 base url 是什么

https://mp.weixin.qq.com/s/SYGPuHKO7ShzfmBGsQ363w
@wong2

**Comment by wong2** [comment]
哦这个啊，是支持的呀，你在ChatHub设置里ChatGPT切换到API mode就能改了

**Comment by Maddaxman** [comment]
哦哦，记错了是有的
