### ISSUE TITLE
Bard doesn't show any pictures,only texts.

### ISSUE THREAD

**Issue by TYLERCHEN999** [chathub-dev/chathub#484]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
Can you give me an example prompt for generating pictures?

**Comment by TYLERCHEN999** [comment]
> Can you give me an example prompt for generating pictures?
show me a picture of the capacitor used in DRAM

**Comment by TYLERCHEN999** [comment]
when asked the sam question ,bard.google.com give me the picture I needed instantly

**Comment by wong2** [comment]
Supported in latest version. v1.20.6
