### ISSUE TITLE
Chathub bard gives completely different answer compared with bard.google.com when I asked the same question

### ISSUE THREAD

**Issue by TYLERCHEN999** [chathub-dev/chathub#485]
**Describe the bug**
当我问 “how many kinzhal missiles have been shot down by ukraine army using patriate missiles up to today”（乌克兰击落了几枚俄罗斯匕首导弹）

Chathub bard：According to the publicly available information, there is no confirmed report of Ukraine shooting down any Kinzhal missiles using Patriot missiles. The Ukrainian military has claimed to have shot down several Kinzhal missiles, but these claims have not been verified by independent sources. The Russian military has denied that any Kinzhal missiles have been shot down.
The Kinzhal is a hypersonic missile that can travel at speeds of up to Mach 10. It is a very difficult missile to shoot down, and the Patriot missile system is not specifically designed to intercept hypersonic missiles. However, the Patriot missile system has been upgraded with new capabilities that make it more effective against hypersonic threats. It is possible that Ukraine has shot down some Kinzhal missiles, but there is no concrete evidence to support this claim.

bard.google.com：According to the sources I have access to, Ukraine has shot down at least 6 Kinzhal missiles using Patriot missiles. The first shootdown was confirmed by the US government on May 4, 2023, and the second shootdown was confirmed on May 16, 2023. It is possible that there have been other shootdowns that have not been confirmed, but these are the only two that have been publicly acknowledged.
The Kinzhal is a hypersonic missile that can travel at speeds of up to Mach 10, making it difficult to intercept. However, the Patriot missile system is designed to intercept high-speed targets, and it has been successful in shooting down a number of Kinzhals.
The shootdowns of Kinzhals by Ukraine are a significant development, as they demonstrate that the country's air defenses are capable of countering Russia's most advanced weapons. This could deter Russia from using Kinzhals in the future, or it could lead to Russia developing new and even more advanced hypersonic missiles.

我不知道这算不算bug，但显然Chathub bard的回复是错的，即使我换一种方法再次问它这个问题，它的回答也是这样，感觉是为俄罗斯军方站台的。

**Comment by wong2** [comment]
ChatHub的回答是直接调用Bard接口的，你在Bard多问几次看看回答是否也会不一致呢？AI模型是有这样的问题

**Comment by cvladan** [comment]
That is normal for all LLM models
