### ISSUE TITLE
bing CAPTCHA 验证

### ISSUE THREAD

**Issue by ciiwhjp65** [chathub-dev/chathub#488]
User needs to solve CAPTCHA to continue.

![image](https://github.com/chathub-dev/chathub/assets/118330907/3f484a2c-a6c7-49ac-9d20-090cc0472845)

看起来这个需要一个弹窗了~

**Comment by ciiwhjp65** [comment]
试了下，还是不行，报了个Unknown error
 
















在 2023-05-26 18:00:37，"Wang Dàpéng" ***@***.***> 写道：

正好，你可以帮我试试吗，遇到这个错误的时候，打开 https://www.bing.com/turing/captcha/challenge 然后再回到ChatHub试试是不是正常了

**Comment by beanu** [comment]
遇到问题之后，打开这个页面，https://www.bing.com/turing/captcha/challenge，然后回到ChatHub在刷新一下就可以用了。

**Comment by kura-X** [comment]
> 正好，你可以帮我试试吗，遇到这个错误的时候，打开 https://www.bing.com/turing/captcha/challenge 然后再回到ChatHub试试是不是正常了

23/6/3测试通过，打开captcha页面验证通过后，回到chathub需要再刷新后可用。

**Comment by wong2** [comment]
谢谢

**Comment by hughdev** [comment]
不行了，一直通不过验证
