### ISSUE TITLE
ChatGLM WebSocket closed with reason: (1006).

### ISSUE THREAD

**Issue by Benedictum-X** [chathub-dev/chathub#489]
以下设置环境中均会出现WebSocket closed with reason: (1006).
1. 不挂梯子
2. 挂梯子，但不开启全局代理
3. 挂梯子，并且将chatglm.cn域名加入梯子的强制使用VPN通道的域名名单，但不开启全局代理

一旦开启全局代理，则可以在ChatHub中正常对话和使用。很迷，请教下原因？

**Comment by wong2** [comment]
把 lmsys.org 加入代理规则就可以了

**Comment by Benedictum-X** [comment]
已解决。感谢！
