### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by Yang-lin-09** [chathub-dev/chathub#492]
请问一下，是否有计划推出桌面端app？

**Comment by wong2** [comment]
目前没有。桌面端好处是啥呢？

**Comment by Yang-lin-09** [comment]
应该没啥好处，主要是不太习惯，用的时候要开个浏览器。

**Comment by GentlemanHu** [comment]
<img width="655" alt="image" src="https://github.com/chathub-dev/chathub/assets/34559079/cb20f3bc-6423-4ae3-88c9-333846299aa1">
不知道chrome的这种叫什么，是否extension可以直接像这样安装成APP？

**Comment by wong2** [comment]
这个叫PWA，浏览器插件不能这样

**Comment by l3ony2k** [comment]
![Snipaste_2023-05-31_05-22-59](https://github.com/chathub-dev/chathub/assets/58762081/92b5efbd-7776-4795-bad3-df48bac52e6a)

在插件启动时按上图操作新建快捷方式，然后勾选在单独窗口打开，就可以生成一个可以启动单独窗口的快捷方式，用起来和桌面应用几乎无异。效果见下图：

![Snipaste_2023-05-31_05-24-07](https://github.com/chathub-dev/chathub/assets/58762081/73bf6b53-27ed-4403-bd69-30aeaa21923d)

**Comment by wong2** [comment]
wow 还真不知道这个，这是brave独有的功能么

**Comment by l3ony2k** [comment]
我感觉所有 Chromium 系的浏览器应该都有这个功能的，记得之前 Chrome 好像也可以这么操作。

**Comment by wong2** [comment]
确实，Chrome也可以，太牛了！

**Comment by GentlemanHu** [comment]
厉害了！涨姿势了
如果extension里内置一个功能，可以一键生成快捷方式就完美了

**Comment by papagamer1970** [comment]
De hecho, Microsoft Edge Dev también puede, ¡eso es increíble!
确实,Microsoft Edge Dev也可以,太牛了!
