### ISSUE TITLE
[BUG] How to Clear Chat in the All-In-One

### ISSUE THREAD

**Issue by cvladan** [chathub-dev/chathub#493]
I would like to suggest an improvement that I think is essential to implement:

How to perform a "Clear Chat" in the "All-In-One" view.
In other words, how can I **start a new chat in all active windows at once**?
This feature may exist, but I have not found it yet.

Best regards!

> And, thank you for making this highly useful browser extension and I am a happy Premium user for this very reason.

**Comment by wong2** [comment]
For the first question, a page refresh will do the job!

**Comment by cvladan** [comment]
Hehe. Right :)
I haven't tried it because I thought it would continue old LLM conversation on page-refresh. Thank you!
