### ISSUE TITLE
New browser. License required.

### ISSUE THREAD

**Issue by zolped** [chathub-dev/chathub#511]
Hello, I've purchased the extension a few weeks ago. I've installed a new browser however I didn't save previous the license key and I do not have the email copy containing it either.

Are you able to resend the license key to the email provided during the checkout?

Email in quesiton, for reference: lemonsqueezy.gw225@simplelogin.com.

Thanks in advance.

**Comment by wong2** [comment]
How can I confirm that you're the owner of this email?

**Comment by zolped** [comment]
After you crosscheck it with your ledger, you could simply directly send the license key to the provided email OR If you'd prefer, I can directly email you to a specified address from it OR I could reply your message if you email the provided address. Whatever is easiest. Let me know how to proceed. Thanks

**Comment by wong2** [comment]
I've re-sent the receipt with license key for you.
BTW, you can always find your key here: https://app.lemonsqueezy.com/my-orders/

**Comment by zolped** [comment]
Thanks a bunch. I'll refer to the order page next time. Have a good day!
