### ISSUE TITLE
已经支付成功了升级Premium的费用，但是一直没收到激活码。可能是@gmail.com写成了@gmai.com. 请帮忙处理下。

### ISSUE THREAD

**Issue by github-antry** [chathub-dev/chathub#514]
已经支付成功了升级Premium的费用，但是一直没收到激活码。 我可能把邮箱地址写错了。 正确的邮箱地址是 antryweil@gmail.com， 支付界面提供错误的地址是antryweil@gmai.com

**Comment by wong2** [comment]
帮你退款了。请重新购买一次

**Comment by github-antry** [comment]
> 帮你退款了。请重新购买一次

好的，谢谢了
