### ISSUE TITLE
When I do a fresh clone of chathub I get a vite error 

### ISSUE THREAD

**Issue by adourish** [chathub-dev/chathub#517]
OS: Windows 10
I get the error with npm run build or yarn build
[vite:html-inline-proxy] Could not load C:Projectschathubsidepanel.html?html-proxy&inline-css&index=1.css (imported by sidepanel.html): Cannot read properties of undefined (reading '1')
error during build:
TypeError: Could not load C:Projectschathubsidepanel.html?html-proxy&inline-css&index=1.css (imported by sidepanel.html): Cannot read properties of undefined (reading '1')
    at Object.load (file:///C:/Projects/chathub/node_modules/vite/dist/node/chunks/dep-f2591f42.js:36955:65)
    at file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24656:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24556:28)
    at async file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:23744:75
    at async Queue.work (file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24766:32)

**Comment by wong2** [comment]
Did you run `yarn dev`?

**Comment by adourish** [comment]
Yes, I performed a fresh clone on two different development environments.

![image](https://github.com/chathub-dev/chathub/assets/15817797/de61abe4-101e-4672-a33d-6632b64fe1d3)

**Comment by wong2** [comment]
I'm not sure if this is related to windows... I'm building on a Mac.
