### ISSUE TITLE
已经付款了，找不到订单，邮箱、手机都没有。1179089991@qq.com

### ISSUE THREAD

**Issue by qiuaibo** [chathub-dev/chathub#519]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by qiuaibo** [comment]
如题

**Comment by wong2** [comment]
你好，在后台没有查找到对应的订单。我提交给付款服务商 lemonsqueezy 处理。

**Comment by qiuaibo** [comment]
> 你好，在后台没有查找到对应的订单。我提交给付款服务商 lemonsqueezy 处理。

![Screenshot_2023-06-01-12-19-33-92_3915bacb930634b7e206116f9dc9486f](https://github.com/chathub-dev/chathub/assets/29228484/4b53f8ba-3e0e-4fb9-a038-ad268aaa1df7)

**Comment by wong2** [comment]
好的，偶尔会出现这种问题，我已经提交给他们客服处理了

**Comment by wong2** [comment]
有新进展我会通过邮件和你沟通 🙏
