### ISSUE TITLE
Performing a yarn build - Could not load C:Projectschathubsidepanel.html?html-proxy&inline-css&index=1.css (imported by sidepanel.html): Cannot read properties of undefined (reading '1') error during build:

### ISSUE THREAD

**Issue by adourish** [chathub-dev/chathub#520]
**Describe the bug**
If you perform the following on Windows

1. git clone {chathub}
2. cd chathub
3. yarn install
4. yarn build

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A. Not building

![image](https://github.com/chathub-dev/chathub/assets/15817797/1f876f04-2114-4251-8d04-e921b3bfb555)

[vite:html-inline-proxy] Could not load C:Projectschathubsidepanel.html?html-proxy&inline-css&index=1.css (imported by sidepanel.html): Cannot read properties of undefined (reading '1')
error during build:
TypeError: Could not load C:Projectschathubsidepanel.html?html-proxy&inline-css&index=1.css (imported by sidepanel.html): Cannot read properties of undefined (reading '1')
    at Object.load (file:///C:/Projects/chathub/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:37051:65)
    at file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24656:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24556:28)
    at async file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:23744:75
    at async Queue.work (file:///C:/Projects/chathub/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24766:32)

**Comment by wong2** [comment]
Can you try with the latest code? I noticed that the vite version in your screenshot is v4.3.9, from which I've recently downgraded.

**Comment by adourish** [comment]
1. I have confirmed that it is rollup and Windows paths. If I use codespaces and a Linux terminal, it works fine. If I use Windows and a PowerShell terminal we see the error. 
2. Rollup is funky about CSS and paths. I have not figured out the line of code that has the undefined variable. 
3. It looks like yarn -> vite is swallowing any verbose error messages. 

![image](https://github.com/chathub-dev/chathub/assets/15817797/180f4fa6-1848-4b89-927d-ba27d63c3201)

**Comment by wong2** [comment]
OK

**Comment by wong2** [comment]
That's weird, I can not reproduce this. What node.js version are you using?
