### ISSUE TITLE
你好，付款成功后弹出页面错误，找不到任何激活码

### ISSUE THREAD

**Issue by iiiismile** [chathub-dev/chathub#521]
购买邮箱账号mqinghang@gmail.com
下面错误的截图，以及支付宝截图
这个问题请尽快处理，谢谢
<img width="585" alt="Snipaste_2023-06-01_19-54-00" src="https://github.com/chathub-dev/chathub/assets/33055688/3fbd9794-290f-4650-84bd-c7135b79e672">

![微信图片_20230601195647](https://github.com/chathub-dev/chathub/assets/33055688/c2afadb7-56bb-4c7f-9d93-3bc3801ebb3e)

**Comment by wong2** [comment]
收到，我把该问题提交给支付提供商 Lemon Squeezy，请等待回复

**Comment by wong2** [comment]
有新进展我会通过邮件和你沟通
