### ISSUE TITLE
能帮我换个Premium的邮箱嘛

### ISSUE THREAD

**Issue by xiaokuicui** [chathub-dev/chathub#528]

**Comment by xiaokuicui** [comment]
下单邮箱是 xiaokui.cui@gmail.com, 但是我的邮箱上不去了。帮我换成qq邮箱。xiaokui.cui@qq.com

**Comment by wong2** [comment]
你好，邮箱换不了。我可以帮你退款，然后你用qq邮箱重新购买

**Comment by xiaokuicui** [comment]
> 你好，邮箱换不了。我可以帮你退款，然后你用qq邮箱重新购买

好吧，那帮我退一下，我重新购买下

**Comment by wong2** [comment]
已退款
