### ISSUE TITLE
支付成功之后邮箱没有收到 license key

### ISSUE THREAD

**Issue by Peter1910117** [chathub-dev/chathub#541]
![微信图片_20230607151500](https://github.com/chathub-dev/chathub/assets/135809745/4141faa9-0234-48e0-bb74-5d4d75cbfc9c)
邮箱：pp920117@gmail.com

**Comment by Peter1910117** [comment]
有管理员解决一下吗？

**Comment by wong2** [comment]
收到，我已把该问题反馈给支付服务商Lemon Squeezy，请稍等回复

**Comment by Peter1910117** [comment]
好的，实在不行把那笔退了我重新付

Wang Dàpéng ***@***.***> 于2023年6月8日周四 10:58写道：

**Comment by wong2** [comment]
这个问题麻烦在我这边看不到这笔订单，所以也没办法给你退款，只能找他们客服帮忙。之前也出现过几次，是可以解决的

**Comment by wong2** [comment]
客服回复已解决
