### ISSUE TITLE
请问，为什么除了火星，其他的用不了呢？（Claude、Chatglm）

### ISSUE THREAD

**Issue by k0000100** [chathub-dev/chathub#542]
如题

**Comment by wong2** [comment]
具体什么表现

**Comment by k0000100** [comment]
讯飞星火可以用，GPT 3 我没API就没管了，BING和BARD 我也没管。可是 Claude 和 ChatGLM 我都是在他们自己的网站上正常使用。在 chathub 上提示 WebSocket closed with reason:  (1006).

**Comment by wong2** [comment]
Claude和ChatGLM的网站分别指的是？

**Comment by k0000100** [comment]
或者说，Claude 和 Chatglm 要怎么样才能用？总之就是提示 WebSocket closed with reason: (1006).

**Comment by wong2** [comment]
如果没翻墙的话，可以先翻墙试试（全局模式）

**Comment by k0000100** [comment]
有翻墙，Claude和 Chatglm 都可以使用。只是在 Chathub上用不了

**Comment by wong2** [comment]
ChatHub里，Claude调用的是 https://poe.com，ChatGLM调用的是 https://chat.lmsys.org，都不是官网。
所以我想问你说在他们的网站上指的具体是什么网站？

**Comment by k0000100** [comment]
哦哦，那我不太懂。我是在Slack上加载Claude应用来体验的。Chatglm就是chatglm.cn 上体验的

**Comment by k0000100** [comment]
明白了谢谢

**Comment by wong2** [comment]
可以使用了吗？

**Comment by k0000100** [comment]
不行




k0000100
***@***.***







                       
原始邮件
                       
                     

发件人："Wang Dàpéng"< ***@***.*** &gt;;

发件时间：2023/6/7 17:55

收件人："chathub-dev/chathub"< ***@***.*** &gt;;

抄送人："k0000100"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [chathub-dev/chathub] 请问，为什么除了火星，其他的用不了呢？（Claude、Chatglm） (Issue #542)




 
可以使用了吗？
 
&mdash;
