### ISSUE TITLE
环境变量 不应该在源代码里面吗？？？？

### ISSUE THREAD

**Issue by hieivip** [chathub-dev/chathub#549]
![image](https://github.com/chathub-dev/chathub/assets/54146330/59f35e63-d75d-490a-a4a7-d1f61b94ff48)
源码里面不应该有这些环境变量吗？？？？

**Comment by wong2** [comment]
你这是啥项目，跟ChatHub有什么关系呢？

打很多问号很没有礼貌

**Comment by hieivip** [comment]
![image](https://github.com/chathub-dev/chathub/assets/54146330/ddcf78f5-f2a1-41a5-9b04-30012568df73)
这些不是环境变量吗？

**Comment by hieivip** [comment]
我说 如何修改这个项目ChatGPT 的模型 和 openai  api地址

**Comment by hieivip** [comment]
我的意思是 源码里面是不是没有配置 chatGPT API 地址 还有 key  和 模型的地方

**Comment by wong2** [comment]
源码里没有，你是不是把这个项目和别的项目搞混了哥

**Comment by hieivip** [comment]
> 源码里没有，你是不是把这个项目和别的项目搞混了哥

没有呀，我可以配置这个项目，我只是举个例子；   因为我不想通过页面配置参数；

**Comment by wong2** [comment]
不能，不支持，只能在页面里配置

**Comment by hieivip** [comment]
既然页面可以配置，那就是源码里面肯定是也是可以配置的。
