### ISSUE TITLE
多个All in one 窗口，不需要反复设置。

### ISSUE THREAD

**Issue by lewisteh88** [chathub-dev/chathub#550]
首先我已经购买了premium，感谢做出了如此好用的应用。
这次想问，可否增加可以拥有多个All in one 的直接可点击窗口呢？

比如其中一个是 3 in one. 
再另一个是 2 in one.
之间一键点击切换，不需要进入设置。

用意就是有时候我可能需要3个AI 的回复，那我就使用3 in one，换来的是牺牲可读内容的范围。
但也有些时候需要的是更大的可读空间来展示内容，而选择使用2 in one。

但是这种来回切换必须进入设置的步骤显得很麻烦。

**Comment by wong2** [comment]
很有道理！

**Comment by wong2** [comment]
<img width="1754" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/5727a1e6-eadb-4255-a210-18ad58954ac8">

下个版本实现了此功能
