### ISSUE TITLE
购买后，没有收到激活LICENSE

### ISSUE THREAD

**Issue by lshdavid** [chathub-dev/chathub#556]
购买后，没有收到激活LICENSE。我的购买邮箱是：liush@smm.neu.edu.cn.

**Comment by wong2** [comment]
5月24日购买的？我重新给你发了一下，请查收，垃圾邮箱也检查一下

**Comment by lshdavid** [comment]
什么情况？我付了款，过去这么长时间都没收到激活码？我邮箱liush@smm.neu.edu.cn. 目前为止，也没人联系我。

**Comment by lshdavid** [comment]
抱歉，刚看到你回复了。我检查下邮箱。

**Comment by lshdavid** [comment]
输入激活码后，好像界面没啥变化？

**Comment by lshdavid** [comment]
chatgpt也用不了，显示OpenAI API key not set。

**Comment by lshdavid** [comment]
输入激活码若干次，没有激活成功。操作是直接复制激活码，然后粘贴进那个激活框里面。
