### ISSUE TITLE
Bing chat回复存在问题，经常表示无法理解问题/上下文

### ISSUE THREAD

**Issue by Silypie** [chathub-dev/chathub#558]
我已经遇到过很多次这个问题：同一个question，直接在Bing chat官方页面能得到详细的回复，但是在chathub中使用Bing经常得不到有效回复。
会话风格：Balanced
这里简单给一个例子：
![Imgur](https://i.imgur.com/M5d0VtW.png)
![](https://i.imgur.com/rStrTat.png)

**Comment by Bian-Sh** [comment]
收到

**Comment by wong2** [comment]
为啥关了呀

**Comment by wong2** [comment]
大语言模型的输出是有随机性的
