### ISSUE TITLE
Misread Features.

### ISSUE THREAD

**Issue by Ghopop** [chathub-dev/chathub#559]
你好，我之前购买了你们的高级功能，但我误解了并以为我可以使用GPT。然而，我意识到我实际上需要购买API。我想问一下是否有可能退还我的购买款项。谢谢。

这是我的电子邮件地址 eltenwellingtonnoises@gmail.com，付款日期为2023年6月1日。

**Comment by wong2** [comment]
没有查到这个邮箱对应的订单，你确定是这个邮箱购买的吗

**Comment by Ghopop** [comment]
我拼写错误了电子邮件，非常抱歉，这是正确的电子邮件。eltenwellimgtonnoises@gmail.com
