### ISSUE TITLE
bing报错Unexpected end of JSON input

### ISSUE THREAD

**Issue by zhw883** [chathub-dev/chathub#56]
大佬，插件在chrome和edge里测试都报Unexpected end of JSON input这个错误

**Comment by zhw883** [comment]
<img width="859" alt="1678774866966" src="https://user-images.githubusercontent.com/127825266/224913196-533c3303-e5a4-47c0-8c80-dcc08a5653bd.png">

**Comment by wong2** [comment]
奇怪 🤔
你在bing.com能用吗？
