### ISSUE TITLE
突然出现如此报错 应该如何解决

### ISSUE THREAD

**Issue by Lw520Y** [chathub-dev/chathub#560]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

使用插件的页面上报错，但是在官网的chat页面是正常回答交流的

**Comment by wong2** [comment]
应该是插件用了API模式吧？这个报错的意思是你的OpenAI API额度没了（可能是没绑信用卡），可以在这里查看：https://platform.openai.com/account/billing/overview

如果不想绑信用卡，你可以在ChatHub里改成webapp模式使用

**Comment by Lw520Y** [comment]
非常感谢 确实使用了自己的key 账号额度过期了
