### ISSUE TITLE
Misread Features.

### ISSUE THREAD

**Issue by Ghopop** [chathub-dev/chathub#561]
没有查到这个邮箱对应的订单，你确定是这个邮箱购买的吗

_Originally posted by @wong2 in https://github.com/chathub-dev/chathub/issues/559#issuecomment-1586496382_
            

我拼写错误了我的电子邮件，对此我表示歉意。正确的电子邮件是eltenwellimgtonnoises@gmail.com 付款日期是2023年6月1日。

**Comment by wong2** [comment]
done
