### ISSUE TITLE
Can not compile from source version 1.20.9

### ISSUE THREAD

**Issue by tamchuen** [chathub-dev/chathub#564]
**Describe the bug**
I installed node.js 18.x 64 bit and yarn 1.22.19.
And there is following error message while running "yarn build":
"[vite:html-inline-proxy] Could not load E:Developmentchathubsrc-1.20.9sidepanel.html?html-proxy&inline-css&index=1.css (imported by sidepanel.html): Cannot read properties of undefined (reading '1')". 

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Edition
 - Browser : Chrome

**Comment by wong2** [comment]
Please downgrade vite to 4.2

**Comment by tamchuen** [comment]
I tried downgrading to both vite 4.2.3 and 4.2.0, but still it did not compile.
Here are the commands that I tried:

npm uninstall vite
npm install vite@4.2.0 -D 
npm cache clean --force
yarn build

also

npm uninstall vite
npm install vite@4.2.3 -D 
npm cache clean --force
yarn build
