### ISSUE TITLE
Manage activations

### ISSUE THREAD

**Issue by DRYN07** [chathub-dev/chathub#568]
I haven't bought it yet, sorry if this is obvious after buying. Is there any page to manage activated licenses? I bought an extension once and after I used the x device activation, the extension become useless and there was no way to deactivate previous devices. And all I did was reinstall my computers and reactivate the app... So before I buy this, it would be good to know whether I can manage my activations or not. 

Thanks :)

**Comment by wong2** [comment]
Yes: https://app.lemonsqueezy.com/my-orders/
