### ISSUE TITLE
bing 回答一半报错

### ISSUE THREAD

**Issue by wkx160312746** [chathub-dev/chathub#57]
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by wong2** [comment]
可以截个图吗

**Comment by 15908282204** [comment]
> 
![c080aa2092391ffd53813acb716dfd8](https://user-images.githubusercontent.com/132135088/235389441-38e2368c-db44-4ac7-94a6-aef3001faf02.png)
