### ISSUE TITLE
chatgpt api-key 设置后问答稍长就会 network error

### ISSUE THREAD

**Issue by Seolen** [chathub-dev/chathub#574]
**Describe the bug**
chatgpt api-key 设置后问答稍长就会 network error， 请问该如何解决呢？
即使指令 continue 也无法继续

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
有没有例子给我试试？

**Comment by Seolen** [comment]
Example 1:
I have two tensors, one is A with shape (M, 26) and the other B with shape (M, 1), now I want to add B to A, but only on the max value of A in the second dimension. Describe what each step in the code does.

Example 2:
I want to scale up the score tensor, which is calculated after sigmoid. any suggestions.

可以尝试下能否复现，不排除确实是某时间段的网络问题。

**Comment by wong2** [comment]
看来比较可能是网络问题
