### ISSUE TITLE
希望添加gpt-3.5-turbo-0613和gpt-3.5-turbo-16k选项

### ISSUE THREAD

**Issue by DDesperate** [chathub-dev/chathub#575]
![image](https://github.com/chathub-dev/chathub/assets/27850609/67c33adc-c9c7-4477-962f-101011bd2f43)
![image](https://github.com/chathub-dev/chathub/assets/27850609/e1f53391-b694-4a0a-ad5c-89df3dee7fef)

**Comment by wong2** [comment]
最新版已添加 gpt-3.5-turbo-16k，回头换一下 gpt-3.5-turbo-0613
