### ISSUE TITLE
请问Azure Mode的参数该怎么填写？

### ISSUE THREAD

**Issue by JackieIris** [chathub-dev/chathub#576]
除了Azure API Key这个参数，另外两个参数该怎么填写？

![1](https://github.com/chathub-dev/chathub/assets/25077102/b4c7d12d-dac9-4827-a277-a4162ffd8b0c)

**Comment by wong2** [comment]
**Instance Name:**
<img width="973" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/864a12b9-4a11-4ce8-895d-cde8a83e4ecc">

**Deployment Name:**
<img width="620" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/7993a7d4-f6c7-4a8a-bd46-cfd6d2984a9f">

**Comment by JackieIris** [comment]
谢谢！
