### ISSUE TITLE
讯飞星火的访问被拦截

### ISSUE THREAD

**Issue by Leoqkk** [chathub-dev/chathub#577]
在chathub中访问讯飞星火访问被拦截
会话中显示“当前请求已被拦截，请完成验证后重试”
在讯飞星火的的网页端中可正常使用。
个人无法找到验证入口

**Comment by wong2** [comment]
我这边是，遇到这个情况后，在讯飞网页端聊一句，回到ChatHub里就恢复了

**Comment by Leoqkk** [comment]
已解决，谢谢！
