### ISSUE TITLE
Bing is not available:Forbidden: Sorry, you are not allowed to access this service.

### ISSUE THREAD

**Issue by wv2022** [chathub-dev/chathub#58]
![image](https://user-images.githubusercontent.com/103087689/224932605-630250c4-433a-4ccb-8395-933251a910cb.png)

**Comment by wong2** [comment]
这说明没有new Bing的资格，请去 https://bing.com/new 加入 waitlist

**Comment by wv2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
