### ISSUE TITLE
改一下配色

### ISSUE THREAD

**Issue by naive231** [chathub-dev/chathub#581]
連結的配色不曉得為什麼要用深藍色，看改成用「底線」會不會比較清楚：

![image](https://github.com/chathub-dev/chathub/assets/650107/38c964c5-c1cc-4ea7-973f-9861b4df1565)

**Comment by wong2** [comment]
会优化一下

**Comment by naive231** [comment]
感謝～👍

**Comment by wong2** [comment]
Fixed in next version
