### ISSUE TITLE
gpt4 browsing 用不了了

### ISSUE THREAD

**Issue by luokebi** [chathub-dev/chathub#592]
**Describe the bug**
如题
**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser: chrome

**Comment by napoleon9000** [comment]
Run into the same problem. All  options stopped working for ChatGPT web mode.

Error message: {"detail":"Our systems have detected unusual activity from your system. Please try again later."}

**Comment by wong2** [comment]
Yeah, OpenAI upgraded their verification system for GPT-4 models.
Please upgrade ChatHub to latest version (v1.23.5), which brings gpt-4 model back, but gpt-4-browsing is not recovered yet.

**Comment by napoleon9000** [comment]
> Yeah, OpenAI upgraded their verification system for GPT-4 models. Please upgrade ChatHub to latest version (v1.23.5), which brings gpt-4 model back, but gpt-4-browsing is not recovered yet.

Works in 1.23.5. Thanks!
