### ISSUE TITLE
能否带回Sydney呢？

### ISSUE THREAD

**Issue by Sissidark** [chathub-dev/chathub#593]
能否和另一个项目一样，解除bing的限制，并且解锁Sydney
项目地址：
https://github.com/waylaidwanderer/node-chatgpt-api

**Comment by kaz875** [comment]
[node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api) used system prompt injection of a system role and used the context summary endpoint which limits your context length to just 3k tokens (I tested this myself) so it causes a lot of limitations. 

那个其实也不是原生的 Syndey只是模仿的.
