### ISSUE TITLE
GPT4的所有模型显示错误：{"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}

### ISSUE THREAD

**Issue by YEAHHEYE** [chathub-dev/chathub#595]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by ghitaNE** [comment]
Steps to reproduce the bug :
1. send message using 3.5 GPT 
2. go to settings
3. change model to GPT-4
4. go back to conversion send another message

it returns thsi error : 

{"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}

**Comment by wong2** [comment]
Related discussion: https://github.com/acheong08/ChatGPT/issues/1431

**Comment by wong2** [comment]
Fixed in Chathub v1.24.0
