### ISSUE TITLE
Only chatgpt, Claude, Bing and bard are working other chatbots not working 

### ISSUE THREAD

**Issue by Vickyitsmeee** [chathub-dev/chathub#597]
**Describe the bug**
Only chatgpt, claude, Bing and bard are working all other chatbot not working 

**laptop*
 - OS: Windows 10
 - Browser Google Chrome, Microsoft edge

**Comment by wong2** [comment]
Try this: open https://chat.lmsys.org/ in your browser, then go back to ChatHub

**Comment by Vickyitsmeee** [comment]
> Try this: open https://chat.lmsys.org/ in your browser, then go back to ChatHub

https://chat.lmsys.org/ is not opening

**Comment by wong2** [comment]
@Vickyitsmeee Where are you located?

**Comment by Vickyitsmeee** [comment]
> @Vickyitsmeee Where are you located?

Accra, Ghana

**Comment by wong2** [comment]
@Vickyitsmeee I think maybe you need to use VPN to access lmsys.org services.

**Comment by Vickyitsmeee** [comment]
> @Vickyitsmeee I think maybe you need to use VPN to access lmsys.org services.

I

> > Try this: open https://chat.lmsys.org/ in your browser, then go back to ChatHub
> 
> https://chat.lmsys.org/ is not opening

It is working now, fantastic, Thank you👏👍

**Comment by Pwoerlevel** [comment]
> Try this: open https://chat.lmsys.org/ in your browser, then go back to ChatHub

thank you man
