### ISSUE TITLE
精简界面：请把“主题”和“多合一个数选择”界面放在设置里

### ISSUE THREAD

**Issue by Ribaru** [chathub-dev/chathub#600]
请把“主题”和“多合一个数选择”界面放在设置里，因为“主题”和“多合一个数选择”一旦设定好，并不会频繁改动。

这样臃肿的主界面能回归从前的简约。

谢谢！

**Comment by wong2** [comment]
也有用户希望可以这样快速切换不同模式 https://github.com/chathub-dev/chathub/issues/550

**Comment by Ribaru** [comment]
> 

这样啊，每个人的需求是如此的不同啊，

那么是否可以在”设置“里增加一个选项，能够自主选择显示和隐藏哪些按钮？感谢

**Comment by Ribaru** [comment]
> 

侧边收起以后，依然会显示”主题“图标欸。
感谢。

**Comment by wong2** [comment]
😂 这个也不想看到吗

**Comment by wong2** [comment]
好的，下一版把主题图标也隐藏掉

**Comment by Ribaru** [comment]
> 好的，下一版把主题图标也隐藏掉

感谢^_^
