### ISSUE TITLE
{"error":{"code":"DeploymentNotFound","message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

### ISSUE THREAD

**Issue by namezzy** [chathub-dev/chathub#601]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser \: Microsoft EDGE

我使用的是Azure的OpenAI 然后自定义域名之前一直用着好好的，现在突然出现这个问题了,我在手机端可以正常使用(和chathub使用的是一个)
{"error":{"code":"DeploymentNotFound","message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

辛苦帮忙看一下，感谢！

![image](https://github.com/chathub-dev/chathub/assets/26276606/892e3031-8264-4dd2-aafc-e10b5899dad3)

**Comment by wong2** [comment]
Azure应该用Azure Mode呀？

**Comment by wong2** [comment]
还是说你对Azure API做了代理？

**Comment by namezzy** [comment]
感谢您的回复，我是对Azure API 进行了代理，在其他平台都可以正常使用。就是突然在您开发的Chathub 突然报错了（其实上周的时候报错了一次，我把chathub给重装之后又好了）

**Comment by namezzy** [comment]
这次重装之后也不好用哈

**Comment by wong2** [comment]
方便把你的API Host发给我调试一下吗？我的邮箱：wonderfuly@gmail.com

**Comment by namezzy** [comment]
已发送 谢谢您啊

**Comment by wong2** [comment]
你的代理是使用了哪个开源项目吗？可以发我看看不

**Comment by namezzy** [comment]
> 你的代理是使用了哪个开源项目吗？可以发我看看不

https://github.com/hbsgithub/deno-azure-openai-proxy  
我用的这个，辛苦您了。

**Comment by wong2** [comment]
我建议你在ChatHub里用Azure Mode，具体参数怎么填可以看这个：https://github.com/chathub-dev/chathub/issues/576#issuecomment-1594046245
