### ISSUE TITLE
能不能在all in one窗口中单独对某个model连续对话时光标不要跳转回底部

### ISSUE THREAD

**Issue by lyjpaul** [chathub-dev/chathub#602]
目前对all in one的几个模型提问之后，如果某个模型回答明显更好，一般回直接在该模型下面连续对话，经常打字打着打着，其他某个模型终于完成了回答（尤其是newbing经常最卡最慢），光标会突然跳转回底部，能否增加一个选项控制或者直接让光标不要突然眺回去？我鼠标选中在哪个对话框就最好一直在那个对话框。

**Comment by wong2** [comment]
Fixed in v1.24.2
