### ISSUE TITLE
付费之后一直不能使用，半个月了，所有模型完全无法使用

### ISSUE THREAD

**Issue by JuneNLSS** [chathub-dev/chathub#603]
**Describe the bug**
付费之后一直不能使用，半个月了，所有模型完全无法使用，一直在转但是一直不给出答复，单选某个模型也是一样，完全没反应。开着梯子和不用梯子，都无法使用。
![1687787947292](https://github.com/chathub-dev/chathub/assets/105905130/5897f6ad-5999-43c8-b5ec-f49c25e40e0e)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [echrome, brave]

**Comment by wong2** [comment]
ChatGPT也不行吗？截图看看？

**Comment by wong2** [comment]
发下购买邮箱，我帮你退款

**Comment by JuneNLSS** [comment]
> 发下购买邮箱，我帮你退款

xianyx0815@163.com

**Comment by JuneNLSS** [comment]
> 发下购买邮箱，我帮你退款

谢谢，如果退款或修复，烦请回复
