### ISSUE TITLE
Bard not working at all

### ISSUE THREAD

**Issue by taishi55** [chathub-dev/chathub#604]
**Describe the bug**
The response for Bard is currently `Cannot read properties of null (reading '0')` I think Google changed something. 

**Desktop (please complete the following information):**
 - OS: Mac & Windows (I tried both)
 - Browser: Chrome & Brave (I tried both)

**Comment by kaz875** [comment]
+1 it was working yesterday still but it stopped today. Also Bing Chat is less stable (although it works at a few shots in a clean session) running into websocket close error a lot.

**Comment by kaz875** [comment]
I looked into this issue a bit, these two fixes from another chatbot project may help): 

Issue post: 
https://github.com/sunner/ChatALL/issues/161

(recent)
https://github.com/sunner/ChatALL/commit/f64c8669fbbf2501e2ac8d7a531b46819db3b339

(earlier)
https://github.com/sunner/ChatALL/commit/47bfbb483c79f30e7330dfc3e1a438e5dae4f14b

That earlier issue above is very similar to what we run into. It seems to happen when the chat starts. Could be possible this time it's a different issue.

**Comment by acneupane** [comment]
> +1 it was working yesterday still but it stopped today. Also Bing Chat is less stable (although it works at a few shots in a clean session) running into websocket close error a lot.

Experiencing the same for both.

**Comment by taishi55** [comment]
it should be `let text = payload[4][0][1][0] as string;` on `bard/api.ts`

**Comment by wong2** [comment]
Fixed in https://github.com/chathub-dev/chathub/commit/a3a945aad0e1c0069cf13727404d83fd0a38acf3

**Comment by wong2** [comment]
https://github.com/chathub-dev/chathub/releases/tag/v1.24.1

**Comment by wong2** [comment]
Released to Chrome web store
