### ISSUE TITLE
Bard可以单独使用，但在chathub中报错

### ISSUE THREAD

**Issue by kura-X** [chathub-dev/chathub#609]
**Describe the bug**
Only Google bard in chathub cannot be used, error message:` Failed to fetch (https://bard.google.com/faq)` but opening the bard page alone can be used normally.

**Desktop (please complete the following information):**
 - OS: Windows11
 - Microsoft Edge版本 114.0.1823.58 (正式版本) (64 位)
 - chatHbub v1.24 from edge store

![image](https://github.com/chathub-dev/chathub/assets/11145578/0738a4ef-3bc3-4bb1-8e72-efb09cd02521)

image：bard  can be used normally.
![image](https://github.com/chathub-dev/chathub/assets/11145578/61605c22-a447-495c-9190-83fd43c0deec)

**Comment by wong2** [comment]
请从chrome商店安装最新版，修复了这个问题
