### ISSUE TITLE
希望增加claude v1.3 100K模型

### ISSUE THREAD

**Issue by moxi000** [chathub-dev/chathub#610]
如题，希望增加几个claude的新模型，包括1.3和1.3 100K

**Comment by wong2** [comment]
指API模式吗？

**Comment by moxi000** [comment]
> 

当然是，poe的claude没有1.3

**Comment by wong2** [comment]
应该不需要指定1.3这种小版本号，默认用的就是最新的

**Comment by moxi000** [comment]
> 

似乎不是这样，目前claude官方的接口仍然提供1.0，例如poe使用的就是，我查了源代码，调用的是1.0

**Comment by wong2** [comment]
> 我查了源代码，调用的是1.0
这个是指poe么？那和我们说的API调用没有关系呀

**Comment by moxi000** [comment]
> 

export enum ClaudeAPIModel {
  'claude-instant-v1' = 'claude-instant-v1',
  'claude-v1' = 'claude-v1',
  'claude-v1-100k' = 'claude-v1-100k',
  'claude-instant-v1-100k' = 'claude-instant-v1-100k',
}
向api传递的参数中，若要使用1.3模型，需要传递model参数为 claude-v1.3-100k，例如：
                    response = c.completion_stream(
                        prompt=conversation,
                        stop_sequences=[anthropic.HUMAN_PROMPT],
                        max_tokens_to_sample="100000",
                        model="claude-v1.3-100k",
                        stream=True,
                    )
                    
传递参数为v1，用的是1.0的接口。
你是插件开发者吗

**Comment by wong2** [comment]
不知道你能不能明白，1 不等于 1.0 

<img width="494" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/e77bb1d4-c69f-4724-aaa2-b2309a1e6317">

也就是说，当我们使用 v1 的时候，是在用 v1 的最新版本，当前就是 1.3；后面如果发布了 1.4，使用 v1 就相当于使用 1.4。指定具体的小版本号是使用旧版模型才需要的。

**Comment by moxi000** [comment]
> 不知道你能不能明白，1 不等于 1.0
> 
> <img alt="image" width="494" src="https://user-images.githubusercontent.com/321947/249381501-e77bb1d4-c69f-4724-aaa2-b2309a1e6317.png">
> 也就是说，当我们使用 v1 的时候，是在用 v1 的最新版本，当前就是 1.3；后面如果发布了 1.4，使用 v1 就相当于使用 1.4。指定具体的小版本号是使用旧版模型才需要的。

我才发现官方这两天更新了接口，你说的对，现在会自动使用最新版的接口。
