### ISSUE TITLE
Stablellm not working 

### ISSUE THREAD

**Issue by Vickyitsmeee** [chathub-dev/chathub#611]
**Describe the bug**
Stablellm gives an error to check network connection and refresh the page .

**Laptop
 - OS: windows10
 - Browser Google Chrome and Microsoft edge

**Comment by wong2** [comment]
Where are you located?

**Comment by Vickyitsmeee** [comment]
> Where are you located?

Accra, Ghana

**Comment by wong2** [comment]
I see, please use a vpn
