### ISSUE TITLE
不认GPT-4 API key

### ISSUE THREAD

**Issue by BrianZ96** [chathub-dev/chathub#614]
**Describe the bug**
请问我拥有GPT-4 API的使用权限，并且在设置里也设置好了，选中了model是GPT-4，为什么当我问are you GPT-4这个问题的时候，他却回答As of my last training data in September 2021, the latest iteration was GPT-3. I do not have any updates or additional information about newer versions like GPT-4.呢？

**Comment by wong2** [comment]
GPT-4 是会说自己是 GPT-3 的
