### ISSUE TITLE
讯飞星火的访问被拦截，进web版聊一句切回来还是被拦截

### ISSUE THREAD

**Issue by limars874** [chathub-dev/chathub#615]
**Describe the bug**
如题。我按之前issue里面提的解决方案，没得效果，不知道只是我的问题还是都这样？
另外好奇问一句，讯飞星火那个网页禁止谷歌浏览器f12开发者工具，有办法破解吗？

**Desktop (please complete the following information):**
 - windows 10
 - Browser [chrome]

**Comment by wong2** [comment]
估计是有某种频率限制
