### ISSUE TITLE
Chatgpt webapp mode has not been working for a long time

### ISSUE THREAD

**Issue by oceanpx** [chathub-dev/chathub#617]
**Describe the bug**
Chatgpt webapp mode has not been working for a long time at least for two weeks. I tried to reboot computer, reinstall the extension. It is just frozen forever. The API mode works well. 

**Desktop (please complete the following information):**
Mac
Google Chrome

**Comment by wong2** [comment]
Can you post a screenshot?

**Comment by oceanpx** [comment]
Here is the screenshot. 
<img width="2180" alt="image" src="https://github.com/chathub-dev/chathub/assets/50639233/e915d03b-6a79-4cba-90ea-dbb1e3a2e63d">

**Comment by oceanpx** [comment]
Updates: I tried again and again to reboot the computer, it is working again now. I have no idea about how the problem is solved. I will follow up and let you know if this happens again.

**Comment by wong2** [comment]
Thanks, I will also check it out

**Comment by Tas667** [comment]
any chances this has ben solved? i got exactly the same issue

**Comment by wong2** [comment]
Please upgrade to v1.42.2 https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma?utm_source=chathub.gg
