### ISSUE TITLE
【问题已经解决】 1.4.1版 Service Worker （无效）

### ISSUE THREAD

**Issue by merlinxdyang** [chathub-dev/chathub#62]
错误显示"service_worker": "src/background/index.ts"

**Comment by yahoowind** [comment]
我的安装完1.4版本也是这个错误。

**Comment by wong2** [comment]
怎么装的呢？要从release下载安装，而不是源码直接安装

**Comment by merlinxdyang** [comment]
> 

原来如此，问题解决，谢谢！

**Comment by yahoowind** [comment]
我是通过下载release安装的，这样的是正常的吗？[image: 1678859079240.png]

Wang Dàpéng ***@***.***> 于2023年3月15日周三 10:54写道：

**Comment by wangwangdalibaohahaha** [comment]
> > 
> 
> 原来如此，问题解决，谢谢！

从哪里下载？

**Comment by wangwangdalibaohahaha** [comment]
> 怎么装的呢？要从release下载安装，而不是源码直接安装

这个要从哪里下载呢？

**Comment by wong2** [comment]
Release 在这里：https://github.com/chathub-dev/chathub/releases
