### ISSUE TITLE
自用得chatgpt API,突然报错，这个如何处理

### ISSUE THREAD

**Issue by dipixiaoliumang** [chathub-dev/chathub#622]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by wong2** [comment]
可能你的免费额度到期了，去 https://platform.openai.com/account/billing/overview 检查一下

**Comment by dipixiaoliumang** [comment]
> 
好的，免费得到期了是不是只能绑卡，如果没有国外得信用卡，是不是只能重新买个新得账号使用~

**Comment by wong2** [comment]
可以研究下虚拟信用卡

**Comment by dipixiaoliumang** [comment]
> 可能你的免费额度到期了，去 https://platform.openai.com/account/billing/overview 检查一下




> 可以研究下虚拟信用卡

感谢~我去看看~

**Comment by wong2** [comment]
时区不同
