### ISSUE TITLE
Please add a "Clear All" button for "All-in-one" mode

### ISSUE THREAD

**Issue by pabloh84** [chathub-dev/chathub#624]
Title says it all!!! 

Keep up the good work! :-)

**Comment by wong2** [comment]
I will consider that. For now, you can do that by refresh the page.

**Comment by insign** [comment]
This is a must. E most original service page has this too.

**Comment by djmoore711** [comment]
_I come here to request the same feature._ 

I had not considered refreshing the page, but I believe a "**clear all**" button (or something of that sort) would be far more intuitive from a user experience standpoint. 

:+1:
