### ISSUE TITLE
购入付费会员前后，都显示超过配额

### ISSUE THREAD

**Issue by SYLIVIA-RUI** [chathub-dev/chathub#625]
对话显示
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by SYLIVIA-RUI** [comment]
![image](https://github.com/chathub-dev/chathub/assets/138375096/592c333e-e384-41ba-a763-ac79f19ff720)

**Comment by wong2** [comment]
这个是ChatGPT API的限额，你需要打开 https://platform.openai.com/account/billing/overview 检查一下

**Comment by SYLIVIA-RUI** [comment]
我没有梯子···现在去弄一下，谢谢

**Comment by SYLIVIA-RUI** [comment]
> 这个是ChatGPT API的限额，你需要打开 https://platform.openai.com/account/billing/overview 检查一下

我没有梯子···现在去弄一下，谢谢

**Comment by wong2** [comment]
可以问下你是从哪里了解到ChatHub的吗？

**Comment by SYLIVIA-RUI** [comment]
> 可以问下你是从哪里了解到ChatHub的吗？
我说我查学术方面想用，然后朋友找给我的
