### ISSUE TITLE
填写chatgpt api key导致chatgpt账号被封。。。

### ISSUE THREAD

**Issue by imwx** [chathub-dev/chathub#63]
说是用于商业用途

**Comment by imwx** [comment]
你玩什么，见不得说缺点是么，开发的东西当宝贝供着？

**Comment by wong2** [comment]
因为不可能是因为使用chathub导致账号被封

**Comment by imwx** [comment]
只能对你呵呵，chatgpt不翻根本上不去，我最近完全没访问过，只在前天用你的插件，填了一下api key，立马就收有邮件了。原因可能的确不是你的插件，而是openai封禁中国ip。但是最好关掉这个功能，因为中国用户本来访问不了，账号反倒没事，通过你的插件填了，通了，账号就倒霉了。

**Comment by wong2** [comment]
那你不如写信劝openai不要封禁中国ip 😅

**Comment by imwx** [comment]
掩耳盗铃吧

**Comment by imwx** [comment]
麻烦你自己看看chrome商店的评价，多谢你开放这个功能，导致很多人账号被封了
