### ISSUE TITLE
{"detail":"Our systems have detected unusual activity from your system. Please try again later."}

### ISSUE THREAD

**Issue by sgws388999** [chathub-dev/chathub#631]
{"detail":"Our systems have detected unusual activity from your system. Please try again later."} 怎么解决呀？

**Comment by PhillipRt** [comment]
@wong2 check out this repo, this guy managed to reverse engineer the mobile bot detection and his addon never gets this issue since version 4.0 https://github.com/saeedezzati/superpower-chatgpt

**Comment by wong2** [comment]
I believe ChatHub also solved this issue. Are you still facing it?

**Comment by ihugoal** [comment]
same issue, cannot use chatgpt...

**Comment by wong2** [comment]
@ihugoal Which model are you using?

**Comment by kura-X** [comment]
@wong2 
same problem.


OS: Windows11，
Microsoft Edge版本版本 114.0.1823.67 (正式版本) (64 位)
chatHbub v1.26.1 from chrome store

Error when using GPT4，GPT-3.5 has no such error message

![image](https://github.com/chathub-dev/chathub/assets/11145578/049e0d1e-989d-4db3-98b0-34f1820052b2)

**Comment by wong2** [comment]
@kura-X Please try again.

**Comment by kura-X** [comment]
> @kura-X Please try again.
Still having this problem intermittently

**Comment by mohalikeyou** [comment]
相同的问题，使用的是chatGPT web版，GPT4.
OS为最新版的Windows11， 插件为最新版，使用的是clash for windows代理
我该如何解决？

**Comment by wong2** [comment]
I've found a solution to this issue and is implementing it

**Comment by mohalikeyou** [comment]
> I've found a solution to this issue and is implementing it
Thank you so much!

**Comment by mohalikeyou** [comment]
> I've found a solution to this issue and is implementing it

Thank you so much!

**Comment by wong2** [comment]
v1.27.0 published to Chrome Web Store, please give it a try!

**Comment by mohalikeyou** [comment]
> v1.27.0 published to Chrome Web Store, please give it a try!

I have used it for twos day, no problem found.Thanks!

**Comment by mohalikeyou** [comment]
> v1.27.0 published to Chrome Web Store, please give it a try!

I have used it for two days, no problem found, thanks!
