### ISSUE TITLE
购买后无法收到激活码

### ISSUE THREAD

**Issue by VeakizZ** [chathub-dev/chathub#633]
我的邮箱是VeakizZ@proton.me

**Comment by wong2** [comment]
Can you provide a screenshot of your purchase?

**Comment by VeakizZ** [comment]
![Uploading mmexport1688631724325.jpg…]()

**Comment by VeakizZ** [comment]
![Uploading mmexport1688631724325.jpg…]()

**Comment by wong2** [comment]
Picture broken. But not problem, I'll contact the payment provider Lemonsqueezy for this issue.

**Comment by VeakizZ** [comment]
好的 谢谢

**Comment by VeakizZ** [comment]
大概什么时候能好

**Comment by wong2** [comment]
这个不一定，要等他们客服的回复。等有消息我发你邮件
