### ISSUE TITLE
I did not receive an email with my lisence key.

### ISSUE THREAD

**Issue by WanzerJ** [chathub-dev/chathub#635]
I paid through WeChat, but did not receive my lisence key.
My email is 1174962774@qq.com.

**Comment by wong2** [comment]
I have resent you the license. Also check the spam folder.

**Comment by WanzerJ** [comment]
I can receive this email from you, but I can’t receive the email with Lisence Key。
Can you try sending it to another email address?
***@***.***




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "chathub-dev/chathub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月6日(星期四) 晚上11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chathub-dev/chathub] I did not receive an email with my lisence key. (Issue #635)





 
I have resent you the license. Also check the spam folder.

**Comment by WanzerJ** [comment]
还是没用。

**Comment by wong2** [comment]
请检查垃圾邮箱

**Comment by WanzerJ** [comment]
我检查过了，我还看了有没有拉黑你们的邮箱，应该都是没有的

**Comment by wong2** [comment]
用我的个人邮箱给你的qq邮箱发了

**Comment by WanzerJ** [comment]
谢谢~
