### ISSUE TITLE
每次从源码构建输入“yarnbuild”的时候都会报错

### ISSUE THREAD

**Issue by catherine-lisa** [chathub-dev/chathub#640]
每次从源码构建的时候，输入yarn build，都会报错TypeError: Could not load C:Userscatherine-lisaDownloadschathub-1.25.0chathub-1.25.0sidepanel.html?html-proxy&inline-css&index=1.css (imported by sidepanel.html): Cannot read properties of undefined (reading '1')

意思是没有找到1.css文件，但是我看了整个源码都没有该文件，其他人build的时候都可以成功吗？不是少了什么文件吗?

**Comment by wong2** [comment]
你的Node.js和yarn版本分别是？

**Comment by catherine-lisa** [comment]
node.js版本是18.16.1，yarn的版本号是1.22.19

**Comment by wong2** [comment]
我没能复现，但试着改了一下，你拉下最新代码再试试呢

**Comment by catherine-lisa** [comment]
已解决，谢谢！
