### ISSUE TITLE
Claude-2 support 

### ISSUE THREAD

**Issue by timlincool** [chathub-dev/chathub#645]
poe.com的模型改了 ,新增Claude-2-100k messages ,是否能够支持呢?
另外https://claude.ai/ 能否也支持一下? 辛苦了

The model of poe.com has been changed, adding Claude-2-100k messages, is it supported?
In addition, can https://claude.ai/ also support it? Thank you

**Comment by wong2** [comment]
claude.ai 已支持，升级到 v1.29.0，然后在设置里对Claude选择webapp模式即可

**Comment by wong2** [comment]
Poe的也加了
