### ISSUE TITLE
购买付费会员后（微信支付），提示支付成功，但回到主界面依然用不了会员功能。 谷歌浏览器（浏览器已登入谷歌账号）

### ISSUE THREAD

**Issue by paop2016** [chathub-dev/chathub#649]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
需要激活的，你的邮箱会收到一个激活码，然后在插件Premium那个页面点按钮激活它

**Comment by paop2016** [comment]
收到，已激活，十分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月14日(星期五) 上午10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chathub-dev/chathub] 购买付费会员后（微信支付），提示支付成功，但回到主界面依然用不了会员功能。 谷歌浏览器（浏览器已登入谷歌账号） (Issue #649)





 
需要激活的，你的邮箱会收到一个激活码，然后在插件Premium那个页面点按钮激活它
