### ISSUE TITLE
ChatGPT使用Web API时无法使用GPT-4 

### ISSUE THREAD

**Issue by BlackStar1453** [chathub-dev/chathub#652]
会一直显示{"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}，我查看了网络请求似乎是因为arkose_token没有正确生成。

**Comment by wong2** [comment]
用的是什么版本呀

**Comment by BlackStar1453** [comment]
ChatHub - All-in-one chatbot client 1.25.0

**Comment by BlackStar1453** [comment]
之前能够正常使用，arkose_token也能够正确生成，但是好像就是昨天还是前天就用不了。GPT-3.5能够正常使用。

**Comment by wong2** [comment]
试试升级到最新版：https://github.com/chathub-dev/chathub/releases/tag/v1.29.1
