### ISSUE TITLE
购买了会员，但是没发激活码到邮件中

### ISSUE THREAD

**Issue by qiwang-GZU** [chathub-dev/chathub#653]
购买了会员，已经扣钱了，但是没有发激活码到邮件中

**Comment by qiwang-GZU** [comment]
![微信截图_20230716204935](https://github.com/chathub-dev/chathub/assets/85480174/d42d7aae-612b-4b7d-a097-9eaeca795b69)

**Comment by wong2** [comment]
我重发了一下，也请查看一下垃圾邮箱

**Comment by qiwang-GZU** [comment]
您好能换个邮箱发吗？我这个学校的邮箱可能屏蔽了你们的邮件，垃圾箱也无法找到。新邮箱（wangqi@samlab.cn）
![image](https://github.com/chathub-dev/chathub/assets/85480174/21d182f7-6057-41be-857e-0dc1533211e4)
![image](https://github.com/chathub-dev/chathub/assets/85480174/850d123e-9458-410e-af17-a1e023770354)

**Comment by wong2** [comment]
已发

**Comment by qiwang-GZU** [comment]
![1689572873662](https://github.com/chathub-dev/chathub/assets/85480174/d6cce7e9-b5dd-416b-b67f-8e4d4994e381)

谢谢哈，我已经收到了激活码，但能从后台帮我改一下邮箱吗？我还是收不到你们的邮件，我没法登录激活，应该是我们学校的邮箱屏蔽了所有邮件。

**Comment by wong2** [comment]
改成 [wangqi@samlab.cn](mailto:wangqi@samlab.cn) 这个邮箱了

**Comment by wong2** [comment]
😭 看来 LemonSqueezy 不能修改订单的邮箱，你后面有需要就找我吧
