### ISSUE TITLE
FIX Bard from Italy

### ISSUE THREAD

**Issue by Giugie1998** [chathub-dev/chathub#655]
**Describe the bug**
I am Italian and since yesterday they have finally made Bard available in Italy also
I tried to use it, normally on the official website it goes without problems, through chathub always the error in the screenshot ('Failed to fetch (https://bard.google.com/faq)')

I also tried to delete the cache but I don't see any results

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

![image](https://github.com/chathub-dev/chathub/assets/19718646/84cfdc03-3b85-4d6d-8ace-c9233e96471a)

**Comment by wong2** [comment]
I will take a look!

**Comment by wong2** [comment]
Can you open this link: https://bard.google.com/faq normally?

**Comment by Giugie1998** [comment]
Yes, I open it without prubablemi, I tried a little while ago and now it works I don't know if you have made some changes, if it were you can also close the ticket :)

**Comment by wong2** [comment]
I think it may be some caching issue.
