### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by dushuning** [chathub-dev/chathub#66]
![image](https://user-images.githubusercontent.com/48204151/225217258-7aa3b601-a5ec-44cb-b325-ae6cc16b9f69.png)
配置了正确的key，还是无法使用，这是为什么呢

**Comment by wong2** [comment]
翻墙 + 你需要 new Bing权限

**Comment by dushuning** [comment]
我正常的chatgpt都可以使用啊，老哥，fanqiang不用说，肯定是有的，只是在使用chathub的情况下，使用不了
