### ISSUE TITLE
Activation Code

### ISSUE THREAD

**Issue by Ironrod777** [chathub-dev/chathub#660]
I have just purchased the premium plan but did not receive an activation code - where do I find it?

**Comment by wong2** [comment]
May i have your email address?

**Comment by Ironrod777** [comment]
david@steampoweredmarketing.com

**Comment by Ironrod777** [comment]
Hi Wong - any suggestions?

**Comment by wong2** [comment]
Unfortunately, this is an issue with the payment provider LemonSqueezy, I need to contact them to help to solve the issue.

**Comment by Ironrod777** [comment]
OK, please let me know when I can have the code.

**Comment by Ironrod777** [comment]
If I do not get a reply from you by the end of business today, I will be submitting a fraud report to my bank.

**Comment by Ironrod777** [comment]
Why can't you just email me the activation code?

**Comment by wong2** [comment]
Because I don't have it either. The license key is generated by LemonSqueezy, but now they didn't receive the money from Stripe, they can't create an order, so there's no license key.

**Comment by Ironrod777** [comment]
Any news?

**Comment by wong2** [comment]
Hi @Ironrod777 I finally got response from LemonSqueezy, they say:

> I don't see any orders for [david@steampoweredmarketing.com](mailto:david@steampoweredmarketing.com) either.

Can you show a proof of your purchase?

**Comment by wong2** [comment]
<img width="538" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/d935098e-de41-4581-adcc-3ea0677518be">

This is what I get.

**Comment by wong2** [comment]
I'll close this for now. Please re-open with a valid proof of purchase.

**Comment by wong2** [comment]
Have you see the screenshot I send you?

**Comment by Ironrod777** [comment]
[Lemony Receipt.docx](https://github.com/chathub-dev/chathub/files/12161964/Lemony.Receipt.docx)

**Comment by Ironrod777** [comment]
Were you able to open the word doc, showing my proof of purchase?

**Comment by Ironrod777** [comment]
Why did you close this ticket?

You have not sent me my activation code, nor have you refunded me the money you charged me.

I would like an activation code today please.

**Comment by wong2** [comment]
Hi @Ironrod777 , I've sent your email to LemonSqueezy, and get a response that they can not find an order with it.
Can you contact the LemonSqueezy customer service again? You can find them here: https://www.lemonsqueezy.com/help
