### ISSUE TITLE
No Activation Code sent

### ISSUE THREAD

**Issue by bigspice34** [chathub-dev/chathub#661]
I paid for the premium chathub license and have not received the activation code despite having a receipt of purchase

**Comment by wong2** [comment]
what is your email for the purchase?

**Comment by bigspice34** [comment]
did you resend it?

**Comment by wong2** [comment]
Sorry, but your email displays as this:

<img width="481" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/e2be8ae8-db1c-4207-bbea-48fc9fa437c8">

**Comment by Ironrod777** [comment]
I also did not receive my activation code. No one from support has replied to me for a couple of days, so I'm preparing to submit a fraud report to my bank. I think you may want to do the same.

**Comment by wong2** [comment]
@bigspice34 I need your email, so I can contact LemonSqueezy about this issue.

**Comment by bigspice34** [comment]
I responded to the initial email. It’s ***@***.***

**Comment by wong2** [comment]
As I've posted above, it shows as ***@***.*** to me. Please check the screenshot:
![image](https://github.com/chathub-dev/chathub/assets/321947/b652cf1a-6344-411e-be8e-c84f4b34cce5)

**Comment by bigspice34** [comment]
I know I just responded with the email again

**Comment by wong2** [comment]
It's still `***@***.***`.

**Comment by wong2** [comment]
Open this https://github.com/chathub-dev/chathub/issues/661 in a browser and check it yourself.

**Comment by wong2** [comment]
Just open the f**king GitHub link and see it yourself.

**Comment by wong2** [comment]
Don't waste my time. Alright?

**Comment by bigspice34** [comment]
Umm EXCUSE you. I am trying to resolve this issue. I just “f***ing” asked,
“since you can’t see the email how can I send it in a way that you can?”
And your response is to curse at me?!

That’s extremely disrespectful and rude of you. And says a lot if this is
how you handle customer “service”

**Comment by wong2** [comment]
Please reopen with a valid email address.

**Comment by bigspice34** [comment]
That is a “f***ing” valid email address. Answer any of the questions I’ve
asked please

**Comment by Jackmin801** [comment]
@bigspice34
Replying issues by email will cause emails in the message to be censored.
So either **reply this discussion on the github website** or **email @wong2 directly at [wonderfuly@gmail.com](mailto:wonderfuly@gmail.com)**

**Comment by bigspice34** [comment]
I don’t want to email wong2 because they were being “f***ing” rude. I would
like my account refunded please

**Comment by Jackmin801** [comment]
Im not affiliated with him by the way, just happened upon this discussion.
I understand that you are upset but I think he wasn't aware of the censorship behavior and thought you were messing with him.

Anyways, even if he is to refund you, he will still need to know which order is yours to process it.

**Comment by wong2** [comment]
Thanks @Jackmin801 for clarifying this. 
I apologize to @bigspice34 for my previous comment because I thought you're a spammer. 
But I still need your email so I can contact LemonSqueezy to process or refund your order.

**Comment by bigspice34** [comment]
Thank you for the apology. I am responding on GitHub this time so the email shouldn't be censored. The email on the account is chriswhite2020@gmail.com I'd prefer to get the authorization code please

**Comment by bigspice34** [comment]
> Thanks @Jackmin801 for clarifying this. I apologize to @bigspice34 for my previous comment because I thought you're a spammer. But I still need your email so I can contact LemonSqueezy to process or refund your order.

@wong2 did you send the updated message?

**Comment by wong2** [comment]
<img width="668" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/4a6c47d1-6074-43cb-ad54-15b18b729d5b">

@bigspice34 I just got the response from LemonSqueezy customer service. And I re-sent the license key to you, please check your email.

**Comment by Ironrod777** [comment]
Hello Wong2, please re-open #660 and process the refund of my activation charges, as you still have not sent me the code.

**Comment by bigspice34** [comment]
Thank you very much! it's finally working
