### ISSUE TITLE
already log in Microsoft account but still could not use BING

### ISSUE THREAD

**Issue by loolxulei** [chathub-dev/chathub#662]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser ： Microsoft Edge
 - like picture attached， i already logged in the Microsoft account but still could not talk to BING

**Comment by wong2** [comment]
I didn't see a picture.

**Comment by mattmacpherson** [comment]
Same issue.

v1.29.5
OS: macOS 13.4.1
Browser: Brave

**Comment by wong2** [comment]
I'll take a look! In the meantime, please retry some times.

**Comment by mattmacpherson** [comment]
> I'll take a look! In the meantime, please retry some times.

Working now!
