### ISSUE TITLE
StableLM and Llama not working 

### ISSUE THREAD

**Issue by Vickyitsmeee** [chathub-dev/chathub#664]
**Describe the bug**
StableLM and Llama not working 

**Desktop 
 - OS: Windows 10
 - Browser:Google Chrome, Microsoft edge

**Comment by Vickyitsmeee** [comment]
Even if I refresh the page I am getting the same message

**Comment by Vickyitsmeee** [comment]
Even dolly does the same

**Comment by wong2** [comment]
This will be fixed in next version.

**Comment by Vickyitsmeee** [comment]
> This will be fixed in next version.

OK thank you 👍
