### ISSUE TITLE
Poe error: Cannot read properties of null (reading '2')

### ISSUE THREAD

**Issue by kidcvs** [chathub-dev/chathub#673]
**描述错误**
使用Poe Mode，Model无论是GPT-3.5还是GPT-4，都提示Cannot read properties of null (reading '2')。但登录 https://poe.com/GPT-4 却是正常的。
**桌面（请填写以下信息）：**
- 操作系统：macOS 14.0
- 浏览器：版本 114.0.5735.198（正式版本） (arm64)

**Comment by superwhyun** [comment]
+1

**Comment by dkmin** [comment]
+1

**Comment by OrkWard** [comment]
+1

**Comment by madnight** [comment]
+1

**Comment by namezzy** [comment]
+1

**Comment by wong2** [comment]
Thanks for reporting, I'm fixing this.

**Comment by wong2** [comment]
Poe has upgraded their protection system, this will take some time to crack.

**Comment by namezzy** [comment]
> Poe has upgraded their protection system, this will take some time to crack.

Appreciate your help!

**Comment by wong2** [comment]
This has been fixed in v1.31.0, though the web store version is pending for review.
You can manually install here: https://github.com/chathub-dev/chathub/releases/tag/v1.31.0

**Comment by wong2** [comment]
v1.31.0 has been published to Chrome Web Store.

**Comment by jiusheng6** [comment]
> 此问题已在 v1.31.0 中修复，但网上商店版本正在等待审核。 您可以在这里手动安装：https://github.com/chathub-dev/chathub/releases/tag/v1.31.0

(400 (https://poe.com/api/gql_POST))

**Comment by wong2** [comment]
@jiusheng6 Can you try again?

**Comment by XJ-03** [comment]
ChatGPT is available now, while Claude's still showing: Cannot read properties of null (reading '2')

**Comment by jiusheng6** [comment]
> @jiusheng6 Can you try again?

I've tried. It's always the same.

**Comment by superwhyun** [comment]
Updated to v1.31.0, but I got following error.

(400 (https://poe.com/api/gql_POST))

**Comment by PanXinglin** [comment]
(400 (https://poe.com/api/gql_POST))

**Comment by wong2** [comment]
Fixed again!

**Comment by kaz875** [comment]
Appreciated the effort @wong2 - things are getting tougher with Poe. Fingers crossed we can still keep up here.

**Comment by jiusheng6** [comment]
(405 (https://chathub.gg/api/poe/decode-formkey))

**Comment by wong2** [comment]
Fixed again

**Comment by madnight** [comment]
We need to setup a LLM in a Github Workflow with a cronjob timer, executing every minute, that automatically fixed the POE integration and pushes the code.

**Comment by wong2** [comment]
Altough this is working for now, I'd suggest users move to other mode:
* for Claude, the webapp mode is more stable.
* for ChatGPT, use webapp or API mode.

**Comment by chilledwack** [comment]
今天使用在 v1.31.0 使用 Poe 的 GPT4 模型反应很慢，字基本上是一个一个吐出来的，用 poe 的网页版本很快。
