### ISSUE TITLE
chathub 侧边栏问题

### ISSUE THREAD

**Issue by xiyan818** [chathub-dev/chathub#675]
![image](https://github.com/chathub-dev/chathub/assets/44111611/da9d001f-2b30-4583-85e8-53e194ebc2b0)
如图，之前不用移动底下的滚动条，只需要移动上下滚动条即可完整显示。移动左右滚动条看起来不是很方便。

**Comment by wong2** [comment]
收到

**Comment by wong2** [comment]
Fixed in next version.
