### ISSUE TITLE
什么时候支持GP-4

### ISSUE THREAD

**Issue by bigfootcn** [chathub-dev/chathub#68]

**Comment by saccohuo** [comment]
![image](https://user-images.githubusercontent.com/13887263/225359362-bddb0ae1-9d52-4275-9f36-75d043a24532.png)
等wong2大佬发布

**Comment by kgxiu** [comment]
求大佬告知，要怎么添加

**Comment by kaichii** [comment]
> 求大佬告知，要怎么添加

等更新

**Comment by imwx** [comment]
慎用chatgpt，填了key，用中国ip访问，会封账号的

**Comment by HenMie** [comment]
> 慎用chatgpt，填了key，用中国ip访问，会封账号的

大陆ip访问不了api吧？港澳台ip才可以。澳不清楚，港是不能用ChatGPT的，台本来就可以用ChatGPT。
