### ISSUE TITLE
POE模式下ChatGPT 4.0对话失败显示：Cannot read properties of null (reading '2')

### ISSUE THREAD

**Issue by Juneone96** [chathub-dev/chathub#682]
Claude使用poe也会出现同样的问题，希望得到回复解决

**Comment by wong2** [comment]
你是什么浏览器？ChatHub是什么版本？

**Comment by Juneone96** [comment]
> 

Chathub: Settings (v1.30.1) 
Chrome: Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by wong2** [comment]
请把ChatHub更新到最新版，修复了此问题。
