### ISSUE TITLE
我购买了会员，但是不能够对话，总是显示错误，我挂了各个国家的梯子都不行。

### ISSUE THREAD

**Issue by wanghy1996111** [chathub-dev/chathub#687]
![1690506970727](https://github.com/chathub-dev/chathub/assets/140769097/5bc9b106-d97f-49bf-b8f8-446197a3d0c8)

**Comment by wong2** [comment]
你的购买邮箱是？我帮你退款吧

**Comment by jemoleip** [comment]
我也是一样的问题，我非常想用这个产品，请问一下是什么问题，有其他解决办法吗

**Comment by wanghy1996111** [comment]
> 你的购买邮箱是？我帮你退款吧

购买邮箱是：547630896@qq.com

**Comment by wong2** [comment]
@wanghy1996111 已退

**Comment by wong2** [comment]
@jemoleip 是因为机器人服务支持的国家不一样，首先都不支持大陆IP，其次大部分也不支持香港。如果用代理软件的话，大部分默认的代理规则里面，微软/Bing是不走代理的，需要单独配置。

**Comment by jemoleip** [comment]
折腾了一下午，改了规则，换了其他的国家的代理，用的全局代理也不行，只有 bard在新加坡节点下可以用，但是其他的单独点进去提示的登录网页就可以，我不会搞了，麻烦你帮我退一下款了，jemoleip@gmail.com，哭了

**Comment by wong2** [comment]
@jemoleip 已退

**Comment by SHENG0902** [comment]
我也是挂提子节点根本没有用访问失败，可以帮我退款吗邮箱15861885530@163.com
