### ISSUE TITLE
Premium License

### ISSUE THREAD

**Issue by olympiorenno** [chathub-dev/chathub#696]
**Describe the bug**
premium license is not activating on second device
in first windows 64 browser chrome is ok

**Desktop (please complete the following information):**
 - OS: MACOS Version 13.4.1 (c)
 - Browser Chrome Version 115.0.5790.114 (Official Build) (x86_64)
Tks

**Comment by wong2** [comment]
May I have your email of purchasing?

**Comment by olympiorenno** [comment]
***@***.***

tks


Olympio Rennó
www.helpdesk.com.br
cel: 11-98427-0708
[image: Linkedin] <http://www.linkedin.com/in/olympiorenno>


Em ter., 1 de ago. de 2023 às 14:18, wong2 ***@***.***>
escreveu:

**Comment by wong2** [comment]
Sorry, but you need to reply this message in GitHub. Email addresses are redacted in email replies.

**Comment by olympiorenno** [comment]
olympio@helpdesk.com.br

**Comment by wong2** [comment]
From the dashboard, I can see that you have reached the 5 activations limit.
You can deactivate some devices from here: https://app.lemonsqueezy.com/my-orders/

**Comment by olympiorenno** [comment]
Thank you, I removed the 5 activations, and activated the devices I wanted again, there were 3 activations but 5 devices appeared and on the mac it didn't work, but now it's ok, thank you very much for your attention and fast support.
Windows / Chrome
Activated on 2 Aug 2023, 03:22

Windows / Chrome
Deactivated on 2 Aug 2023, 03:21

Mac / Chrome
Deactivated on 2 Aug 2023, 03:21

Windows / Chrome
Deactivated on 2 Aug 2023, 03:20

Mac / Chrome
Deactivated on 2 Aug 2023, 03:20

Mac / Chrome
Deactivated on 2 Aug 2023, 03:20

Windows / Chrome
Activated on 1 Aug 2023, 04:46

Mac / Chrome
Activated on 31 Jul 2023, 16:20

Windows / Chrome
Activated on 31 Jul 2023, 14:44
