### ISSUE TITLE
会话中 web access （联网）问题

### ISSUE THREAD

**Issue by xiyan818** [chathub-dev/chathub#703]
# 有的时候，Bing 中会出现 web access 选项，如图1
![image](https://github.com/chathub-dev/chathub/assets/44111611/03a959fa-4cb6-4144-9d50-e7d255f357d7)
# 但有的时候又没有，如图2
![image](https://github.com/chathub-dev/chathub/assets/44111611/7b06b73e-0689-4ac6-af43-eba939e15327)
# Bard 也会出现这种情况。不知道是不是一个 bug。以及 Bing 和 Bard 勾不勾选这个 **web access** 会有什么区别吗？

**Comment by wong2** [comment]
是bug，Bing和Bard不该出现的因为他们永远是联网的
