### ISSUE TITLE
PI is not answering since yesterday ({"error":"No remaining trial turns."}

### ISSUE THREAD

**Issue by daffi7** [chathub-dev/chathub#705]
**Describe the bug**
I had some conversations with Pi last week, but since yesterday, PI has been refusing to talk to me, always outputting only {"error":"No remaining trial turns."}
I am not recollecting asking anything controversial or doing anything unusual (other bots are not complaining). Some of my prompts are quite long (7000 characters?), otherwise I used it pretty normally. Also, PI rejected before any prompt longer than 1000 characters, but yesterday it changed and it does not answer any prompts.

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Browser: Chrome Beta (created an App from the ChatHub extension page)

**Comment by wong2** [comment]
Thanks, I'll take a look.

**Comment by wong2** [comment]
Have you sign-in at https://pi.ai/talk ?

**Comment by daffi7** [comment]
yes, yes I can.

**Comment by daffi7** [comment]
Any solution, please?

**Comment by wong2** [comment]
I wasn't able to reproduce this issue. Can you try to log in at https://pi.ai/ and try again?

**Comment by daffi7** [comment]
It helped.
