### ISSUE TITLE
可以增加上下分隔的视图吗

### ISSUE THREAD

**Issue by Kelvin-Doremi** [chathub-dev/chathub#707]
Can you add a split view with vertical orientation?

**Comment by wong2** [comment]
What do you mean? Can you draw a sketch?

**Comment by Kelvin-Doremi** [comment]
![image](https://github.com/chathub-dev/chathub/assets/67680245/89b1e94f-5538-44cd-9aaa-e3db76dd2358)
Like this, I hope to combine the 2 top boxes into one box and combine the 2 bottom boxes into one box since I prefer to use GPT in the vertical screen and if I split the box with horizontal orientation, it's very uncomfortable to read.

**Comment by wong2** [comment]
I see! I'll figure it out.

**Comment by wong2** [comment]
<img width="998" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/19185f01-957e-4d9f-8e47-80714bbcaaf8">

**Comment by Kelvin-Doremi** [comment]
Ok, but how can I use this function

**Comment by wong2** [comment]
Please wait for next release.

**Comment by wong2** [comment]
Released in v1.33.8 in Chrome web store.
