### ISSUE TITLE
Bing only responds with UnauthorizedRequest

### ISSUE THREAD

**Issue by vincentllora** [chathub-dev/chathub#708]
**Describe the bug**
When entering prompts in Bing, it only responds with UnauthorizedRequest. I've seen something similar before, but it would also have a link to re-authorize, but now there is no way to re-authorize.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by wong2** [comment]
Can you try to make a chat on Bing.com? Maybe this is will fix it.

**Comment by vincentllora** [comment]
I went to Bing.com and signed in. That did the trick. Thanks.

**Comment by vincentllora** [comment]
I went to Bing.com and signed in. That did the trick. Thanks.

**Comment by wong2** [comment]
Great!

**Comment by vincentllora** [comment]
Just a note - you cannot initiate a chat on Bing.com in Chrome, but you can sign in to Bing.com and that was all that was needed for authorization. Thanks again for the lightning fast response.

**Comment by wong2** [comment]
I'll add a login link to Bing.com in this case. Thanks for reporting!
