### ISSUE TITLE
The purchased license cannot be activated.

### ISSUE THREAD

**Issue by BestTx** [chathub-dev/chathub#714]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
email： chenshuaiprivate@163.com

**Comment by wong2** [comment]
Is there any errors?

**Comment by BestTx** [comment]
No error is reported.

**Comment by BestTx** [comment]
No device is activated when the email account is queried.

**Comment by wong2** [comment]
You need to activate in the extension with your license key:

<img width="975" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/e8db1ff5-da2b-4314-8fc1-d21bf079077c">

**Comment by wong2** [comment]
Can you try again? And which version of ChatHub are you using?

**Comment by BestTx** [comment]
设置 (v1.33.9)

**Comment by wong2** [comment]
安装最新版再试试？1.34.0

**Comment by BestTx** [comment]
The problem is solved after the upgrade. Thank you.
