### ISSUE TITLE
Claude 2 无法回复完整会话

### ISSUE THREAD

**Issue by xuuou** [chathub-dev/chathub#716]
**Describe the bug**
在对Claude 2进行对话时，回答的结果只能显示第一个字在不断变化，无法显示完整的句子。

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Edge]

**Comment by wong2** [comment]
I've found the cause. This issue has been fixed in v1.34.2, please wait for next release.

**Comment by wong2** [comment]
新版本已发布到Chrome商店，请更新
