### ISSUE TITLE
request

### ISSUE THREAD

**Issue by venkat2305** [chathub-dev/chathub#717]
Hello, I am reaching out to ask if there is a chance to receive a discount for the premium edition of this application. I am a student from India, and I find this app very useful, but the price of 20USD is too high for me, considering the purchase power parity. I understand that this is not a feature request, but I would appreciate it if you could offer me a lower price that is more affordable for me. This would help me a lot in my studies and projects. Thank you for your time and attention.

**Comment by wong2** [comment]
I'm sorry, but currently there are no plans for this
