### ISSUE TITLE
Claude (webapp/Claude-2) displays Unexpected agent error

### ISSUE THREAD

**Issue by Shmily0921** [chathub-dev/chathub#718]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
Is it always like this?

**Comment by Shmily0921** [comment]
> 总是这样吗？

It appeared yesterday and today, and it's still there

**Comment by wong2** [comment]
May I have your input to Claude? I'll try to reproduce it.

**Comment by wong2** [comment]
I've found the cause. This issue has been fixed in v1.34.2, please wait for next release.

**Comment by wong2** [comment]
The fix has been published to Chrome web store.
