### ISSUE TITLE
大神您好，我遇到这个问题，请问怎么解决？

### ISSUE THREAD

**Issue by davidliu1210** [chathub-dev/chathub#723]
我的操作系统是Win10专业版22H2 19045.3086
谷歌浏览器版本 115.0.5790.110（正式版本） （64 位）

使用时，Bing出现报错：Failed to fetch (https://www.bing.com/turing/conversation/create)
后附图片
![Quicker_20230821_170636](https://github.com/chathub-dev/chathub/assets/128200681/ce5aafde-4563-4251-988e-43b67e768d46)

已翻墙，IP在新加坡

请问这个问题怎么解决？

麻烦指导，不胜感激。

**Comment by wong2** [comment]
试试这样能不能解决：
打开 https://bing.com
右上角设置里修改国家或地区到新加坡
<img width="466" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/9c150545-6f79-4b35-ac39-9a6077740f9e">

**Comment by davidliu1210** [comment]
大神您好，我在浏览器中访问https://bing.com时，老是被重定向到https://cn.bing.com/，请问这个问题怎么解决，有啥好办法吗？
&nbsp;


刘大伟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月21日(星期一) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chathub-dev/chathub] 大神您好，我遇到这个问题，请问怎么解决？ (Issue #723)





 
试试这样能不能解决：
 打开 https://bing.com
 右上角设置里修改国家或地区到新加坡

**Comment by wong2** [comment]
改国家、语言，然后清除cookie，这样试试看
