### ISSUE TITLE
GPT PLUS activation 

### ISSUE THREAD

**Issue by beni69006** [chathub-dev/chathub#727]
Hello,
Thank you for this awesome app!
I have a GPT PLUS account. How do I activate it and get GPT-4 on the module?
Thank you.

**Comment by wong2** [comment]
Hi, just login to https://chat.openai.com
And use ChatGPT webapp mode in ChatHub.

<img width="370" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/89756ca0-8cec-4e1f-8196-612291a3e30e">
