### ISSUE TITLE
Is the web access of ChatGPT bypassing the API?

### ISSUE THREAD

**Issue by lyjpaul** [chathub-dev/chathub#728]
I would like a detailed explanation of how web access works when using ChatGPT3.5 through the API with web access enabled.

It seems that there is a prompt to enable DuckDuckGo. Is this an add-on powered by GPT4? And how does it impact the content of GPT3.5 in CharHub?

**Comment by wong2** [comment]
No, it's not a GPT-4 plugin or something similar. It's fully implemented in ChatHub via prompt engineering, so it also works with GPT 3.5 and Claude.

**Comment by lyjpaul** [comment]
Per my understanding, the process involves searching the question input before using ChatGPT. The search results are then combined with the question and sent to ChatGPT3.5 in order to generate a web-connected answer. However, I'm curious about the permission request from DuckDuckGo that appears when clicking on the web access button for the first time.

Another topic that concerns me is OpenAI's claim of not using API data to train their models. So my question is: how does web access behave in ChatHub?

Thank you for your response and please consider this issue resolved.

**Comment by wong2** [comment]
Yes, ChatHub is performing a request to duckduckgo API to get search results.
