### ISSUE TITLE
I have purchased a licenced version, but after some trials of entering it shows- "Sorry, you have reached chat turns limit in this conversation." 

### ISSUE THREAD

**Issue by iknalos** [chathub-dev/chathub#730]
Having purchased the trial I wasnt expecting this thing to happen as it mentions clearly:-
Premium
  1.  More layouts in All-In-One mode
        4-in-1, 3-in-1
  2.  Web Access
      Improving accuracy by searching up-to-date information from the internet
  3.  Full-text search for chat history
  4. Customize theme
  5. Quick access in Chrome side bar
  6. Compare with image input

**Comment by wong2** [comment]
Hi, this is a limitation of Bing itself. You need to start a new conversation after some turns. It behaves the same with the Bing Chat website.
