### ISSUE TITLE
Bing Chat: either it doesn't know what mode it is in, or its mode is configured incorrectly.

### ISSUE THREAD

**Issue by DrewNeilson** [chathub-dev/chathub#731]
In ChatHub's settings, in the Bing section, I've selected "precise".
On the all-in-one page, the layout that I've selected is 2-in-1 side-by-side, with Bing on the left, and Bard on the right.
On the all-in-one page, when I type the following into Bing's chat box:
"Please tell me which of your chat modes--creative, balanced, or precise--you are in. If you are in anything other than precise mode, switch to precise mode."
Bing's response is "Sorry! That’s on me, I can’t give a response to that right now. What else can I help you with?"
If I respond with "Please tell me which of your chat modes--creative, balanced, or precise--you are in."
Bing's response is the same.
If I respond with "If you are in anything other than precise mode, switch to precise mode."
Bing's response is the same.
If I respond with "test" to make sure that Bing is functional, Bing's response is the same as before.

If I clear the conversation and type "test", Bing actually responds to the word "test". However, if I follow that up with "Please tell me which of your chat modes--creative, balanced, or precise--you are in", Bing responds with "I am currently in the `Balanced` mode. Is there anything else you would like to know? 😊" This is despite the fact that I selected "precise" in ChatHub's settings.
If I respond with "If you are in anything other than precise mode, switch to precise mode", Bing responds with "I am sorry, but I am not able to switch modes on my own. You can switch my mode by using the toggle button. Is there anything else you would like to know? 😊"

If in my browser I go to Bing.com (where I am already signed in using my Microsoft account), click on "chat", and click on my most recent chat history (from when I asked Bing what mode it is in), the color of Bing's bubbles indicate that it was in "precise" mode at the time of that conversation, despite the fact that it said that it was in balanced mode.

OS: the current version of Windows 10 Pro
Browser: Edge

**Comment by wong2** [comment]
This is normal. Bing Chat is a language model that only knows the data it was trained on and is unaware of the mode it is operating in unless explicitly informed.
