### ISSUE TITLE
 claude poe decode-formkey 错误

### ISSUE THREAD

**Issue by KingDoum** [chathub-dev/chathub#736]
当我使用 claude poe模式的时候，出现错误
明明昨天都可以正常使用，今天就出了bug 希望能及时修复~
(405 (https://chathub.gg/api/poe/decode-formkey))

**Comment by wong2** [comment]
Fixed in next version. Please wait for release.

**Comment by cypggs** [comment]
> Fixed in next version. Please wait for release.

me too 
<img width="1478" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/b51760b1-daec-4a91-8a43-4f6a8def37e5">

**Comment by KingDoum** [comment]
chatgtp 可以使用 api模式，调用 其他的接口进行使用，好歹不影响你的学习

**Comment by KingDoum** [comment]
> > Fixed in next version. Please wait for release.
> 
> me too <img alt="image" width="1478" src="https://user-images.githubusercontent.com/3694954/263448362-b51760b1-daec-4a91-8a43-4f6a8def37e5.png">

chatgtp 可以使用 api模式，调用 其他的接口进行使用，好歹不影响你的学习

**Comment by wong2** [comment]
v1.36.0 released to Chrome web store
