### ISSUE TITLE
claude webapp 模式无法使用

### ISSUE THREAD

**Issue by piaodaxiawork** [chathub-dev/chathub#737]
**Describe the bug**
我可以正常通过https://claude.ai/ 网站方位claude。但是使用chathub 的webapp 模式使用claude时，会提示  (403 Forbidden (https://claude.ai/api/organizations/9199d893-4112-48db-a77e-b75aa9b7d7a9/chat_conversations)) 。

**Desktop :**
 - OS: Windows 11
 - Browser ：Chrome

**Comment by wong2** [comment]
一直这样吗？

**Comment by piaodaxiawork** [comment]
> 一直这样吗？

是的，遇到这个问题已经有一段时间了，现在还是这样。

**Comment by UsamaKarim** [comment]
I am getting the following error on Claude in Poe mode.
`(https://chathub.gg/api/poe/decode-formkey))`
Extention version `v1.35.5`
<img width="1809" alt="image" src="https://github.com/chathub-dev/chathub/assets/64292174/641c6ea3-a42f-4773-9527-0f36e35ef8da">

**Comment by wong2** [comment]
@UsamaKarim Please upgrade to v1.36+ from Chrome web store

**Comment by piaodaxiawork** [comment]
> **Describe the bug** 我可以正常通过https://claude.ai/ 网站方位claude。但是使用chathub 的webapp 模式使用claude时，会提示 (403 Forbidden (https://claude.ai/api/organizations/9199d893-4112-48db-a77e-b75aa9b7d7a9/chat_conversations)) 。
> 
> **Desktop :**
> 
> * OS: Windows 11
> * Browser ：Chrome

在清理了浏览器缓存、重新安装chathub插件之后问题解决了。
