### ISSUE TITLE
使用支付宝购买会员后，没有收到激活码，订单管理显示邮箱不可用

### ISSUE THREAD

**Issue by PenneyNiu** [chathub-dev/chathub#738]
难道是我的邮箱填错了吗
请帮我解决一下，感谢！
我的邮箱：panpanniu1993@gmail.com

![微信图片_20230826180703](https://github.com/chathub-dev/chathub/assets/65593780/4a6483a3-4a9e-4e9a-9ab4-42812f7471c9)

**Comment by wong2** [comment]
查到您填写的邮箱是：panpanniu1993@163.com

**Comment by PenneyNiu** [comment]
> 查到您填写的邮箱是：[panpanniu1993@163.com](mailto:panpanniu1993@163.com)

非常抱歉！我邮箱填错了，请帮我改成panpanniu1993@gmail.com吧，非常感谢！谢谢！

**Comment by wong2** [comment]
改了，试试是否能登录呢

**Comment by PenneyNiu** [comment]
已收到激活码，谢谢！但还不能登录

![微信截图_20230826215452](https://github.com/chathub-dev/chathub/assets/65593780/6ce7e141-59ed-45c0-8377-a1cc077b816f)

**Comment by wong2** [comment]
看来LemonSqueezy的邮箱不能这样修改，我可以帮你退款，然后你再用正确邮箱购买一次。需要这样操作吗？

**Comment by PenneyNiu** [comment]
> 看来LemonSqueezy的邮箱不能这样修改，我可以帮你退款，然后你再用正确邮箱购买一次。需要这样操作吗？

我已经使用了一次激活码，还可以退款重购吗？

**Comment by wong2** [comment]
可以，退款后这个激活码会失效

**Comment by PenneyNiu** [comment]
> 可以，退款后这个激活码会失效

好的，我已经反激活了，请帮我退款，我会重新购买，麻烦你了，感谢！
