### ISSUE TITLE
接口出问题了吗

### ISSUE THREAD

**Issue by saodiawei** [chathub-dev/chathub#740]
![image](https://github.com/chathub-dev/chathub/assets/37406241/29f5468c-a16b-4691-8bdd-e6d2736e86a6)
![image](https://github.com/chathub-dev/chathub/assets/37406241/49a67cd7-1182-4377-8f0e-c747cbc44e7b)

**Comment by wong2** [comment]
https://github.com/chathub-dev/chathub/issues/736

**Comment by wong2** [comment]
v1.36.0 released to Chrome web store
