### ISSUE TITLE
iflytek spark interface problem 

### ISSUE THREAD

**Issue by Joonyvon** [chathub-dev/chathub#741]
Interface error
           
{"timestamp":"2023-08-27T12:51:06.326+08:00","status":404,"error":"Not Found","path":"/iflygpt/u/chat_message/chat"}

**Comment by wong2** [comment]
fixed in next version

**Comment by Joonyvon** [comment]
> fixed in next version

good job

**Comment by wong2** [comment]
Released v1.36.1
