### ISSUE TITLE
我选择了PayPal付款，然后成功了，怎么才能使用会员服务？

### ISSUE THREAD

**Issue by yangameng** [chathub-dev/chathub#742]
license在哪啊？
邮箱：hijiashu@qq.com

**Comment by wong2** [comment]
没有收到邮件嘛？垃圾邮箱也检查一下

**Comment by yangameng** [comment]
刚收到了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月27日(周日) 晚上6:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chathub-dev/chathub] 我选择了PayPal付款，然后成功了，怎么才能使用会员服务？ (Issue #742)




 
没有收到邮件嘛？垃圾邮箱也检查一下
