### ISSUE TITLE
联网模式下，gpt3.5返回的代码结果会被截断

### ISSUE THREAD

**Issue by beiyouwuyanzu** [chathub-dev/chathub#743]
如图所示， 联网搜索启用时， 返回的代码结果会被截断， 这时候取消联网就没有这个问题
联网模式还挺好用的，但是这个问题出现的比较频繁， 希望修复这个bug
![image](https://github.com/chathub-dev/chathub/assets/30210999/6359c80a-d0fd-45fc-92dc-7db337ad3f42)

**Comment by wong2** [comment]
收到

**Comment by wong2** [comment]
Released v1.36.2
