### ISSUE TITLE
chat gpt 401

### ISSUE THREAD

**Issue by double666321** [chathub-dev/chathub#744]
**Describe the bug**
I purchased a paid membership and activated it, but I reported an error 401 when using chat gpt
The chat gpt set is in API mode, and the key in the email is filled in or not, and error 401 is reported.

**Desktop (please complete the following information):**
 - Browser   chrome

**Comment by wong2** [comment]
You may have some misunderstandings. ChatHub Premium unlocks the premium features of ChatHub, and the license key you receive is not an OpenAI API key.

**Comment by double666321** [comment]
Yes, I made a mistake, I got the account key again
