### ISSUE TITLE
We've sent you a magic link to login. Please check your email.

### ISSUE THREAD

**Issue by jinny51** [chathub-dev/chathub#745]
is:issue is:open 我购买了付费会员，输入自己的邮箱以后，提示“We've sent you a magic link to login. Please check your email.”，但我邮箱并没有收到任何信息。

**Comment by jinny51** [comment]
jinny@techvision.com.cn

**Comment by wong2** [comment]
查看下垃圾邮箱呢？
另外你不需要登录来使用会员功能，只要在插件里用你购买后邮箱收到的license key激活就可以了

**Comment by jinny51** [comment]
邮箱没收到任何邮件。包括垃圾邮箱~~~

**Comment by wong2** [comment]
奇怪，我重新为您发送了一次license key，请看看这次是否能收到

**Comment by jinny51** [comment]
还是没有，晕死了，我这个是企业邮箱，会不会是这个原因？

**Comment by jinny51** [comment]
要不改个邮箱吧？
注册的时候提交的是jinny@techvision.com.cn
改为jinny.r@qq.com
可以吗？

**Comment by wong2** [comment]
邮箱改不了，我可以为你退款，然后用新邮箱重新购买

**Comment by jinny51** [comment]
好吧，那退款，我重新填邮箱，再买一次

**Comment by wong2** [comment]
已退

**Comment by jinny51** [comment]
什么时候可以看到退款信息？

**Comment by jinny51** [comment]
晕，这会全收到了，10几封邮件~~~~

**Comment by wong2** [comment]
哈哈尴尬了，已经退款了，你收到的license key也是失效的

**Comment by jinny51** [comment]
没事，我再买一个，这下填QQ邮箱吧，企业邮箱太坑了。

**Comment by wong2** [comment]
你上次购买时的折扣码：065W1JMK  可以再用一次

**Comment by jinny51** [comment]
我选择再次购买，发现邮箱已经被锁定了，无法修改。。

**Comment by wong2** [comment]
https://app.lemonsqueezy.com/my-orders/ 点右上角退出登录

**Comment by jinny51** [comment]
可以了，已经重新弄好了，谢谢你啊
顺便问一句，我设置了gpt4，但是他告诉我还是3，这是为什么呢

**Comment by wong2** [comment]
<img width="860" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/452c027d-fd8d-459f-8eb2-6d08c1c06e35">

正常，它不知道自己是谁

**Comment by jinny51** [comment]
好吧。
