### ISSUE TITLE
我已经科学了，为什么还会提示科学上网，这个后台域名是什么，我单独再配置下proxy

### ISSUE THREAD

**Issue by cypggs** [chathub-dev/chathub#746]
<img width="1266" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/7842f3ad-d460-4ae7-ba66-564bcb6e0c97">

**Comment by wong2** [comment]
是因为这个服务改接口了，等我修复一下

**Comment by cypggs** [comment]
> 是因为这个服务改接口了，等我修复一下

https://[chinese.llama.family](https://chinese.llama.family/)/
能用这个么，还支持中文的llama

**Comment by wong2** [comment]
我看看啊

**Comment by wong2** [comment]
Fixed in v1.36.2

**Comment by cypggs** [comment]
> Fixed in v1.36.2

Llama 2: We have three new bots powered by Llama 2, a large language model that Meta released. You can try it here: https://poe.com/Llama-2-70b. We are looking forward to providing access to fine-tuned versions of Llama as the community creates those. If you are experimenting with fine-tuning Llama or any other model, it’s easy to use Poe as a frontend for your model via our API. Try [developer.poe.com](https://developer.poe.com/api-bots/quick-start) to get started. We are also interested in helping to host fine-tuned versions of Llama so that developers don’t have to manage a server or pay large costs if their bot becomes popular. Please reach out to us at [developers@poe.com](mailto:developers@poe.com) if you are interested in participating in this program.

POE支持Llama-2-70b  接入这个好像更优秀，复用POE模式会不会更稳定😄

**Comment by wong2** [comment]
有道理

**Comment by wong2** [comment]
不过同时使用多个poe的机器人，容易被识别出来并封号，有点风险。

**Comment by cypggs** [comment]
> 不过同时使用多个poe的机器人，容易被识别出来并封号，有点风险。

可否串行执行，当多个渠道用了poe，串行跑，也不着急多等一伙😄。

**Comment by cypggs** [comment]
> 是因为这个服务改接口了，等我修复一下
现在是bing不行
<img width="1291" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/c9babe1c-019b-4f0b-8f26-0301a884d8ca">
bing官网是ok的
<img width="1085" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/d73867d7-bbb3-400b-a02b-da06d324d26d">

**Comment by wong2** [comment]
@cypggs 更新到 v1.36.3 修复了Bing的问题

**Comment by cypggs** [comment]
> @cypggs 更新到 v1.36.3 修复了Bing的问题

<img width="1321" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/ce90553c-102b-4c67-8ed0-9634ba2b7554">
EDGE浏览器扩展商店貌似还没更新

**Comment by wong2** [comment]
Edge商店审核很慢...

**Comment by cypggs** [comment]
> Edge商店审核很慢...

搞定了，删了Edge的，直接安装goolge的，google的商店也能给edge用。

**Comment by cypggs** [comment]
> @cypggs 更新到 v1.36.3 修复了Bing的问题

<img width="1509" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/1d885017-8995-4845-b866-2104a6b0a015">
<img width="649" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/a1e4d36e-123e-4fb1-b25b-84ba331c48d8">
<img width="639" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/f79a4472-ae47-4953-90c3-9391af685b26">
还是不稳定
官网正常
<img width="1148" alt="image" src="https://github.com/chathub-dev/chathub/assets/3694954/cbc88e11-d6fe-4ceb-b4bf-43198ae4a130">
