### ISSUE TITLE
缴费页面留了错误的邮箱，目前没有办法登录该怎么办，已经在支付宝反馈但暂未收到回复

### ISSUE THREAD

**Issue by patty5991** [chathub-dev/chathub#747]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
邮箱是？我帮你退款，然后你重新购买

**Comment by patty5991** [comment]
这是来自QQ邮箱的自动回复。
 
您好，您的邮件已收到，如果需要我会尽快给您回复。

**Comment by wong2** [comment]
看到您另一个issue了，我已经帮你退款。请重新购买。

**Comment by patty5991** [comment]
好的，非常感谢，退款我已经收到了。我已经换了一个邮箱已经重新购买了，也激活了，但是我在操作的时候，除了ChatGPT能用，其他几个都显示不能连接需要科学上网，但我其实网络都正常的，是不是因为那些需要挨个注册账号？这里是截图
<img width="810" alt="QQ浏览器截图20230829041404" src="https://github.com/chathub-dev/chathub/assets/143435956/a56ba154-7af2-45a8-a1d5-61c07fa4685c">
