### ISSUE TITLE
bing和llama2会话创建失败

### ISSUE THREAD

**Issue by Juneone96** [chathub-dev/chathub#749]
![image](https://github.com/chathub-dev/chathub/assets/140543869/ed9f9b77-1227-436f-bb85-e02128b35f17)
版本：v1.36.1
Chrome：Version 116.0.5845.111 (Official Build) (64-bit)

**Comment by wong2** [comment]
@Juneone96 Where are you located? Are you using a proxy to access Bing?

**Comment by wong2** [comment]
The issue with llama 2 has been fixed in v1.36.2
