### ISSUE TITLE
bing CAPTCHA验证并且刷新仍然一直出现Verify 

### ISSUE THREAD

**Issue by timlincool** [chathub-dev/chathub#751]
**Describe the bug**
使用bing 出现User needs to solve CAPTCHA to continue. 后跳出Verify 
点击后会跳新视窗 ,验证通过后回到 chathub ,刷新或重新打开新的chathub 后仍然还是跳出Verify 
多次尝试无果 ,请问该如何解决?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome , edge
 - 版本 1.36.1

**Comment by wong2** [comment]
我看看

**Comment by wong2** [comment]
感觉跟代理节点有关系，换换试试？
