### ISSUE TITLE
请问chrome里面哪里可以打开侧边栏啊？

### ISSUE THREAD

**Issue by wangxin0020** [chathub-dev/chathub#760]
如题，希望网页旁边放一个小助手，不希望打开整个标签。

 - OS: [Windows]
 - Browser [chrome,]

**Comment by wangxin0020** [comment]
找到了，在这里
![image](https://github.com/chathub-dev/chathub/assets/5867779/7a98bb5c-aade-4318-83ff-3e5ee57248ea)

**Comment by wong2** [comment]
是可以加个按钮什么的
