### ISSUE TITLE
梯子需要开全局才能用bing

### ISSUE THREAD

**Issue by ceeeeeeeeeeeeeeeeb** [chathub-dev/chathub#762]
![image](https://github.com/chathub-dev/chathub/assets/109498063/076ef9e2-e7b9-4b25-8c9f-553df4cdacfd)
用的clash，第一句是梯子开了全局，bing 能正常连接  第二句切换到规则模式就不行了 提醒网络问题。 有没有办法在规则模式下也走代理？
这应该是个关于clash配置的问题，但人太菜 不会，麻烦教一教

**Comment by wong2** [comment]
对，是规则配置的问题。可以参考我这条推特：https://twitter.com/wong2_x/status/1682683646711590912
