### ISSUE TITLE
扩展页面不能调用 沉浸式翻译扩展 进行翻译

### ISSUE THREAD

**Issue by ceeeeeeeeeeeeeeeeb** [chathub-dev/chathub#763]
![image](https://github.com/chathub-dev/chathub/assets/109498063/45c3db36-e7b1-402e-935c-6e42551da3aa)
提醒没有权限翻译。
有办法解决吗，用这个翻译扩展可自动把中文输入翻译为英文 然后把英文回答翻译为中文，效率更高。

**Comment by wong2** [comment]
没有，插件没法在插件的页面使用的

**Comment by wong2** [comment]
没有，插件没法在插件的页面使用的
