### ISSUE TITLE
你已经达到了该模型今日免费消息上限

### ISSUE THREAD

**Issue by Robertagibbs** [chathub-dev/chathub#764]
claude和being都出现这个问题，怎么解决？
<img width="664" alt="image" src="https://github.com/chathub-dev/chathub/assets/143872752/bf7dfcf2-ead7-4158-a02d-ffffba0a32fe">

**Comment by wong2** [comment]
下面写了呀，“这是poe.com的限制”，解决办法：买poe的会员，或者Claude换到别的模式，比如 webapp 模式

**Comment by Robertagibbs** [comment]
web的话要自己注册一个claude账号。Being这个老是出问题。

wong2 ***@***.***>于2023年9月3日 周日18:38写道：

**Comment by wong2** [comment]
对的，注册一个claude账号很容易。Bing这个还需要再看看

**Comment by Robertagibbs** [comment]
不是那么容易，现在都要国外的手机号接SMS，好不容易才买到一家

wong2 ***@***.***>于2023年9月3日 周日20:45写道：

**Comment by wong2** [comment]
哦刚试了下确实要手机号了，我当时注册的时候还不用...

**Comment by bighaidao** [comment]
> 是那么容易，现在都要国外的手机号接SMS，好不容易才买到一家

claude 需要手机号了？
