### ISSUE TITLE
有两个服务有问题，请给解决一下：

### ISSUE THREAD

**Issue by yangameng** [chathub-dev/chathub#766]
chatGPT一直在生成状态，没有结果。
![image](https://github.com/chathub-dev/chathub/assets/75940154/b7943a0d-4326-43b4-8359-fc6a4c429299)

另外Bard显示Bard isn't currently supported in your country

**Comment by wong2** [comment]
Bard这个需要你自己解决了，让 bard.google.com 代理到美国
