### ISSUE TITLE
chatgpt 一直Loading

### ISSUE THREAD

**Issue by popeye47** [chathub-dev/chathub#769]
![image](https://github.com/chathub-dev/chathub/assets/143996483/6557d57d-91c3-4456-9ca6-e70a9018b557)

**Comment by wong2** [comment]
重启下浏览器能好吗？

**Comment by popeye47** [comment]
> 重启下浏览器能好吗？

浏览器重启不管用，清理浏览器缓存才好使，不过今天又出现了，复现率有点高

**Comment by HailPHP** [comment]
> > 重启下浏览器能好吗？
> 
> 浏览器重启不管用，清理浏览器缓存才好使，不过今天又出现了，复现率有点高

今天发现这个问题，用你的方法可以了
