### ISSUE TITLE
chatGPT用不了？我已经用了美国的VPN了。。。

### ISSUE THREAD

**Issue by yangameng** [chathub-dev/chathub#770]
![image](https://github.com/chathub-dev/chathub/assets/75940154/7868d3a5-dce0-4ebc-abf1-38461806b2cf)
怎么设置才能用？客服能不能给解决一下？

**Comment by wong2** [comment]
<img width="491" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/afb329ff-7fd8-458e-9286-2281e9e9f6e3">

你没有填写自己的API key呀

**Comment by yangameng** [comment]
买你们的会员还需要这个吗？那这个付费会员有什么意义？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月4日(周一) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chathub-dev/chathub] chatGPT用不了？我已经用了美国的VPN了。。。 (Issue #770)




  
你没有填写自己的API key呀

**Comment by wong2** [comment]
<img width="441" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/56d1e2cb-ca79-41bf-8771-2f507e284551">

付费会员提供的是列出来的这些高级功能

**Comment by wong2** [comment]
如果你需要退款，可以帮你退款
