### ISSUE TITLE
Any button for resetting all AI conversations at once?

### ISSUE THREAD

**Issue by rouninnomi** [chathub-dev/chathub#775]
Great extension, thank you! I am a fun of this extension. Today I became a premium member.

Is there any button for resetting all conversations at once?
When I want to start a new topic, I have to push clear button of each AI manually one by one. 
I hope new feature is ready. 

Thanks!

**Comment by wong2** [comment]
You can refresh the page to achieve this!

**Comment by rouninnomi** [comment]
Ah! That was a blind spot! Thank you!
