### ISSUE TITLE
20230906 Bing, 讯飞星火都用不了，请修复。

### ISSUE THREAD

**Issue by forhonourlx** [chathub-dev/chathub#777]
**Describe the bug**
bing: InvalidRequest
讯飞: {"timestamp":"2023-09-06T10:05:13.475+08:00","status":404,"error":"Not Found","path":"/iflygpt/u/chat_message/chat"}

**Comment by wong2** [comment]
更新下版本，都修复过了

**Comment by forhonourlx** [comment]
感谢。已更新，补充：(403 (https://qianwen.aliyun.com/addSession))

**Comment by wong2** [comment]
我看看

**Comment by wong2** [comment]
通义这个修好了，请更新
