### ISSUE TITLE
充值没有收到激活的连接

### ISSUE THREAD

**Issue by jianyun22** [chathub-dev/chathub#778]
**Describe the bug**
1.昨晚打开chathub插件进行充值，充值的邮箱为 yunjian323@hotmail.com
2.充值完，获取激活链接的时候，发现邮箱（yunjian323@hotmail.com）并没有申请
3.重新申请邮箱yunjian323@hotmail.com
4.再次获取激活链接，期望结果：成功获取到链接，实际：没有收到任何激活连接
**Desktop (please complete the following information):**
 - OS: Windows11
 - chrome

**Comment by wong2** [comment]
重新给你发送了一下license，请检查邮件，垃圾箱也检查一下

**Comment by jianyun22** [comment]
> 重新给你发送了一下license，请检查邮件，垃圾箱也检查一下
还是没有收到。能否发到我的其他邮箱，比如：jianyun22@126.com 感谢

**Comment by jianyun22** [comment]
> 重新给你发送了一下license，请检查邮件，垃圾箱也检查一下

![image](https://github.com/chathub-dev/chathub/assets/39075136/58ca565d-a45b-41af-bbc6-d1928543f35b)

**Comment by wong2** [comment]
又发送了一遍，邮箱是：yunjian323@hotmail.com

**Comment by wong2** [comment]
请确认邮箱没错？

**Comment by jianyun22** [comment]
还是没有收到
![image](https://github.com/chathub-dev/chathub/assets/39075136/9b1cf6b4-a274-4847-91b0-c65cdf9b4049)

**Comment by jianyun22** [comment]
我自己给自己发是能收到的
![image](https://github.com/chathub-dev/chathub/assets/39075136/999db869-083f-4d65-b95c-6afe2c8313b3)

**Comment by jianyun22** [comment]
我自己给自己发是能收到的
![image](https://github.com/chathub-dev/chathub/assets/39075136/a37cc3ee-b9d4-4bd8-996f-4d892a72cffe)

**Comment by jianyun22** [comment]
我自己给自己发是能收到的
![image](https://github.com/chathub-dev/chathub/assets/39075136/368b2624-e55b-4b62-b512-5bb3a48cb87b)

**Comment by wong2** [comment]
你这个邮箱好奇怪。。我帮你退款了，请换个邮箱购买吧
