### ISSUE TITLE
手抖填错了邮箱还有得救吗？

### ISSUE THREAD

**Issue by betterkunjian** [chathub-dev/chathub#779]
**Describe the bug**
邮箱填错了
![image](https://github.com/chathub-dev/chathub/assets/41765676/37d54e74-07cf-46dc-b6e7-e3df87e25cd6)

如果可以重发的话，辛苦重发到hurqle32617@chacuo.net

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
已退款，请重新用正确邮箱购买
