### ISSUE TITLE
希望能增加自适应，适配手机版

### ISSUE THREAD

**Issue by greyair** [chathub-dev/chathub#78]
![Screenshot_2023-03-16-01-11-35-362_com lemurbrowser exts-edit](https://user-images.githubusercontent.com/12966678/225388844-e3aa9002-51ca-4416-9641-cfb16089426d.jpg)

手机上面适配的不太好，希望能适配下

**Comment by situkei** [comment]
狐猴？

**Comment by alitrack** [comment]
@greyair 你用的iPhone 还是Android？ 

我也正想反馈这个问题呢，我用的是Android ，装的Yandex Browser

顺便说下，如果可以把对话部分最大话，这样手机上也会方便很多
