### ISSUE TITLE
未收到激活邮件

### ISSUE THREAD

**Issue by lpm20090618** [chathub-dev/chathub#780]
**Describe the bug**
1.已经为chathub插件进行充值，充值的邮箱为 LPM090618@outlook.com
2.充值完，获取激活链接的时候，发现邮箱未收到邮件
3更换邮箱lpm090618@icloud.com

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
没有查询到 LPM090618@outlook.com 这个邮箱关联的订单

**Comment by wong2** [comment]
查到了这个的：LPM09018@outlook.com 所以是邮箱填错了？

**Comment by lpm20090618** [comment]
是邮箱填错了 不好意思 重新发一下哈 谢谢

Oops！
________________________________
发件人: wong2 ***@***.***>
发送时间: Friday, September 8, 2023 5:42:11 PM
收件人: chathub-dev/chathub ***@***.***>
抄送: lpm20090618 ***@***.***>; Author ***@***.***>
主题: Re: [chathub-dev/chathub] 未收到激活邮件 (Issue #780)


***@***.******@***.***> 所以是邮箱填错了？

―

**Comment by wong2** [comment]
我这边没法改邮箱，我帮你退款了，用正确邮箱重新购买吧

**Comment by lpm20090618** [comment]
谢谢🙏

Oops！
________________________________
发件人: wong2 ***@***.***>
发送时间: Friday, September 8, 2023 5:47:56 PM
收件人: chathub-dev/chathub ***@***.***>
抄送: lpm20090618 ***@***.***>; Author ***@***.***>
主题: Re: [chathub-dev/chathub] 未收到激活邮件 (Issue #780)


我这边没法改邮箱，我帮你退款了，用正确邮箱重新购买吧
