### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vincentzzzxxx** [chathub-dev/chathub#781]
Do you have a lot of time? I hope you can add more tabs or some optimized way to have multiple conversations at once with all the chatbots.

你有很多时间吗？我希望你可以添加更多选项卡或一些优化的方式，以便能够同时进行多个对话，与所有的聊天机器人

**Comment by wong2** [comment]
I can't understand your request.

**Comment by Alpha-DoughJoe** [comment]
I dont think ghe realizes, at least To my understanding, that he is asking for what the paid subscription provides. he just wants it free lol
