### ISSUE TITLE
Text output much too short ? Lifetime license also ?

### ISSUE THREAD

**Issue by Mike2023a** [chathub-dev/chathub#782]
Hello, good evening! I would very much like to buy a lifetime license, is the text output longer with this license ? For some, the text is currently only 356 words, not even 1000 words are the AI. Then another question : I should buy 35 USD for the license from you and then again 20 USD for chatGPT PLUS at OpenAI.What is the sense ? Good, you have a huge selection of different AI chats, it would be good if you got chatGPT for the lifetime license. I think for me this is illogical and makes no sense! Greeting Michael

**Comment by wong2** [comment]
The benefits of ChatHub Premium are well listed on the Premium page, please checkout.
