### ISSUE TITLE
bing已登录仍然显示UnauthorizedRequest

### ISSUE THREAD

**Issue by echo-art** [chathub-dev/chathub#783]

**Comment by Rain-Good** [comment]
可能因为你的bing地区设置在中国

**Comment by ayugioh2003** [comment]
<img width="596" alt="image" src="https://github.com/chathub-dev/chathub/assets/5466631/ae32d3fd-3c71-4396-ad24-21d77c44842c">

同樣的狀況 (已在 new bing 網頁登入微軟帳號)
前幾天 bing 還可以正常運作

**Comment by wong2** [comment]
[chathub.zip](https://github.com/chathub-dev/chathub/files/12571898/chathub.zip)

试试这个版本？

**Comment by ayugioh2003** [comment]
@wong2 我回報一下我的狀況

我昨天時，還會遇到這個狀況
但在今天下午，bing 就恢復運作了 (還沒有安裝 zip)

後續有狀況再來通報

**Comment by wong2** [comment]
好的，谢谢

**Comment by ayugioh2003** [comment]
@wong2 今天早上有再測試了一下

從 chrome webstore 安裝的 chathub
又出現 UnauthorizedRequest 的提示訊息

我用 zip 檔安裝的 chathub 
new bing ai 則可以正常運作

**Comment by wong2** [comment]
@ayugioh2003 好的，说明这个修复是有效果的，我把它发布到webstore去
