### ISSUE TITLE
邮箱有效性校验

### ISSUE THREAD

**Issue by jschen1009** [chathub-dev/chathub#785]
我购买了激活码，但是好像填错了邮箱，那邮箱好像无法收发邮件，这种问题该如何处理？

**Comment by jschen1009** [comment]
@wong2 能否帮忙重新发个激活码到我邮箱（jschen1209@gmail.com） 如有必要我可以提供我的订单信息

**Comment by wong2** [comment]
购买时填的邮箱还记得吗？

**Comment by jschen1009** [comment]
jianshan_1209@yahoo.cn 或 jianshan_1209@qq.com 或 jschen1209@gmail.com  我就这三个邮箱 第一个不能用 后面两个没收到

**Comment by jschen1009** [comment]
订单时间是9月7日 01:51:40

**Comment by jschen1009** [comment]
@wong2 [jianshan_1209@yahoo.cn](mailto:jianshan_1209@yahoo.cn) 或 [jianshan_1209@qq.com](mailto:jianshan_1209@qq.com) 或 [jschen1209@gmail.com](mailto:jschen1209@gmail.com) 我就这三个邮箱 第一个不能用 后面两个没收到
订单时间是9月7日 01:51:40

**Comment by wong2** [comment]
帮你退款了，请用正确邮箱重新购买吧
