### ISSUE TITLE
Already Paid but never receive any code

### ISSUE THREAD

**Issue by tujuhtigatujuh** [chathub-dev/chathub#787]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by tujuhtigatujuh** [comment]
Hey, I made a purchase and never receive any code. If I don't get the code within an hour I request a full refund. Thanks

**Comment by wong2** [comment]
I need your email of payment to help you.

**Comment by tujuhtigatujuh** [comment]
***@***.***

**Comment by wong2** [comment]
Hi, please reply your email address from the GitHub website.

**Comment by tujuhtigatujuh** [comment]
wijayanto.wisnu@gmail.com

**Comment by wong2** [comment]
Sorry I can't find an order with this email. Please contact the payment provider LemonSqueezy for this issue: https://www.lemonsqueezy.com/help Thanks!

**Comment by tujuhtigatujuh** [comment]
I will, thanks

**Comment by tujuhtigatujuh** [comment]
I have contacted lemonsqueezy and they correct the problem. Please check if there’s a record of my payment now. Thanks.

**Comment by wong2** [comment]
Yes, there it is. And I've re-sent a recipt with the license code to you.
