### ISSUE TITLE
暗色模式plz

### ISSUE THREAD

**Issue by anserzhang** [chathub-dev/chathub#79]

**Comment by situkei** [comment]
+1  最好还能自行设置卡通头像

**Comment by puppetdevz** [comment]
同求

**Comment by puppetdevz** [comment]
同求暗黑模式

**Comment by X3vvv** [comment]
可以尝试Chrome插件：dark reader

**Comment by shadow-hg** [comment]
+1，自己手动强行改了一个版本，但是版本更新一下就没了

**Comment by lqmike** [comment]
+1, dark mode please thank you

**Comment by Y80** [comment]
> 可以尝试Chrome插件：dark reader

这个插件只对网页生效，对插件打开的 Tab 不生效 😢

**Comment by limbia** [comment]
同求!!!

**Comment by wong2** [comment]
Dark mode is here: https://github.com/chathub-dev/chathub/releases/tag/v1.9.4

**Comment by Y80** [comment]
> Dark mode is here: https://github.com/chathub-dev/chathub/releases/tag/v1.9.4
👋
大佬，现在不发布 Chrome 插件商城了吗，以后都在这里 release 里发布最新版？

**Comment by wong2** [comment]
會更新到商店的，只是商店需要審核，所以要等幾天

**Comment by wong2** [comment]
已更新到商店
