### ISSUE TITLE
Bing is requestiong Captcha everytime I asked a question with mutltiple AIs

### ISSUE THREAD

**Issue by tujuhtigatujuh** [chathub-dev/chathub#790]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
Did you solve it once?

**Comment by tujuhtigatujuh** [comment]
I did, and it keep asking me again for every new messages

Sent via Superhuman ( ***@***.*** )

**Comment by eakiyama** [comment]
Me too. Is there a solution?

**Comment by wong2** [comment]
Fixed in latest version
