### ISSUE TITLE
Someone copied your extension

### ISSUE THREAD

**Issue by Explosion-Scratch** [chathub-dev/chathub#792]
See
https://github.com/SingularityLabs-ai/MultiGPT-mini/commit/4488c061ddf77b4b1f82a4640cf859548427d05c

You can see in the code that they directly copied it, because all the code is the same, also @wong2 is referenced several times (looks like they forgot to find and replace):

https://github.com/SingularityLabs-ai/MultiGPT-mini/commit/4488c061ddf77b4b1f82a4640cf859548427d05c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R29-R36

**Comment by wong2** [comment]
Thanks, I've noticed this project previously, but seems there's nothing we can do about it.
