### ISSUE TITLE
Error using Bing - InternalServerError: Error processing request

### ISSUE THREAD

**Issue by kaz875** [chathub-dev/chathub#794]
**Describe the bug**
When starting a new bing session, running into this error: InternalServerError: Error processing request.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browse: Chrome

**Comment by Jasmine-V-LehmanCollege** [comment]
i have the same error. Do you still have the error?

**Comment by wong2** [comment]
Please try again with the latest version.
