### ISSUE TITLE
Bing异常：Failed to fetch

### ISSUE THREAD

**Issue by Lion176** [chathub-dev/chathub#795]
![image](https://github.com/chathub-dev/chathub/assets/97778001/9994fd5e-f199-425e-a122-433c7e7b689e)
报错：Failed to fetch (https://www.bing.com/turing/conversation/create)
请检查您的网络连接，中国用户可能需要科学上网

网络是正常的，谷歌浏览器里可以正常访问newbing

**Comment by wong2** [comment]
解决了？

**Comment by Lion176** [comment]
可能是我机场的问题，我今天换了一家新的机场

Lion Y ***@***.***>于2023年9月18日 周一15:36写道：
