### ISSUE TITLE
BUG:Bing ServiceClient failure for UserOffense

### ISSUE THREAD

**Issue by Lion176** [chathub-dev/chathub#798]
**Describe the bug**
Bing报错：ServiceClient failure for UserOffense
 ---> Failed to call "UserOffense" at "https://WestUS2.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=InternalServerError - ReasonPhrase=Internal Server Error.

![image](https://github.com/chathub-dev/chathub/assets/97778001/4081a149-1233-4593-9473-d7bd6caba4cd)
![image](https://github.com/chathub-dev/chathub/assets/97778001/293f6fd9-0ab2-4738-ab3c-c2c2129c7119)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome,]

**Comment by chinaperrin** [comment]
I'm having the same problem. 
chathub v1.37.2
OS: [Windows]
Browser [Edge]

**Comment by wong2** [comment]
Please upgrade to the latest version from chrome web store
