### ISSUE TITLE
技术咨询：各位大佬。GPT的API限速每分钟3次，为什么ChatHub可以没有限速？

### ISSUE THREAD

**Issue by yuch25** [chathub-dev/chathub#800]
如题，用ChatHub调用API可以一直问，没有限速问题。但用Python调用一分钟只能三次，请问各位大佬，这类工具是如何实现突破API限速的？

**Comment by wong2** [comment]
通过 api key 调用的？

**Comment by yuch25** [comment]
> 通过 api key 调用的？

是呀，用下面Python代码一分钟只能3次。
import openai
openai.api_key = 'sk-XXXXXXXXXXXXXXXXXXXXXXXXXX'
response = openai.ChatCompletion.create(
                      model="gpt-3.5-turbo",
                      messages=[{"role": "system", "content":prompt_system},
                                {"role": "user", "content": prompt_sentence + "\n" + prompt_user}
                               
想问问ChatHub的API模式是怎么实现突破3次限制的呀？ 
![image](https://github.com/chathub-dev/chathub/assets/56544472/b48d5d57-0c31-4608-abda-81476b495953)

**Comment by wong2** [comment]
没做什么特殊的，调用限制应该是跟着你的key来的
