### ISSUE TITLE
llmsys chatbot 无法加载返回消息

### ISSUE THREAD

**Issue by 0smboy** [chathub-dev/chathub#802]
**Describe the bug**
llmsys的几个bot都无法响应消息，返回的错误都是一致的：
```js

ChatMessageList-83ed97fc.js:50404 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at ChatMessageList-83ed97fc.js:50404:1612
    at ChatMessageList-83ed97fc.js:64:1947
```
<img width="1745" alt="image" src="https://github.com/chathub-dev/chathub/assets/91452062/9d60da53-08bc-4730-a279-3f704b2069f4">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser : Chrome Version 116.0.5845.187 (Official Build) (arm64)

**Comment by wong2** [comment]
It seems you're using an outdated version of ChatHub, please upgrade.

**Comment by 0smboy** [comment]
@wong2 I compiled it with the latest code and the models are all the latest models from llmsys!
