### ISSUE TITLE
Claude Pro?

### ISSUE THREAD

**Issue by Ajijic23** [chathub-dev/chathub#805]
Would be great to use Claude Pro (much greater limits to chats) with ChatHub...

For example I'm using ChatHub for the first time today and it's already giving me error for Claude:
"You’ve reached the daily free message limit for this model"
Perhaps because it hasn't been 24h since my last usage... annoying though.  We need Claude Pro.

**Comment by wong2** [comment]
If you have subscribed to Claude Pro at claude.ai, you can use it by switching to webapp mode in ChatHub setting
<img width="358" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/305f0380-ea8f-40fc-af20-71a6744e65dd">
