### ISSUE TITLE
I got the following BadRequest error and kept being denied the use of chathub.

### ISSUE THREAD

**Issue by nolecruiser** [chathub-dev/chathub#812]
**Describe the bug**
I usually search chathub in my desktop.  but today I used it in my lap top. searching several general questions in Korean, and all of a sudden got the folllowing error message and could never recover the normal state again.

ServiceClient failure for UserOffense ---> Failed to call "UserOffense" at "https://koreasouth.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details:

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - my ID and email     nolecruiser@gmail.com
![chathub_error_bad_request](https://github.com/chathub-dev/chathub/assets/75657370/71dd1448-90a2-4acf-94dd-becc707f408b)

**Comment by Rapahannock** [comment]
Got the same error. Thought it was the Lemur browser I use on Android, but I get the same error using Edge.

**Comment by nolecruiser** [comment]
Thank you for the message.   What can I do then?   Is there any way to
contact the company and ask for a solution?

2023년 9월 29일 (금) 오전 9:20, Rapahannock ***@***.***>님이 작성:

**Comment by nolecruiser** [comment]
I am not familiar with this Q&A system, I only posted here because I
couldn't find any other channel to raise the issue with anybody.

2023년 9월 29일 (금) 오전 9:23, David K ***@***.***>님이 작성:

**Comment by Rapahannock** [comment]
No this is the right channel to report issues. Other users may chime in but the developer will look to resolve.

**Comment by Jasmine-V-LehmanCollege** [comment]
I also have this error with bing. so far bard and chat gpt works fine.

**Comment by ayugioh2003** [comment]
same situation

![image](https://github.com/chathub-dev/chathub/assets/5466631/ac97c9cf-890b-40ca-b4ad-c0275cac4057)

**Comment by BravoiOS** [comment]
same here

<img width="527" alt="CleanShot 2023-09-29 at 20 32 40@2x" src="https://github.com/chathub-dev/chathub/assets/7866559/b036cf91-db3e-471c-962f-a0da6994bf36">

**Comment by nolecruiser** [comment]
The problem still remains the same.   Is this a chathub problem ?   or a MS Bing problem ?    What channel could I address this problem?   chathub ?  MS ?

**Comment by skhaki99** [comment]
Me with the same issue in Korea :-(
![image](https://github.com/chathub-dev/chathub/assets/147015306/54177f01-7839-488a-8633-1a466e83aadb)

It seems that this problem depends on devices.
Because I've been using chathub in my personal laptop, and bing chat in chathub was working well !

I want to solve this problem quickly.
Let me know if anyone solved this issue. Thank you :-)

**Comment by skhaki99** [comment]
I got a news from another post.
@wong2 is replied the post like this :
![image](https://github.com/chathub-dev/chathub/assets/147015306/81d30c07-30e7-4ee3-8dfe-62e77da48ec8)

So, as soon as he came back from vacation, this issue will be solved, I hope. :-P

https://github.com/chathub-dev/chathub/issues/813

**Comment by wong2** [comment]
This has been fixed in the latest version v1.38.0, please upgrade from Chrome web store.

**Comment by nolecruiser** [comment]
Thank you so so so much for letting me know this !!!

2023년 10월 5일 (목) 오후 7:20, wong2 ***@***.***>님이 작성:
