### ISSUE TITLE
Bing error "ServiceClient failure for UserOffense"

### ISSUE THREAD

**Issue by Jasmine-V-LehmanCollege** [chathub-dev/chathub#813]
**Describe the bug**

Hi, thank you for this fantastic app. I love it, and having ChatGPT, Bing, and Bard, an all-in-one search extension, is fantastic. I bought the premium plan, and even though I am getting an error using Bing, it is still totally worth it. Thank you. Keep up the excellent work. 

The error I am having with Bing is:

"ServiceClient failure for UserOffense ---> Failed to call "UserOffense" at "https://EastUS2.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details:"
 
 
**Desktop (please complete the following information):**

 - OS: [Windows 10]
 - Browser [Edge]

**Comment by 3L1AS** [comment]
Similar Error in Chrome: ServiceClient failure for UserOffense
 ---> Failed to call "UserOffense" at "https://NorthEurope.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details:

**Comment by Darrenlijc** [comment]
Still, get this error today

Btw:
- OS: MacOS 14.1
- Browser: Chrome

**Comment by wong2** [comment]
Sorry, I'm on a vacation,it will be a few days before I can access to a computer.

**Comment by Rapahannock** [comment]
Enjoy your vacation! Don't worry about Bing issues, they can wait.

**Comment by wong2** [comment]
This has been fixed in the latest version v1.38.0, please upgrade from Chrome web store.

**Comment by Jasmine-V-LehmanCollege** [comment]
the chrome store still has version 1.37

**Comment by dengwanc** [comment]
Edge store still has version 1.37.2, thx fixed the issue

**Comment by wong2** [comment]
Yeah Edge store is waiting for review. Please upgrade from Chrome web store now.

**Comment by wong2** [comment]
Please install v1.38.0 from https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

**Comment by Jasmine-V-LehmanCollege** [comment]
@wong2, thank you so much for your dedication to this app. It is working beautifully now.
