### ISSUE TITLE
My mistake, I can’t give a response to that right now. Let’s try a different topic.

### ISSUE THREAD

**Issue by wukan1986** [chathub-dev/chathub#82]
回答一些问题时，回答到一半，忽然全删，改成了"My mistake, I can’t give a response to that right now. Let’s try a different topic."

能否将此屏蔽？

**Comment by rushabhT3** [comment]
I also get this from the bing ai chat bot and even after mentioning this multiple times nothing has happened

**Comment by wong2** [comment]
Bing has some limitation on topics it can talk.
