### ISSUE TITLE
在使用Ｂing聊天中，总是出现"ServiceClient failure for UserOffense  ---> Failed to call "UserOffense" at "https://koreasouth.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details:"   最新版本Ｖ1.37.2仍未能解决此问题？

### ISSUE THREAD

**Issue by slevonshen** [chathub-dev/chathub#822]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by Jasmine-V-LehmanCollege** [comment]
yes he closed my thread and posted it is fix in version 1.38 I am wondering if it is posted to download somewhere else or do we have to update it manually.

**Comment by Rapahannock** [comment]
> yes he closed my thread and posted it is fix in version 1.38 I am wondering if it is posted to download somewhere else or do we have to update it manually.

Possibly close out of your browser and relaunch. Also note that some browser remain open in the background when you think you've closed it. I checked today without downloading anything in addition, nor manually updating any extensions and its back working.

**Comment by Jasmine-V-LehmanCollege** [comment]
I deleted it and rebooted my computer, and edge extension is still displaying the latest version 1.37

**Comment by wong2** [comment]
Please install v1.38.0 from https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

**Comment by slevonshen** [comment]
Thank you!  The problem has sovled already!&nbsp;


柘桑木
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月6日(星期五) 下午2:03
收件人: "chathub-dev/chathub";
抄送: "Author";
主题: Re: [chathub-dev/chathub] 在使用Ｂing聊天中，总是出现&quot;ServiceClient failure for UserOffense  ---&gt; Failed to call &quot;UserOffense&quot; at &quot;https://koreasouth.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide&quot;. StatusCode=BadRequest - ReasonPhrase=Bad Request. Details:&quot;   最新版本Ｖ1.37.2仍未能解决此问题？ (Issue #822)





 
Closed #822 as completed.
 
&mdash;
