### ISSUE TITLE
CHATHUB is UPDATED on Chrome, NOT on Edge Browser

### ISSUE THREAD

**Issue by Jasmine-V-LehmanCollege** [chathub-dev/chathub#824]
**Describe the bug**

Hello, Please update the CHATHUB Extension at the Edge Browser Store. It is updated in the CHROME Store. However, I don't use Chrome Browser. This is a School Computer. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
The Edge store review process will take about a week.

**Comment by Jasmine-V-LehmanCollege** [comment]
Okay, I closed the issue. I read in another chat that the Edge browser is waiting for a review. Thank you for your feedback. Awesome extension.

**Comment by Jasmine-V-LehmanCollege** [comment]
/
