### ISSUE TITLE
chatGPT cannot select the corresponding stock chat for continuation

### ISSUE THREAD

**Issue by onlyhuman028** [chathub-dev/chathub#83]
Thank you! The chat HUB function is very powerful and easy to use. A small suggestion: it seems that chatGPT cannot select the corresponding stock chat for continuation. I hope this feature will be available in the next version. Thanks again.
谢谢！chat HUB功能很强大。很好用。提一点小意见，chatGPT 似乎不能选择对应的存量chat进行续写。希望下一个版本有次功能。再次感谢

**Comment by wong2** [comment]
收到
