### ISSUE TITLE
Bing does not work

### ISSUE THREAD

**Issue by UMMAN2005** [chathub-dev/chathub#830]
Despite the fact that i have logged in bing chat and i literally can use it from official website, when i try to use bing in chathub i got the error below. 

UnauthorizedRequest

However i logged i  successfully. Also i have used 3 different browser.

 - OS: Windows
 - Browser Chrome, Opera, Edge

**Comment by wong2** [comment]
Which version of ChatHub are you using?

**Comment by UMMAN2005** [comment]
Well it is working now. I deleted it and built from source code. Now it is Version 1.38.1. Thanks for help. Your question make me to consider about building from source code as releases can be old and it is really like that. Thank you very much again!
