### ISSUE TITLE
ChatGPT运行错误429

### ISSUE THREAD

**Issue by one2world** [chathub-dev/chathub#832]
429
请检查您的网络连接，中国用户可能需要科学上网。

必现的方式是提问第一次正常，之后就会提示429。 如果清理重新提问， 也是第一次正常， 之后429。
我用另一款软件运行却正常。

**Comment by wong2** [comment]
你是以什么模式使用ChatGPT的？API还是webapp mode

**Comment by one2world** [comment]
api 模式， api 是找到网上免费共享的。429的时候尝试Bree AI可以正常使用

**Comment by wong2** [comment]
共享的可能遇到限速了吧
