### ISSUE TITLE
支持webpack方式构建么

### ISSUE THREAD

**Issue by allentown521** [chathub-dev/chathub#833]
这样不需要每次修改完代码重新reload了，github上有不少这样的脚手架，不知道目前是否支持

**Comment by allentown521** [comment]
突然发现项目中vite config代码，是不是用的这个模板：https://github.com/JohnBra/vite-web-extension
可以用vite方式构建吧

**Comment by wong2** [comment]
是的，目前就是用vite的呀，而且支持HMR

**Comment by wong2** [comment]
yarn dev 即可

**Comment by allentown521** [comment]
good job
