### ISSUE TITLE
bing返回的结果为啥与官网的效果差距很大

### ISSUE THREAD

**Issue by luyajun01** [chathub-dev/chathub#836]
**Describe the bug**
如题，举例：
<img width="1166" alt="image" src="https://github.com/chathub-dev/chathub/assets/4561365/c722eb8f-fae0-496e-b1eb-7656882e1683">
<img width="370" alt="image" src="https://github.com/chathub-dev/chathub/assets/4561365/a255d7d7-8e5f-409f-8d88-cfb20aa85209">

麻烦看下

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Browser [e.g. edge dev] 
 - chathub version 1.38.1

**Comment by wong2** [comment]
看起来你这Bing官网用的是creative模式，在ChatHub里也是吗？

**Comment by luyajun01** [comment]
是的一样的
2023年10月16日 +0800 10:48 wong2 ***@***.***>，写道：

**Comment by luyajun01** [comment]
对于Bing还有2个问题，第一，按理来说返回的值应该都有“你好，这是必应”这样的开头语吧？第二，为啥我的Bing的对话历史记录里面找不到在chathub上的对话记录
2023年10月16日 +0800 10:48 wong2 ***@***.***>，写道：
