### ISSUE TITLE
请问：chatgpt为什么会提示429

### ISSUE THREAD

**Issue by lakie0605** [chathub-dev/chathub#838]
您好：
     购买了付费会员、chatgpt是api模式、api是自己的、梯子是自己私有的。
     apiHost用的腾讯云搭建的硅谷的云函数（能ping通）但是还是出现了429。
 感谢解答

**Comment by lakie0605** [comment]
请问OpenAI的apiHost的具体url能提供一下吗

**Comment by wong2** [comment]
把你填的清空就可以了，默认会使用openai的

**Comment by lakie0605** [comment]
那就不行，还是429

**Comment by lakie0605** [comment]
然后我切换回云函数的apihost，查看日志，是请求成功了的
START RequestId: 6cae7f7d14ac052819252fd3e127021f[HPM] Proxy created: /  -> https://api.openai.comExample app listening at http://localhost:9000Init Report RequestId: 6cae7f7d14ac052819252fd3e127021f Coldstart: 129ms (PullCode: 0ms InitRuntime: 3ms InitFunction: 126ms) Memory: 64MB MemUsage: 15.57MBEND RequestId: 6cae7f7d14ac052819252fd3e127021fReport RequestId: 6cae7f7d14ac052819252fd3e127021f Duration: 170ms Memory: 64MB MemUsage: 17.03MB

**Comment by lakie0605** [comment]
请问能怎么解决吗？刚冲了会员就不能用

**Comment by lakie0605** [comment]
已解决，谢谢

**Comment by wong2** [comment]
是什么原因呢？

**Comment by lakie0605** [comment]
chatgpt欠费了
