### ISSUE TITLE
你好，我充值邮箱写错了，收不到验证码

### ISSUE THREAD

**Issue by zhuanzhuansama** [chathub-dev/chathub#839]
你好，我充值时，因为失误把邮箱后缀 @gmail.com 写成了 @gmil.com，导致收不到验证码。可以申请退款吗
订单号：2023101722001339171447166678
商家订单号：src_1O2AeIEkNJHWF29kCPvtqWvs

**Comment by wong2** [comment]
你好，应该是这个吧 rliumeow@gmil.com 我帮你退款了

**Comment by zhuanzhuansama** [comment]
已收到退款，谢谢～

wong2 ***@***.***> 于2023年10月18日周三 11:06写道：
