### ISSUE TITLE
Bing Issue

### ISSUE THREAD

**Issue by 3L1AS** [chathub-dev/chathub#842]
I am a pro user and use the extension daily, love it! 

Unfortunately, since today Bing does not work and shows this error:

"InternalServerError: Error processing request."

Did they change something in the API?

 - OS: Windows 11
 - Browser: Chrome

**Comment by wong2** [comment]
Which version of chathub are you using?

**Comment by 3L1AS** [comment]
1.38.2

**Comment by 3L1AS** [comment]
Never mind, seems to work again. Not sure why it did not before. Sorry for bothering you.
