### ISSUE TITLE
隔壁ChatAll一直在更新支持更多的模型，请求支持更多模型

### ISSUE THREAD

**Issue by zangwill** [chathub-dev/chathub#846]
开发者你好，隔壁[ChatAll](https://github.com/sunner/ChatALL)一直在更新支持更多的模型，感觉[chathub](https://github.com/chathub-dev/chathub)支持的有点少了，是否可以更多地支持一些
![image](https://github.com/chathub-dev/chathub/assets/19372775/7da27517-975e-453b-9e0e-cd8c275bf1c6)

**Comment by wong2** [comment]
你最需要哪些？

**Comment by zangwill** [comment]
并不是都需要，但是感觉ChatAll的理念很好，可以更好地从不同模型中选答案。

ChatALL ：

- 🤠大模型重度玩家，希望从大模型找到最好的答案，或者最好的创作
- 🤓大模型研究者，直观比较各种大模型在不同领域的优劣
- 😎大模型应用开发者，快速调试 prompt，寻找表现最佳的基础模型
[支持的 AI](https://github.com/sunner/ChatALL/blob/main/README_ZH-CN.md#%E6%94%AF%E6%8C%81%E7%9A%84-ai)

**Comment by wong2** [comment]
会挑一些效果好的增加
