### ISSUE TITLE
能否在All in one界面增加一个横向滑动条，并支持横向滚动

### ISSUE THREAD

**Issue by zangwill** [chathub-dev/chathub#847]
开发者你好，如图，是否可以在图中横线的位置再添加一条横向滚动条，并支持横向滚动，让其他所有启用的AI都可以显示在上面。

 ![image](https://github.com/chathub-dev/chathub/assets/19372775/0cd8002d-5c5d-4b27-bff4-1993b0f5d03d)

**Comment by wong2** [comment]
横向滚动是很差的体验，不考虑增加
