### ISSUE TITLE
建议作者添加一个选择之后弹出提示，一键给大模型发送选择的内容。大模型可以选择自己的账号

### ISSUE THREAD

**Issue by Rgoogle** [chathub-dev/chathub#849]
![image](https://github.com/chathub-dev/chathub/assets/93381523/1e228c45-55c2-4cad-8ff5-357c4ced5e70)
![image](https://github.com/chathub-dev/chathub/assets/93381523/225dd86d-8729-4794-ac72-ed9a4a645578)
还有一个功能就是，能不能使用bard模型的时候，用自己的账号啊？？？比如gpt3.5可以接入poe官网的免费的。比如用我自己是poe账号。这样就不用你们的token了

**Comment by wong2** [comment]
Bard模型现在就是使用你自己的账号的，如果你在浏览器里登出了Google账号会发现它无法使用了
