### ISSUE TITLE
I can’t find the license key after WeChat payment, and now I can’t activate premium membership

### ISSUE THREAD

**Issue by SagaCere** [chathub-dev/chathub#850]
**Describe the bug**
There is no email sent to my mailbox, what should I do now

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Comment by wong2** [comment]
What is your email address?

**Comment by SagaCere** [comment]
***@***.***

**Comment by SagaCere** [comment]
> 您的电子邮件地址是什么？

ContrerasBrandon1tnty5@gmail.com

**Comment by wong2** [comment]
I can't find an order with this email. If you're charged, please contact the payment provider LemonSqueezy https://www.lemonsqueezy.com/help

**Comment by SagaCere** [comment]
> 我找不到使用此电子邮件的订单。如果您被收费，请联系支付提供商 LemonSqueezy https://www.lemonsqueezy.com/help

Can you try the two email addresses camilla-shy@qq.com or 2026036309@qq.com again? I’m not sure which one was used at the time.

**Comment by wong2** [comment]
None of them.

**Comment by wong2** [comment]
If you're charged, please contact the payment provider LemonSqueezy https://www.lemonsqueezy.com/help
