### ISSUE TITLE
啊，Claude账号也被封掉了

### ISSUE THREAD

**Issue by Jieoz** [chathub-dev/chathub#852]
**Describe the bug**
![](https://p.sda1.dev/13/ef5d74a5caeef83a7e666f7074182885/Snipaste_2023-10-23_09-13-53.png)
使用了一天之后
![](https://p.sda1.dev/13/e8236d94b91ae8e3f747a1077b32f281/Snipaste_2023-10-23_09-17-19.png)
**Desktop (please complete the following information):**
 - OS:Windows 11
 - Browser chrome

**Comment by xiaoniu2014** [comment]
被封的也太快了

**Comment by wong2** [comment]
😭

**Comment by Gin8527** [comment]
注册了2个号，第2个注册完用了一次就被封了
