### ISSUE TITLE
Bing官网与chathub的功能有相差

### ISSUE THREAD

**Issue by evelynn996** [chathub-dev/chathub#853]
使用bing可以生成图片
![image](https://github.com/chathub-dev/chathub/assets/93717293/4f8255bf-0663-44ed-a6a7-7205c1775b8e)
![image](https://github.com/chathub-dev/chathub/assets/93717293/75000018-1bca-4ef5-a8ab-0f3caa25a84c)

然而在chathub上不太行？
![image](https://github.com/chathub-dev/chathub/assets/93717293/be3ef6e3-54c5-4e34-a29c-46944ce67731)

**Comment by wong2** [comment]
还不支持生成图片
