### ISSUE TITLE
WebSocket closed with reason:  (1006).

### ISSUE THREAD

**Issue by hongyang51** [chathub-dev/chathub#86]
![image](https://user-images.githubusercontent.com/13972600/225583624-15aff9cb-c9c5-479f-a7a1-d2d8e512b853.png)

乌班图 使用 Clash 科学上网，Bing 会有这个异常错误，ChatGpt正常。

不太清楚这个WebSocket 怎么过滤掉。

**Comment by Mickychen00** [comment]
Same in My Macbook Pro M1

**Comment by HLRJ** [comment]
WebSocket closed with reason:  (1006).

**Comment by TianChen2017** [comment]
WebSocket closed with reason:  (1006).

This is really annoying. Hope it can be fixed. Cheers.

**Comment by wjlu** [comment]
我也有这个问题

**Comment by kebaxing** [comment]
换下节点

**Comment by Oraer** [comment]
的确，更换节点就可以了

**Comment by hongyang51** [comment]
![image](https://user-images.githubusercontent.com/13972600/236613705-fb9502a0-d284-47cd-b9a8-4206e0cef6d0.png)
我的原因是 之前是默认的socks端口号 没有写对。 修改成上图就好了

**Comment by cindynap** [comment]
我也有这个问题，我在墙外，不需要换节点啊
