### ISSUE TITLE
chatgpt无响应

### ISSUE THREAD

**Issue by Long-louis** [chathub-dev/chathub#860]
**Describe the bug**
询问webapp模式的chatgpt时会像下面一样无响应，而且在gpt网页内新建了相应的无响应对话，报错如第二张图。但是在chatgpt网页内直接提问是正常的。
![image](https://github.com/chathub-dev/chathub/assets/41790869/7e753248-6ec8-4dea-a2a2-00c1a1c9b74a)
![image](https://github.com/chathub-dev/chathub/assets/41790869/63fd9308-03f3-4210-84f0-24f8054b7058)

**Desktop (please complete the following information):**
 - OS: Windows[e.g. Windows]
 - Browser ： Edge[e.g. chrome, brave]

**Comment by MageYes** [comment]
我在询问webapp模式的chatgpt时，会遇到 Unexpected agent error。但在chatgpt网页内直接提问也是正常的。

**Comment by Mjmaster** [comment]
今天他chatgpt勾选“联网搜索”后，会显示“Unexpected agent error”。不勾选联网搜索则正常。

**Comment by gongzhaoman** [comment]
之前3.5不需要arkose_token的，现在需要了。4之前是不是一直都需要啊，好像也有解决的，有谁知道解决方案给指一个路谢谢。

**Comment by wong2** [comment]
请更新到最新版v1.38.3 https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

**Comment by gongzhaoman** [comment]
> 请更新到最新版v1.38.3 https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

我的是1.38.3也不行

**Comment by wong2** [comment]
@gongzhaoman 奇怪，我在1.38.3里对3.5也开启了arkose token，我这边是正常了

**Comment by gongzhaoman** [comment]
> @gongzhaoman 奇怪，我在1.38.3里对3.5也开启了arkose token，我这边是正常了

我刚刚重启了一下浏览器，好了

**Comment by wong2** [comment]
好的！
