### ISSUE TITLE
chathub里bing的回答有误，而网页版的bing回答正确

### ISSUE THREAD

**Issue by Mjmaster** [chathub-dev/chathub#861]
**Describe the bug**
问题：滴灌通有什么风险吗？

在Chathub的bing里，回答是错误的。而在bing网页和bing app里的回答是正确的，请见截图。

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - 
![2023-10-24 17_17_18-ChatHub](https://github.com/chathub-dev/chathub/assets/19359947/80a461cb-62c3-4662-b484-7aecdf9d4682)
![2023-10-24 17_17_33-配备 GPT-4 的必应聊天](https://github.com/chathub-dev/chathub/assets/19359947/8fdae965-d5e0-4229-878c-c1862279aea4)

**Comment by wong2** [comment]
你这个Bing有点奇怪，正常来说Bing的顶部不应该有 “联网搜索” 的，请卸载重装最新版再试试？

**Comment by wong2** [comment]
<img width="1118" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/27664a43-f6a8-4ccd-9f49-c008038f3fb8">

**Comment by wong2** [comment]
<img width="1036" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/ee42d160-dc79-43b3-9896-e43d200bbd86">

**Comment by wong2** [comment]
感觉这个问题应该还是大模型自身的随机性问题

**Comment by Mjmaster** [comment]
这确实挺奇怪的，我又试了几次。网页版每次都是正确的，哈哈哈。算了，就这样吧，不纠结了。

![2023-10-24 22_06_19-配备 GPT-4 的必应聊天](https://github.com/chathub-dev/chathub/assets/19359947/16cae774-1ff3-4b34-b95f-281caacced60)
![2023-10-24 22_08_52-配备 GPT-4 的必应聊天](https://github.com/chathub-dev/chathub/assets/19359947/6280d480-cce3-48eb-88e2-670100ef0019)

**Comment by wong2** [comment]
我猜是因为每个账号对这个关键词搜索结果不同，再加上大模型的不确定性
