### ISSUE TITLE
ChatGPT not working

### ISSUE THREAD

**Issue by vincentllora** [chathub-dev/chathub#862]
**ChatGPT not working**
When trying to use ChatGPT, there is no response, only the three pulsating dots. I open https://chat.openai.com/ in another tab and it works fine.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by wong2** [comment]
Please upgrade to latest version v1.38.3, which fixed this issue

https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

**Comment by SeanBannister** [comment]
Still experiencing this with 1.38.5.

**Comment by wong2** [comment]
@SeanBannister Can you describe what you're experiencing?

**Comment by SeanBannister** [comment]
When I attempt to send a message to ChatGPT I see the 3 loading dots indefinitely.
