### ISSUE TITLE
Pi Issue

### ISSUE THREAD

**Issue by 3L1AS** [chathub-dev/chathub#864]
Pi seems to have some issue: 

{"error":"No remaining trial turns.","code":"no_remaining_trial_turns"}

 - OS: [Windows]
 - Browser [chrome]

**Comment by wong2** [comment]
Please try login at pi.com

**Comment by 3L1AS** [comment]
Ah. That fixed it. Thanks for the hint.

**Comment by 3L1AS** [comment]
Ah. That fixed it. Thanks for the hint.
