### ISSUE TITLE
是否有计划做成网页应用呢

### ISSUE THREAD

**Issue by lilinrestart** [chathub-dev/chathub#865]
或者我要做成网页应用该从哪里入手：）ps：没接触过ts这样的前端代码

**Comment by wong2** [comment]
插件的很多能力网页做不到

**Comment by lilinrestart** [comment]
> 插件的很多能力网页做不到

后面有计划做一个prompt的编辑模块吗，这个还是挺实用的

**Comment by wong2** [comment]
什么意思呢

**Comment by lilinrestart** [comment]
> 什么意思呢

就是我有很多个prompt模板我想存下来用，不用每次都重新写，或者有一个prompt模板库可以上传

**Comment by wong2** [comment]
![image](https://github.com/chathub-dev/chathub/assets/321947/be90766f-9f4a-422e-a03c-ccdd3d3783d1)
有这个功能呀，你点这个图标
