### ISSUE TITLE
把PI的对话框改成别的引擎之后，改不回PI了

### ISSUE THREAD

**Issue by Indexv2021** [chathub-dev/chathub#866]
**Describe the bug**

**Desktop:**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
![image](https://github.com/chathub-dev/chathub/assets/91307377/7c1f3159-bc30-429d-b0b0-75b59a58b690)

**Comment by wong2** [comment]
收到 UI上有点问题

**Comment by Indexv2021** [comment]
这里是来自青春活力粥送糖的回复，您的邮件我已收到，感谢！

**Comment by zangwill** [comment]
暂时可以用键盘的上下键调整

**Comment by wong2** [comment]
你这个好像不是UI的问题，需要在设置里面把Pi这个bot开启

**Comment by Indexv2021** [comment]
> 你这个好像不是UI的问题，需要在设置里面把Pi这个bot开启

现在还是不行。不过过了一段时间之后pi又有了。

**Comment by Indexv2021** [comment]
> 你这个好像不是UI的问题，需要在设置里面把Pi这个bot开启

嗯嗯，设置里找到了
