### ISSUE TITLE
Translator

### ISSUE THREAD

**Issue by vincentzzzzzz** [chathub-dev/chathub#867]
Hi, I have bought and used ChatHub since the early days, but what makes me a bit uncomfortable is the browser's default translator and other extensions like Mouse Tooltip Translator, Monica ((I quite like the bilingual translation feature of this extension). bilingual translation of this extension) cannot work on ChatHub. Hope you can help to get these working on ChatHub, I think it's very necessary, thank you very much.

**Comment by wong2** [comment]
That's a limitation of the browser, that extensions can not work on other extensions.
