### ISSUE TITLE
chatgpt访问异常，网页版可以正常响应

### ISSUE THREAD

**Issue by jschen1009** [chathub-dev/chathub#868]
![image](https://github.com/chathub-dev/chathub/assets/31001147/e529b7b7-9afd-4624-9535-2a691737038b)

**Comment by wong2** [comment]
请更新到最新版：https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

**Comment by jschen1009** [comment]
更新后正常了 谢谢

**Comment by jschen1009** [comment]
![image](https://github.com/chathub-dev/chathub/assets/31001147/c831ce31-b691-434d-a31f-782db9619b2d)
通义千问访问异常

**Comment by wong2** [comment]
@jschen1009 请开一个新的issue
