### ISSUE TITLE
通义千问访问报“Error: undefined undefined”错误

### ISSUE THREAD

**Issue by jschen1009** [chathub-dev/chathub#870]
![image](https://github.com/chathub-dev/chathub/assets/31001147/fc78ef04-2126-42e8-825c-4b211a546722)

**Comment by wong2** [comment]
请更新到最新版 1.38.7

https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma
