### ISSUE TITLE
Error: WebSocket closed with reason:  (1006). 

### ISSUE THREAD

**Issue by mbilotti321** [chathub-dev/chathub#871]
I am consistently getting this error: WebSocket closed with reason:  (1006). for Llama 2, Wizard LM, and Vicuna; ChatGPT does not have this error, but just spins and spins. I've closed and restarted. This has been going on for days. 

**Desktop (please complete the following information):**
 - OS: Windows 22H2
 - Browser: Chrome

**Comment by wong2** [comment]
Which version are you using?
Please upgrade to latest version and try again https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma?utm_source=chathub.gg

**Comment by mbilotti321** [comment]
It seems to have helped, thank you!
