### ISSUE TITLE
返金してください

### ISSUE THREAD

**Issue by skunk0915** [chathub-dev/chathub#872]
**Describe the bug**
実際のGPT3.5と比較して精度が低すぎる。これでは使えない。プレミアムのキャンセルをしてください。

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment]
Which ChatGPT mode are you using?

**Comment by skunk0915** [comment]
GPT3.5

**Comment by skunk0915** [comment]
実際の出力例の比較

![Group 33](https://github.com/chathub-dev/chathub/assets/10370744/db8d8c4f-d4eb-4e59-8242-52ebc3248d09)

**Comment by Neal050617** [comment]
Can you try disabling online search and then give it a shot?

**Comment by skunk0915** [comment]
期待する動作になった。OK。
