### ISSUE TITLE
ChatGPT {"detail":"Disallowed CORS origin chrome-extension://iaakpnchhognanibcahlpcplchdfmgma"}

### ISSUE THREAD

**Issue by zhouyusd** [chathub-dev/chathub#874]
**Describe the bug**
{"detail":"Disallowed CORS origin chrome-extension://iaakpnchhognanibcahlpcplchdfmgma"}

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Comment by wong2** [comment]
Are you still facing this?

**Comment by zhouyusd** [comment]
Now it's good.
