### ISSUE TITLE
Is there a feature roadmap? Some features I'm looking for

### ISSUE THREAD

**Issue by nszumowski-champlain** [chathub-dev/chathub#875]
Features I'd love in Premium that I've noticed in a few other extensions:

- GitHub PR summarization
- Inclusion in Google search results regarding search query
- Current web page summarization

**Comment by wong2** [comment]
These features are out of the scope of ChatHub, so there is no plan to implement them in the near future. Thanks for suggesting!

**Comment by SpanishHearts** [comment]
Too sad, I was just about to purchase premium but if this is missing the ability to summarize pages and YouTube videos, it's out of my use-cases.
