### ISSUE TITLE
Is it possible to add a customized instruction feature?

### ISSUE THREAD

**Issue by BrianZ96** [chathub-dev/chathub#876]
Like the free version of the ChatGPT, gives the option and possibility to add some constant customized instructions for every new conversation.

**Comment by wong2** [comment]
Do you mean the "Custom Instructions" feature?

**Comment by BrianZ96** [comment]
Hi wong2, yes, exactly this function.

**Comment by wong2** [comment]
If you're using ChatGPT webapp mode in ChatHub, it will respect your Custom Instructions set on the ChatGPT website.
As for API mode, there's no Custom Instructions api available.
