### ISSUE TITLE
趁你们促销付了款又用不了。无法登陆无法激活

### ISSUE THREAD

**Issue by fashion8888888** [chathub-dev/chathub#881]
啥情况？付了款不能激活？点击管理设备与订单要留邮箱登入。输入了邮箱收到一个链接点击进去又是一片空拍？然并卵。购买流程体验非常差了

**Comment by wong2** [comment]
付款之后你应该会收到一封邮件，里面有激活码，然后在插件里使用这个激活码激活

**Comment by fashion8888888** [comment]
我重新购买了一次。这次似乎成功了。第一次购买没有收到邮件。登入后也看不到订单。刚又付了一次款收到了邮件。以表支持

**Comment by fashion8888888** [comment]
Order #2589
