### ISSUE TITLE
提示：你已经达到了该模型今日免费消息上限

### ISSUE THREAD

**Issue by fashion8888888** [chathub-dev/chathub#882]
购买并激活高级会员第一次使用提示:你已经达到了该模型今日免费消息上限。 这是poe.com的限制。请指导如何排除故障。一次都还没有用上。谢谢
![b3](https://github.com/chathub-dev/chathub/assets/150023584/108201aa-db34-48e2-b9d6-e404dd8fc934)

**Comment by wong2** [comment]
你应该是选了poe的GPT-4和Claude模型吧，它是有非常少的用量限制的，你可能发了一条就达到限制了。建议使用webapp模式（需要自己有OpenAI账号）或者API模式（需要自己有OpenAI的API key）

**Comment by fashion8888888** [comment]
你应该是选了poe的GPT-4和Claude模型吧---是的；我想高级会员是可以选择此项。

**Comment by wong2** [comment]
我明白了，您可能对ChatHub高级会员的功能有所误解，它并不为您提供GPT-4的访问权限，您仍然需要自己有方法访问GPT-4，如ChatGPT Plus或OpenAI API key。ChatHub高级会员提供的功能在购买前的页面列的很清楚。

**Comment by fashion8888888** [comment]
是的。购买前是通过弹出的促销页面引导并快速付款。第一次未成功（已发贴）第二次购买并体验的。确实没有感受到成会付费会员带来的好处。测试了一下并不再试了。看来还只能是通过网页的收藏夹直接进入对应的官网使用较为方便。

**Comment by wong2** [comment]
不需要这些高级会员功能的话，可以帮你退款

**Comment by fashion8888888** [comment]
好的。请帮我退款。。给你们带来不便非常抱歉。谢谢

**Comment by wong2** [comment]
![image](https://github.com/chathub-dev/chathub/assets/321947/33337e8f-e0f1-400e-9db6-dd005d602169)

发现我这里还退不了，你这个订单被风控了（应该也是你第一笔购买付了钱但没有收到邮件的原因）。
这个情况需要你找支付服务商LemonSqueezy客服退款了 https://www.lemonsqueezy.com/help 告诉他们你的邮箱，让他们退你两笔的钱

**Comment by fashion8888888** [comment]
好的。我尝试
