### ISSUE TITLE
Paid ... no email... cant login

### ISSUE THREAD

**Issue by Alpha-DoughJoe** [chathub-dev/chathub#884]
I paid for a premium subscription week ago and have since been able to get in touch with anybody or access premium features i've set up an email specifically for this issue somebody from the project please reach out I am no longer even sure which email connected 2 but I have the billing statement as proof thank you

alphaagg-hubissue@abine.org

**Comment by bbsnakelhb** [comment]
Me too. I use WeChat Pay, No emails received!

**Comment by wong2** [comment]
Hi, if you're not receiving emails after payment, please contact the payment provider LemonSqueezy at https://www.lemonsqueezy.com/help It happens randomly with payment from WeChat Pay or Alipay.
