### ISSUE TITLE
ChatGLM2、WizardLM、Mistral、Falcon、Vicuna、Llama 2查询反馈如下报错

### ISSUE THREAD

**Issue by strengthen8** [chathub-dev/chathub#886]
WebSocket closed with reason: (1006).

**Comment by wong2** [comment]
你的ChatHub版本是？

**Comment by strengthen8** [comment]
v1.39.0，我是付费用户。

**Comment by wong2** [comment]
<img width="535" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/096c7374-7336-4955-b62d-ff77b318bd96">

请更新到最新版，会有关于这个报错的提示

**Comment by strengthen8** [comment]
更新后点击网站后，可以了，谢谢！
