### ISSUE TITLE
提供chathub的api接入

### ISSUE THREAD

**Issue by luoysuan** [chathub-dev/chathub#887]
能否为付费用户提供chathub的api接入？

**Comment by wong2** [comment]
ChatHub的API指什么呢

**Comment by luoysuan** [comment]
> ChatHub的API指什么呢

类似gpt的开放的api，希望通过api的方式执行提问请求

**Comment by wong2** [comment]
哦这个做不到，ChatHub是一个纯浏览器端的应用（相当于ChatGPT的前端），没办法对外提供API

**Comment by luoysuan** [comment]
> 哦这个做不到，ChatHub是一个纯浏览器端的应用（相当于ChatGPT的前端），没办法对外提供API

chatgpt的逆向api能否提供一下相关的资料呢

**Comment by wong2** [comment]
全都在代码里了

**Comment by luoysuan** [comment]
> 全都在代码里了
不会ts，能和我说一下具体在什么文件里面吗

**Comment by wong2** [comment]
提供付费咨询

**Comment by luoysuan** [comment]
已经付费过了 还需要其它付费吗？

> 提供付费咨询

**Comment by wong2** [comment]
当然，为软件付费和为软件背后的原理付费是两回事

**Comment by luoysuan** [comment]
> 当然，为软件付费和为软件背后的原理付费是两回事
什么价格呢

**Comment by wong2** [comment]
¥500/小时
