### ISSUE TITLE
可以提供 GPT-4-1103的 model 吗

### ISSUE THREAD

**Issue by gxfantasy** [chathub-dev/chathub#888]
目前只有 GPT-4

**Comment by wong2** [comment]
更新到最新版，有 gpt-4-turbo 了

**Comment by quduoduo** [comment]
1.39.1还看不到

**Comment by wong2** [comment]
最新版是 1.39.2

**Comment by msly** [comment]
@wong2   gpt-3.5-turbo-1106是3.5的最新版, Developers can access this new model by calling gpt-3.5-turbo-1106 in the API. Applications using the gpt-3.5-turbo name will automatically be upgraded to the new model on December 11.

**Comment by wong2** [comment]
@msly 这个我也加一下

**Comment by BrianZ96** [comment]
报错说没有manifest怎么办呢

**Comment by wong2** [comment]
@BrianZ96 请描述清楚，你做了什么，产生了这个结果？

**Comment by wong2** [comment]
最新版 v1.39.3 已经把 gpt-3.5-turbo 模型更新到了最新版
