### ISSUE TITLE
仅有Bing问答无法使用

### ISSUE THREAD

**Issue by strengthen8** [chathub-dev/chathub#889]
Failed to fetch (https://www.bing.com/turing/conversation/create)

请检查您的网络连接，中国用户可能需要科学上网

试过切换其它VPN也是一样。

**Comment by wong2** [comment]
代理切换到全局模式试试

**Comment by strengthen8** [comment]
就是全局模式的

**Comment by wong2** [comment]
那你打开 https://www.bing.com 截图看看

**Comment by strengthen8** [comment]
![image](https://github.com/chathub-dev/chathub/assets/26496661/5bcecb2d-21cd-4ce6-ab47-c95bca04d4cd)

**Comment by wong2** [comment]
国内版 😂 没有Chat功能，你在网上搜一下切换到国际版的方法吧，长这样：
<img width="1387" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/6f8eb519-86f6-4624-bfc0-3e051508d34d">
