### ISSUE TITLE
使用usage疑惑

### ISSUE THREAD

**Issue by BrianZ96** [chathub-dev/chathub#892]
Hi 开发组成员：

之前我一直再用Edge的add-on来获得最新版的chathub，但是目前我看到edge add-on的最新版本仍是1.38.2，而非release里最新的tag 1.39.3. 我曾尝试过下载.zip然后解压拖拽到edge的add-on页面，但是他会提醒无效的manifest文件。我看到以前的1.38.1的压缩包里面有一个manifest，但是最新的1.39.3压缩包里有的是manifest.tf。

请问还有什么其他渠道可以获取到集成在Edge中的最新版本chathub呢？

感谢！

**Comment by wong2** [comment]
你下载的.zip应该是源代码，但这个项目是需要编译使用的。
请在 https://github.com/chathub-dev/chathub/releases/tag/v1.39.3 下载最新的编译版本安装
