### ISSUE TITLE
wechat已支付后，显示支付失败。无收到激活码。

### ISSUE THREAD

**Issue by cmlcc88** [chathub-dev/chathub#896]
wechat已支付后，显示支付失败。无收到激活码。

**Comment by wong2** [comment]
您的邮箱是？

**Comment by cmlcc88** [comment]
***@***.***
这一个是付款的时候录入的邮箱
________________________________
发件人: wong2 ***@***.***>
发送时间: 2023年11月14日 11:39
收件人: chathub-dev/chathub ***@***.***>
抄送: suicm ***@***.***>; Author ***@***.***>
主题: Re: [chathub-dev/chathub] wechat已支付后，显示支付失败。无收到激活码。 (Issue #896)


您的邮箱是？

―

**Comment by wong2** [comment]
请在GitHub的界面回复您的邮箱，通过邮件回复的邮箱地址会被GitHub打码

**Comment by cmlcc88** [comment]
> 请在GitHub的界面回复您的邮箱，通过邮件回复的邮箱地址会被GitHub打码

c.mlcc@hotmail.com

**Comment by wong2** [comment]
你好，我无法找到您的订单。如果您已被扣款，请联系支付服务提供方LemonSqueezy的客服：https://www.lemonsqueezy.com/help 可能是支付被风控了
