### ISSUE TITLE
paid, sent email, still not working

### ISSUE THREAD

**Issue by dextroslabs666** [chathub-dev/chathub#898]
**Describe the bug**

been trying to fix this, it wont really run more than 2 ai models at a time, occaisional 3 from llama / mistral LMSYS hosted, not sure how these work. but im regretting paying 45$ for the app so far for not much capabilities other than "for 45$ i can now i can change the background..

"websocket error"

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : [ OPERA, EDGE, CHROME]
 - ChatHub Version Settings (v1.39.4)

**Comment by wong2** [comment]
I'm not sure I understand you correctly, do you mean you're getting "websocket error" when using llama / mistral ?

**Comment by dextroslabs666** [comment]
yes

**Comment by wong2** [comment]
Please follow the instructions in the extension when this occurs.
