### ISSUE TITLE
Adapt to Android mobile phone users.

### ISSUE THREAD

**Issue by kongqig** [chathub-dev/chathub#90]
News writers can adapt the page to mobile users and use it in browsers that support mobile plug-ins. The page of this plug-in is very strange, especially when the mobile phone is in portrait, the page effect is very bad.
I hope the author can solve and adapt, thank you.

**Comment by HenMie** [comment]
> News writers can adapt the page to mobile users and use it in browsers that support mobile plug-ins. The page of this plug-in is very strange, especially when the mobile phone is in portrait, the page effect is very bad. I hope the author can solve and adapt, thank you.

There are more suitable apps available on Android that are more convenient than browser plugins. For example, the one I use on Android is "ChatBoost", and there are many similar apps you can search for.

**Comment by wong2** [comment]
This extension does not aim for use on mobile devices
