### ISSUE TITLE
请检查您的网络连接，中国用户可能需要科学上网

### ISSUE THREAD

**Issue by warmth-baixf** [chathub-dev/chathub#902]
我已开启vpn全局模式并能成功访问chatGPT和google，但是使用chathub仍然报错，请检查您的网络连接，中国用户可能需要科学上网

**Comment by quduoduo** [comment]
同样问题

**Comment by wong2** [comment]
ChatGPT使用了哪种模式？

**Comment by quduoduo** [comment]
API

**Comment by wong2** [comment]
截图看看报错信息

**Comment by quduoduo** [comment]
![image](https://github.com/chathub-dev/chathub/assets/6185000/2678a451-d621-4c0d-946f-73e8bca2642a)

**Comment by wong2** [comment]
这个是你的代理ip被封了
