### ISSUE TITLE
bing网页里面可以正常使用，但是在Chathub里面提示错误

### ISSUE THREAD

**Issue by xiyan818** [chathub-dev/chathub#905]
bing在Chathub里面会提示如下错误，但是我在网页中打开bing的时候，是可以正常使用bing chat的
![image](https://github.com/chathub-dev/chathub/assets/44111611/ff68e909-709d-4b03-acd1-368c1a3ed53d)

**Comment by zasl** [comment]
![image](https://github.com/chathub-dev/chathub/assets/17813691/9f80cbff-89d7-4c3d-b7d6-df4b4129cfe8)
情况一样，我是这个错误
