### ISSUE TITLE
chatGPT keep loading Bing UnauthorizedRequest

### ISSUE THREAD

**Issue by Long-louis** [chathub-dev/chathub#906]
Describe the bug
Already upgraded to v1.39.8
![image](https://github.com/chathub-dev/chathub/assets/41790869/96afa277-78f4-488b-8193-c3d31e79399b)
When asking Bing for the first time, it will prompt UnauthorizedRequest, then asking again will be fine.
In webapp mode, chatGPT always shows three dots loading. But opening chat.opeai.com can ask questions normally.
![image](https://github.com/chathub-dev/chathub/assets/41790869/a205189d-4d6d-46e5-95ff-686307bbb103)

Desktop (please complete the following information):
- OS: [e.g. Windows]
- Browser [e.g. chrome, brave]
- ChatHub Version [you can find it in ChatHub Settings]

**Comment by SeanBannister** [comment]
I can also confirm my Chat GPT hasn't worked for weeks, just the 3 dots when i ask a question, no responses at all on my end.

**Comment by wong2** [comment]
Hopefuly the next version will solve this problem

**Comment by wong2** [comment]
Please upgrade to the latest version: https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma
