### ISSUE TITLE
我购买了激活码，进行二次开发。然后收到激活提示，这有影响吗？

### ISSUE THREAD

**Issue by bookmarkbao** [chathub-dev/chathub#911]
**Describe the bug**
我购买了激活码，进行二次开发。然后收到激活提示，这有影响吗？
同一台电脑，由于打包时就提示要激活码，我就不断激活，最后就变成超过5次激活数。怎么解决呢。实际上，就在一台电脑，同一个浏览器，开发模式下不断激活而已。按理，开发模式不应该不受激活码影响么，或者可以识别出是不同设备。
<img width="836" alt="image" src="https://github.com/chathub-dev/chathub/assets/61926298/04068660-2c76-4b46-88a9-0e85d8269173">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by wong2** [comment]
问题解决了？
