### ISSUE TITLE
GPT4 又不能用了😭

### ISSUE THREAD

**Issue by luokebi** [chathub-dev/chathub#914]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by wong2** [comment]
嗯今天OpenAI升级了防护策略，我已经修复了，请等待新版本

**Comment by luokebi** [comment]
是 1.41.1 吗，我看 3 小时前更新的

**Comment by wong2** [comment]
1.42.0 还没发出来

**Comment by luokebi** [comment]
坐等😭

**Comment by wong2** [comment]
https://chromewebstore.google.com/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma?utm_source=chathub.gg 更新了
