### ISSUE TITLE
Claude Permission Error

### ISSUE THREAD

**Issue by Rapahannock** [chathub-dev/chathub#915]
**Describe the bug**
Claude's only response is {"error":{"type":"permission_error","message":"Invalid model","code":"model_not_allowed"}}
Tried clearing cache, etc. This is occurring on multiple devices.

**Desktop (please complete the following information):**
 - OS: Windows, Android
 - Browser: Edge, LemurBrowser
 - ChatHub Version: 1.42.0 (Chrome Plugin)

![error](https://github.com/chathub-dev/chathub/assets/45186344/e431bd83-832d-4149-82c7-6a165cba96ce)

**Comment by wong2** [comment]
Thanks for reporting! Claude has changed their model today, I will update ChatHub soon.

**Comment by wong2** [comment]
Should be fixed in the latest version: https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma
