### ISSUE TITLE
Add models from labs.perplexity.ai

### ISSUE THREAD

**Issue by PhillipRt** [chathub-dev/chathub#917]
Reasons to support labs.perplexity.ai:
- completely free
- Supports multiple default and finetuned llama models
- inference is a lot faster than lmsys
- has custom finetuned llama models that are uncensored
- supports perplexity search in the online models with up to date information

**Comment by wong2** [comment]
ChatHub has supported perplexity labs model since v1.42.0

**Comment by PhillipRt** [comment]
Oh did not realise that the edge version was outdated, great work. 
Would be nice if the llama 2 model from lmsys could be switched to the llama-2-70b-chat from perplexity labs as lmsys always ends the session

**Comment by wong2** [comment]
Sure, I'll implement that in the future.

**Comment by GITHUBTRASHACCOUNT** [comment]
also implement perpelixy ai , bing ai, claude2 inside of chatgpt4 for chrome extension

**Comment by wong2** [comment]
@GITHUBTRASHACCOUNT I don't understand it.

**Comment by Bian-Sh** [comment]
收到
