### ISSUE TITLE
bing 登录成功后，发起提问，聊天窗口提示报错

### ISSUE THREAD

**Issue by Frank-MJ** [chathub-dev/chathub#92]
Cannot read properties of undefined (reading 'value')

**Comment by ApocalypsezZ** [comment]
+1

**Comment by jian2450** [comment]
+1

**Comment by freejenyu** [comment]
+1

**Comment by wangyoucao577** [comment]
+1

**Comment by wong2** [comment]
+1 的朋友，报的错是 `Cannot read properties of undefined (reading 'value')` 还是 404？

**Comment by DCxDESIGN** [comment]
> +1 的朋友，报的错是 `Cannot read properties of undefined (reading 'value')` 还是 404？

![image](https://user-images.githubusercontent.com/48208459/226114514-f038ce59-6f81-4e9a-8a0a-71b8788136ab.png)

**Comment by wong2** [comment]
可以看看这个请求的响应是什么吗？

**Comment by DCxDESIGN** [comment]
> 可以看看这个请求的响应是什么吗？

抱歉我不是前端所以不太懂，是要看这个吗：

![image](https://user-images.githubusercontent.com/48208459/226115346-d33b496b-6322-4a07-ac8d-856198dd7c76.png)

**Comment by Larry-Louis** [comment]
我今天也报了这个，好像是代理ip被bing封了。。。

**Comment by wong2** [comment]
可以看下你们的插件的版本号吗？我怀疑实际上是这个问题：#99

**Comment by DCxDESIGN** [comment]
> 

我的是 1.4.2，而且一直开着代理

**Comment by wong2** [comment]
@DCxDESIGN 你试试 v1.5.2呢？https://github.com/chathub-dev/chathub/issues/99#issuecomment-1475103330

**Comment by DCxDESIGN** [comment]
> @DCxDESIGN 你试试 v1.5.2呢？[#99 (comment)](https://github.com/chathub-dev/chathub/issues/99#issuecomment-1475103330)

1.5.2 问题依旧
![image](https://user-images.githubusercontent.com/48208459/226159077-6814580f-386e-4bde-81e6-9aec9c1bc60b.png)

不过我发现确实是代理节点的问题，换成别的节点就好了，我去找服务商确认一下

**Comment by wong2** [comment]
@DCxDESIGN 如果你还能复现，可以帮我看看吗？

<img width="668" alt="image" src="https://user-images.githubusercontent.com/321947/226161226-5eaace5c-4718-46a5-bcb7-daf1d4eb0fec.png">

在开发者工具的 Network/网络 里找到一个名为 ”create“ 的请求，切换到 Response/响应 看看里面的内容是什么

**Comment by DCxDESIGN** [comment]
> 在开发者工具的 Network/网络 里找到一个名为 ”create“ 的请求，切换到 Response/响应 看看里面的内容是什么

![image](https://user-images.githubusercontent.com/48208459/226170217-7bfc0fcc-9438-41cf-a2c6-cbd61a6d22ee.png)

**Comment by DCxDESIGN** [comment]
正常情况下是这样：

![image](https://user-images.githubusercontent.com/48208459/226170399-924b37b4-3312-4c1d-921a-31c5f15603f3.png)

**Comment by wong2** [comment]
> > 在开发者工具的 Network/网络 里找到一个名为 ”create“ 的请求，切换到 Response/响应 看看里面的内容是什么
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/48208459/226170217-7bfc0fcc-9438-41cf-a2c6-cbd61a6d22ee.png)
> 
> 

可以把“标头”左边的x点一下再截个图吗

**Comment by DCxDESIGN** [comment]
![image](https://user-images.githubusercontent.com/48208459/226170960-d963fbe3-22f1-4a75-8797-1ba195760774.png)

这样吗

**Comment by wong2** [comment]
好的 谢谢

**Comment by wong2** [comment]
[debug.zip](https://github.com/chathub-dev/chathub/files/11010766/debug.zip)

@DCxDESIGN 可以安装这个包试试看吗？安装方法：
<img width="737" alt="image" src="https://user-images.githubusercontent.com/321947/226171448-446dccb7-064c-4d12-a58f-6127ea258674.png">

**Comment by DCxDESIGN** [comment]
> [debug.zip](https://github.com/chathub-dev/chathub/files/11010766/debug.zip)
> 
> @DCxDESIGN 可以安装这个包试试看吗？安装方法： <img alt="image" width="737" src="https://user-images.githubusercontent.com/321947/226171448-446dccb7-064c-4d12-a58f-6127ea258674.png">

抱歉刚看到，试了下，可以用了，是因为增加了一个 edgeservices.bing.com 的请求吗

**Comment by wong2** [comment]
对的

**Comment by DCxDESIGN** [comment]
好的，那么期待商店版更新了

**Comment by wong2** [comment]
Release了 v1.5.3 https://github.com/chathub-dev/chathub/releases
插件商店也已提交审核

**Comment by wong2** [comment]
修复该问题的 v1.5.3 版本已更新到Chrome Web Store！

**Comment by pc439527** [comment]
1.6 今天开始报这个错
![image](https://user-images.githubusercontent.com/71417700/227412696-aa7a482a-96e6-4cc4-9284-bad893d76cd3.png)

**Comment by pc439527** [comment]
换节点可以了~估计被ban了

**Comment by vachelxiong** [comment]
V1.8.1，试了下，也是：Cannot read properties of undefined (reading 'value')。下载debug.zip，按提示操作了，也不行。悲催。辛苦@Wong2 啦。

**Comment by dslwz2008** [comment]
同样问题，无法使用

**Comment by wong2** [comment]
试试这个包：https://github.com/chathub-dev/chathub/issues/164#issuecomment-1482452818

**Comment by shy-song** [comment]
新包还是跳出了错误提示，两个包都试过了

**Comment by shanzhendao** [comment]
Yes, indeed it is still not necessary to use. The above prompts still exist. Could you please provide a solution? Thank you.

**Comment by shanzhendao** [comment]
我刚才尝试了一下，把节点从美国换成了英国，就可以使用了。
I just tried it out and switched the node from the US to the UK, and now it works.

**Comment by lwkin** [comment]
无法使用，提示：Cannot read properties of undefined (reading 'value')，怎么操作？使用的是最新版的1.8.3

**Comment by wong2** [comment]
换换代理

**Comment by vv-l** [comment]
使用了最新版本后可以用了，并且配置了X-Forwarded-For。

**Comment by wong2** [comment]
最新版本自带了 X-Forwarded-For

**Comment by Lorelei0619** [comment]
![image](https://github.com/chathub-dev/chathub/assets/131435633/8a7a2bd1-0f4c-41a3-bf1f-ca7e4b5f3c6b)
这个报错的主要原因是？~

**Comment by wong2** [comment]
Bing要使用代理
