### ISSUE TITLE
在 ChatGPT 使用第三方 API 时提示 400 Bad Request

### ISSUE THREAD

**Issue by xiyan818** [chathub-dev/chathub#920]
在 ChatGPT 使用第三方 API 时提示 400 Bad Request
但是第三方 API 在别的软件上使用是没有问题的
![image](https://github.com/chathub-dev/chathub/assets/44111611/dfd561c3-a5d2-439c-b278-c11af873c344)

**Comment by wong2** [comment]
什么第三方api，怎么设置的呢？

**Comment by xiyan818** [comment]
![image](https://github.com/chathub-dev/chathub/assets/44111611/a02bbfc3-5d2f-4a49-975f-eab71aefa232)
在这里设置的，不是 openai 官方 api，是第三方的 api

**Comment by wong2** [comment]
我需要知道你的API host填写了什么才能帮你

**Comment by namezzy** [comment]
我的也是.使用第三方的就报错：https://oneapi.withlevi.top/ 使用自己搭建的

**Comment by namezzy** [comment]
使用自己搭建的在上个版本使用是gpt4.0是没有问题的 只有gpt3.5提示404 然后更新最新版本之后gpt3.5和4.0都会报错404

**Comment by xiyan818** [comment]
![image](https://github.com/chathub-dev/chathub/assets/44111611/d17c45b5-2c3a-4cf1-a542-b49b1dcc9ff6)

**Comment by LuRenJiasWorld** [comment]
似乎是因为有些API假定content一定是字符串，如果传入的是数组就会出现400错误。

![image](https://github.com/chathub-dev/chathub/assets/29622423/7f198a05-8b81-4d3d-8fb7-3a8f8b1ed1ff)

**Comment by wong2** [comment]
有可能！

**Comment by LuRenJiasWorld** [comment]
> 有可能！

我使用的是 https://openai-hk.com/ 可供参考

**Comment by xiyan818** [comment]
这方面我不太懂。我需要做些什么来规避这个问题呢？

> 有可能！

**Comment by wong2** [comment]
可能需要我改一下，兼容这种情况，我研究看看

**Comment by wong2** [comment]
已修复 v1.42.3 https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma
