### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by xiaoxuanNLP** [chathub-dev/chathub#922]
一直出现500。我是用python程序访问，没有问题。不是我的代理的问题。我三台电脑最近使用chathub都出现这个问题，使用的是API模式
![屏幕截图 2023-11-27 151403](https://github.com/chathub-dev/chathub/assets/43531566/c7745e26-35e1-467b-80e8-1dabdd3dfa10)

**Comment by wong2** [comment]
API模式下使用的是openai官方的host还是自己搭的？

**Comment by xiaoxuanNLP** [comment]
是自己搭的，但是我保证api的访问是没有问题的，python程序可以正常访问

**Comment by wong2** [comment]
那估计和这个是一个原因：https://github.com/chathub-dev/chathub/issues/920 等下个版本修复

**Comment by xiaoxuanNLP** [comment]
好的，我再提供一个现象。之前我一直是正常使用，在北京时间11.24以后三台电脑陆续出现500的情况，期间我没有更改任何配置

**Comment by wong2** [comment]
嗯问题已经找到并修复了，在等待Chrome插件商店审核

**Comment by wong2** [comment]
已更新v1.42.3 https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma
