### ISSUE TITLE
购买会员已缴费，但显示失败“Can't capture Stripe payment. No payment intent found for cart e641a35c-88a2-494e-a4c2-c7c5440250c4”

### ISSUE THREAD

**Issue by tianjizixia** [chathub-dev/chathub#924]
购买会员已缴费，但显示失败“Can't capture Stripe payment. No payment intent found for cart e641a35c-88a2-494e-a4c2-c7c5440250c4”

**Comment by wong2** [comment]
请提供下邮箱

**Comment by Roger1111111** [comment]
我是永久会员，重启了一下电脑，就无法再登陆了，用了Key登陆，显示使用次数到达上限，咋回事呢

**Comment by Roger1111111** [comment]
我的邮箱是zhenli98@hotmail.com, Order number是#433

**Comment by wong2** [comment]
@Roger1111111 https://app.lemonsqueezy.com/my-orders/ 在这里管理

**Comment by Roger1111111** [comment]
> @Roger1111111 https://app.lemonsqueezy.com/my-orders/ 在这里管理

那个Key不能用了，能否给个新的啊
