### ISSUE TITLE
Summarize multiple chats

### ISSUE THREAD

**Issue by SeanBannister** [chathub-dev/chathub#928]
I'll often chat to 6 chatbots and then read all of their responses to find the best one. Which I presume is why most people use the multi-chat feature.

I've noticed I can speed up the process of reading all the responses by copying all of the results and asking a chatbot to summarize them. I'm amazed at how often this is the best possible answer.

This would be an amazing feature to add if this process could be automated.

My very simple prompt at the moment looks like this:

I asked six AI chatbots [question] they responded with the following, please summarize these responses:
"[Response1]"
"[Response2]"
"[Response3]"
"[Response4]"
"[Response5]"
"[Response6]"

**Comment by wong2** [comment]
Nice idea!

**Comment by teddante** [comment]
I really like this as well, just opened an issue only to see this, it's a great idea!

**Comment by SeanBannister** [comment]
Thank you so much for implementing this, absolutely amazing.
