### ISSUE TITLE
请问一次买断付费，可以同时激活几台设备？

### ISSUE THREAD

**Issue by lionqy163** [chathub-dev/chathub#930]
请问一次买断付费，可以同时激活几台设备？

**Comment by wong2** [comment]
5 devices

**Comment by lionqy163** [comment]
请问定义一台设备的标准是什么？
激活后的设备能否取消激活，进行设备的更换？

**Comment by lionqy163** [comment]
> 5 devices

请问定义一台设备的标准是什么？
激活后的设备能否取消激活，进行设备的更换？

**Comment by wong2** [comment]
每次激活操作算一次，反激活就减一

**Comment by lionqy163** [comment]
> 每次激活操作算一次，反激活就减一

请问有计划接入“文心一言”么？

**Comment by wong2** [comment]
文心一言接起来有点麻烦，效果又没那么好
