### ISSUE TITLE
完全用不了啊，全部都是无法连接

### ISSUE THREAD

**Issue by ljw0808** [chathub-dev/chathub#931]
国内用不了，不是chatgpt国内无法建立账号，就是Failed to establish websocket connection.还是麻烦退一下款吧

**Comment by ljw0808** [comment]
邮箱是873526574@qq.com

**Comment by caichicong** [comment]
退回到v1.38.5就正常了，貌似是新版的bug

**Comment by wong2** [comment]
已退
