### ISSUE TITLE
Setting ChatGPT API Model to "gpt-4-32k" returns a 404 error.

### ISSUE THREAD

**Issue by SeanBannister** [chathub-dev/chathub#932]
**Describe the bug**
When I set the ChatGPT to "API Mode" and set the "API Model" to "gpt-4-32k", sending a message to ChatGPT returns a 404 error. All other models work fine.

![image](https://github.com/chathub-dev/chathub/assets/197231/20fdc487-1fbe-41cd-99c8-e7b8394a78dd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - ChatHub Version: v1.42.3

**Comment by wong2** [comment]
Yes I get the same result. It seems that gpt-4-32k is not open to everyone yet.

**Comment by SeanBannister** [comment]
here's details for anyone else wondering... https://community.openai.com/t/request-for-update-on-gpt-4-32k-or-16k-release/309160
