### ISSUE TITLE
在官网以及其他第三方APP中正常，但ChatHub中无法使用ChatGPT，报错404！

### ISSUE THREAD

**Issue by imFeige** [chathub-dev/chathub#935]
**Describe the bug**
前提是，网络正常，第三方ChatGPT软件以及ChatGPT官网，以及其他AI模型都可以正常使用！
但是使用ChatGPT则报错： 404 提示请检查您的网络连接，中国用户可能需要科学上网
使用的API模式，API在第三方APP中正常使用！

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser: Chrome
 - ChatHub Version: v1.43.1
<img width="1016" alt="image" src="https://github.com/chathub-dev/chathub/assets/72223743/ccb82b58-3e3b-4bc8-a858-3ca2d0abc9e6">

**Comment by imFeige** [comment]
就是OpenAI官网生成的API

**Comment by imFeige** [comment]
<img width="708" alt="image" src="https://github.com/chathub-dev/chathub/assets/72223743/54d3aaa5-5fc6-4be0-8bb9-7e993db20421">
即使使用Webapp 模式也一样报错404~很奇怪！ChatGPT官网正常问答

**Comment by imFeige** [comment]
我也很奇怪，之前一直正常使用，就刚才突然发现出问题，以为网络不对，我使用的分流规则有OpenAI分组，bard和claude，都正常，然后又去官网试了下GPT也正常，我使用的第三方APP是opencat，也正常！所以来提问~

**Comment by wong2** [comment]
试了下我这里还是正常的，要不你卸载重装下试试？

**Comment by imFeige** [comment]
我是付费会员，卸载重装不影响吧？需要再次激活？

**Comment by imFeige** [comment]
不用了，莫名其妙的又好了~关贴了，感谢耐心回复！真是奇怪~~哈哈

**Comment by wong2** [comment]
太好了
