### ISSUE TITLE
Perplexity输入api后依然无法连接，但是官网能正常使用

### ISSUE THREAD

**Issue by Juneone96** [chathub-dev/chathub#936]
![image](https://github.com/chathub-dev/chathub/assets/140543869/904f7c94-8a10-4031-b61c-0fad37a18455)

**Comment by Juneone96** [comment]
> ![image](https://private-user-images.githubusercontent.com/140543869/287461671-904f7c94-8a10-4031-b61c-0fad37a18455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzYwMjMsIm5iZiI6MTcwMTUzNTcyMywicGF0aCI6Ii8xNDA1NDM4NjkvMjg3NDYxNjcxLTkwNGY3Yzk0LThhMTAtNDAzMS1iNjFjLTBmYWQzN2ExODQ1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxNjQ4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWI1YjJkMmMwMTBmODQ2MzYwN2JmYTA0ZTJjZjJjYTIzZmU3NzNiNjI0MDY0NTc3NjJkNzVhNmQwM2EzNDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s_dyTpRZrq7NLG7ARqOoHfYnOzFrZ6VfjWWHZR3bDE4)

但是切换到webapp模式时对话框内也能正常使用，确认api配置无误

**Comment by Juneone96** [comment]
> 所以是webapp模式正常，API模式不行对吧。 Perplexity的API key是按照这个步骤来的吗？https://docs.perplexity.ai/docs 注意要预充值点数

是的，api已经配置好了，能正常计费，但还是不行（前段时间突然可以了，结果今天重新下载插件后又出现了这样的问题）

**Comment by wong2** [comment]
怀疑是网络问题，你切换下代理节点试试
