### ISSUE TITLE
上传插件到Edge插件商店

### ISSUE THREAD

**Issue by andywowws** [chathub-dev/chathub#94]
没有VPN上不了谷歌插件商店

**Comment by NJYZ-96** [comment]
可是你都能到这里来进行反馈了，为什么还会有上不了谷歌的困扰呀？感觉好矛盾

**Comment by wangwangdalibaohahaha** [comment]
> 可是你都能到这里来进行反馈了，为什么还会有上不了谷歌的困扰呀？感觉好矛盾

这个随便上

**Comment by NJYZ-96** [comment]
> > 可是你都能到这里来进行反馈了，为什么还会有上不了谷歌的困扰呀？感觉好矛盾
> 
> github不需要vpn也能上啊。。。

额，我的逻辑是：能到github来找到这个项目并注册账号反馈，代表你应该有较强的信息搜集能力，有这样能力的人想要使用Google应该不困难才对；
再者，相比于使用谷歌插件商店，似乎注册ChatGPT账号更加困难；
所以我有些困惑，看起来很矛盾

**Comment by andywowws** [comment]
这。。。我本来就有账户啊，再说了我是从哔哩哔哩了解到这个项目的

**Comment by wong2** [comment]
我之前上传过Edge商店被拒绝了，找时间再传一次。

**Comment by smanx** [comment]
chrome上chatgpt的插件一大堆，edge商店一个都没有，估计微软不让上

**Comment by lixinkui69** [comment]
> 

哈哈哈

**Comment by lixinkui69** [comment]
> 



> 没有VPN上不了谷歌插件商店

直接下载不行吗

**Comment by lixinkui69** [comment]
> 

直接下载

**Comment by lixinkui69** [comment]
> > > 可是你都能到这里来进行反馈了，为什么还会有上不了谷歌的困扰呀？感觉好矛盾
> > 
> > 
> > GitHub不需要VPN也能上啊。。。
> 
> 额，我的逻辑是：能到github来找到这个项目并注册搜集账号反馈，代表你应该有较强的信息能力，有这样能力的人想要使用Google应该不困难才对; 再者，相比于使用谷歌插件商店，似乎注册ChatGPT账号更加困难; 所以我有些困惑，看起来很矛盾

确实

**Comment by darkelfzdy** [comment]
我也有类似需求，但最好是直接在GitHub上提供crx的下载格式。我在公司上是从沙盒系统连接外网，根本没法使用vpn，要更新扩展只有直接安装crx，压缩文件解压安装都不行。

**Comment by funny233-github** [comment]
> > > 可是你都能到这里来进行反馈了，为什么还会有上不了谷歌的困扰呀？感觉好矛盾
> > 
> > 
> > github不需要vpn也能上啊。。。
> 
> 额，我的逻辑是：能到github来找到这个项目并注册账号反馈，代表你应该有较强的信息搜集能力，有这样能力的人想要使用Google应该不困难才对； 再者，相比于使用谷歌插件商店，似乎注册ChatGPT账号更加困难； 所以我有些困惑，看起来很矛盾

信息搜索能力强要new bing干嘛，还有不是所有人都愿意用VPN,我更趋向于合法途径

**Comment by wong2** [comment]
已上架：https://microsoftedge.microsoft.com/addons/detail/chathub-allinone-chat/kdlmggoacmfoombiokflpeompajfljga
