### ISSUE TITLE
可以增加一个模型说明页面吗 

### ISSUE THREAD

**Issue by shwezhu** [chathub-dev/chathub#945]
对比了一下 Chathub 和 Edge 上的 Bing Chat,  感觉结果差别挺大, 找了一下 README 只说用的是 bing chat, 没找到具体的, 想问下Chathub用的是最新的 Bing copilot 接口吗?

**Comment by wong2** [comment]
是的，可以发下对比吗？

**Comment by shwezhu** [comment]
> 是的，可以发下对比吗？

https://sl.bing.net/zz4FycPP88

https://shareg.pt/5W4ZA0C

都是用的 Precise 模式, 既然用的同一个, 可能因为是解析的样式, 显得差别看着很大

**Comment by shwezhu** [comment]
> > 是的，可以发下对比吗？
> 
> https://sl.bing.net/zz4FycPP88
> 
> https://shareg.pt/5W4ZA0C
> 
> 都是用的 Precise 模式, 既然用的同一个, 可能因为是解析的样式, 显得差别看着很大

Bing 的分享点进去不完整, 好奇怪

**Comment by shwezhu** [comment]
> 是的，可以发下对比吗？

<img width="654" alt="Screenshot 2023-12-09 at 19 57 41" src="https://github.com/chathub-dev/chathub/assets/54054395/68c48cce-4c4b-4f40-ac87-b29e8fb17ae8">
<img width="991" alt="Screenshot 2023-12-09 at 19 57 54" src="https://github.com/chathub-dev/chathub/assets/54054395/94f353da-58e5-4375-9385-0c3d1c604da9">
<img width="969" alt="Screenshot 2023-12-09 at 19 58 02" src="https://github.com/chathub-dev/chathub/assets/54054395/0c6f0d5b-91c8-4154-9839-b742cf2f6066">
