### ISSUE TITLE
Message that "hidden" SAVE Button

### ISSUE THREAD

**Issue by Gacode123** [chathub-dev/chathub#953]
**Describe the bug**
Because of this message, I can't click on save when I am trying to save GPTs

**Desktop (please complete the following information):**
 - OS: Windows
<img width="359" alt="BUG" src="https://github.com/chathub-dev/chathub/assets/98417387/03bb24e2-794e-497a-bced-d95f189454c2">

 - Browser Chrome
 - ChatHub Version Settings (v1.44.1)

**Comment by wong2** [comment]
Will fix soon!
