### ISSUE TITLE
Suggest adding pplx-70b-online model

### ISSUE THREAD

**Issue by chaixuqing** [chathub-dev/chathub#956]
PPLX-70B-Online is a large language model (LLM) developed by Perplexity AI, which focuses on delivering helpful, up-to-date, and factual responses. It is an online LLM, meaning it can use knowledge from the internet to provide the most up-to-date information when forming a response. 

Key features of PPLX-70B-Online include:

- **Online Access**: The model can access the latest information from the internet, enabling real-time, precise responses to queries.
- **Factual Accuracy**: Perplexity AI employs various techniques to maximize factual accuracy and minimize the generation of inaccurate statements.
- **Accessibility**: PPLX-70B-Online is publicly accessible via Perplexity's API and Labs web interface, allowing developers to integrate the technology into their own applications and websites.

Perplexity AI's PPLX-70B-Online model has been shown to outperform other leading models, such as GPT-3.5 and Llama2-70B, in terms of freshness, factuality, and overall preference.

**Comment by wong2** [comment]
Please check the setting page as ChatHub already supports the pplx model.
