### ISSUE TITLE
Placement of "Keep tab open" reminder makes other pages unusable

### ISSUE THREAD

**Issue by ralfw** [chathub-dev/chathub#957]
**Describe the bug**
As shown in these screenshots the message "Please keep the tab open" obstructs ChatGPT (and possibly other) functionality (like creating a sharable link or saving a GPT):

<img width="822" alt="Bildschirmfoto 2023-12-12 um 09 35 10" src="https://github.com/chathub-dev/chathub/assets/132662/a599ef86-4cb8-49c2-bc9e-b25e0b7b0d46">

<img width="611" alt="Bildschirmfoto 2023-12-12 um 09 34 35" src="https://github.com/chathub-dev/chathub/assets/132662/e1fe8b98-0b57-43dd-b294-b7291f41606e">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Arc
 - ChatHub Version: v1.44.1
 
 **Suggestion**
 Add a setting to let user switch off the reminder.

**Comment by wong2** [comment]
This is a bug, and it has been fixed in v1.44.2, please upgrade!
