### ISSUE TITLE
使用ChatGPT的回答都很简短，跟使用ChatGPT官网回答完全不同

### ISSUE THREAD

**Issue by nettm** [chathub-dev/chathub#958]
**Describe the bug**
最近发现使用chathub的ChatGPT怎么问，回答都很简短，而直接使用ChatGPT官网进行提问，则回答的比较全面。无论使用Webapp 模式还是API 模式都是如此，不知道是为什么。

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - ChatHub Version: v1.44.2

样例如下：
how to improve nginx performance

chathub中的回答：
![image](https://github.com/chathub-dev/chathub/assets/3842718/5203e444-5ab7-425b-9496-71e6900e72ac)

ChatGPT官网回答：
![image](https://github.com/chathub-dev/chathub/assets/3842718/1d805330-f36b-4d05-aead-f1e80d2e91e8)

**Comment by wong2** [comment]
是不是开启了“联网搜索”？

**Comment by nettm** [comment]
> 是不是开启了“联网搜索”？

关闭“联网搜索”也是如此，我特意试过。

**Comment by nettm** [comment]
> 是不是开启了“联网搜索”？

我试试，可能是这个原因。
