### ISSUE TITLE
Add Mistral API

### ISSUE THREAD

**Issue by PhillipRt** [chathub-dev/chathub#959]
Mistral just released an API for the Mistral-Medium model, which rivals GPT-4 in some benchmarks.
It would be great if it were supported. The API works exactly the same as for OpenAI, so it shouldn't be too difficult.

https://docs.mistral.ai/platform/client

**Comment by wong2** [comment]
This is now possible with the **Custom chatbots** feature in ChatHub 2.0
<img width="642" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/8f433531-246b-482f-a931-40058a7a369a">

**Comment by wong2** [comment]
https://doc.chathub.gg/custom-chatbots/mistral
