### ISSUE TITLE
前问昨天开始无法使用，访问域名好像变了，可直接访问网页

### ISSUE THREAD

**Issue by strengthen8** [chathub-dev/chathub#962]
[GET] "https://qianwen.aliyun.com": <no response> Failed to fetch
试过fan'qi翻墙与未翻墙
![image](https://github.com/chathub-dev/chathub/assets/26496661/2f9b41c6-58d0-435d-919f-731e83ff4764)
![image](https://github.com/chathub-dev/chathub/assets/26496661/a072808d-f178-4d66-89d3-3f57f240fe59)

**Comment by fankun576678634** [comment]
> 把代码中的 qianwen.aliyun.com 替换成 tongyi.aliyun.com/qianwen 就可以了

同样的问题, 请问在哪里修改?

**Comment by wong2** [comment]
我晚上更新一下

**Comment by lionqy163** [comment]
> > 把代码中的 qianwen.aliyun.com 替换成 tongyi.aliyun.com/qianwen 就可以了
> 
> 同样的问题, 请问在哪里修改?

ctrl+F，在源码里搜索

**Comment by wong2** [comment]
Chrome插件商店更新了1.45.1，修复了这个问题
