### ISSUE TITLE
Perplexity webapp doesn't work | Perplexity webapp 模式失效

### ISSUE THREAD

**Issue by imty42** [chathub-dev/chathub#967]
**Describe the bug**

Perplexity webapp doesn't work
Perplexity webapp 模式失效

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge
 - ChatHub Version: v1.45.0

<img width="956" alt="Snipaste_2023-12-19_17-10-56" src="https://github.com/chathub-dev/chathub/assets/1010013/2d60cf5f-d90a-4481-9121-90b8b4be446f">

Follow the Chathub tip, open the site, https://labs.perplexity.ai/
按提示打开：https://labs.perplexity.ai/

After one msg sent, and it blocks, can't sent any other msg.
但只能发送一条消息，之后就不可以了

Back to the Chathub extension page, send another msg, not work.
回到 Chathub 插件交互页尝试发消息，依然提示需要去访问 https://labs.perplexity.ai/

---
### Other try | 其他尝试
<img width="1278" alt="Snipaste_2023-12-19_17-17-26" src="https://github.com/chathub-dev/chathub/assets/1010013/7ff8e183-c195-418e-aaab-dcb5d0861245">

Click the button "Try Perplexity"
点击页面右上角，“Try Perplexity”

The site is, https://www.perplexity.ai/
打开：https://www.perplexity.ai/

And it works.
是可以交互的

**Comment by allentown521** [comment]
me too

**Comment by imty42** [comment]
Maybe cause this reason
可能是这个原因

Today the proxy I choose is HongKong and it works
今天我碰巧在用香港IP，发现是可用的

and IP from Japan not work
日本IP是不可用的

cc @allentown521 @wong2
