### ISSUE TITLE
回答生成过程中，按下鼠标左键选中文本时，选中的文本会乱跳

### ISSUE THREAD

**Issue by X3vvv** [chathub-dev/chathub#97]

**Comment by X3vvv** [comment]
> the problem seems to be solved, but the UI isn't very satisfying, because of the slider on the bottom, and part of the text on the bottom always cannot be displayed completely while the answer is generated by ChatGPT or Bing.
> 
> ![image](https://user-images.githubusercontent.com/65343237/225988498-34c0ecf1-bb0d-4463-bfec-1aa0a1b1cb17.png)
this problem only happens in the "All in one" window

**Comment by RoseLuu99** [comment]
Hi

**Comment by wong2** [comment]
Please open a new issue for the UI problem
