### ISSUE TITLE
Gemini Pro through poe

### ISSUE THREAD

**Issue by mokaasa** [chathub-dev/chathub#970]
Please add Gemini Pro through poe

**Comment by wong2** [comment]
Why is this necessary? The Gemini API key is easy to get and free for personal use.

**Comment by mokaasa** [comment]
I thought it is only free via Poe. From where can I get Gemini API PRO key?

**Comment by wong2** [comment]
<img width="511" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/bee16d88-88a6-425c-902a-d6e57b70ddab">

There is a quick link in the Settings page.
