### ISSUE TITLE
插件崩溃后重新加载但是已保存的prompt API等记录没了，但只备份了很老的版本，有什么办法恢复至最近的吗

### ISSUE THREAD

**Issue by Juneone96** [chathub-dev/chathub#979]
如题，且每次重新加载chathub要重新激活license，但是这样会占用激活名额

**Comment by wong2** [comment]
你是用开发者模式加载的？日常使用建议安装Chrome商店的

**Comment by Juneone96** [comment]
> 你是用开发者模式加载的？日常使用建议安装Chrome商店的

抱歉没太理解，确实之前一直开着开发者模式加载的，目前已经取消了，接下来需要再做什么呢

**Comment by wong2** [comment]
从 https://chromewebstore.google.com/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma 安装使用

但之前的数据一旦卸载就没有了
