### ISSUE TITLE
ChatGPT的答案中，有分级的内容不会分组显示

### ISSUE THREAD

**Issue by coach2excel** [chathub-dev/chathub#98]
例如：
以下是七个最不可能被AI取代的行业及其特点和原因：

医疗保健行业
特点：医疗保健行业需要高度人性化的服务，包括诊断、治疗、护理等，需要医生和护士具备人际交往、同理心等能力。
原因：AI可以协助医生进行诊断和治疗，但无法代替医生与患者之间的人际交往和情感交流。
教育行业
特点：教育需要针对每个学生的特点和需求提供个性化的教学服务，需要教师具备较强的人际交往、情感理解和教学能力。
原因：AI可以协助教师进行教学和评估，但无法代替教师与学生之间的情感交流和个性化的教学服务。
艺术行业
特点：艺术需要创造性和想象力，需要艺术家具备独特的审美和创作能力。
原因：AI可以生成艺术作品，但无法代替艺术家独特的审美和创作能力。
餐饮行业
特点：餐饮需要提供高质量的食品和服务，需要厨师和服务员具备烹饪技能和服务技能。
原因：AI可以协助厨师进行烹饪，但无法代替良好的服务和人性化的体验。

**Comment by wong2** [comment]
你的prompt是什么，可以发一下吗
