### ISSUE TITLE
I cannot buy premium

### ISSUE THREAD

**Issue by Mttbnchtt** [chathub-dev/chathub#983]
**Describe the bug**
I use Brave (Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (arm64)) and Chrome (Version 120.0.6099.129 (Official Build) (arm64)) on MacBook Pro M1 with OS Sonoma 14.2.1. I can use ChatHub free version, but, when I click on Premium, a new tab opens and then an error message appears. The error message says:
This site can’t be reachedchathub.gg took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_TIMED_OUT

I tried both on Brave and on Chrome. How to buy the premium version?

**Desktop:**
 - OS: Mac Sonoma 14.2.1 (see above for more details)
 - Browser: Brave and Chrome (see above for more details)
 - ChatHub Version v1.46.0

**Comment by wong2** [comment]
You can buy Premium here instead: https://chathub.lemonsqueezy.com/
