### ISSUE TITLE
Anyscale Endpoints Support

### ISSUE THREAD

**Issue by SinaYa** [chathub-dev/chathub#986]
Please add support for the Anyscale API (or instructions on how to use it if it's already possible but an easy one-click configuration would be great) because:
- Their API is 400 times cheaper than that of ChatGPT-4
- Their fine-tuned models are 16 times cheaper than finetuned GPT-3.5
- They give people 10 dollars free credit on signup (which can be enough for a lifetime with their pricing) 
- They have the latest uncensored models.

Here's a link to their documentation: https://app.endpoints.anyscale.com/docs

**Comment by wong2** [comment]
In the future version, support will be provided for accessing models from any OpenAI-compatible APIs.

**Comment by wong2** [comment]
Please upgrade to 2.0 and check the settings page, there's a Custom chatbots feature.
