### ISSUE TITLE
chatgpt 使用api key模式无法使用gpt4模型

### ISSUE THREAD

**Issue by lionqy163** [chathub-dev/chathub#989]
**Describe the bug**
chatgpt 使用api key模式无法访问gpt4模型
我们现在的openai的等级是2级，是可以使用gpt4 模型的，但是在插件设置中无论如何切换模型chatgpt都是用gpt3进行回复
![image](https://github.com/chathub-dev/chathub/assets/127304508/f38abdab-cdc4-416b-896f-373726cd0c8d)
调试可见请求参数中的模型名称和官方网站写的不太一样，不清楚是不是原因所在
![image](https://github.com/chathub-dev/chathub/assets/127304508/c0b0d334-7929-4ca5-b668-63c0aac40a93)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
 - ChatHub Version [you can find it in ChatHub Settings]

**Comment by wong2** [comment]
为什么说 “无论如何切换模型chatgpt都是用gpt3进行回复” 呢？
请看你的第二张图片，这个是 “响应标头”，不是请求参数，正说明了他是用 gpt-4 模型回复的。

至于模型名字的问题，ChatHub中设置的对应关系是这样的：

<img width="215" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/410e660e-78a9-4291-a8c0-ad9e33033626">

gpt-4 对应 gpt-4-0613
gpt-4-turbo 对应 gpt-4-1106-preview

**Comment by lionqy163** [comment]
> 为什么说 “无论如何切换模型chatgpt都是用gpt3进行回复” 呢？ 请看你的第二张图片，这个是 “响应标头”，不是请求参数，`gpt-4-0613` 正说明了他是用 gpt-4 模型回复的。
> 
> 至于模型名字的问题，ChatHub中设置的对应关系是这样的：
> 
> <img alt="image" width="215" src="https://private-user-images.githubusercontent.com/321947/293861146-410e660e-78a9-4291-a8c0-ad9e33033626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjk2NjcsIm5iZiI6MTcwNDI2OTM2NywicGF0aCI6Ii8zMjE5NDcvMjkzODYxMTQ2LTQxMGU2NjBlLTc4YTktNDI5MS1hOGMwLWFkOWUzMzAzMzYyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwODA5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDYzNTMyYmYzNTU2OTU5Y2RlYjdkYmU1MDk1MDNiNDQ2OWZhYzA4NzU3OGMzZWY3Mjk2ODNlNmJmYTQ5NTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YHkn1b6no8bGs-I4OvtM5RZvDQKHmXJbScp-EPUmQOY">
> gpt-4 对应 gpt-4-0613 gpt-4-turbo 对应 gpt-4-1106-preview

提完发现了，因为每次切换后我去问gpt，它都说自己是gpt3
![image](https://github.com/chathub-dev/chathub/assets/127304508/f66d0d16-57ea-4035-b1c8-189fc882cfb8)

**Comment by wong2** [comment]
大模型自己的回答不可信的 🤦‍♂️

**Comment by wong2** [comment]
你切换到 gpt-4-turbo 来用吧，是最新的gpt-4模型
