### ISSUE TITLE
bing会话创建失败 404 / Failed to fetch

### ISSUE THREAD

**Issue by 52fhy** [chathub-dev/chathub#99]
(404 (https://www.bing.com/turing/conversation/create))

**Comment by 9th-14** [comment]
同样的问题

**Comment by xyl198809041** [comment]
今天是上午8点测试还是好的,现在就不行了

**Comment by hcpub** [comment]
(404 (https://www.bing.com/turing/conversation/create))
貌似已经挂了

**Comment by wong2** [comment]
奇怪，我刚刚测试了一下，还是正常的
https://www.bing.com/turing/conversation/create 请求成功了

**Comment by spaceship6660** [comment]
我也是这个问题

**Comment by wong2** [comment]
有问题的朋友，你们在 https://bing.com/new 能聊天吗？

**Comment by 6gdfg** [comment]
> 有问题的朋友，你们在 https://bing.com/new 能聊天吗？

之前可以用modheader，然后不行了 这个昨天还可以用，今天早上也不行了

**Comment by 6gdfg** [comment]
> 有问题的朋友，你们在 https://bing.com/new 能聊天吗？

显示(404 (https://www.bing.com/turing/conversation/create))

**Comment by faq0** [comment]
> 有问题的朋友，你们在 https://bing.com/new 能聊天吗？

挂了 VPN 后 bing.com/new 和 ChatHub 都能正常用
不挂 VPN 即使用了 ModHeader 也都用不了
（挂了 ModHeader 进 bing.com/new 显示重定向次数过多，ChatHub 404；不挂 ModHeader 也是 404）

**Comment by xhh98** [comment]
挂了vpn，照样 (404  (https://www.bing.com/turing/conversation/create))？求解

**Comment by xhh98** [comment]
> 挂了vpn，照样

 (404  (https://www.bing.com/turing/conversation/create))
求解？

**Comment by tigerysm** [comment]
什么时候能恢复？同样的404

**Comment by iamxiaozhuang** [comment]
用不了了，会话创建不了。能搞定么？

**Comment by Zstrive** [comment]
同404

**Comment by neuhsm** [comment]
同+1

**Comment by odddouglas** [comment]
我這邊很奇怪，似乎在接收到404之後，再稍微等個十幾分鐘，再重新輸入貌似又可以了

**Comment by YuSanr** [comment]
同样404
挂VPN都没办法的那种
CHATGPT挂VPN能用

**Comment by Ivesfsy** [comment]
(404 (https://www.bing.com/turing/conversation/create)) 今天才不能用了，输入这个网址，又被重定向

**Comment by ChunKingJia** [comment]
求解决，问题雷同

**Comment by wangwangdalibaohahaha** [comment]
用不了了

**Comment by Ooiiihey** [comment]
我也一样，还以为我被封了

**Comment by smanx** [comment]
gg了，估计用的人多被微软注意到了。
国内https://www.bing.com/turing/conversation/create会被定向到https://cn.bing.com/turing/conversation/create，cn的接口之前能用，现在404了

**Comment by situkei** [comment]
呵呵，这个地方学习点新先进东西还需要挂梯，是认为愚民好压迫好管制吗(ㄒoㄒ)

**Comment by ypmjx123** [comment]
跪求大神解决

**Comment by vividolphin** [comment]
完了，这个也不行了，兄弟们找到新的办法了吗

**Comment by slamkk** [comment]
昨天晚上还行！

**Comment by iamxiaozhuang** [comment]
> gg了，估计用的人多被微软注意到了。 国内[https://www.bing.com/turing/conversation/create会被定向到https://cn.bing.com/turing/conversation/create，cn的接口之前能用，现在404了](https://www.bing.com/turing/conversation/create%E4%BC%9A%E8%A2%AB%E5%AE%9A%E5%90%91%E5%88%B0https://cn.bing.com/turing/conversation/create%EF%BC%8Ccn%E7%9A%84%E6%8E%A5%E5%8F%A3%E4%B9%8B%E5%89%8D%E8%83%BD%E7%94%A8%EF%BC%8C%E7%8E%B0%E5%9C%A8404%E4%BA%86)

是的，科学上网就不会被重定向，还可以用。不科学上网可以用skype的方式。

**Comment by wangwangdalibaohahaha** [comment]
skype也用不了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shaosl8006** [comment]
> > 挂了vpn，照样
> 
> (404 (https://www.bing.com/turing/conversation/create)) 求解？

我挂了vpn可以了。

**Comment by bypl** [comment]
我也不能用了 然后new bing重新加入后补队列了，意思是我的new bing 被封了？

**Comment by wong2** [comment]
目前看这个问题是这样的：如果没挂代理，请求 https://www.bing.com/turing/conversation/create 时会被重定向到国内域名 https://cn.bing.com/turing/conversation/create 而这个地址是不存在的，于是404了

**Comment by OgataRinay** [comment]
> 目前看这个问题是这样的：如果没挂代理，请求 https://www.bing.com/turing/conversation/create 时会被重定向到国内域名 https://cn.bing.com/turing/conversation/create 而这个地址是不存在的，于是404了

有解决的办法吗，还是以后得开代理才能正常用了？

**Comment by wong2** [comment]
@OgataRinay 暂时是要开代理用了

**Comment by heham** [comment]
今天刚知道这个，测试同样结果，那个edgegpt的python命令行目前还可以正常

**Comment by wangyoucao577** [comment]
+1

**Comment by songsfly** [comment]
请更换新URL：https://edgeservices.bing.com/edgesvc/turing/conversation/create
亲测可以使用了

**Comment by wong2** [comment]
@songsfly 这个是哪里发现的呀

**Comment by songsfly** [comment]
> @songsfly 这个是哪里发现的呀
我去研究了下EdgeGPT，发现他们用的是这个API

**Comment by wong2** [comment]
@songsfly 感谢！已经用上：https://github.com/chathub-dev/chathub/commit/e3567b004764d1e345f5f29bec7662bc6822c5ac

各位遇到该问题的朋友可以下载 v1.5.2 手动安装
https://github.com/chathub-dev/chathub/releases

**Comment by zzxxccvv108** [comment]
> 谢谢！已经用上：[e3567b0](https://github.com/chathub-dev/chathub/commit/e3567b004764d1e345f5f29bec7662bc6822c5ac)
> 
> 遇到该问题的朋友可以下载 v1.5.2 手动安装 https://github.com/chathub-dev/chathub/releases

下载完应该怎么做？

**Comment by wong2** [comment]
手动安装方法：
https://github.com/chathub-dev/chathub#manual-installation--%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85

**Comment by iamxiaozhuang** [comment]
> 手动安装方法： https://github.com/chathub-dev/chathub#manual-installation--%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85

太好了可以用了！有空把chrome插件网站上的更新一下。

**Comment by ypmjx123** [comment]
万能的网友啊

**Comment by hinayand** [comment]
这个插件的原理是什么，谁能帮忙解释一下```https://edgeservices.bing.com/edgesvc/turing/conversation/create```这个API有哪些参数，参数的作用是什么，我到时候用Python的Flet框架搞个桌面图形界面客户端

**Comment by zhengqwe** [comment]
又不能用了
`Forbidden: Sorry, you are not allowed to access this service.`

**Comment by ypmjx123** [comment]
> 又不能用了 `Forbidden: Sorry, you are not allowed to access this service.`
可以用啊，是不是你没登陆bing账号

**Comment by syaoo** [comment]
newbing可以，chatgpt返回Failed to fetch

**Comment by ypmjx123** [comment]
> newbing可以，chatgpt返回Failed to fetch

这个要VPN和API key才行

**Comment by syaoo** [comment]
> > 又不能用了 `Forbidden: Sorry, you are not allowed to access this service.`
> > 可以用啊，是不是你没登陆bing账号

chatgpt也需要登录么？这个扩展是使用浏览器cookies认证账号吗

**Comment by syaoo** [comment]
> > newbing可以，chatgpt返回Failed to fetch
> 
> 这个要VPN和API key才行

好吧，还以为Webapp Mode可以直接使用的。

**Comment by ypmjx123** [comment]
> > > 又不能用了 `Forbidden: Sorry, you are not allowed to access this service.`
> > > 可以用啊，是不是你没登陆bing账号
> 
> chatgpt也需要登录么？这个扩展是使用浏览器cookies认证账号吗

对啊，你得浏览器的bing账号先登陆了，chatgpt只需要APIkey和VPN

**Comment by ypmjx123** [comment]
> > > newbing可以，chatgpt返回Failed to fetch
> > 
> > 
> > 这个要VPN和API key才行
> 
> 好吧，还以为Webapp Mode可以直接使用的。

那个是chatGPT 4，老外都不一定能用得上，跟何况国内

**Comment by manakong** [comment]
**我想问下，大家用的什么梯子，好用的**

**Comment by wong2** [comment]
修复该问题的 v1.5.3 版本已更新到Chrome Web Store！

**Comment by zzzjl2021** [comment]
> 修复该问题的 v1.5.3 版本已更新到Chrome Web Store！

没有提醒更新，我是手动卸载重装的，但是问题已经解决，谢谢！

**Comment by runsground** [comment]
(404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

**Comment by oeieo** [comment]
> (404 (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

+1

**Comment by ypmjx123** [comment]
> > (404 (https://edgeservices.bing.com/edgesvc/turing/conversation/create))
> 
> +1

+2

**Comment by LIU-LIU-LIU** [comment]
> > > （404（https://edgeservices.bing.com/edgesvc/turing/conversation/create））
> > 
> > 
> > +1
> 
> +2
>> +3

**Comment by wong2** [comment]
收到，看来这个接口也被重定向了

**Comment by neuhsm** [comment]
> 收到，看来这个接口也被重定向了

今早我也遇到了这个问题，但是安装最新版本又可以用了

**Comment by runsground** [comment]
> 装

是v1.7.0嘛，亲测不行啊，你再试试呢

**Comment by elijahchan2019** [comment]
1.7.0 Mac上chrome亲测不行

**Comment by neuhsm** [comment]
> > 收到，看来这个接口也被重定向了
> 
> 今早我也遇到了这个问题，但是安装最新版本又可以用了

好像突然也没了...

**Comment by neuhsm** [comment]
刚刚还用着的..突然没了

**Comment by wong2** [comment]
确实这个接口没了

**Comment by wjhbj** [comment]
(404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

**Comment by shaosl8006** [comment]
只能挂梯子了。

**Comment by ninghtpass** [comment]
+1 404

**Comment by LIU-LIU-LIU** [comment]
> 只能挂梯子了。

挂梯子也不行，我挂梯子bing直接白屏，www.bing.com 和cn.bing.com都一样。我手上只有日本和韩国的 都不行。以前挂香港的梯子可以上。

**Comment by shaosl8006** [comment]
> > 只能挂梯子了。
> 
> 挂梯子也不行，我挂梯子bing直接白屏，www.bing.com 和cn.bing.com都一样。我手上只有日本和韩国的 都不行。以前挂香港的梯子可以上。

我挂了梯子用chathub是没有问题的。最新的edge右的边栏也没有问题。

**Comment by iamxiaozhuang** [comment]
(404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))
前几天刚升级换成这个地址又不行了！

**Comment by ychen2023** [comment]
梯子用啥比较好？稳定 简单的

**Comment by wong2** [comment]
Reference: https://github.com/acheong08/EdgeGPT/issues/178

**Comment by wincao** [comment]
刚能用两天，今天23号又404了

**Comment by ypmjx123** [comment]
> **我想问下，大家用的什么梯子，好用的**

expressVPN

**Comment by wong2** [comment]
目前看没有好的解决办法，需要自己用代理了

**Comment by wong2** [comment]
他应该走了代理吧？

**Comment by neuhsm** [comment]
没有，和我一样的，他还是用我发给他的压缩包添加的扩展

**Comment by neuhsm** [comment]
刚刚还专门用了一下，他可以正常使用

**Comment by songsfly** [comment]
一个思路：利用cloudflare进行代理会话创建，不过dev的域名似乎访问困难，建议chathub插件可以通过访问cloudflare直接返回会话id最好了。我已经通过修改chathub代码，手动填充conversationId和conversationSignature等字段再次对话成功了
![image](https://user-images.githubusercontent.com/4994360/227289742-c29ac67b-e998-4925-88c9-de899024ee0e.png)
![image](https://user-images.githubusercontent.com/4994360/227289830-84810960-2538-4efc-b3a9-58812c11a658.png)

**Comment by lper** [comment]
我搭建一个中转调用接口服务，国内可以直接用，需要私聊我哦

**Comment by ypmjx123** [comment]
> 一个思路：利用cloudflare进行代理会话创建，不过dev的域名似乎访问困难，建议chathub插件可以通过访问cloudflare直接返回会话id最好了。我已经通过修改chathub代码，手动填充conversationId和conversationSignature等字段再次对话成功了 ![image](https://user-images.githubusercontent.com/4994360/227291430-a6c89cd7-cc8e-4b0b-a733-3c8e675ab59c.png)
> 
> ![image](https://user-images.githubusercontent.com/4994360/227289830-84810960-2538-4efc-b3a9-58812c11a658.png)
> 
> 而通过代码验证亦是可行的。 ![image](https://user-images.githubusercontent.com/4994360/227302747-d3819559-954b-4ef1-9277-ed3a0ba56dd2.png)
好高级的样子哎，教教我

**Comment by backSpaceMe** [comment]
#

> 我搭建一个中转调用接口服务，国内可以直接用，需要私聊我哦

哥

**Comment by backSpaceMe** [comment]
> 我搭建一个中转调用接口服务，国内可以直接用，需要私聊我哦

哥

**Comment by backSpaceMe** [comment]
> 一个思路：利用cloudflare进行代理会话创建，不过dev的域名似乎访问困难，建议chathub插件可以通过访问cloudflare直接返回会话id最好了。我已经通过修改chathub代码，手动填充conversationId和conversationSignature等字段再次对话成功了 ![image](https://user-images.githubusercontent.com/4994360/227291430-a6c89cd7-cc8e-4b0b-a733-3c8e675ab59c.png)
> 
> ![image](https://user-images.githubusercontent.com/4994360/227289830-84810960-2538-4efc-b3a9-58812c11a658.png)
> 
> 而通过代码验证亦是可行的。 ![image](https://user-images.githubusercontent.com/4994360/227302747-d3819559-954b-4ef1-9277-ed3a0ba56dd2.png)

哥!

**Comment by wong2** [comment]
建议不要用第三方中转接口，把cookie暴露给第三方很危险，要中转的话也自建比较好

**Comment by backSpaceMe** [comment]
> 建议不要用第三方中转接口，把cookie暴露给第三方很危险，要中转的话也自建比较好

@wong2 @songsfly 他的想法如何

**Comment by wong2** [comment]
![image](https://user-images.githubusercontent.com/321947/227404521-f40ebb1f-c34b-439b-b5b6-ee331d18e003.png)

Try this?

**Comment by Dauch** [comment]
> ![image](https://user-images.githubusercontent.com/321947/227404521-f40ebb1f-c34b-439b-b5b6-ee331d18e003.png)
> 
> Try this?

试了，没有用呢

**Comment by CodeFishK** [comment]
> > ![image](https://user-images.githubusercontent.com/321947/227404521-f40ebb1f-c34b-439b-b5b6-ee331d18e003.png)
> > Try this?
> 
> 试了，没有用呢

试了没用

**Comment by Burgerdash** [comment]
> cloudflare
清理过cookie重新上过了嘛？

**Comment by Burgerdash** [comment]
> > > ![image](https://user-images.githubusercontent.com/321947/227404521-f40ebb1f-c34b-439b-b5b6-ee331d18e003.png)
> > > Try this?
> > 
> > 
> > 试了，没有用呢
> 
> 试了没用

先清理cookie再用代理呢？（没开代理之前不能尝试访问bing）

**Comment by Burgerdash** [comment]
> > 
> > 试了，没有用呢
> 
> 试了没用

试过清理cookie后再用代理上bing嘛？

**Comment by youthkiss** [comment]
> 

全局代理不需要清理cookie那些就直连了

**Comment by hinayand** [comment]
(404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

API又没力（悲

**Comment by codeplayhub** [comment]
还有些许的试用次数，跟大家分享一下了，暂时解解大家的渴
[chat.shareyun.com](https://shareyun.com/)

期待各位大神继续破解了限制，Fighting!

**Comment by Simon-Yi** [comment]
目前来看，用上述的各种方法都不行了，期待新的办法

**Comment by lper** [comment]
> 

我搭建中转服务，可以直接用的

**Comment by hinayand** [comment]
> > 
> 
> 我搭建中转服务，可以直接用的

那么能登陆自己的账号吗？可以保证隐私吗？

**Comment by lper** [comment]
> > > 
> > 
> > 
> > 我搭建中转服务，可以直接用的
> 
> 那么能登陆自己的账号吗？可以保证隐私吗？
是你的账号登录，https中转，可以加密传输~

**Comment by hinayand** [comment]
> > > > 
> > > 
> > > 
> > > 我搭建中转服务，可以直接用的
> > 
> > 
> > 那么能登陆自己的账号吗？可以保证隐私吗？
> > 是你的账号登录，https中转，可以加密传输~

那么怎么去使用啊

**Comment by hinayand** [comment]
> > > > 
> > > 
> > > 
> > > 我搭建中转服务，可以直接用的
> > 
> > 
> > 那么能登陆自己的账号吗？可以保证隐私吗？
> > 是你的账号登录，https中转，可以加密传输~

算了，我还是等开源服务端实现吧

**Comment by wong2** [comment]
https://github.com/acheong08/EdgeGPT-Proxy 这里有个开源的代理服务

**Comment by runsground** [comment]
可以使用了嘛这是...为什么我还不行

**Comment by forrestgao** [comment]
我开全局代理也不行啊，奇怪了……油管谷歌都没问题

**Comment by wong2** [comment]
@forrestgao 版本是 1.9.0 了吗

**Comment by dslwz2008** [comment]
@wong2 试了一下1.9.0 ，开代理可用

**Comment by chenyan123456789** [comment]
> @wong2 试了一下1.9.0 ，开代理可用
我这边也开了代理 除非是全局代理,不然还是不行

**Comment by wong2** [comment]
@chenyan123456789 说明你的代理规则里，bing没有走代理，改一下规则就可以了

**Comment by sdpy3634** [comment]
不用代理  一直failed to fetch 有什么办法吗

**Comment by wong2** [comment]
https://twitter.com/wong2_x/status/1639900972729380865

**Comment by CountMCristo** [comment]
开代理并且保证bing能够走到代理，有的代理即便开了但是bing也没有走代理。然后就能正常使用了。

**Comment by longware** [comment]
就安装第一天能用，后来一直不行，反而chatgpt可以

**Comment by coooliang** [comment]
Failed to fetch (https://www.bing.com/turing/conversation/create) 我也是这样

**Comment by xuwu6** [comment]
bing源网站挂了吗，我都找不到bing聊天口了

**Comment by longware** [comment]
需要富强



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月15日 15:06 |
| 收件人 | ***@***.***> |
| 抄送至 | HELLO ***@***.***>***@***.***> |
| 主题 | Re: [chathub-dev/chathub] bing会话创建失败 404 / Failed to fetch (Issue #99) |

bing源网站挂了吗，我都找不到bing聊天口了

**Comment by xuwu6** [comment]
你们翻了能用吗？，我怎么翻都不行，全局都不行了

**Comment by ypmjx123** [comment]
https://bing.vcanbb.top/web/#/



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月15日(周四) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chathub-dev/chathub] bing会话创建失败 404 / Failed to fetch (Issue #99)




 
你们翻了能用吗？，我怎么翻都不行，全局都不行了

**Comment by xuwu6** [comment]
谢谢

**Comment by sususnow** [comment]
> 你们翻了能用吗？，我怎么翻都不行，全局都不行了

翻了也不能用

**Comment by 78812737ehdj** [comment]
> > 
> 
> 我搭建中转服务，可以直接用的

大佬，教教我

**Comment by HarrisonPareto** [comment]
VPN 其他访问正常，BING访问仍有问题

Failed to fetch (https://www.bing.com/turing/conversation/create)

**Comment by echo-art** [comment]
bing已登录仍然显示UnauthorizedRequest

**Comment by ypmjx123** [comment]
> +1 版本：(v1.43.6) 复现时间：2023年12月7日09:13:46

能用了？

**Comment by totemcool** [comment]
我换了日本节点可以用
