### ISSUE TITLE
chatgpt 可以避免老弹出机器人校验

### ISSUE THREAD

**Issue by jschen1009** [chathub-dev/chathub#993]
![ScreenClip](https://github.com/chathub-dev/chathub/assets/31001147/b44276cf-a7cf-4f84-bc0f-4408db6d6118)

**Comment by wong2** [comment]
我还没遇到过这个，你是什么频率会出现呢？

**Comment by jschen1009** [comment]
每个问题都会弹

**Comment by wong2** [comment]
最新版已解决此问题
